package-lock.json
package.json
src/solidity/imports.js

On a quick benchmark, this provides between one and two orders of magnitude speed improvement in extracting imports from source files.

Use solidity-extract-imports instead of a full parser

---

sample-project/contracts/Greeter.sol

Sample project compilation issues a warning due to deprecated usage of constructor over Greeter.sol.

Updated constructor on Greeter.sol to remove deprecated warning.

---

.env.sample
.gitignore
docs/.vuepress/config.js
docs/.vuepress/override.styl
docs/README.md
docs/deploy/deploy.sh
package-lock.json
package.json

Fixes #3 
I've just added vuepress and a `docs` folder.  
Nothing special than a beautiful way to expose your README.
To start I've only (symbolic) linked README.md in project root but, anyone can now write docs by adding or editing .md files into docs folder.
To produce docs website you need to merge PR and then run: `npm run docs:deploy`.
README.md will be converted in a vue.js single page application and pushed to the `gh-pages` branch so you will be able to have your docs at https://nomiclabs.github.io/buidler and it will look like this https://vittominacori.github.io/buidler.
NOTE: if you are deploying to a custom domain add a CNAME file with your domain into `docs/.vuepress/public` folder.

Adding vuepress to build docs into gh-pages #3

---

package-lock.json
package.json
test/mocha.opts
test/solidity/compiler.ts

TS-node ignores some parts of tsconfig.json by default. That behaviour
can be disabled with a flag or env variabler.
I installed dotenv and add it to mocha.opts. This way the env var is
defined however you run your tests (with/without npm, in travis, from
your IDE/editor, etc).

Fix TS types resolution on tests.

---

src/core/runtime-environment.ts
test/core/runtime-environment.ts

Bugs fixed:
1. If a subtask was run the injected values were lost
2. BLACKLISTED_PROPERTIES was being injected
3. runSuper was always removed if a subtask was run
4. tasks completion was not awaited, leading to all sort of errors.

Fix various bugs in runtime environment

---

src/core/providers/ethereum.ts
src/core/providers/web3x-ethereum.ts
src/types.ts
test/core/providers/ethereum.ts
test/core/providers/web3x-ethereum.ts

1. Temporarily fix of a web3x typing
2. Properly convert promises to callback based apis, resulting in unhandled errors not being lost.
3. Throw errors on some unsupported methods of EthereumProvider
4. Fix some error handling
5. Fix some tests

Multiple improvements to the providers

---

src/cli/ArgumentsParser.ts
src/core/errors.ts
test/cli/ArgumentsParser.ts

This PR contains a few improvements to `ArgumentParser`. The main one is that it now enforces CLI param names to be lowercase. 
This decision is somewhat conservative and may change in the future, but it's also very easy to explain and to reason about.

Small changes to ArgumentParser

---

package-lock.json
package.json
src/cli/cli.ts
src/core/errors.ts
src/util/packageInfo.ts

This PR validates the node version and fails with a clear message if it doesn't meet Buidler's requirements. 
This is important as we aren't supporting old version. We should define a policy for this in the future.

Add node version validation

---

src/core/tasks/builtin-tasks.ts
src/util/glob.ts

We used to have some logic to import them dynamically. This PR removes that and imports everything statically. This will be important when we webpack/rollup the project.
There were two reasons for the dynamic imports:
1. It ensures that all of them are imported.
2. It ensures a (any) consistent order of imports.
TSLint also ensures an order, so we get (2) statically too. (1) is not enforced now, but the errors for not importing one are kind of obvious (eg: a missing task).

Import the builtin tasks definitions with static imports

---

.gitignore
config.ts
package.json
src/config.ts
tsconfig.common.json
tsconfig.json
tsconfig.prod.json

The goal of this PR is to compile the production version into the root folder of the npm package. This way plugin authors can extend types using `declare module "buidler/types" {...}` instead of `declare module "buidler/dist/src/types" {...}`.

Split development and prod ts config files

---

src/core/errors.ts
src/core/runtime-environment.ts
src/core/tasks/dsl.ts
src/core/tasks/task-definitions.ts
test/core/runtime-environment.ts
test/core/tasks/dsl.ts
test/core/tasks/task-definitions.ts

This PR replaces the use of "overload" for "override" as it was wrong. It also fixes a typo in a filename.

Replace overload for overridden

---

src/core/providers/accounts.ts
src/core/providers/construction.ts
src/core/providers/ethereum.ts
src/core/providers/gas-providers.ts
src/core/providers/network.ts
src/core/providers/wrapper.ts
src/core/runtime-environment.ts
src/types.ts
test/core/providers/accounts.ts
test/core/providers/construction.ts
test/core/providers/gas-providers.ts
test/core/providers/mocks.ts
test/core/providers/network.ts
test/core/providers/wrapper.ts

It's still not clear how the EIP-1193 provider interface will relate to Node.JS's EventEmitter. We remove the latter for now.

Remove the added EventEmitter from the EIP-1193 interface

---

src/cli/cli.ts
src/core/errors.ts
src/util/caller-package.ts
test/fixture-projects/nested-node-project/package.json
test/fixture-projects/nested-node-project/project/nested-caller-package-tester.ts
test/fixture-projects/nested-node-project/project/package.json
test/fixture-projects/nested-node-project/top-caller-package-tester.ts
test/util/caller-package.ts

This PR implements a `BuidlerPluginError` class, which automatically infers which plugin it is being constructed from.

BuidlerPluginError

---

src/builtin-tasks/test.ts

We weren't waiting for mocha to complete, as we were just passing it a callback and returning from the "test" task.
This resulted in lots of bugs, as the environment is removed before the tests finished.
This PR promisifies mocha before running it, and awaits it.

Fix bug in test task

---

src/internal/core/providers/construction.ts
src/internal/core/providers/gas-providers.ts
src/types.ts
test/internal/core/providers/construction.ts
test/internal/core/providers/gas-providers.ts

Estimating gas is not an exact process. The amount from gas actually needed can differed from the one that your node estimated, which results in out of gas errors.
This PR tries to remedy that by multiplying the estimation by a user-configurable multiplier, copying what other libraries/frameworks do.
A new field is added to the config in this PR. Now each network's config can have an optional `gasMultiplier` field. If provided, it must be a number. If not present, it defaults to `1.25`.

Add gas multiplier to automatic estimation

---

src/builtin-tasks/test.ts

This PR makes `test` task exit buidler's process passing the number of mocha failures as status number.

Change test task termination

---

src/register.ts

The idea behind `buidler/register` is that it initializes the Buidler environment and injects it, as if a module that loads it were executed within a `task`. So we enable `source-maps` support in `buidler/register`, to better mimic what happens when executing tasks.

Enable source-maps support in buidler/register

---

src/builtin-tasks/utils/cache.ts

If some file (e.g. .gitignore) was present in the artifacts dir, and its mod date was after the source's one, nothing would compile.
Now only .json files are consider from artifacts dir, and only .sol files from the sources one.

Fix bug in cache logic.

---

src/internal/cli/cli.ts

Calling `process.exit` after running the main task will help us spot bugs where something outlives it.

Finish the Buidler process after running the main task

---

sample-project/scripts/sample-script.js
src/internal/cli/cli.ts

Rationale: This promotes being more conscious with your async processes, and let us interact with libraries that may outlive Buidler scripts, like ganache-core's provider.

Make the sample script kill the process once it's done

---

src/builtin-tasks/console.ts
src/builtin-tasks/run.ts
src/internal/util/scripts-runner.ts
test/internal/util/scripts-runner.ts

We always passed `buidler/register` to the script runner, so that's abstracted now.

Create runScriptWithBuidler in script runner module

---

src/internal/util/console.ts
src/register.ts

Starting from Node 10, when an expression evaluates to a proxy, the console shows the proxy itself, not the proxied value.
This makes all our lazy-loaded objects confusing, so we disable this feature in buidler/register.

Show proxied objects in the console instead of the proxies themselves.

---

sample-project/buidler.config.js
sample-project/scripts/sample-script.js
sample-project/test/sample-test.js
src/internal/core/runtime-environment.ts
src/types.ts
test/internal/core/runtime-environment.ts

The [EIP1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md) suggests naming the provider `ethereum`. We do so to avoid unnecessary differences with the standard.

 Rename the Buidler Runtime Environment's provider to `ethereum`

---

package.json
src/internal/core/config/default-config.ts
src/types.ts
test/internal/core/config/config-resolution.ts
test/internal/solidity/compiler/downloader.ts
yarn.lock

This PR updates the default version of solc to 0.5.5 and changes its default evm target setting to `"petersburg"`.

Update solc and its default evm target

---

src/internal/core/errors.ts
src/internal/core/params/argumentTypes.ts
test/internal/core/params/argumentTypes.ts

This PR just adds an argument type for JSON.
This arg type is mostly useful for internal tasks, as a way to pass an arbitrary kind of data.

Add JSON argument type

---

src/builtin-tasks/test.ts
src/internal/cli/cli.ts
src/internal/core/project-structure.ts
src/internal/core/typescript-support.ts
src/register.ts
test/fixture-projects/broken-typescript-config-project/buidler.config.ts
test/fixture-projects/broken-typescript-config-project/tsconfig.json
test/fixture-projects/typescript-project/buidler.config.ts
test/fixture-projects/typescript-project/script.ts
test/internal/core/typescript-support.ts

This PR enables the use of TS in:
1. config files, using `buidler.config.ts`
2. tests
3. scripts (i.e. `npx buidler run script.ts`)
TypeScript support is automatically enabled if `typescript` and `ts-node` are installed in the same `node_modules` than Buidler.
This PR doesn't add typings for the different libraries, nor generates typing for contracts. These things must be handled in their plugins.

Initial TypeScript support

---

src/builtin-tasks/compile.ts
src/builtin-tasks/task-names.ts
src/internal/solidity/compiler/compiler-input.ts
src/internal/solidity/compiler/index.ts
src/types.ts
test/helpers/compiler.ts
test/internal/solidity/compiler/compiler-input.ts
test/internal/solidity/compiler/index.ts

This PR makes changing the compiler almost trivial. Now anyone can override 'compile:run-compiler' (which takes the standard solc JSON input and returns the standard solc JSON output) and use another version of solc. A possible use of this is to run solc in Docker.
Depends on #188

Encapsulate the solc selection in an internal task

---

test/helpers/context.ts

The @nomiclabs/buidler/config module wasn't being unloaded

Fix resetBuidlerContext function

---

.env
.travis.yml
package.json
src/internal/@types/deepmerge/index.d.ts
src/internal/@types/ethereumjs-tx/index.d.ts
src/internal/@types/ethereumjs-util/index.d.ts
src/internal/@types/not-typed.d.ts
src/internal/@types/solc/index.d.ts
src/internal/core/config/config-resolution.ts
test/mocha.opts
tsconfig.common.json
yarn.lock

This PR simplifies how we use `ts-node`.
Previously, we were using `dotenv` to set the `TS_NODE_FILES` env to `true`. This is not really necessary, makes things slower, and complicates our planned migration to a monorepo.
Instead of using that, we now define non-typed modules in a per-folder way, and set `typeRoots` in `tsconfigs.json`.
This PR also optimizes the testing setup a little further by separating `yarn test` form `yarn coverage`.

Simplify ts-node setup

---

packages/buidler-core/src/internal/lib/buidler-lib.ts

We were exporting `BuidlerRuntimeEnvironment | undefined`. This PR changes it to `BuidlerRuntimeEnvironment`.

[buidler-core] Fix type exported by Buidler library

---

packages/buidler-core/src/internal/core/providers/accounts.ts

Locally signed transactions are sent with `eth_sendRawTransaction`. This RPC call receives a hex-encoded raw transaction. We weren't hex-encoding it, but just calling `rawTransactionBuffer.toString()`.

Fix transactions serialization bug

---

config/tslint/tslint.json
package-lock.json
package.json
packages/buidler-core/src/internal/cli/HelpPrinter.ts
packages/buidler-core/src/internal/core/config/extenders.ts
packages/buidler-core/src/internal/core/runtime-environment.ts
packages/buidler-core/src/internal/core/tasks/dsl.ts
packages/buidler-core/src/internal/core/tasks/task-definitions.ts
packages/buidler-core/src/internal/solidity/compiler/downloader.ts
packages/buidler-core/src/internal/solidity/compiler/index.ts
packages/buidler-core/src/internal/solidity/dependencyGraph.ts
packages/buidler-core/src/internal/solidity/resolver.ts
packages/buidler-ethers/src/ethers-provider-wrapper.ts
packages/buidler-truffle4/src/artifacts.ts
packages/buidler-truffle4/src/provisioner.ts
packages/buidler-truffle5/src/artifacts.ts
packages/buidler-truffle5/src/provisioner.ts
packages/buidler-web3-legacy/src/web3-provider-adapter.ts
packages/buidler-web3/src/web3-provider-adapter.ts

This PR adds some more lint rules. 
The most important one is that it forces private fields/methods to start with an underscore. This is important for javascript users, as they can't distinguish between private and public fields (that's a TS thing) and they'd consider everything public otherwise.

More lint rules, mostly about naming

---

CONTRIBUTING.md
packages/buidler-core/src/builtin-tasks/clean.ts
packages/buidler-core/src/builtin-tasks/compile.ts
packages/buidler-core/src/builtin-tasks/console.ts
packages/buidler-core/src/builtin-tasks/run.ts
packages/buidler-core/src/builtin-tasks/utils/cache.ts
packages/buidler-core/src/internal/artifacts.ts
packages/buidler-core/src/internal/cli/project-creation.ts
packages/buidler-core/src/internal/core/params/argumentTypes.ts
packages/buidler-core/src/internal/core/project-structure.ts
packages/buidler-core/src/internal/core/providers/accounts.ts
packages/buidler-core/src/internal/core/providers/wrapper.ts
packages/buidler-core/src/internal/solidity/compiler/downloader.ts
packages/buidler-core/src/internal/solidity/compiler/index.ts
packages/buidler-core/src/internal/solidity/resolver.ts
packages/buidler-core/src/internal/util/glob.ts
packages/buidler-core/src/internal/util/packageInfo.ts
packages/buidler-core/src/internal/util/scripts-runner.ts
packages/buidler-ethers/src/index.ts
packages/buidler-solhint/src/index.ts
packages/buidler-solpp/src/index.ts

This PR defines a clear set of rules about how to import dependencies in a performant way. 
The rules are documented in `CONTRIBUTING.md`.
Closes #198

Define a clear set of rules about how to import dependencies

---

docs/documentation/README.md
packages/buidler-core/src/builtin-tasks/compile.ts
packages/buidler-core/src/internal/core/config/default-config.ts
packages/buidler-core/src/internal/solidity/compiler/compiler-input.ts
packages/buidler-core/src/types.ts
packages/buidler-core/test/helpers/compiler.ts
packages/buidler-core/test/internal/core/config/config-resolution.ts
packages/buidler-core/test/internal/solidity/compiler/compiler-input.ts

This is an alternative solution to #271
We just let solidity choose the default evm version. This is easier to maintain, and can't result in version errors.

Let solidity choose the default evm version

---

packages/buidler-truffle5/src/constants.ts
packages/buidler-truffle5/src/index.ts
packages/buidler-truffle5/src/provisioner.ts
packages/buidler-truffle5/test/buidler-project-solc-0.4/buidler.config.js
packages/buidler-truffle5/test/tests.ts

The netorkws' `gasMultiplier` param was ignored by `buildler-truffle5`. This PR fixes that.

Set the gas multiplier to Truffle Contracts

---

docs/documentation/README.md
packages/buidler-core/src/internal/core/providers/gas-providers.ts
packages/buidler-core/test/internal/core/providers/construction.ts
packages/buidler-core/test/internal/core/providers/gas-providers.ts
packages/buidler-truffle5/src/constants.ts

Now that we duplicate Ganache's gas estimations we can change the default `gasMultiplier` to 1, so we don't (1) multiply ganache estimations even further, (2) multiply estimations from well-behaving nodes.

Change default gasMultiplier to 1

---

packages/buidler-core/src/internal/core/config/config-validation.ts
packages/buidler-core/test/internal/core/config/config-validation.ts

This PR makes the `url` required when setting up a network, except for networks `auto` and `develop`.

Make the network's url field a required parameter

---

packages/buidler-core/src/builtin-tasks/console.ts
packages/buidler-core/src/builtin-tasks/run.ts
packages/buidler-core/src/internal/core/params/env-variables.ts
packages/buidler-core/src/internal/util/scripts-runner.ts
packages/buidler-core/test/fixture-projects/project-with-scripts/assert-buidler-arguments.js
packages/buidler-core/test/fixture-projects/project-with-scripts/buidler.config.js
packages/buidler-core/test/internal/core/params/env-variables.ts
packages/buidler-core/test/internal/util/scripts-runner.ts

Forward Buidler arguments

---

packages/buidler-core/package-lock.json
packages/buidler-core/package.json
packages/buidler-ethers/package-lock.json
packages/buidler-ethers/package.json
packages/buidler-solhint/package-lock.json
packages/buidler-solhint/package.json
packages/buidler-solpp/package-lock.json
packages/buidler-solpp/package.json
packages/buidler-truffle4/package-lock.json
packages/buidler-truffle4/package.json
packages/buidler-truffle5/package-lock.json
packages/buidler-truffle5/package.json
packages/buidler-web3-legacy/package-lock.json
packages/buidler-web3-legacy/package.json
packages/buidler-web3/package-lock.json
packages/buidler-web3/package.json

This PR publishes Buidler Beta 8
The complete list of changes is:
* Buidler doesn't set a default evm version anymore (#277)
* Show stack traces on unknown errors (#287)
* Config validation (#285)
* Print a warning when ts-node fails to load (#289)
* Set the `gasMultiplier` to Truffle Contracts (#292)
* Fix multiple JSON-RPC errors (#292)
* Automatically Ganache gas estimations (#292)
* Change default `gasMultiplier` to 1 (#297)
* Make custom networks' `url` a required parameter (#298)
* Fix a bug that made `buidler run` and `buidler console` ignore some parameters (#300)

Buidler Beta 8

---

config/tslint/tslint.json
packages/buidler-core/README.md
packages/buidler-core/package-lock.json
packages/buidler-core/package.json
packages/buidler-core/src/internal/context.ts
packages/buidler-core/src/internal/core/config/config-env.ts
packages/buidler-core/src/internal/core/config/config-loading.ts
packages/buidler-core/src/internal/core/errors.ts
packages/buidler-core/src/internal/core/execution-mode.ts
packages/buidler-core/src/internal/core/plugins.ts
packages/buidler-core/src/internal/core/typescript-support.ts
packages/buidler-core/src/internal/util/scripts-runner.ts
packages/buidler-core/test/fixture-projects/plugin-loading-project/node_modules/pack1/package.json
packages/buidler-core/test/fixture-projects/plugin-loading-project/node_modules/requires-missing-pack/package.json
packages/buidler-core/test/fixture-projects/plugin-loading-project/node_modules/requires-other-version-pack1/package.json
packages/buidler-core/test/fixture-projects/plugin-loading-project/node_modules/requires-pack1/package.json
packages/buidler-core/test/fixture-projects/plugin-loading-project/node_modules/validates-import-style/package.json
packages/buidler-core/test/internal/core/plugins.ts

This refactor changes how we load plugins. Instead of always loading them from the Buidler project's `node_modules`, we use the normal module resolution.
It also improves plugin error messages when Buidler is installed globally, instructing the user to fix their dependencies problems globally.

Refactor plugin system

---

packages/buidler-core/src/internal/core/errors.ts
packages/buidler-core/src/internal/lib/buidler-lib.ts
packages/buidler-core/test/fixture-projects/config-imports-lib-project/buidler.config.js
packages/buidler-core/test/internal/core/config/config-loading.ts

Throw a nicer error when the lib is imported from the config

---

docs/guides/README.md
docs/guides/create-task.md
docs/guides/truffle-migration.md
packages/buidler-truffle5/README.md
packages/buidler-web3/README.md

This PR updaters the docs wherever they indicated to install `web3@1.0.0-beta.37`. They now instruct the user to use the `--save-exact` npm flag.

Fix web3 installation instructions

---

packages/buidler-docker/src/buidler-docker.ts
packages/buidler-vyper/src/compilation.ts

This PR adds logic to the Docker library and the vyper plugin to handle the case when there's no Docker socket.

[buidler-vyper] Handle missing Docker socket

---

packages/buidler-core/src/builtin-tasks/run.ts
packages/buidler-core/src/internal/artifacts.ts
packages/buidler-core/src/internal/cli/ArgumentsParser.ts
packages/buidler-core/src/internal/cli/HelpPrinter.ts
packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/core/config/config-validation.ts
packages/buidler-core/src/internal/core/errors.ts
packages/buidler-core/src/internal/core/params/argumentTypes.ts
packages/buidler-core/src/internal/core/params/env-variables.ts
packages/buidler-core/src/internal/core/plugins.ts
packages/buidler-core/src/internal/core/providers/accounts.ts
packages/buidler-core/src/internal/core/providers/chainId.ts
packages/buidler-core/src/internal/core/providers/provider-utils.ts
packages/buidler-core/src/internal/core/runtime-environment.ts
packages/buidler-core/src/internal/core/tasks/task-definitions.ts
packages/buidler-core/src/internal/solidity/compiler/downloader.ts
packages/buidler-core/src/internal/solidity/resolver.ts
packages/buidler-core/src/internal/util/lazy.ts
packages/buidler-core/src/internal/util/strings.ts
packages/buidler-core/test/helpers/errors.ts
packages/buidler-core/test/internal/core/errors.ts
packages/buidler-core/test/internal/util/strings.ts

This plugin makes two medium-sized refactors:
1) Introduces a new constructor to `BuidlerPluginError` that lets you specify the plugin name.
2) Introduces a small template language for `BuidlerError` messages, and updates all the messages and uses of `BuidlerError`.

BuidlerError refactor

---

docs/documentation/README.md
docs/guides/create-plugin.md
packages/buidler-core/sample-project/scripts/sample-script.js
packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/lib/buidler-lib.ts
packages/buidler-core/src/register.ts
packages/buidler-ethers/src/index.ts
packages/buidler-ethers/test/ethers-provider-wrapper.ts
packages/buidler-truffle4/test/tests.ts
packages/buidler-web3-legacy/src/index.ts
packages/buidler-web3-legacy/test/web3-provider-adapter.ts
packages/buidler-web3/src/index.ts
packages/buidler-web3/test/web3-provider-adapter.ts

This PR finishes up the work started in #309 by doing two things.
1) It assigns the default network to `buidlerArguments.network` if no value is present. This is not completely backward-compatible though, as it's type is now different.
2) Replaces all the uses `env.ethereum` for `env.network.provider`.

Finish up #309

---

packages/buidler-core/src/internal/cli/ArgumentsParser.ts

This PR depends on #323. It must be rebased & merged after that one.

Show missing arguments error with CLA-formated parm names

---

packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/core/params/buidler-params.ts

This PR fixes the case where `npx buidler --help task` would fail because of missing or invalid arguments.

Don't parse a task's arguments just to print its help

---

config/typescript/@types/ethereumjs-tx/index.d.ts
packages/buidler-core/package.json
packages/buidler-core/src/internal/core/errors.ts
packages/buidler-core/src/internal/core/providers/accounts.ts
packages/buidler-core/src/internal/core/providers/construction.ts
packages/buidler-core/src/internal/core/providers/http.ts
packages/buidler-core/src/internal/core/runtime-environment.ts
packages/buidler-core/src/internal/util/keys-derivation.ts
packages/buidler-core/src/types.ts
packages/buidler-core/test/internal/core/providers/accounts.ts
packages/buidler-core/test/internal/core/providers/construction.ts
packages/buidler-core/test/internal/core/providers/http.ts
packages/buidler-core/test/internal/util/keys-derivation.ts
packages/buidler-ethers/test/ethers-provider-wrapper.ts

This PR removes web3x. The reasons to do that are:
1. We used very few parts of it, and it's not a small library.
2. We used a very old version.
3. It had some problems handling networking errors.
We replaced it with:
1. Our own HttpProvider based on `node-fetch`, which handles offline and unresponsive nodes correctly.
2. We use `ethereumjs-util`, `bip32` and `bip39` to derive keys and sign.
Fixes #276 
~~PS: This PR is based on #323~~

Remove web3x

---

packages/buidler-core/src/builtin-tasks/run.ts
packages/buidler-core/src/builtin-tasks/test.ts
packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/test/builtin-tasks/run.ts
packages/buidler-core/test/internal/core/typescript-support.ts

This PR changes the way `TASK_TEST` and `TASK_RUN` provide returns exit codes to the parent process. Previously, they called `process.exit`. They now set `process.exitCode`, and the CLI uses it.

Don't kill Buidler in TASK_TEST nor TASK_RUN

---

packages/buidler-core/src/internal/util/scripts-runner.ts

This PR adds debug logging to the script runner module. This will shed some light on how `buidler run` works.

Add logging to scripts-runner

---

packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/core/params/buidler-params.ts
packages/buidler-core/src/types.ts
packages/buidler-core/test/internal/cli/ArgumentsParser.ts
packages/buidler-core/test/internal/core/params/env-variables.ts
packages/buidler-core/test/internal/core/runtime-environment.ts
packages/buidler-core/test/internal/core/tasks/task-definitions.ts

This PR introduces a new Buidler argument that enables `debug`'s logs.

Implement --verbose Buidler argument

---

packages/buidler-etherscan/src/AbiEncoder.ts
packages/buidler-etherscan/src/index.ts

Fixes #338.
Passing a wrong number of constructor arguments now shows a message like the following:

Fix error message on invalid number of constructor arguments

---

packages/buidler-core/src/internal/core/providers/gas-providers.ts

Cache gas limit (per process), so that `eth_getBlockByNumber` is only called once for obtaining it per execution. This should greatly reduce data usage.

Cache gas limit

---

packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/core/errors.ts
packages/buidler-core/test/internal/core/errors.ts

This PR prevents the CLI from duplicating error messages.
This is done in two ways:
1. Remove an unnecessary argument in a `console.error`
2. Add user-defined type guards for `BuidlerError` and `BuidlerPluginError`. This is necessary for development time. When running Buidler and plugins locally, it's not uncommon to have multiple instances of these classes due to linking.

[core] Don't duplicate errors in the CLI

---

.travis.yml
docs/guides/README.md
docs/guides/create-task.md
docs/guides/truffle-migration.md
packages/buidler-truffle5/README.md
packages/buidler-truffle5/package.json
packages/buidler-web3/README.md
packages/buidler-web3/package.json

This PR upgrades web3 1.0.0-beta.37 to 1.2.0. It also updates the CI config, as it can now run on node 12.

Upgrade web3 to the stable version

---

packages/buidler-core/src/internal/core/providers/construction.ts
packages/buidler-core/src/internal/core/providers/gas-providers.ts
packages/buidler-core/src/internal/core/providers/provider-utils.ts
packages/buidler-core/src/internal/core/providers/wrapper.ts
packages/buidler-core/src/internal/core/runtime-environment.ts
packages/buidler-core/test/internal/core/providers/accounts.ts
packages/buidler-core/test/internal/core/providers/chainId.ts
packages/buidler-core/test/internal/core/providers/construction.ts
packages/buidler-core/test/internal/core/providers/gas-providers.ts
packages/buidler-core/test/internal/core/providers/mocks.ts
packages/buidler-core/test/internal/core/providers/provider-utils.ts
packages/buidler-core/test/internal/core/providers/wrapper.ts
packages/buidler-solhint/test/tests.ts
packages/buidler-truffle4/src/index.ts
packages/buidler-truffle4/src/provisioner.ts
packages/buidler-truffle5/src/index.ts
packages/buidler-truffle5/src/provisioner.ts

This PR simplifies how we handle the `gas` and `gasPrice` providers. Now they do fewer request, by not re-requesting info that we already have, and by using `truffle-contract`'s default values.
It also revamps the providers' tests, as they were too fragile.

Simplify gas and gas price providers

---

packages/buidler-core/src/internal/util/lazy.ts
packages/buidler-web3/src/index.ts

This PR replaces our previous fix with a more robust one. This is needed because users may have more than one `web3` version (as transitive dependencies), and the previous fix wasn't enough.

Better handling of web3 recursive requires

---

packages/buidler-core/src/internal/context.ts
packages/buidler-core/src/internal/core/config/config-env.ts
packages/buidler-core/src/internal/core/config/config-loading.ts
packages/buidler-core/src/internal/core/config/config-resolution.ts
packages/buidler-core/src/internal/core/errors.ts
packages/buidler-core/src/internal/reset.ts
packages/buidler-core/src/types.ts
packages/buidler-core/test/fixture-projects/config-extensions/buidler.config.js
packages/buidler-core/test/fixture-projects/invalid-config-extension/buidler.config.js
packages/buidler-core/test/internal/core/config/config-extensions.ts

This is a WIP PR that introduces a new function to the config environment. It works very similarly to `extendEnvironment`, but it's used to extend/resolve the config.
The function is called `extendConfig` for now. I'm not sold on that name.

Config extension/resolution mechanism for plugins

---

packages/buidler-core/src/internal/core/plugins.ts
packages/buidler-core/test/fixture-projects/plugin-loading-project/node_modules/validates-import-style/index.js
packages/buidler-core/test/fixture-projects/plugin-loading-project/node_modules/validates-import-style/package.json
packages/buidler-core/test/internal/core/plugins.ts
packages/buidler-ethers/src/index.ts
packages/buidler-solhint/src/index.ts
packages/buidler-solpp/src/index.ts
packages/buidler-truffle4/src/index.ts
packages/buidler-truffle5/src/index.ts
packages/buidler-web3-legacy/src/index.ts
packages/buidler-web3/src/index.ts

This PR disables the old-style plugins' import detection, effectively turning it into a no-op.
This was done because some corner cases were found, and it doesn't seem to be needed anymore. All of our doc and marketing material uses the new style, and it has been released for some time.

Disable old style import detection

---

packages/buidler-core/src/internal/core/providers/gas-providers.ts

This PR adds some logic to catch reverts on gas estimation. If that happens, we return the block gas limit.

Don't fail if gas estimation reverts

---

packages/buidler-core/package.json
packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/src/internal/core/providers/accounts.ts

We used to use a fork because of a TS error. Its type definitions have been removed.

Use upstream eth-sig-util

---

packages/buidler-core/src/internal/buidler-evm/provider/blockchain.ts
packages/buidler-core/src/internal/buidler-evm/provider/input.ts
packages/buidler-core/src/internal/buidler-evm/provider/modules/evm.ts
packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/src/internal/buidler-evm/provider/provider.ts
packages/buidler-core/test/internal/buidler-evm/helpers/assertions.ts
packages/buidler-core/test/internal/buidler-evm/provider/modules/evm.ts

This PR adds to new RPC methods to Buidler EVM: `evm_snapshot` and `evm_revert`.
They accept the same parameters and behave like the Ganache implementation of those methods.

Add snapshots functionality to Buidler EVM

---

docs/guides/deploying.md

The example: 
```sh
npx buidler run --network your-network scripts/deploy.js
```
is missing the command "run"

corrected the run command.

---

packages/buidler-core/src/internal/solidity/imports.ts
packages/buidler-core/test/internal/solidity/imports.ts

We are using a parser to extract Solidity imports. This sometimes fails, mostly when the parser fails to detect invalid syntax.
This PR adds a fallback method to extract the imports using a regexp.

Add regexp-based imports extraction as a fallback

---

packages/buidler-core/src/internal/cli/project-creation.ts

Web3.js has released an RC version as `latest`. This breaks the sample project installation, because Buidler validates its plugins' dependencies, and the RC version fails that validation.
This PR fixes this situation by installing `web3@^1.2.0` instead of `web3`.

Fix Web3 installation in the sample project

---

packages/buidler-core/src/internal/buidler-evm/stack-traces/consoleLogger.ts
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/contract-creation/not-reverting/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/contract-creation/not-reverting/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/contract-creation/reverting/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/contract-creation/reverting/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/multiple-messages/not-reverting/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/multiple-messages/not-reverting/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/multiple-messages/reverting/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/multiple-messages/reverting/test.json

This PR fixes a bug in the console.log module of Buidler EVM. 
Before this changes, it only paid attention to console.log in directly called contracts, and not in internal messages. This PR fixes that and adds regression tests for it.

Make console.log work for internal txs

---

packages/buidler-core/src/internal/buidler-evm/stack-traces/consoleLogger.ts
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/multiple-messages/multiple-creates/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/console-logs/multiple-messages/multiple-creates/test.json

Another iteration of #427, this time covering internal txs made from constructors

Fix console.log in internal txs made from constructors

---

CONTRIBUTING.md
scripts/run-tests.js

* Document Docker Desktop requirement for `buidler-vyper` package tests.
* Ignore Vyper tests for Windows environment, since Docker Desktop is not available unless using Windows 10 Pro version.
✅ Tested on Windows 10

Tests setup improvement

---

packages/buidler-core/src/internal/buidler-evm/provider/node.ts

This PR improves Buidler EVM's invalid nonce error message.
Most of the time this error happens when users forget an `await` and run multiple transactions in parallel. We added a hint about this to the error message.

Improve Buidler EVM's invalid nonce error message

---

packages/buidler-waffle/src/index.ts

This PR fixes a problem with the Waffle plugin.
Waffle's provider was being created in the BRE extender function, which makes a `net_version` request. This was triggering Buidler EVM's intialization before the compilation process finished.
This PR makes the extension a `lazyObject`.

Make the Waffle plugin's BRE extension lazy

---

docs/guides/waffle-testing.md
packages/buidler-waffle/README.md
packages/buidler-waffle/package.json
packages/buidler-waffle/src/index.ts

Simplifies the installation of `buidler-waffle`, and makes it work when linked for local development.

Buidler waffle fixes

---

packages/buidler-core/src/builtin-tasks/node.ts

This task has a check that prevents you from running it using `--network`, but it was failing when a `defaultNetwork` was set.
This PR fixes it.

Fix node task's network selection protection

---

docs/guides/vscode-tests.md

This PR adds info about how to run ts-based tests from within vscode.

Add TypeScript info to vscode guide

---

packages/buidler-core/src/internal/core/errors-list.ts

When a plugin requires another one to be installed, the error message says:
```
npm install --save-dev @nomiclabs/buidler-web3@^1.2.0
```
which is nice because you can easily copy and paste it (well, unless you use yarn, but that's something for a different issue). The problem is that this doesn't work in zsh if you have `extendedglob` enabled.
This PR just surrounds the package and version with double quotes. Maybe a better solution is to check if there's a caret in the version and add quotes just in that case... but that seems more involved, so I went with the easy solution.

Add quotes package version

---

packages/buidler-core/test/internal/core/typescript-support.ts
scripts/run-tests.js

Run non-ganache-dependant packages tests in parallel.
The ganache-dependant packages are run in series, to prevent overloading the local ganache instance with requests. 
This is an just experimental or "proposal" PR. The intention is to discuss if the tradeoff of a faster global test execution time, is worth the "sacrifice" in clarity of the test logs (they will be unavoidably interleaved). However, maybe this is not too bad considering that the important stuff is still visible, such as a failing test and context info on which/where/why the test failed. Also, as a matter of thought, maybe we can think on reducing the amount of logs by using a different test reporter, such as the builtin "dot" reporter - we probably don't need to see over and over the names of the tests that do pass.
On …

Test dev perf enhancements III (global test run in parallel)

---

.github/workflows/CI.yml

Run CI triggers on:
1. Push to main branches (master, development) + auxiliar "wip*"-prefixed brances (for internal use)
2. Pull Request from any branch, internal or external (forks)
The only issue is that we won't get checks on regular feature/fix/wip branches until a PR is created.. We'll see if we can find a better alternative from the GH community (on [this post](https://github.community/t5/GitHub-Actions/Duplicate-checks-on-quot-push-quot-and-quot-pull-request-quot/m-p/52171#M8425) I've created)

Fix ci run

---

packages/buidler-core/src/internal/core/providers/construction.ts
packages/buidler-core/src/types.ts

The Aragon buidler plugin requires extra headers to identify itself to [Frame](https://frame.sh/)
This PR applies the existing extraHeaders functionality to the user's provided network config
---
If you would prefer this change to target the `master` branch see PR https://github.com/nomiclabs/buidler/pull/501

Allow extra headers

---

docs/buidler-evm/README.md
packages/buidler-core/src/internal/buidler-evm/provider/input.ts
packages/buidler-core/src/internal/buidler-evm/provider/modules/evm.ts
packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/test/internal/buidler-evm/provider/modules/evm.ts

**Changes:**
1. Allow evm_mine to accept a timestamp param to mine an empty block at the exact timestamp.
2. Add new evm_setNextBlockTimestamp to register a timestamp for the next block to be mined at.
3. Add the doc for evm_setNextBlockTimestamp.
4. Add relevant tests for those changes.
**Noted behaviors:**
Regarding `evm_setNextBlockTimestamp`, it requires one and only one timestamp param. It set the timestamp as a field named `_nextBlockTimestamp` of the `node`, this field is taken and restored as per snapshot operations, just like `blockTimeOffsetInSeconds`. Once the `_nextBlockTimestamp` is set, the next block will be mined with the timestamp set to its value, EXCEPT if the next block is mined with `evm_mine(timestamp`. Whenever a new block is mined, `_nextBlockTimestamp` is reset to …

Enable buidler evm to support exact timestamp testing

---

docs/config/README.md
packages/buidler-core/src/internal/core/config/config-validation.ts
packages/buidler-core/src/internal/core/providers/construction.ts
packages/buidler-core/src/types.ts
packages/buidler-core/test/internal/core/config/config-validation.ts

This PR does a few small improvements to #502:
- It renames `headers` to `httpHeaders`.
- Documents this new option.
- Adds validation logic for it.

Http headers config polishing

---

packages/buidler-core/src/internal/buidler-evm/provider/modules/eth.ts
packages/buidler-core/src/internal/buidler-evm/provider/modules/evm.ts
packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/test/internal/buidler-evm/helpers/contracts.ts
packages/buidler-core/test/internal/buidler-evm/provider/modules/eth.ts
packages/buidler-core/test/internal/buidler-evm/provider/modules/evm.ts

1. pending block tag will execute the call in a new block, hence higher block number and higher timestamp
2. latest block tag (or no block tag) will execute the call in the latest block
3. earliest block tag or specific block number are NOT supported, yet
Correct time offset management
1. if a new block is mined with a fixed timestamp (either via evm_mine or evm_setNextBlockTimestamp), time offset will be recalculated as `timestamp - realtime`
2. if a new block is mined with the auto generated timestamp (which is `realtime + timeoffset`), time offset stays unchanged
3. Refactored and moved some timestamp logic and validation to the node scope instead of the evm scope

Correct behavior of block tag in eth_call and proper time offset management

---

packages/buidler-core/package.json
packages/buidler-core/src/internal/solidity/imports.ts

This PR changes our Solidity parser to @fvictorio's fork. 
This should fix our import extraction logic. While we have a fallback implementation, it's not very accurate and gives false positives very easily. Having a up-to-date parser is clearly better.
Note that this parser is a fork of Consensys Dilligence's fork of Fede Bond's parser, and is also used by solidity-coverage.

Update Solidity parser

---

docs/.vuepress/components/Plugins.vue
docs/.vuepress/config.js
docs/.vuepress/theme/Layout.vue
docs/.vuepress/theme/Navbar.vue
docs/.vuepress/theme/styles/code.styl
docs/.vuepress/theme/styles/theme.styl
docs/README.md
docs/buidler-evm/README.md
docs/getting-started/README.md
docs/guides/create-task.md
docs/guides/ganache-tests.md
docs/guides/typescript.md
docs/guides/vscode-tests.md
docs/package.json
docs/troubleshooting/common-problems.md
docs/tutorial/debugging-with-buidler-evm.md
docs/tutorial/writing-and-compiling-contracts.md

The title is self explanatory but there are some things to consider:
- I followed [this guide](https://florimond.dev/blog/articles/2019/06/vuepress-upgrade-1-0/) and [the official migration guide](https://v1.vuepress.vuejs.org/miscellaneous/migration-guide.html)
- `::: tips :::` now require a plugin to work which I installed, same as `ga`
- the `.content` class which we're using for defining styles now has a `__default` sufix. Didn't find a reason for this but had to add some new selectors to `styles.styl`
- [Custom Layouts](https://v1.vuepress.vuejs.org/theme/default-theme-config.html#custom-page-class) behaviour changed, I had to edit both `Plugins.vue` and `Layout.vue` in order to make the `/plugins` section work (part of this is explained …

[web/docs] Upgrade Vuepress from 0.x to 1.x

---

packages/buidler-etherscan/src/etherscan/EtherscanService.ts

* Otherwise the delay between requests is too short, and
Etherscan API might return an error:
`Max rate limit reached, please use API Key for higher rate limit`.

buidler-etherscan plugin: increase verification delay 1000 -> 3000.

---

package.json
packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/src/internal/internalTypes.ts
packages/buidler-core/src/internal/util/lazy.ts
packages/buidler-ethers/README.md
packages/buidler-ethers/package.json
packages/buidler-ethers/src/ethers-provider-wrapper.ts
packages/buidler-ethers/src/helpers.ts
packages/buidler-ethers/src/type-extensions.d.ts
packages/buidler-ethers/test/ethers-provider-wrapper.ts
packages/buidler-etherscan/package.json
packages/buidler-etherscan/test/util/ContractDeployer.ts
packages/buidler-ganache/package.json
packages/buidler-waffle/package.json
packages/buidler-waffle/src/waffle-provider-adapter.ts

Fix #534 
I thought I would contribute to migrating to ethers v5.x earlier by submitting a PR. Most of the API changes were pretty straightforward and there weren't any critical complications. Changes include updating ethers and typescript since Typescript was outdated related to ethers typings
All the tests are passing except one which was skipped, however there are two issues that should be investigated so I commented with FIXME notes:
1) lazyFunction<T extends Function> wasn't injecting types correctly because of the Typescript upgrade (temporarily solved by type casting functionCreator)
2) error_please test for ethers-provider-wrapper was failling deepEqual although the error messages looked very similar (temporarily solved by skipping test)

Migrate to ethers v5

---

config/tslint/tslint.json
packages/buidler-core/src/internal/buidler-evm/provider/node.ts

This PR fix a bug reported that prevented Buidler EVM to return past logs in some cases.
The cause of the bug was that `<=` was being used to compare two `BN.js` instances. This PR fixes it and enables a tslint rule to prevent this mistake to happen again.

Fix error when getting past logs

---

packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/test/internal/buidler-evm/provider/modules/eth.ts

This PR fixes a bug that made Buidler EVM fail if a `fromBlock` or `toBlock` larger than the latest block's number was used.
fixes #484

Fix out-of-bound log filters

---

.github/workflows/CI.yml

GitHub Actions' cache has been very unreliably lately, and it's unclear if it was bringing any benefit. This PR removes it.
This should be considered a WIP/experimental PR.

Remove cache from github actions

---

packages/buidler-core/src/internal/core/params/argumentTypes.ts
packages/buidler-core/test/internal/core/params/argumentTypes.ts
packages/buidler-core/test/internal/core/runtime-environment.ts

We accidentally introduced a small breaking change in 1.3.0. Before that version was released, arguments passed to Buidler tasks weren't validated. The only thing Buidler knew how to do was parsing strings into those values.
Starting with Buidler 1.3.0, we introduced runtime type validations when running tasks programmatically. This validation logic was off for the json type, as some values that could be parsed from strings into jsons, were accepted by the validation strategy.
This PR fixes this, by accepting anything but `undefined` as a valid `json` argument.
Thanks @gitpusha for reporting this issue.

Make json ArgumentType accept anything but undefined

---

packages/buidler-etherscan/src/index.ts

Add missing file extension in reconstructed full contract name
Fixes #560

Fix buidler-etherscan unable to verify

---

packages/buidler-ganache/package.json

This PR fixes buidler-ganache's tests by reinstalling some dependencies that are needed to run them.

Fix buidler-ganache tests

---

packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/src/internal/constants.ts
packages/buidler-core/src/internal/core/config/config-validation.ts

This PR fixes an error in the config validation module that made it load Buidler EVM every time.

Don't load Buidler EVM if it's not necessary

---

packages/buidler-core/console.sol

* see https://forum.openzeppelin.com/t/solidity-0-6-8-introduces-spdx-license-identifiers/2859 for details

Update console.log to solc v0.6.8

---

docs/buidler-evm/README.md
docs/build-plugins-doc.ts
docs/fix-api-docs.sh
docs/getting-started/README.md
docs/plugins/README.md

- Adds `npx buidler node` section to Quick Start guide
- Removes "Help us improve this page!" on plugins and API pages
- Informs when a plugin is external (not created by Nomic Labs)

Documentation improvements

---

docs/advanced/buidler-runtime-environment.md

The [previous link](https://buidler.dev/advanced/buidler-runtime-environment.html#creating-your-own-tasks) wasn't redirecting the user anywhere.

docs: fix broken link to tasks docs

---

docs/guides/typescript.md

[This is how next.js imports type extensions](https://nextjs.org/docs/basic-features/typescript) and I think it'd be great to mention this alternative in the Buidler docs.
This is a solution to one of the problems I enumerated in #586.

docs: add triple-slash directive alternative

---

docs/guides/typescript.md

At least as of ethers@4.0.47 and buidler@1.3.3, the "eth" property doesn't exist anymore within the "ethers" object imported from @nomiclabs/buidler.

docs: update ethers API for getSigners

---

packages/buidler-waffle/src/index.ts
packages/buidler-waffle/src/waffle-chai.ts

This PR is a workaround an issue with buidler-waffle that leads to source maps not working and line numbers being off.
To learn more about this issue: https://github.com/EthWorks/Waffle/issues/281

Workaround buidler-waffle source maps issue

---

packages/buidler-web3/package.json

This PR just changes the minimum version of `Web3` required to use `@nomiclabs/buidler-web3`.
Thanks @felix2feng for reporting and testing this 🙌

Allow using buidler-web3 with older web3 versions

---

packages/buidler-core/sample-project/buidler.config.js
packages/buidler-core/sample-project/contracts/Greeter.sol

Open Zeppelin's contracts are already at `^0.6.0`, and I think it's time to pull ahead here. Especially if you're creating a project from scratch, it's likely that you will choose version 0.6 or above.

Update sample project Solidity version to ^0.6.8

---

.github/workflows/CI.yml
.github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
packages/buidler-core/LICENSE
packages/buidler-core/sample-project/LICENSE.md
packages/buidler-core/sample-project/contracts/Greeter.sol
packages/buidler-etherscan/package-lock.json

This PR relicenses the sample project to The Unlicense.
It was previously already released into the public domain but without a proper license.
This change is necessary to avoid warning that `solc` emits when compiling files without a license.

Relicense the sample project to The Unlicense

---

packages/buidler-ethers/src/helpers.ts

This PR addresses #647, making tests run with ethers much faster. Some transactions run up to 10x faster, and received reports of entire test suits running 5x faster.
This only addresses it for ethers v4, so the issue should be left open. ethers v5 will be released tomorrow.

[buidler-ethers] Use network's config default gas value if present

---

docs/guides/waffle-testing.md
packages/buidler-core/package.json
packages/buidler-core/src/internal/cli/project-creation.ts
packages/buidler-ethers/README.md
packages/buidler-ethers/package-lock.json
packages/buidler-ethers/package.json
packages/buidler-ethers/src/ethers-provider-wrapper.ts
packages/buidler-ethers/src/helpers.ts
packages/buidler-ethers/src/index.ts
packages/buidler-ethers/src/type-extensions.d.ts
packages/buidler-ethers/test/ethers-provider-wrapper.ts
packages/buidler-ethers/test/index.ts
packages/buidler-waffle/README.md
packages/buidler-waffle/package-lock.json
packages/buidler-waffle/package.json
packages/buidler-waffle/src/deploy.ts
packages/buidler-waffle/src/fixtures.ts
packages/buidler-waffle/src/index.ts
packages/buidler-waffle/src/link.ts
packages/buidler-waffle/src/matchers.ts
packages/buidler-waffle/src/tsconfig.json
packages/buidler-waffle/src/type-extensions.d.ts
packages/buidler-waffle/src/waffle-chai.ts
packages/buidler-waffle/src/waffle-provider-adapter.ts
packages/buidler-waffle/test/buidler-project/test/tests.js
packages/buidler-waffle/test/index.ts
packages/buidler-waffle/tsconfig.json
scripts/check-dependencies.js

This PR introduces the necessary changes to support ethers v5 and waffle v3. These are:
* Creates an ethers v5 based `@nomiclabs/buidler-ethers@2.0.0`.
* Creates an ethers v5 and waffle v3 based `@nomiclabs/buidler-waffle@2.0.0`.
* Creates a new version of Buidler that uses these new plugins in the sample project.
* Updates the Waffle testing guide.

Ethers v5 and Waffle v3 support

---

packages/buidler-core/src/internal/sentry/anonymizer.ts
packages/buidler-core/src/internal/sentry/reporter.ts
packages/buidler-core/src/internal/sentry/subprocess.ts
packages/buidler-core/src/internal/sentry/transport.ts
packages/buidler-core/src/internal/util/packageInfo.ts
packages/buidler-core/test/internal/sentry/anonymizer.ts
packages/buidler-core/test/internal/sentry/reporter.ts

This PR improves what errors are reported

Improve error reporting

---

packages/buidler-core/src/internal/cli/ArgumentsParser.ts
packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/core/errors-list.ts
packages/buidler-core/src/internal/core/params/argumentTypes.ts
packages/buidler-core/src/internal/core/runtime-environment.ts
packages/buidler-core/src/internal/core/tasks/task-definitions.ts
packages/buidler-core/src/types.ts
packages/buidler-core/test/internal/core/params/argumentTypes.ts
packages/buidler-core/test/internal/core/tasks/task-definitions.ts

This PR refactors how `ArgumentType` are handled.
It introduces the following breaking changes:
* There are now two types for `ArgumentType`s
* `ArgumentType`, which validates args at runtime
* `CLIArgumentType` which can also parse strings into the arg type.
* It forbids non-internal tasks from using non-cli `ArgumentType`s
* It moves the `ArgumentType`'s types to `types.ts` (🤪), as they are part of the public api
* It introduces the `any` argument type

Refactor ArgumentTypes

---

packages/buidler-core/console.sol

I'm not sure if we should use `<0.8.0` or `<=0.7.0`. I think it's better to use `<0.8.0` and fix it if there's some breaking change in 0.7.x, than having to upgrade the pragma for each new patch.

Upgrade console.sol version pragma

---

docs/guides/waffle-testing.md

I fought with a "Transaction run out of gas" generic error for 24hrs to end up finding that it's Waffle's fault:
https://github.com/EthWorks/Waffle/blob/3.0.2/waffle-cli/src/deployContract.ts#L4-L7
They set a default gas limit of 4 million when deploying a contract, but don't throw a specific reason when this is the reason for why a test case fails.
It'd be nice to warn Buidlereans about this.

docs: add warning about waffle defaults

---

packages/buidler-core/src/internal/buidler-evm/stack-traces/source-maps.ts
packages/buidler-core/test/internal/buidler-evm/stack-traces/compilation.ts
packages/buidler-core/test/internal/buidler-evm/stack-traces/test.ts

For example:
```
$ BUIDLER_TESTS_SOLC_PATH=/path/to/soljson.js BUIDLER_TESTS_SOLC_VERSION=0.6.12 npm test
```
Maybe this should be documented somewhere? Where is the best place to do it?

Allow running tests with path to solc

---

packages/buidler-core/src/internal/context.ts
packages/buidler-core/src/internal/core/config/config-loading.ts
packages/buidler-core/src/internal/core/errors-list.ts
packages/buidler-core/src/internal/core/plugins.ts
packages/buidler-core/src/internal/core/typescript-support.ts

This PR introduces two small changes that ensure that Buidler works correctly with monorepos, even is different packages are hoisted.
Fixes #570
Fixes #468

Make Buidler work correctly with monorepos

---

packages/buidler-waffle/src/deploy.ts
packages/buidler-waffle/src/fixtures.ts
packages/buidler-waffle/src/index.ts
packages/buidler-waffle/src/link.ts
packages/buidler-waffle/src/type-extensions.d.ts
packages/buidler-waffle/src/waffle-chai.ts
packages/buidler-waffle/src/waffle-provider-adapter.ts
packages/buidler-waffle/test/buidler-project-custom-accounts/buidler.config.js
packages/buidler-waffle/test/buidler-project/test/tests.js
packages/buidler-waffle/test/helpers.ts
packages/buidler-waffle/test/index.ts

Fixes #690.
I only changed the `fixtures.ts` file in the `buidler-waffle` package. Changelog:

fix: Signer instead of Wallet in loadFixture

---

packages/buidler-core/src/internal/buidler-evm/stack-traces/compiler-to-model.ts
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_5/abi-v2/nested-arrays-as-public-parameter/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_5/abi-v2/nested-arrays-as-public-parameter/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_5/special-cases/function-type-as-public-parameter/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_5/special-cases/function-type-as-public-parameter/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_6/abi-v2/nested-arrays-as-public-parameter/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_6/abi-v2/nested-arrays-as-public-parameter/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_6/special-cases/function-type-as-public-parameter/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_6/special-cases/function-type-as-public-parameter/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_7/abi-v2/nested-arrays-as-public-parameter/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_7/abi-v2/nested-arrays-as-public-parameter/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_7/special-cases/function-type-as-public-parameter/c.sol
packages/buidler-core/test/internal/buidler-evm/stack-traces/test-files/0_7/special-cases/function-type-as-public-parameter/test.json
packages/buidler-core/test/internal/buidler-evm/stack-traces/test.ts

This improves the function selector derivation by looking at the `functionSelector` field whenever available and uses the `typeDescription.typeString` field for function and array types.
A couple of test cases were added for all supported compiler series that pass after applying these improvements:
- A contract that has a public function with a function typed parameter.
- A contract that has a public function with a nested array parameter.

Improve the derivation of function selectors from the AST

---

packages/buidler-etherscan/README.md
packages/buidler-etherscan/src/ABIEncoder.ts
packages/buidler-etherscan/src/ABITypes.ts
packages/buidler-etherscan/src/index.ts
packages/buidler-etherscan/src/solc/bytecode.ts
packages/buidler-etherscan/test/buidler-project/buidler.config.js
packages/buidler-etherscan/test/buidler-project/contracts/TestLibrary.sol
packages/buidler-etherscan/test/integration/PluginTests.ts
packages/buidler-etherscan/test/unit/ABIEncoder.ts
packages/buidler-etherscan/test/unit/solc/bytecode.ts

This pull request:
- Adds support for library contracts themselves.
- Adds a nice error message for integer overflow when encoding constructor arguments.
- Improves the error messages for failures during the importation of constructor argument modules.

Library support for buidler-etherscan

---

packages/buidler-core/package-lock.json
packages/buidler-core/package.json
packages/buidler-core/src/builtin-tasks/compile.ts
packages/buidler-core/src/internal/cli/analytics.ts
packages/buidler-core/src/internal/util/global-dir.ts

This adds a global directory module that is responsible for reading and writing global (i.e. per user) settings, data and cache for internal features.

Add global dir module to buidler-core internals.

---

packages/buidler-core/src/internal/buidler-evm/provider/modules/eth.ts
packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/test/internal/buidler-evm/provider/modules/eth.ts

This PR allows optional block number parameter in RPC methods eth_call, eth_estimateGas, eth_getBalance, eth_getTransactionsCount, eth_getStorageAt and eth_getCode.

Allow optional block number parameter

---

packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/lib/buidler-lib.ts
packages/buidler-core/src/register.ts

This introduces a tiny breaking change. Now `bre.buidlerArguments.network` can be `undefined` at runtime.
This was accepted by it's type, but was always set during runtime for backwards compatibility with versions that didn't have a `defaultNetwork` setting.

Let BuidlerArguments.network be undefined

---

packages/buidler-core/src/internal/hardhat-network/provider/errors.ts
packages/buidler-core/src/internal/hardhat-network/provider/modules/hardhat.ts
packages/buidler-core/src/internal/hardhat-network/provider/node.ts
packages/buidler-core/test/internal/hardhat-network/provider/fork/ForkStateManager.ts
packages/buidler-core/test/internal/hardhat-network/provider/modules/hardhat.ts

This PR restricts the restriction of `buidler_impersonate` that prevented it from working in non-forked bevm instances.

Drop restrictions to buidler_impersonate

---

packages/buidler-core/src/internal/core/providers/http.ts
packages/buidler-core/test/internal/core/providers/http.ts
packages/buidler-core/test/internal/hardhat-network/helpers/providers.ts
packages/buidler-core/test/internal/hardhat-network/jsonrpc/client.ts
packages/buidler-core/test/internal/hardhat-network/provider/forked-provider.ts
packages/buidler-core/test/internal/hardhat-network/provider/modules/eth.ts

This PR changes the HttpProvider so it makes retries when a 429 is received.

HttpProvider: Respect HTTP 429's Retry-After header

---

packages/buidler-vyper/src/compilation.ts

ethereum/vyper is out of date, new docker repo is vyperlang/vyper
fixes #814

Change docker repo from ethereum/vyper to vyperlang/vyper

---

packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/builtin-tasks/console.ts
packages/hardhat-core/src/builtin-tasks/run.ts
packages/hardhat-core/src/builtin-tasks/test.ts

I also made it so that compiler warnings are not shown with `--quiet` (errors are still shown). I'm not 100% sure about that though.

Call compile with quiet from other tasks

---

.github/workflows/CI.yml
packages/hardhat-core/src/internal/core/providers/http.ts

We disabled it some time ago because it was super slow, but apparently they fixed that. Let's see...

Enable cache in the windows CI

---

packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/core/config/config-loading.ts

I'm not sure at all about this approach, it feels like a gradient descent fix.
One alternative I can think is to change `loadConfigAndTasks` so that it returns both the user config and the resolved config, but this is a bigger change.
@alcuadrado wdyt?

Show missing solidity warning only for compile task

---

packages/hardhat-core/src/builtin-tasks/clean.ts
packages/hardhat-core/src/builtin-tasks/task-names.ts
packages/hardhat-core/src/internal/util/global-dir.ts

@alcuadrado I'm not sure if this should *only* remove the global cache, or do it *in addition* to the normal `clean` task functionality. Right now it does the former.

Add --global flag to clean task

---

packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/builtin-tasks/task-names.ts

Add a task for logging a message at the end of the compilation.
Right now the only possible message is of a successful compilation (or nothing, if there was nothing compiled) because we throw if there's a compilation error.

Add logging task at the end of the compilation

---

packages/hardhat-core/package.json
packages/hardhat-core/sample-project/hardhat.config.js
packages/hardhat-core/src/internal/cli/project-creation.ts
packages/hardhat-core/src/internal/core/config/default-config.ts
packages/hardhat-core/test/fixture-projects/default-config-project/hardhat.config.js
packages/hardhat-core/test/internal/core/config/config-resolution.ts
packages/hardhat-core/test/internal/solidity/compiler/downloader.ts
packages/hardhat-etherscan/package.json
yarn.lock

This PR:
* Upgrades the default version of solc
* Rememoves the .gitattributes & github message
* Uses a fixed solc version in the sample and empty configs, to avoid the warning
* Adds `@types` to the generated config files, as that's working again with the new plugins loading strategy

Upgrade the default version of solc and update the sample project

---

.github/workflows/CI.yml
packages/hardhat-ethers/README.md
packages/hardhat-ethers/src/helpers.ts
packages/hardhat-ethers/src/index.ts
packages/hardhat-ethers/src/type-extensions.ts
packages/hardhat-ethers/test/hardhat-project/contracts/AmbiguousLibrary.sol
packages/hardhat-ethers/test/hardhat-project/contracts/AmbiguousLibrary2.sol
packages/hardhat-ethers/test/hardhat-project/contracts/NonUniqueLibrary.sol
packages/hardhat-ethers/test/hardhat-project/contracts/TestContractLib.sol
packages/hardhat-ethers/test/hardhat-project/contracts/TestNonUniqueLib.sol
packages/hardhat-ethers/test/index.ts
packages/hardhat-ethers/test/mocha.env.js

This adds an error when creating an `ethers.contractFactory` for an abstract contract and adds an option to link libraries when creating contract factories.

Hardhat-ethers library linking.

---

CONTRIBUTING.md
docs/advanced/building-plugins.md
docs/advanced/hardhat-runtime-environment.md
docs/guides/create-task.md
docs/guides/hardhat-console.md
docs/guides/scripts.md
docs/guides/typescript.md
docs/guides/vscode-tests.md
docs/guides/waffle-testing.md
docs/tutorial/creating-a-new-hardhat-project.md
docs/tutorial/testing-contracts.md
packages/hardhat-core/LICENSE
packages/hardhat-core/README.md
packages/hardhat-core/src/internal/context.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/test/fixture-projects/plugin-dynamic-import-not-installed/hardhat.config.js
packages/hardhat-core/test/internal/context.ts
packages/hardhat-core/test/internal/core/errors.ts
packages/hardhat-waffle/README.md

This PR also replaces usages of `@nomiclabs/hardhat` in the context of
an npm package with the correct plain `hardhat`.

Remove unused errors

---

packages/hardhat-ethers/src/helpers.ts
packages/hardhat-ethers/src/type-extensions.ts

The type `ethers.BytesLike` includes hex strings.

Type simplification in hardhat-ethers plugin

---

packages/hardhat-core/src/builtin-tasks/test.ts
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/core/config/config-loading.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/core/execution-mode.ts
packages/hardhat-core/src/internal/core/project-structure.ts
packages/hardhat-core/src/internal/core/typescript-support.ts
packages/hardhat-core/src/internal/util/scripts-runner.ts
packages/hardhat-core/src/register.ts
packages/hardhat-core/test/internal/core/typescript-support.ts
packages/hardhat-ganache/test/fixture-projects/hardhat-project-with-configs/hardhat.config.ts
packages/hardhat-ganache/test/fixture-projects/hardhat-project-with-configs/scripts/custom-accounts-sample.js
packages/hardhat-ganache/test/fixture-projects/hardhat-project/hardhat.config.js
packages/hardhat-ganache/test/fixture-projects/hardhat-project/hardhat.config.ts
packages/hardhat-ganache/test/index.ts

This PR changes how TS is handled in Hardhat. Now, we consider the typescript mode to be enabled if the config is in ts. 
There's an edge case when testing plugins that use the `script-runner` module (i.e. `run('run', ...)`). Their fixture projects may have a `.js` config, so TS is not loaded in the subrprocess spawn by `script-runner`, and still try to import the plugin sources, which are in ts. This was only present in the ganache plugin, so I fixed it by turning their config files to .ts.

Update how TS is detected and loaded

---

packages/hardhat-core/sample-project/scripts/sample-script.js
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/cli/project-creation.ts
packages/hardhat-core/src/internal/core/execution-mode.ts
packages/hardhat-core/src/internal/core/project-structure.ts
packages/hardhat-core/src/internal/util/packageInfo.ts
packages/hardhat-core/test/internal/util/packageInfo.ts

This PR updates the project creation module:
* It now creates a `package.json` if none is present.
* The empty config creation also instructs you to install hardhat if necessary
* The sample project also installs hardhat if necessary
* We now use double quotes between packages when printing instructions.
It also fix a minor error in the sample project, that prevented its sample script from working as instructed after the sample project is initialized.
Finally, it fixes a bug in how we detect that an installation is not local.

Update project creation module

---

docs/_redirects
docs/errors/buidler-errors.md

This PR adds the necessary redirects to the website to avoid 404s.
It contains two commits. The first one adds the redirects needed because of the rename from Buidler to Hardhat. To get to know which redirects were needed, I used this command:
`git diff --summary --diff-filter=ACDMR  development site-migration-redirects docs`
The second commit adds a "Buidler errors" section to the site, and its redirects. What I did was just building the site from `development`, and copy pasting those autogenerated things.
This PR is based on the `hardhat.org` branch to avoid conflicts.

Site migration redirects

---

packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
packages/hardhat-core/test/internal/solidity/compiler/downloader.ts
packages/hardhat-core/test/internal/solidity/compiler/index.ts

This PR avoids unzipping .exe files in windows. This is necessary
because solc builds for windows are distributed as .exe files from
0.7.2, but were .zip files before that version.
This also tries to handle unexpected errors when the compiler is
obtained: if there was such an error while getting a native compiler,
it tries to fetch the solcjs compiler instead.
One downside of this is that if a problem appears and it's persistent,
then hardhat will try to download the native compiler *every time*, fail
and *then* use solcjs.

Fix native compiler in windows

---

packages/hardhat-core/src/internal/cli/cli.ts

There is already a check that disables telemetry inside of `analytics.ts`, however, the prompt is still shown. This is problematic in CI environments especially because there is currently no way to skip this check (e.g. with `--yes` // `--no`). As a result, CI currently gets stuck infinitely.

fix: do not prompt for consent in ci environments

---

packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/cli/project-creation.ts

This PR implements three changes to the telemetry consent prompt:
1. It doesn't show it if not running in an interactive terminal. When running hardhat from a script, it defaults to not reporting anything.
2. It adds a timeout to the prompt. If we don't get an answer in a short period of time, we don't report anything, nor store any consent value.
3. Don't enable the error reporting unless we have explicit consent from the user.

Fix telemetry consent prompt

---

packages/hardhat-ethers/src/type-extensions.ts

This removes standalone types in `hardhat-ethers` type extensions.

Warn against standalone types in hardhat-ethers type extensions.

---

packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/utils/source-names.ts
packages/hardhat-core/test/utils/source-names.ts

Fix source name validation for names that start with '.'

---

packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
packages/hardhat-core/src/types/config.ts
packages/hardhat-etherscan/package.json
packages/hardhat-etherscan/src/etherscan/EtherscanService.ts
packages/hardhat-etherscan/src/index.ts
packages/hardhat-etherscan/src/pluginContext.ts
packages/hardhat-etherscan/src/solc/bytecode.ts
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/.gitignore
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/ReentrancyGuard.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/TestContract.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/TestContract1.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/TestLibrary.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/TestParamList.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/TestReentrancyGuardImported.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/TestReentrancyGuardLocal.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/imported/ReentrancyGuard.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/contracts/libraries/SafeMath.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/hardhat.config.js
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-only-contracts/paramList.js
packages/hardhat-etherscan/test/helpers.ts
packages/hardhat-etherscan/test/integration/PluginTests.ts
yarn.lock

This adds a minimum build subtask that returns compiler input and output
for a single contract. Artifacts are not emitted for this build.
If the minimum build verification fails, the plugin falls back to verifying the contract with a full build.
Fixes #804.

Add minimum build verification for hardhat-etherscan.

---

packages/hardhat-ethers/src/ethers-provider-wrapper.ts
packages/hardhat-ethers/src/signer-with-address.ts
packages/hardhat-ethers/test/index.ts

Closes #1037.
This case was being handled already but I added a test for it since it is quite easy to make this mistake.
Update:
The test wasn't reproducing the issue correctly. There is no way to reproduce it in the plugin test environment that I know of.
#1037 is only one specific way of triggering this slowdown. With this fix, it should be hard to trigger it now.

Fix a family of slowdown issues with Hardhat providers in ethers.

---

packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/solidity/compilation-job.ts
packages/hardhat-core/src/internal/solidity/dependencyGraph.ts
packages/hardhat-core/src/types/builtin-tasks/compile.ts
packages/hardhat-core/test/builtin-tasks/compile.ts
packages/hardhat-core/test/internal/solidity/compilation-job.ts
packages/hardhat-core/test/utils/mock-file.ts

This PR improves the errors shown when the files can't be compiled.

Improve compilation job error messages

---

packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-stack-trace.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidityTracer.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_7/out-of-gas/oog-chaining/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_7/out-of-gas/oog-chaining/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts

This PR fixes how out of gas errors are managed by the solidity tracing engine, by introducing two changes:
* Now successive OOGs are chained in a single stack traces. This happens when a contract calls another contract, which OOGs, and makes the caller OOG.
* Detects when a contract call OOGs, making the caller revert. A new stack trace entry type was introduced for this.

Fix how OOG errors are managed in Hardhat network's stack traces

---

packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/test/internal/artifacts.ts

@wighawag suggested some time ago that build info names should be deterministic, which I think it's a good idea, as it makes collaboration and debugging easier. Right now the names change on every build, so sometimes you lose your references, and makes it harder to communicate with teammates.
I initially thought that using a hash-based identifier would be too slow, as the solc output can be incredibly big. Today I realized that we don't need to include the output in the hash preimage, cause it's deterministically derived from the rest of the fields.
This PR implements just that.
Thanks @wighawag for the idea.

Deterministic buildInfo names

---

packages/hardhat-core/src/internal/hardhat-network/stack-traces/compiler-to-model.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/contracts-identifier.ts

This issue is the first step in having stack traces for mainnet contracts. 
I modified the contract identifier class so that it ignores the metadata hash field.
This is really hard to test. We should make the model classes that Hardhat network uses serializable so that we can easily construct test cases using Hardhat, serialize them, and save them.
Please, review this carefully, @fvictorio. If you want, we can jump into a quick call to do it together.

Ignore the metada hash in the ContractsIdentifier class

---

packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/provider/types/Block.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/contracts-identifier.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth.ts

This PR fixes:
1. How HardhatProvider's logging is initialized. `console.log`s weren't going through the logging infra if `loggingEnabled` was true in the `hardhat` network.
2. Fix how `eth_call` handled `blockTag`, actually running the calls in the block's context.
3. Let `eth_call` use gas limit's higher than the block's one. This is implemented with a temporal workaround which has been documented in the code.

Fix eth_call and HarhatProvider's logging initialization

---

packages/hardhat-core/package.json
yarn.lock

Closes #1095.
This PR upgrades `@solidity-parser/parser` to the latest version, that should stop showing the node 14 warning about the circular dependency and should work fine with node versions below 14.

Upgrade solidity parser

---

packages/hardhat-core/src/internal/core/config/config-validation.ts
packages/hardhat-core/test/internal/core/config/config-validation.ts

Closes #1051.
This PR modified the _configuration validator_ code in order to disallow `url` property of the `hardhat` object. This issue was caused because the modified conditional clause was testing `url` against `undefined`, which is a falsy value, but the property could be present after all. In order not to tackle with validations against this property in a subsequent step of the execution (which indeed is the **purpose** of the _configuration validator_) this conditional clause now uses `.hasOwnProperty` instead of comparing the value with `undefined`, where this property could be present with an undefined value.
Test cases have been added as well for the case of `hardhat` object containing an `url` property with value equal or not equal to `undefined`.
I am happy to bring my efforts …

Hardhat network configuration should not contain url property

---

docs/tutorial/testing-contracts.md

Change `assertion objet` -> `Assertion object`

Fix typos in testing-contracts.md

---

packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts
packages/hardhat-core/test/fixture-projects/autocomplete/custom-tasks/hardhat.config.js
packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkStateManager.ts
packages/hardhat-core/test/internal/hardhat-network/provider/node.ts

This PR fixes the cost of SSTORE. Before this PR writing a value that used to be zero was incorrectly priced.

Fix SSTORE gas cost in fork mode

---

packages/hardhat-core/src/utils/source-names.ts
packages/hardhat-core/test/fixture-projects/project-with-hardhat-directory/.gitignore
packages/hardhat-core/test/fixture-projects/project-with-hardhat-directory/contracts/Greeter.sol
packages/hardhat-core/test/fixture-projects/project-with-hardhat-directory/hardhat.config.js
packages/hardhat-core/test/fixture-projects/project-with-hardhat-directory/hardhat/README.md
packages/hardhat-core/test/internal/solidity/resolver.ts
packages/hardhat-core/test/utils/source-names.ts

If the directory `hardhat` exists in the project root, then importing
`hardhat/console.sol` fails if it doesn't exist within such a directory.
This adds an exception for this case and ensures the path resolves to
the `console.sol` packaged with Hardhat.
Fixes #998.

Fix name resolution for `hardhat/console.sol` when `hardhat` directory exists.

---

docs/guides/mainnet-forking.md

The first time I read mainnet forking I tried using my Infura account, but that didn't work. I think specifying that the node must be an archive node helps a bit.

docs: mention archive noe in mainnet-forking

---

docs/config/README.md

The default value is actually 10000 ETH but writing 10000 in the balance field will not produce anything. You need to write 10000 ETH in Wei, i.e 10000000000000000000000.

Fixed balance default value in Wei.

---

packages/hardhat-etherscan/src/etherscan/EtherscanService.ts
packages/hardhat-etherscan/src/index.ts
packages/hardhat-etherscan/src/network/prober.ts
packages/hardhat-etherscan/test/integration/PluginTests.ts

The Etherscan backend may not see the deployed bytecode if it was deployed recently. This adds an error message that better describes this issue and recommends waiting for five confirmations at least.
Apart from that, this pull request improves some messages and prints the URL to the verified contract in the console when the verification is successful.

Add error message for one case in hardhat-etherscan.

---

docs/guides/waffle-testing.md

Adds a warning block describing asynchronous Waffle matchers to the testing documentation. 
I chose to place this immediately after the existing link to Waffle docs and description of matcher use. I chose to make it a warning as improper usage results in false negatives when testing.
To consider: recommend using the eslint `no-floating-promises` plugin?
Discussion coming from here:
https://twitter.com/_prestwich/status/1355623851246247936

doc: add warning block about async Waffle matchers

---

packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-ethers/src/signers.ts
packages/hardhat-ethers/test/index.ts

This pull request:
- Adds JSON-RPC method `eth_signTypedData_v4` and implements it with `signTypedData_v4` of `eth-sig-util`.
- Its implementation mimics MetaMask's. It attempts to parse the typed message parameter as a JSON if it is a string.
- Modifies the JSON-RPC method `eth_signTypedData` to mark it as not supported.
- Adds JSON-RPC method `eth_signTypedData_v3` and marks it as not supported.
- Adds method `_signTypedData` for `SignerWithAddress` in `hardhat-ethers`.
- Adds test in `hardhat-ethers` for `SignerWithAddress._signTypedData`.
Context:  [EIP712](https://eips.ethereum.org/EIPS/eip-712) early implementation.

Add JSON-RPC `eth_signTypedData_v4` method to Hardhat Network.

---

packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_5/console-logs/uint/most-significant-bit-set/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_5/console-logs/uint/most-significant-bit-set/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_6/console-logs/uint/most-significant-bit-set/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_6/console-logs/uint/most-significant-bit-set/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_7/console-logs/uint/most-significant-bit-set/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_7/console-logs/uint/most-significant-bit-set/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts

Fix console.log unsigned int print.

---

packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/evm.ts

Several tests were assuming the first account had a 0 nonce, and therefore they broke after #979.
This PR mostly moves those tests to use the second account, that right now has a nonce of 0. This is very brittle, of course, but it should work for now.
There is only one non-trivial change, I will comment it inline.

Fix tests that depend on a 0 nonce

---

packages/hardhat-core/src/internal/hardhat-network/jsonrpc/client.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts

This PR fixes two errors in Hardhat Network:
1. A race condition in the fork's jsonrpc client's cache.
2. Previously, internal errors were treated as unrecognized reverts. This lead to many unrelated errors that happened when forking (e.g. HTTP errors) being treated as reverts. They are now rethrown.

Fix Hardhat Network bugs

---

docs/.vuepress/plugins.js

This PR adds [hardhat-tracer](https://github.com/zemse/hardhat-tracer) plugin to the plugins list.

Add hardhat-tracer plugin

---

packages/hardhat-core/src/internal/hardhat-network/jsonrpc/client.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts
packages/hardhat-core/test/internal/hardhat-network/jsonrpc/client.ts
packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkStateManager.ts

I discovered this while toying around with a fork of a fork (mainnet => hardhat fork => hardhat fork) to optimize our test run performance.
~~The storage slot parameter is currently incorrectly validated via the `rpcQuantity` type.~~

fix: storage slot param validation

---

packages/hardhat-core/src/internal/hardhat-network/provider/utils/reorgs-protection.ts

This PR enables caching in Hardhat Network's forking when using Ropsten.
The reason this wasn't enabled before was that there's no clear info about what was the max reorg on Ropsten. We assume now that 100 is a reasonable bound. This may not be the case, but we'd revisit it if it were to happen.
@fvictorio do you think we can add this to tomorrow's release?

Enable caching in Ropsten forks

---

packages/hardhat-core/src/internal/hardhat-network/provider/output.ts

mixHash is a [32 byte value](https://sourcegraph.com/github.com/ethereum/go-ethereum/-/blob/core/types/block.go#L83:21). The call to`bufferToRpcData` only pads the `mixHash` to 32 hexadecimal characters, which is 16 bytes. 
Currently this is breaking my usage of a forked Hardhat network with running a graph-node - https://github.com/graphprotocol/graph-node/issues/2212.

fix: pad mixHash to 32 bytes

---

docs/metamask-issue.md

The original GitHub issue linked has been closed, and a new one has been opened to support HH out of the box.
Old value: https://github.com/MetaMask/metamask-extension/issues/9827
New value: https://github.com/MetaMask/metamask-extension/issues/10290.
This PR updates the link to point to the new issue.

The MM GitHub issue has moved - fixed link

---

packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
packages/hardhat-core/test/internal/solidity/compiler/downloader.ts

This PR fixes #1332 and replaces #1329.
The difference with this PR is that it doesn't add support for nightly versions, but just fixes #1332 and updates the compilers repository url.
The implementation in #1329 lead to some really slow startup times (>10sec) in some cases, so we should redesign it. I created it so that we can push this fix in the next release, and later add support for the nightlies.

Smaller downloader fix

---

docs/config/README.md
packages/hardhat-core/src/internal/constants.ts
packages/hardhat-core/src/internal/hardhat-network/provider/HardhatStateManager.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeCommon.ts
packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts

This PR adds a new `HardhatStateManager`, based off `ForkStateManager`, which keeps everything in memory in a flat structure (i.e. no MPTs involved). This means that our blocks always have an incorrect state root now. Before this PR this only happened when forking.
`ForkStateManager` doesn't support hardforks before Spurious Dragon, as it's not possible to do that when fetching the accounts via the rpc. We kept the same limitation in `HardhatStateManager` to avoid introducing extra complexity, so we also forbid older hardforks in the config. 
This change should be reverted soon, once `DefaultStateManager` gets fixed.

Use custom state manager as a temporal fix to a bug in DefaultStateManager

---

CONTRIBUTING.md
packages/hardhat-vyper/README.md

Is it like still relevant to have 0.1.0b10 in docs? 
imho, 0.2.x looks a lil bit better

Changing ethereum/vyper to vyperlang/vyper in docs

---

docs/hardhat-network/README.md
packages/hardhat-core/package.json
yarn.lock

Vanilla `eth_signTypedData` was marked as unsupported in https://github.com/nomiclabs/hardhat/pull/1189, in favor of the v4 version. This PR updates the docs to reflect that.

Update docs on supported flavor of signTypedData

---

package.json
packages/common/package.json
packages/e2e/package.json
packages/hardhat-core/package.json
packages/hardhat-docker/package.json
packages/hardhat-ethers/package.json
packages/hardhat-etherscan/package.json
packages/hardhat-etherscan/src/network/prober.ts
packages/hardhat-ganache/package.json
packages/hardhat-shorthand/package.json
packages/hardhat-solhint/package.json
packages/hardhat-solpp/package.json
packages/hardhat-truffle4/package.json
packages/hardhat-truffle5/package.json
packages/hardhat-vyper/package.json
packages/hardhat-waffle/package.json
packages/hardhat-web3-legacy/package.json
packages/hardhat-web3/package.json
yarn.lock

This PR moves the devDependencies from the root to where they belong. This was done the other way because it worked better with npm & lerna, but we haven't used that in a long time.

Declare devDependencies in each package instead of the root

---

docs/guides/typescript.md

Change "en variable" to "env variable" 
The standard for shorthand for an environment variable is "env" not "en."
Making this change will help improve understanding of what is meant here.

Typescript Guide fix wording

---

packages/hardhat-core/sample-project/test/sample-test.js

The reason to do this is that otherwise the test doesn't work out-of-the-box when run against a testnet.

Wait for tx to be mined in sample project

---

packages/hardhat-waffle/src/waffle-chai.ts
packages/hardhat-waffle/test/fixture-projects/hardhat-project/test/tests.js

The current package does not support the hexEqual Chai matcher.
https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#hex-equal

Support HexEqual with hardhat waffle

---

.github/workflows/CI.yml
packages/e2e/.mocharc.json
packages/hardhat-core/src/internal/core/providers/http.ts

This PR disables the Hardhat Network's forking tests in all of the CI jobs, and creates a new one that runs them with a single configuration (i.e. node version and os).
This isolates the CI's instability in a single job, so that any problem with Alchemy doesn't cancel the entire CI run. Furthermore, somehow making less requests in parallel makes the test run more reliable.  We should investigate why this happens, but in the meantime let's go for this approach so that we have a reliable CI once again.

Split forking tests

---

packages/hardhat-etherscan/src/network/prober.ts

Quick PR to add support for polygon's testnet on `hardhat-etherscan`, using the api found [here](https://mumbai.polygonscan.com/apis#contracts).
The PR was based off of the previous work done in #1532 (thanks @BrknRobot !)

[feat] Add Polygon testnet support

---

packages/hardhat-etherscan/src/network/prober.ts

Because I noticed that CI was failing on the `master` branch.

Fix linter error for clean CI run

---

packages/e2e/.eslintrc.js
packages/hardhat-core/.eslintrc.js
packages/hardhat-core/test/.eslintrc.js
packages/hardhat-docker/.eslintrc.js
packages/hardhat-docker/test/.eslintrc.js
packages/hardhat-ethers/.eslintrc.js
packages/hardhat-ethers/test/.eslintrc.js
packages/hardhat-etherscan/.eslintrc.js
packages/hardhat-etherscan/test/.eslintrc.js
packages/hardhat-ganache/.eslintrc.js
packages/hardhat-ganache/test/.eslintrc.js
packages/hardhat-shorthand/.eslintrc.js
packages/hardhat-shorthand/test/.eslintrc.js
packages/hardhat-solhint/.eslintrc.js
packages/hardhat-solhint/test/.eslintrc.js
packages/hardhat-solpp/.eslintrc.js
packages/hardhat-solpp/test/.eslintrc.js
packages/hardhat-truffle4/.eslintrc.js
packages/hardhat-truffle4/test/.eslintrc.js
packages/hardhat-truffle5/.eslintrc.js
packages/hardhat-truffle5/test/.eslintrc.js
packages/hardhat-vyper/.eslintrc.js
packages/hardhat-vyper/test/.eslintrc.js
packages/hardhat-waffle/.eslintrc.js
packages/hardhat-waffle/test/.eslintrc.js
packages/hardhat-web3-legacy/.eslintrc.js
packages/hardhat-web3-legacy/test/.eslintrc.js
packages/hardhat-web3/.eslintrc.js
packages/hardhat-web3/test/.eslintrc.js

This PR changes how we define paths in our eslint config files, using absolute paths instead.
The reason I'm submitting it is that my editor was complaining that it was imposible to load the eslint config for `hardhat-core/test`. I fixed it according to the message it shown (which seemed to make sense), and `yarn lint` stopped working.
[This section of their documentation](https://eslint.org/docs/user-guide/configuring/configuration-files#relative-glob-patterns) seems to indicate that using `--config` changes how relative paths are interpreted, so my guess is that webstorm uses that, as our npm scripts don't use it.
To avoid this confusion, I used node.js' `__dirname` to declare everything with absolute paths instead.

Use absolute paths in eslint config files

---

.github/workflows/LATEST_DEPENDENCY_VERSIONS.yml

This PR fixes a Github Actions workflow that's run with the latest version of every dependency.  This workflow is scheduled to run every 8 hours.
The changes are:
- Upgrade node to version 12, as solcjs has a bug with node 10.
- Install the correct docker image of vyper
- Stop installing `node-gyp-cache`
- Use a better workflow name. No idea why I used a THAT_NAME in the first place.
- Removed the forking-related tests, as those are too unstable to run in a cron job, and those don't use anything new wrt dependencies.
Note that I tested the workflow by making it run on push, and then rebased this PR.

Fix LATEST_DEPENDENCY_VERSIONS workflow

---

docs/guides/mainnet-forking.md

This bit a user because `ethers.provider.getSigner` doesn't return a `SignerWithAddress`.

Use `ethers.getSigner` instead of `ethers.provider.getSigner`

---

packages/hardhat-core/src/internal/core/jsonrpc/types/output/transaction.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/rpcToBlockData.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/rpcToTxData.ts
packages/hardhat-core/src/internal/hardhat-network/provider/transactions/ReadOnlyValidEIP1559Transaction.ts
packages/hardhat-core/test/internal/hardhat-network/provider/node.ts

This PR implements the EIP-1559 version of the transaction class that we use to read remote txs when forking.
This completes most of the forking functionality changes required for London.

Implement ReadOnlyValidEIP1559Transaction

---

packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/estimateGas.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts

This PR turned out to be more challenging than expected.
The reason for this are that:
(1) `eth_call` should run an EVM Message that doesn't pay gas unless the user specifies it. EIP-1559 makes this more complex, as you can't just set the gas price to 0, because of the baseFeePerGas. To workaround this we create a new block with base fee 0 when we run an `eth_call`, but that will break BASEFEE (see: #1688).
(2) The default `maxFeePerGas` and `maxPriorityFeePerGas` in `eth_estimateGas` can be tricky to compute, specially when it's in an older block. I'm not sure how to test this yet.
On the plus side, this PR also fixes #1436.
fixes #1601
fixes #1602

Adapt `eth_estimateGas` and `eth_call` to London

---

packages/hardhat-core/src/internal/hardhat-network/provider/TxPool.ts
packages/hardhat-core/test/internal/hardhat-network/provider/TxPool.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts

This was almost done by @fvictorio :)
The only difference is that, in Geth, both `maxFeePerGas` and `maxPriorityFeePerGas` need to be 110% higher.
See: https://github.com/ethereum/go-ethereum/blob/f05419f0fb8c5328dca92ea9fb184d082300344a/core/tx_list.go#L279
fixes #1620

Adapt the tx replacement logic for London

---

docs/_redirects

Some time ago we merged two doc sections, and forgot to add a redirect. This PR adds it.

Add missing redirect

---

.github/workflows/e2e-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-etherscan-ci.yml
.github/workflows/hardhat-ganache-ci.yml
.github/workflows/hardhat-network-forking-ci.yml
.github/workflows/hardhat-network-tracing-ci.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/hardhat-waffle-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml
.github/workflows/lint.yml
docs/.vuepress/config.js
docs/_redirects
docs/reference/stability-guarantees.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/cli/cli.ts

This PR drops support for Node.js 10. This means that we stop running that version on our CI, and that we print a warning if you use it.
It also adds documentation about our stability guarantees, and links it in the warning mentioned above.

Drop support for Node.js 10

---

packages/hardhat-core/package.json
yarn.lock

This PR upgrades the ethereumjs dependencies to make sure that users don't use `v5.5.1` of the vm, which has an accidental breaking change.

Upgrade the ethereumjs dependencies

---

docs/.vuepress/plugins.js

---
My first Hardhat plugin 😊
https://github.com/paulrberg/hardhat-packager

docs: list hardhat-packager in plugins list

---

packages/hardhat-core/README.md

This PR makes two small changes to the main README.md file:
1. Remove the CI badge, as it doesn't make sense any more, with our current CI setup.
2. Remove the warning about this being the development version, as that was accidentally pushed to [`npm`](https://www.npmjs.com/package/hardhat) on most releases, which is confusing.

README.md updates

---

packages/hardhat-etherscan/src/index.ts
packages/hardhat-etherscan/src/network/prober.ts
packages/hardhat-etherscan/src/solc/bytecode.ts

Resolves #1730
Adds support for verifying contracts on Optimistic Ethereum (OVM). Notes:
- It seemed like a more work to access the provider's chainId everywhere that `isOvmInferred()` is used, so I went with the latter approach to keep the diff smaller and minimize the risk of breaking any exiting functionality.
- No test cases have been added, but this code was used to verify the Uniswap V3 contracts on Optimistic Ethereum. Sample verification [here](https://optimistic.etherscan.io/address/0x1F98431c8aD98523631AE4a59f267346ea31F984#code)
- Added lots of comments which should explain everything going on, but let me know if you have any questions
Thanks to @ben-chain and @K-Ho of Optimism for their help

hardhat-etherscan: add optimism support

---

.github/PULL_REQUEST_TEMPLATE.md

I saw someone use the checklist, by deleting the unused ones and checking the box for a doc change, but they *did not* base it on the `website` branch.  That made me think that maybe they just saw the first part, "This PR includes a documentation change," and ignore the rest of the statement, so I thought it would be good to make this tweak.

Subtle tweak to PR template

---

docs/guides/compile-contracts.md

---
Since [v2.6.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.6.0), Hardhat accepts "london" as one of the allowed values for `evmVersion`.

docs: mention "london" among accepted values for "evmVersion"

---

packages/hardhat-core/src/internal/hardhat-network/provider/modules/evm.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/evm.ts

Addresses #1732.
Adds a new type, private to the `evm` module, that includes both `number` and `rpcQuantity` types.
Modifies `evm_increaseTime`, `evm_mine`, and `evm_setNextBlockTimestamp` to accept this new type.

Accept hex strings for rpc test methods

---

packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts

---
I haven't added tests yet, but I wanted to be sure this was the right way to do it first.
So the issue was that, when tracing tracing transactions that was sent using `impersonate_account`, the sender was getting lost and the trace resulted in something completely different if the transaction is checking for the sender (eg. in a `onlyOwner` modifier).

Use the right `sender` when tracing a transaction

---

packages/hardhat-core/test/internal/util/hardforks.ts

This PR loosens an internal utils test that checks that all ethereumjs hardforks are supported by hardhat.
This was discovered in our (ethereumjs) hardhat e2e test when we added `shanghai` as a future hard fork placeholder to `@ethereumjs/common` and it failed on this test.
I am opening this PR to ensure that a patch release from `@ethereumjs/common` including a new hardfork doesn’t break the hardhat tests. This PR removes the check. I was going to rewrite it to:
```typescript
for (const name of Object.values(HardforkName)) {
assert.include(
hardforks.map((h) => h[0]),
name
);
}
```
but this is already covered by the prior test (`Only has hardforks that ethereumjs recognizes`)

Loosen ethereumjs hardforks check

---

packages/hardhat-waffle/README.md

Newbies won't immediately understand why `chai.use` is normally needed, therefore they also won't know why it's a benefit that `hardhat-waffle` takes care of this automatically.  So document it explicitly.

Fully explain the benefit of chai.use

---

config/eslint/eslintrc.js
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts
packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
packages/hardhat-etherscan/src/solc/version.ts

---
This PR sets no-return-await to "off" and sets @typescript-eslint/return-await to "error" in eslintrc config to enforce return await as requested in #1596 . It also fixes all linting errors that occur as a result of the change.

Replace no-return-await with @typescript-eslint/return-await

---

.changeset/warm-adults-bake.md
packages/hardhat-etherscan/src/network/prober.ts

This PR adds support for verifying smart contracts against [Arbiscan](https://twitter.com/etherscan/status/1432112087489257482)

hardhat-etherscan: add arbitrum support

---

.github/workflows/e2e-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-etherscan-ci.yml
.github/workflows/hardhat-ganache-ci.yml
.github/workflows/hardhat-network-forking-ci.yml
.github/workflows/hardhat-network-tracing-ci.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/hardhat-waffle-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml

This PR fixes how our github actions workflows defined the globs that are used to decide if they should be run based on the paths modified by a PR/push.
We were using `**/*` instead of jut `**`, so PRs that only modified top-level files within a package didn't trigger CI runs. For example changesets' PRs didn't.

Fix github actions globs

---

docs/hardhat-network/guides/mainnet-forking.md

Should be a `,` instead of `;`

Fix typo on Mainnet forking docs

---

docs/guides/truffle-migration.md

The Truffle migrations page was out of date, incorrectly claiming that no plugins yet exist which implement a deployment system for Hardhat.  However since that was written, hardhat-deploy has emerged, and the same text in `/guides/deploying.md` was already updated accordingly.
So update the paragraph in `truffle-migration.md` to match, and cross-link to `/guides/deploying.md`.
This is relevant to the discussion in #381.

Give Truffle recommendations consistent with existing deployment guide

---

packages/hardhat-truffle4/package.json
packages/hardhat-truffle5/package.json

Because `master` CI runs are failing like:
```
Run node scripts/check-dependencies.js
@nomiclabs/hardhat-truffle4 has different versions of hardhat as peerDependency and devDependency
@nomiclabs/hardhat-truffle5 has different versions of hardhat as peerDependency and devDependency
Error: Process completed with exit code 1.
```

Sync waffle plugins' hardhat devDependency to peerDependency

---

docs/.vuepress/plugins.js

List plugin that transfers Link token between accounts

---

.changeset/giant-panthers-repeat.md
docs/hardhat-network/reference/README.md
packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts

---
This pull request fixes https://github.com/nomiclabs/hardhat/issues/2010 by creating a `hardhat_getAutomine` JSON-RPC call that retrieves the `Node` `_automine` private member variable.
The changes focus on adding this functionality, test cases, and associated documentation, considering @alcuadrado's recommendation about using `hardhat_getAutomine` instead of `evm_getAutomine` for not introducing non-standard JSON-RPC calls into the `evm` provider.
A screenshot of the successful test cases execution is attached below.
I appreciate that you take care when reviewing, as this is one of my first contributions to this exciting project.

Added hardhat_getAutomine JSON-RPC call

---

CONTRIBUTING.md

---
issue: #2024 
Removed uncessary `"` at the end of import statement . 
Before the changes:
`import ... from "mod""`
After the changes:
``import ... from "mod"``

removed uncessary quote

---

docs/.vuepress/plugins.js

---
**Plugin Description:**
Hardhat plugin to deploy your smart contracts across multiple Ethereum Virtual Machine (EVM) chains with the same deterministic address. Currently only preselected test networks are supported. Production networks will be added as we move into a wider beta phase.

add xdeployer plugin

---

.changeset/cold-ligers-divide.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/cli/analytics.ts
yarn.lock

---
Hi! Here's a quick PR to bump `uuid` to the latest version. The reason is that currently, when we install `hardhat` in our projects, we get the following warning:
```
warning hardhat > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```
This PR fixes it. It follows the upgrading guidelines from https://www.npmjs.com/package/uuid#upgrading-from-uuid3x.
There are also 2 more warnings that are **not** covered by this PR:
```
warning hardhat > mocha > debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. …
```

Bump uuid to ^8.3.2 and @types/uuid to ^8.3.1

---

.changeset/cool-rats-do.md
packages/hardhat-etherscan/src/network/prober.ts

---
Support contracts verification for the snowtrace.io (Etherscan-like Avalanche explorer)

Avalanche verify support

---

.changeset/selfish-falcons-decide.md
packages/hardhat-core/src/builtin-tasks/node.ts

Banteg originally reported that with the new version of Node.js he couldn't connect to `hardhat node`. The reason is that now node resolves `"localhost"` to an ipv6, so we only listen on ipv6 by default.
This PR fixes that by making it explicit that we want the ipv4 version of `localhost` (i.e. `127.0.0.1`)

Use 127.0.0.1 as default hostname

---

.changeset/rich-chefs-attack.md
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/src/internal/constants.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/utils/contract-names.ts
packages/hardhat-core/src/utils/source-names.ts
packages/hardhat-core/test/internal/artifacts.ts

Core feature goal: Implement an appropriate edit-distance algorithm (Levenshtein) to suggest similar artifacts if a requested artifact is not found (i.e. if a user made a typo in the name)
New functions:
Public:
- `formArtifactPathFromFullyQualifiedName`
Private:
- `_trueCasePath`
- `_trueCasePathSync`
- `_getAllContractNamesFromFiles`
- `_getAllFullyQualifiedNamesSync`
- `_handleWrongArtifactForFullyQualifiedName`
- `_handleWrongArtifactForContractName`
- `_handleMultipleSimilarContractNames`
- `_getSimilarContractNames`
- `findDistance` (Levenshtein logic)
Added Error 703: `ERRORS.ARTIFACTS.TYPO_SUGGESTION`
Example:
```
HardhatError: HH703: Artifact for contract "Lob" not found, but we found some that were similar:
Lab
Lib.sol:Lib
Lib2.sol:Lib
Please replace Lob for the correct contract …
```

Use Levenshtein distance to display similar artifact names if given name is not found

---

.changeset/orange-brooms-prove.md
packages/hardhat-core/src/internal/core/jsonrpc/types/output/log.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
packages/hardhat-core/src/internal/hardhat-network/provider/output.ts
packages/hardhat-core/test/internal/hardhat-network/jsonrpc/client.ts
packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkBlockchain.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionReceipt.ts

---
It seems that the cumulativeGasUsed and logIndex fields in transaction receipts were not correct.
For cumulativeGasUsed: the `gas` field of the receipt is actually already the `cumulativeGasUsed` ; so we can use it directly,
or compute it from the `gasUsed` value of the result.
For the logIndex, it actually isn't per transaction, but within a block.
Note : how `logIndex` should be set is not actually in the specs, but that's how it's commonly implemented, cf. [Geth implementation](https://github.com/ethereum/go-ethereum/blob/87a11a87c2bcbeedce9e088698b48d8fa2a09450/core/types/receipt.go#L272-L314)

Fix the returned cumulative gas used and log index in transaction receipts

---

.changeset/fair-monkeys-cheat.md
packages/hardhat-core/src/internal/constants.ts
packages/hardhat-core/src/internal/core/config/config-resolution.ts
packages/hardhat-core/src/internal/core/config/config-validation.ts
packages/hardhat-core/src/internal/core/config/default-config.ts
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/hardhat-network/provider/TransactionQueue.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/types/config.ts
packages/hardhat-core/test/internal/core/config/config-resolution.ts
packages/hardhat-core/test/internal/core/config/config-validation.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/TransactionQueue.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
packages/hardhat-core/test/internal/hardhat-network/provider/node.ts

This adds a new parameter to the Hardhat config: `networks.hardhat.txpool` which can be an object:
```ts
{
fifo: boolean;
}
```
Setting `fifo` to `true` will overwrite the default txpool ordering, so that transactions are mined in a FIFO queue.
This is especially useful when using the fork feature of Hardhat (great feature BTW), if you want to replay a block up to a certain point. Since some blocks on ETH mainnet are not ordered by decreasing gasprice anymore (cf. Flashbots), we have to find a way for the user to mine transactions in a specific, non-traditional, order.
I'm not sure about the naming of the config though...

Add FIFO mode to the transaction pool

---

.changeset/giant-candles-accept.md
docs/hardhat-network/reference/README.md
packages/hardhat-core/src/internal/core/config/config-validation.ts
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/types/config.ts
packages/hardhat-core/test/fixture-projects/hardhat-network-with-custom-coinbase/hardhat.config.js
packages/hardhat-core/test/internal/core/config/config-validation.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockByHash.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getBlockByNumber.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/index.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/test/internal/hardhat-network/provider/node.ts

This PR addresses #1918 by adding a new `coinbase` field to the Hardhat Network config and introducing a new `hardhat_setCoinbase` RPC method.

Configurable coinbase

---

docs/tutorial/deploying-to-a-live-network.md

During the deployment stage, Hardhat will throw an error saying `Invalid account: #0 for network: ropsten - private key too long, expected 32 bytes`.  I removed the `0x` string concatenation to make it easier for other people.

change: remove 0x from private key in tutorial

---

docs/advanced/building-plugins.md

The `task` function expects an **async** action, this is now reflected in the docs building plugins guide (it has been updated in the cli sample projects previously).
The netlify preview:
https://deploy-preview-2100--nomiclabs-hardhat.netlify.app/advanced/building-plugins.html#extending-the-hardhat-runtime-environment

Update "building-plugins" doc to change example task signature

---

.changeset/odd-trees-accept.md
packages/hardhat-core/src/internal/hardhat-network/provider/modules/logger.ts

In the context of a file we should not include the escape codes while logging, but instead write raw text.
Relates to #467
This PR has been tested on MacOS.
To reproduce the issue:
```shell
hh node > log.txt
curl -H "Content-Type: application/json" -X POST --data \
'{"id":1337,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}' \
http://localhost:8545
curl -H "Content-Type: application/json" -X POST --data \
'{"id":1337,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}' \
http://localhost:8545
curl -H "Content-Type: application/json" -X POST --data \
'{"id":1337,"jsonrpc":"2.0","method":"eth_blockNumber","params":[]}' \
http://localhost:8545
vim log.txt
```
The overwrite and color codes are appearing in the log file. With this PR applied the bottom of the log should be:
``` …
```

Only log ansi escape characters when writing to terminal

---

.changeset/wise-nails-lick.md
packages/hardhat-ethers/src/internal/index.ts
packages/hardhat-ethers/test/index.ts

Extends the BigNumber prototype provided by `hardhat-ethers` to include a formatter for node inspection tools. Large BigNumbers that are inspected in hardhat console will now display with commas to help readability.
The formatter uses `,` for readability in large BigNumbers:
```
1
1,000
999,999,999
```
Relates to #2109.
To test manually, build the `hardhat-ethers` plugin locally and link (see `CONTRIBUTION.md`) the plugin to a local hardhat project. From that project run hardhat console (i.e. `hh console`), you should then be able to see the newly formatted BigNumbers:
```shell
> ethers.BigNumber.from(999999999999789)
999,999,999,999,789
```

Add custom formatter for BigNumber's in console

---

docs/.vuepress/plugins.js

- [x ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
---
@alcuadrado Moved the PR to over here
This plugin allows the use of Hardhat with the Yul+ and Yul target languages, as well as compilation of .yul and yulp files into solc artifacts. I've found it tremendously helpful when writing and debugging EVM assembly, and Yul+ (slightly better than raw assembly) and wanted to contribute it. It's a little rough atm lacking tests or descriptive errors, but its still much better than current Yul support.

Add Yul+ and Yul Plugin to Community Plugin Section

---

.changeset/strange-rocks-poke.md
.changeset/wise-nails-lick.md
packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
packages/hardhat-core/src/internal/util/download.ts
packages/hardhat-core/test/internal/solidity/compiler/downloader.ts

This PR is an attempt to deal with #1466 
A halt during compiler download can lead the compiler list file to be partially written (and so invalid json). On a subsequent run the parsing of the compiler list fails and leaves the hardhat install in a broken state (requiring a `npx hardhat clean --global`).
This PR changes the compiler downloader behaviour to parse the file and on `SyntaxError`, redownload and retry the parse once more. Other errors that are not syntax based are rethrown.
Additional tests have been added to the test suite, but if you are attempting to reproduce the bug manually:
1. create a new hardhat project based on the basic template
2. Start `npx hardhat node`
3. Run the sample deploy script `npx hardhat run ./scripts/sample-script.js --network localhost` triggering a …

Fix recovering from malformed compiler list

---

docs/.vuepress/plugins.js

I just released a new plugin to generate documentation based on the NatSpec comments of the contracts.
Can we add it to the community plugins list?

Add @primitivefi/hardhat-dodoc to the plugins

---

config/eslint/eslintrc.js
packages/hardhat-core/src/internal/hardhat-network/jsonrpc/handler.ts
packages/hardhat-core/src/internal/hardhat-network/jsonrpc/server.ts
packages/hardhat-etherscan/src/etherscan/EtherscanService.ts
packages/hardhat-ganache/src/ganache-options-ti.ts
packages/hardhat-truffle4/test/fixture-projects/hardhat-project-with-ts-fixture/test/truffle-fixture.ts
packages/hardhat-truffle5/test/fixture-projects/hardhat-project-with-ts-fixture/test/truffle-fixture.ts

As part of hardhats coding conventions we prefer named over default exports from modules. This PR enables an eslint rule to support this.
This is using the eslint import plugin (already installed) and updates the global config.

Add eslint rule to ensure no default exports

---

docs/tutorial/setting-up-the-environment.md

NVM versions < 16 cause a memory fault issue on Macs with the M1 processor at this step: 
https://hardhat.org/tutorial/testing-contracts.html 
because of this error: 
https://stackoverflow.com/questions/65856300/wasm-code-commit-allocation-failed-process-out-of-memory
Hopefully this is helpful?
---

Set the default NVM version to 16

---

.changeset/thin-terms-confess.md
packages/hardhat-etherscan/CONTRIBUTING.md
packages/hardhat-etherscan/README.md
packages/hardhat-etherscan/src/ChainConfig.ts
packages/hardhat-etherscan/src/config.ts
packages/hardhat-etherscan/src/index.ts
packages/hardhat-etherscan/src/network/prober.ts
packages/hardhat-etherscan/src/resolveEtherscanApiKey.ts
packages/hardhat-etherscan/src/types.ts
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-multiple-apikeys-config/.gitignore
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-multiple-apikeys-config/contracts/TestContract.sol
packages/hardhat-etherscan/test/fixture-projects/hardhat-project-multiple-apikeys-config/hardhat.config.js
packages/hardhat-etherscan/test/integration/HardhatRuntimeEnvironmentExtensionTests.ts
packages/hardhat-etherscan/test/unit/ChainConfig.ts
packages/hardhat-etherscan/test/unit/etherscanConfigExtender.ts
packages/hardhat-etherscan/test/unit/resolveEtherscanApiKey.ts

Etherscan has expanded to provided block explorers and verifiers for popular sidechains. The config in the `hardhat-etherscan` plugin assumes there is only one `apiKey` for use in verification, even though the project may be targeting multiple network/sidechains.
This PR adds support in the `hardhat-etherscan` configuration for setting an api key for etherscan per network (i.e. a project could support project verification on both mainnet and polygon at once without hacks).
Extend the current allowed structure of the `hardhat-etherscan` from:
```javascript
{
etherscan: {
apiKey: string, 
}
}
```
to:
```javascript
{
etherscan: {
apiKey: string | EtherscanApiKeys, 
}
}
```
Where `EtherscanApiKeys` is an object with one property for each supported network mapping to the apiKey to used when …

Support multiple api keys

---

.changeset/smooth-worms-end.md
packages/hardhat-ethers/README.md
packages/hardhat-ethers/src/internal/helpers.ts
packages/hardhat-ethers/src/internal/index.ts
packages/hardhat-ethers/src/types/index.ts
packages/hardhat-ethers/test/index.ts

In `hardhat-ethers`, allow passing of artifacts (resolved via custom code) into an equivalent of the `getContractFactory` call, this is instead of resolving by contract name.
The intention here is to support custom contract artifact resolution but still allow the leveraging of `hardhat-ethers`.
Two new functions have been added to support this without altering the existing signature:
* getContractFactoryFromArtifact
* getContractAtFromArtifact
Relates to #1716
```typescript
import { ethers } from "hardhat";
import { Artifacts } from "hardhat/internal/artifacts";
import { Artifact } from "hardhat/types";
export async function getArtifact(contract: string): Promise<Artifact> {
const artifactsPath: string = "./artifacts";
const artifacts = new Artifacts(artifactsPath);
return …
```

Add artifact functions in ethers `getContractFactoryFromArtifact` and `getContractAtFromArtifact`

---

packages/hardhat-core/README.md

This is a small change to fix a typo at the bottom of the `hardhat-core` README:
`buidling` --> `building`
---

hardhat-core: Fix typo in README

---

packages/hardhat-etherscan/README.md

---
In the new description regarding "multiple API keys and alternative block explorers" (btw I love that new feature) was a small typo in the word "optimistim". Not my greatest contribution ofc but I thought I would quickly fix this typo ;-).

fixing optimism typo in `hardhat-etherscan` readme

---

docs/tutorial/testing-contracts.md

---
The example spec throws this TypeScript error due to incompatible types (ether's `BigNumber` vs `number`:
```
error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.
54       expect(finalOwnerBalance).to.equal(initialOwnerBalance - 30);
```
The example should use [`BigNumber.sub`](https://docs.ethers.io/v5/api/utils/bignumber/#BigNumber--BigNumber--methods--math-operations) instead.

docs: fix BigNumber subtraction in testing-contracts

---

.changeset/poor-cycles-own.md
packages/hardhat-etherscan/README.md
packages/hardhat-etherscan/src/ChainConfig.ts
packages/hardhat-etherscan/src/types.ts

---
This PR adds Moonbeam Network as a supported network for the `hardhat-etherscan` plugin. This was previously discussed in a PR that git merged already for Moonriver #2046 
https://moonbeam.network/
https://moonbeam.moonscan.io/

adds moonbeam to hardhat etherscan verify

---

.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-etherscan-ci.yml
.github/workflows/hardhat-ganache-ci.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-waffle-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml

We'll re-enable them when https://github.com/actions/virtual-environments/issues/4896 is fixed.

Disable macos tests in the CI

---

.changeset/something-something.md
packages/hardhat-waffle/src/constants.ts
packages/hardhat-waffle/src/waffle-provider-adapter.ts

---
Fixes #724
> The getWallets method in waffle-provider-adapters.ts throws a plain Error instead of using a NomicLabsBuidlerPluginError.
This PR fixes the plain error handling. I assume that `NomicLabsHardhatPluginError` (class used to throw errors from *core* hardhat plugins) is meant to replace the plain error instead of `NomicLabsBuidlerPluginError` as described in the issue.

Use NomicLabsHardhatPluginError in getWallets for error handling

---

docs/.vuepress/plugins.js

We created a hardhat plugin to make it easy for devs to build on top of unlock by deploying contracts!
We use this internally ourselves :)
---
Adding the Unlock Hardhat plugin to the list of community plugins.

Added the Unlock Hardhat plugin

---

docs/tutorial/debugging-with-hardhat-network.md

Change import instruction, from console.log to console.sol.

TYPO console.log -> console.sol

---

.changeset/shaggy-hotels-wave.md

The changeset bumped `hardhat-ethers` too for some reason. I also added a mention to the PR's author.

Update hardhat-etherscan Aurora changeset

---

.changeset/red-lobsters-work.md
packages/e2e/test/index.ts
packages/hardhat-core/src/builtin-tasks/test.ts

Related to #2220.
The `mocha.dispose()` call seems to throw when the test task is used like this:
```
hh test ./test/test.js
```
But this works:
```
hh test test/test.js
```
Converting the arguments to absolute paths (relative to `process.cwd()`) fixes the issue.

Use absolute paths for test task arguments

---

docs/.vuepress/theme/styles/theme-dark-hc.styl
docs/.vuepress/theme/styles/theme-dark.styl

---
Added `ol` to the dark mode `.page` CSS.
Fixes the issue #2288

Fix: dark mode ordered list text color

---

packages/hardhat-core/src/internal/hardhat-network/jsonrpc/server.ts

If we use the default timeouts, the tests that use the http provider have to wait 4 seconds for the server to close, because it attempts a graceful shutdown and it still has open connections.

Use a low keepAlive in the tests http provider

---

docs/.vuepress/plugins.js

add  plugin hardhat-network-metadata. This plugin allows you to add an extra field `metadata` within a network config like so:
```js
{ ...,
metadata: { 
anything: "goes here", 
seriously: 1224233, 
literallyWhateverYouWant: { a: 1 }
}
}
```

Update plugins.js to add Hardhat Metadata Plugin

---

.changeset/sour-phones-develop.md
docs/.vuepress/plugins.js
packages/hardhat-core/src/internal/hardhat-network/jsonrpc/client.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts

This is a quick fix to #2380. This is not the ideal fix because the fee history is cached per-request instead of per-block, which leads to lots of cache misses. Also, if the remote network can't answer an `eth_feeHistory` we fail, but we could do something better in that case.

Temporary fix to #2380

---

docs/guides/deploying.md

Makes use of the `deployed` method in the deployment guide so that users are aware of the method used to wait for contract deployment confirmation.

Update deployment guide: wait for deployment confirmation

---

.changeset/quick-moons-report.md
packages/hardhat-core/src/builtin-tasks/test.ts

---
Fixes a bug in the `test` task that would override the `grep` options in the config file. 
Fixes #2459

fix: don't override grep options in test task

---

packages/hardhat-core/package.json
packages/hardhat-core/test/internal/hardhat-network/provider/modules/evm.ts

Note that CI runs for this PR show that, for the forking test Action, 1856+35+1 (passing+pending+failing) tests were run, whereas, for [a recent run without this change](https://github.com/NomicFoundation/hardhat/runs/5517403119?check_suite_focus=true), only 404+2 tests were run.
The problem seems to be that our usage of `mocha --recursive "test/internal/hardhat-network/{helpers,jsonrpc,provider}/*.ts"` was not picking up the tests in the subdirectories of `provider` because the glob pattern was only resolving to `.ts` files and not to any folder names, so there was nothing for `--recursive` to act upon. (Thinking further, I suspect that using `--recursive` has no effect when used alongside `.../*.ts`, since no folders will be targeted.)

Fix problem with CI not running all core tests

---

.changeset/hungry-yaks-enjoy.md
packages/hardhat-core/src/builtin-tasks/compile.ts

When the downloaded solidity compiler is the WASM version (because there is no available native compiler for the selected platform) it is still run as a native compiler, because of the missing else statement that set the correct platform.
Closes #2554 and fixes #2329 and #2004 as well.

Fix smart contract compilation when the downloaded solc is for WASM platform.

---

.changeset/chilled-cycles-smile.md
packages/hardhat-core/src/internal/util/lazy.ts
packages/hardhat-core/test/internal/util/lazy.ts

...or lazyFunction
---
Hi! This PR changes the way we call `util.inspect` in lazy objects and functions:
- The current state is that `util.inspect` is called without any additional arguments.
- From [node docs](https://nodejs.org/api/util.html#custom-inspection-functions-on-objects), the custom inspect function is called with three arguments `(depth, options, inspect)` so we can use these when calling inspect on the real object/function.
- In this PR we pass those options, including the depth, to the inspect call. This avoids losing any options but most importantly avoids losing the depth, which would otherwise make us recurse infinitely if we had a lazyObject within a circular object.
- Because of this, I believe this fixes #1473.

Fix passing options and depth when inspecting a lazyObject

---

packages/hardhat-chai-matchers/src/hardhatChaiMatchers.ts
packages/hardhat-chai-matchers/src/hexEqual.ts
packages/hardhat-chai-matchers/src/properAddress.ts
packages/hardhat-chai-matchers/src/properPrivateKey.ts
packages/hardhat-chai-matchers/src/types.ts
packages/hardhat-chai-matchers/test/hexEqual.ts
packages/hardhat-chai-matchers/test/properAddress.ts
packages/hardhat-chai-matchers/test/properPrivateKey.ts

properPrivateKey, properAddress, and hexEquals chai matchers

---

docs/.vuepress/plugins.js

Add [hardhat-hethers](https://github.com/LimeChain/hardhat-hethers) to the list of community plugins. It injects [hethers](https://github.com/hashgraph/hethers.js) into the `hre` object and enables testing of Hedera smart contracts.

Add hardhat-hethers to community plugins

---

.changeset/lazy-islands-cheat.md
packages/hardhat-core/src/internal/cli/HelpPrinter.ts

---
The task parameters marked as optional are not always rendered as such in the printed help. This is a trifle but irksome nonetheless.
For the following `hardhat.config.js`:
```js
task("accounts", "Prints the list of accounts")
.addParam("name")
.addParam("param", undefined, "arg")
.addOptionalParam("key")
.addOptionalParam("value", undefined, "0x")
.addOptionalVariadicPositionalParam("items")
.setAction(async (taskArgs, hre) => console.log([1, 2, 3, 4, 5]));
/**
* @type import('hardhat/config').HardhatUserConfig
*/
module.exports = {
solidity: "0.8.4",
};
```
Running `hh accounts --help` yields:
```sh
$ hh accounts --help
Hardhat version 2.9.3
Usage: hardhat [GLOBAL OPTIONS] accounts --key <STRING> --name <STRING> [--param <STRING>] [--value <STRING>] ...items
OPTIONS:
--key   
--name …
```

Fixes help printing of optional task parameters

---

packages/hardhat-core/src/internal/cli/project-creation.ts

dotenv was not loading my `.env` file properly, and only updating it to the latest version fixed it.
I haven't figured out the root cause of the problem though.
This stackoverflow answer (https://stackoverflow.com/a/70037859/4971151) suggests using
```
require('dotenv').config({path:__dirname+'/.env'})
```
instead of the `require('dotenv').config()` that hardhat is using, but I haven't gotten any problems with dotenv 16 so far, so seems like a cleaner approach.
my `tsconfig.json` file is
```
{
"compilerOptions": {
"declaration": true,
"esModuleInterop": true,
"forceConsistentCasingInFileNames": true,
"module": "commonjs",
"outDir": "dist",
"resolveJsonModule": true,
"strict": true,
"target": "es2019"
},
"include": ["./scripts", "./test", "./typechain", "./deploy", "./lib"],
"files": …
```

dotenv 10.0.0 doesn't load my .env file properly

---

docs/hardhat-network/guides/mainnet-forking.md

---
This PR changes the value of the pinned block in the mainnet forking guide from 11095000 to 14393928. I chose 14393928 because it was the block when I made the change.
closes #2330

Update Pinned Block Number in Mainnet Forking guide

---

.changeset/popular-parents-nail.md
packages/hardhat-core/src/internal/hardhat-network/provider/BlockchainBase.ts
packages/hardhat-core/src/internal/hardhat-network/provider/BlockchainData.ts
packages/hardhat-core/src/internal/hardhat-network/provider/HardhatBlockchain.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/types/HardhatBlockchainInterface.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts

Closes #2467
`solidity-coverage` sets the initial base fee per gas to 1. This value is kept at that level as long as no block uses more than 50% of the available gas.
Since `hardhat_mine` mines empty blocks, it should never increase the base fee per gas, but reserved blocks were defaulting to a base fee of 7. This PR fixes that by using the base fee per gas of the latest block in the reserved blocks.
Of course, this is not correct, but neither was the previous behavior.

Keep the baseFeePerGas constant in reserved blocks

---

.changeset/slow-pianos-double.md
docs/.vuepress/plugins.js
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/test/internal/cli/autocomplete.ts

Projects with a huge number of contracts like OZ's [contract-wizard](https://github.com/OpenZeppelin/contracts-wizard) can get an OOM error during compilation. This PR fixes that problem, by reducing the potential size of the array that accumulates the compilation results to what it was in v2.8.4.
Even with that change, it's still possible to get an OOM if the concurrency level is high and the available memory is not enough. This happens because multiple compilation results are present at the same time, and they may not fit in the available memory. In that case, the workaround is to increase the memory or to reduce the concurrency level. To make the latter option possible, this PR adds a `--concurrency` param to the compile task.

Fix OOM during parallel compilation

---

.github/workflows/comment-on-linter-error.yml
.github/workflows/stale-issues-and-prs.yml

This PR adds two small improvements to our Github actions setup:
1. If you label something as `not-stale`, it won't be autoclosed.
2. It creates a new workflow that comments when the linter fails, including when the PR was submitted by external contributors.

Improve GitHub actions

---

.changeset/sixty-trainers-help.md
packages/e2e/test/index.ts
packages/hardhat-core/src/internal/cli/cli.ts

---
If you run hardhat --version and are not in a HardHat project directory, you will be prompted to create a new project, if your terminal is interactive.
This change moves the --version flag processing earlier in the main function so that it doesn't require you to be in a HardHat project directory to check the version.

Allow --version flag to be used when not in a Hardhat project directory

---

.changeset/tricky-cougars-shout.md
packages/hardhat-chai-matchers/src/changeTokenBalance.ts
packages/hardhat-core/package.json

This fixes some problems with the released packages.
- Hardhat didn't have the `common` directory as part of the published files, so `common/bigInt` is not available, rendering the chai matchers unusable.
- The `changeTokenBalance` matcher was still doing a top-level import of ethers.

Beta issues

---

packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts

There are a couple of tests that fail with an "insufficient balance" error when the fork provider is used. This happens when gas prices are high (as they are right now).
This PR fixes this by just setting the base fee to 0 in those tests.

Fix fork tests when gas prices are high

---

.changeset/four-foxes-sleep.md
packages/hardhat-core/src/builtin-tasks/node.ts
packages/hardhat-core/src/builtin-tasks/utils/watch.ts
packages/hardhat-core/test/builtin-tasks/node.ts

---
Fixes the `node` task by closing the `chokidar` file watcher after the server has closed.
This prevents programmatic usages of the `node` task from hanging. For example, a test (eg `mocha`, `jest`) may run the `node` task for mainnet forking and terminate the server when the tests complete, but the test framework will hang because `chokidar` will not allow the process to quit.
I've included a test to show that the `node` task terminates. The test will still pass without these changes, but (as described) the test framework will hang despite the test passing. I could find no way to make the test fail, as the `chokidar` watcher is a not exposed in the current state of the code.

fix: close node watcher after task

---

.changeset/gentle-points-provide.md
packages/hardhat-etherscan/README.md
packages/hardhat-etherscan/src/ChainConfig.ts
packages/hardhat-etherscan/src/types.ts

---
This PR adds Sepolia, the new Ethereum test network, to the `hardhat-etherscan` plugin. 
- RPC for Sepolia: https://nunki.htznr.fault.dev/rpc.
- 0.242069 ETH has been sent to [`0x4444c3F7D7d3153Dc0773C31ae10cf9B5495d4Bb`](https://sepolia.etherscan.io/address/0x4444c3F7D7d3153Dc0773C31ae10cf9B5495d4Bb).

Add Sepolia to Hardhat Etherscan

---

packages/hardhat-chai-matchers/package.json
packages/hardhat-chai-matchers/scripts/check-subpath-exports.js
packages/hardhat-chai-matchers/src/emit.ts
packages/hardhat-chai-matchers/src/reverted/revertedWithCustomError.ts
packages/hardhat-chai-matchers/src/withArgs.ts
packages/hardhat-chai-matchers/test/events.ts
packages/hardhat-chai-matchers/test/fixture-projects/hardhat-project/contracts/Events.sol
packages/hardhat-chai-matchers/test/fixture-projects/hardhat-project/contracts/Matchers.sol
packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts

Support predicate in .withArgs()

---

docs/config/README.md

Added hardware wallet config example

added hardware wallet example

---

packages/hardhat-core/package.json
packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/evm.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-docker/package.json
packages/hardhat-etherscan/package.json
yarn.lock

For some reason (which I believe is related to some interaction between sinon an undici), some tests were taking a long time while the server was being closed. This was adding more than 30 seconds to the total time of the test run.
Upgrading undici, plus some other minor changes, fixed it.
Since this is not the first time this happens, I also added a check that fails if the server takes more than one second to close.

Fix slow tests

---

packages/hardhat-chai-matchers/src/tsconfig.json
packages/hardhat-chai-matchers/src/types.ts

This PR deserves a thorough explanation:
As reported in #2836, `hardhat-chai-matchers` was incorrectly adding a `/// <reference types="sinon-chai" />`. This was surprising, as we don't use Sinon in that package.
What happened is that tsc loads all the typing packages from the `typeRoots` you declare by default. In our case, those are set to `<repo>/node_modules/@types` and `<repo>/config/typescript/@types`. Inside the main `@types` we have both `chai` and `chai-sinon`, and given how the Chai overload is written (not a declare module construct), it needs to load both.
I fixed it by explicitly telling tsc to only load `@types/node` and `@types/chai`.

Remove incorrect sinon-chai reference from hardhat-chai-matchers

---

packages/hardhat-core/sample-projects/typescript/tsconfig.json

This PR upgrades the `target` in the sample project's tsconfig to `es2020`, which means users can take advantage of bigint literals (e.g. `1n`) without changing their config.
This `target` is fully supported by Node 14+, as you can see [here](https://github.com/tsconfig/bases/blob/main/bases/node14.json).
We still support Node 12, but we are dropping its support at the end of the month, so the risk of this going wrong is tiny.

Upgrade the target in the sample project's tsconfig

---

docs/redirects.config.js
docs/src/content/docs-landing/index.md
docs/src/content/hardhat-chai-matchers/docs/other-components/_dirinfo.yaml
docs/src/content/hardhat-network-helpers/docs/other-components/_dirinfo.yaml
docs/src/content/hardhat-network/docs/other-components/_dirinfo.yaml
docs/src/content/hardhat-runner/docs/other-components/_dirinfo.yaml
docs/src/content/hardhat-vscode/docs/other-components/_dirinfo.yaml
docs/src/content/layouts.yaml

For https://linear.app/nomic-foundation/issue/HH-861/use-hardhat-component-instead-of-hardhat-project-in-the-docs

website: "other hardhat components", not "projects"

---

docs/redirects.config.js
packages/hardhat-chai-matchers/src/internal/checkIfWaffleIsInstalled.ts
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/core/config/config-loading.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/logger.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-ethers/README.md
packages/hardhat-ethers/src/internal/helpers.ts
packages/hardhat-etherscan/src/solc/libraries.ts
packages/hardhat-shorthand/README.md
packages/hardhat-truffle5/README.md
packages/hardhat-waffle/README.md
packages/hardhat-web3/README.md

Closes HH-795.
I tried to update all URLs that were causing a redirect _except_ for shortlinks. To be consistent with this approach, I moved some redirects to the shortlinks section of `redirects.config.js`
I also added a new `/report-bug` shortlink and updated the `/reportbug` usages. This is just for aesthetics/consistency.

Fix hardhat org links

---

.changeset/thick-masks-hammer.md
packages/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
packages/hardhat-chai-matchers/test/fixture-projects/hardhat-project/contracts/Matchers.sol
packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts

This PR introduces a fix to `revertedWithCustomError().withArgs()`.
As we were using ethers' array-like structures, and with an `as any` 🚨, we were incorrectly iterating the actual errors (i.e. by name and index), leading to always comparing them with `undefined`.
This PR converts the array-like into an actual array first. I also checked that this pattern isn't present in the other matchers.
Thanks @pcaversaccio for reporting it!

Fix reverted with custom error

---

packages/hardhat-chai-matchers/package.json
packages/hardhat-core/package.json
packages/hardhat-docker/package.json
packages/hardhat-ethers/package.json
packages/hardhat-etherscan/package.json
packages/hardhat-ganache/package.json
packages/hardhat-network-helpers/package.json
packages/hardhat-shorthand/package.json
packages/hardhat-solhint/package.json
packages/hardhat-solpp/package.json
packages/hardhat-toolbox/package.json
packages/hardhat-truffle4/package.json
packages/hardhat-truffle5/package.json
packages/hardhat-vyper/package.json
packages/hardhat-waffle/package.json
packages/hardhat-web3-legacy/package.json
packages/hardhat-web3/package.json

We don't manually publish new versions except for first versions, so this is not strictly necessary. But since we typically create new packages by copying an existing one, and we publish first versions manually, I think it's a good idea to have this in place.

Add prepublishOnly scripts

---

.changeset/fifty-jeans-double.md
packages/hardhat-core/src/internal/hardhat-network/stack-traces/error-inferrer.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/call-message/external-calls/asm-reverts-propagation/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/call-message/external-calls/asm-reverts-propagation/test.json

As shown in #2546, Hardhat Network can be too restrictive when deciding if an error is being propagated or not. In particular, it never considers asm-based manual propagation as actual propagation.
This PR loosens our heuristic significantly. If the previous heuristic fails, but the error of the trace and subtrace are equal and not empty, we still consider it to propagate.
There's a minor chance of this resulting in false positives, but I think it's reasonably small.
Another alternative is checking if the `return` opcode is inside of an inline assembly block, but to do that in a performant way we'd need to make a larger change.

Loosen HH Network's error propagation heuristic

---

packages/hardhat-toolbox/README.md
packages/hardhat-toolbox/src/index.ts

I also noticed that we were importing the network helpers in the index of the plugin. I'm pretty sure that this is not necessary, so I removed it.

Add Toolbox migration guide

---

packages/hardhat-core/README.md

---
Hey all, this PR adds a [GitPOAP Badge](https://docs.gitpoap.io/api#get-v1repoownernamebadge) to the README that displays the number of minted GitPOAPs for this repository by contributors to this repo.
You can see an example of this in [our Documentation repository](https://github.com/gitpoap/gitpoap-docs#gitpoap-docs).
This should help would-be contributors as well as existing contributors find out that they will/have received GitPOAPs for their contributions.
CC: @colfax23 @kayla-henrie

[README] Add GitPOAP Badge to Display Number of Minted GitPOAPs for Contributors

---

.changeset/slimy-weeks-jump.md
packages/hardhat-ethers/README.md
packages/hardhat-ethers/src/internal/helpers.ts
packages/hardhat-ethers/test/index.ts

---
New feature. Was previously discussed in [Issue #2170](https://github.com/NomicFoundation/hardhat/issues/2170).
Adds a check for input address to `getContractAt()` — now it MUST have code (be a contract), otherwise function throws.
What was done:
All tests run fine:
**Let me know if anything else is needed for submission :)**

Issue #2170: New check for getContractAt()

---

packages/hardhat-vyper/src/util.ts
packages/hardhat-vyper/test/fixture-projects/generates-gas-field/contracts/A.vy
packages/hardhat-vyper/test/fixture-projects/generates-gas-field/hardhat.config.js
packages/hardhat-vyper/test/tests.ts

Earlier Versions of Vyper generate a gas field in the ABI. This gas estimate is often [incorrect](https://github.com/vyperlang/vyper/issues/2151) and produces invalid typechain objects (see https://github.com/NomicFoundation/hardhat/issues/1696, https://github.com/dethcrypto/TypeChain/pull/711)

Remove gas field from abi

---

.changeset/big-items-scream.md
packages/hardhat-network-helpers/package.json

The `@nomicfoundation/hardhat-network-helpers` module requires the
`hardhat/common` module at runtime. This was added to `hardhat` in
commit 6f5f2f8cd2bd ("Include common directory in the published files"),
which was first released in `hardhat@2.9.5`. The peer dependency should
reflect this so that adding `hardhat-network-helpers` to a project with
(say) `hardhat@2.9.3` doesn't silently produce a broken installation.
wchargin-branch: hardhat-common-peer-dep

Update peer dependency to fix `hardhat/common` dep

---

.github/workflows/pre-release.yml

This is the same change as in #3032, but for the pre-release workflow.

Remove yarn.lock in pre-release workflow

---

docs/src/content/tutorial/testing-contracts.md

Just fixed a typo in the documentation for the testing-contracts that will eventually be used to generate the Lock.ts test.

docs: fix typo

---

packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/core/flamegraph.ts
packages/hardhat-core/src/internal/core/params/hardhat-params.ts
packages/hardhat-core/src/internal/core/runtime-environment.ts
packages/hardhat-core/src/internal/core/task-profiling.ts
packages/hardhat-core/src/profiling.ts
packages/hardhat-core/src/types/runtime.ts
packages/hardhat-core/test/internal/cli/autocomplete.ts

First PR of the compilation times optimization effort.
This PR introduces a Hardhat argument `--flamegraph`, which creates a flamegraph of the Hardhat tasks.

Tasks flamegraph generation

---

packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/src/internal/solidity/dependencyGraph.ts

Third PR of the compilation times optimization effort.
This PR removes many blocking operations in favor of async ones. A common pattern here is changing an iteration for a `await Promise.all(arr.map(...))`.
I believe this PR is ready to review, as these are internal changes that probably don't require new tests.
Depends on https://github.com/NomicFoundation/hardhat/pull/3049

Remove unnecesary blocking operations

---

packages/hardhat-core/src/builtin-tasks/clean.ts
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/src/types/artifacts.ts
packages/hardhat-core/test/internal/artifacts.ts

Seventh PR optimizing the compilation and test loop.
This PR modifies `hre.artifacts` so that it caches the paths to the different files.
Depends on #3053

Cache artifact paths

---

.changeset/famous-points-count.md
packages/hardhat-network-helpers/src/utils.ts
packages/hardhat-network-helpers/test/helpers/setStorageAt.ts

Network helpers: fix set storage at multi leading zeros slot

---

packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/solidity/compiler/index.ts
yarn.lock

As part of the performance optimizations we started checking if the downloaded versions of solc work just once, right after downloading them.
This means that if you already had a non-runnable solc version in your fs, we'd try to use it and it will fail.
This PR makes that error more clear, and adds a hint to the user to clear their global cache, which would fix it.
Fixes #3126

Throw a clear error when native solc fails to run

---

package.json
packages/e2e/package.json
packages/hardhat-chai-matchers/package.json
packages/hardhat-core/.mocharc.json
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/core/config/config-loading.ts
packages/hardhat-core/src/internal/core/project-structure.ts
packages/hardhat-core/src/internal/core/typescript-support.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts
packages/hardhat-core/test/fixture-projects/typescript-esm-project/hardhat.config.cts
packages/hardhat-core/test/fixture-projects/typescript-esm-project/package.json
packages/hardhat-core/test/fixture-projects/typescript-esm-project/tsconfig.json
packages/hardhat-core/test/internal/core/typescript-support.ts
packages/hardhat-docker/package.json
packages/hardhat-ethers/package.json
packages/hardhat-etherscan/package.json
packages/hardhat-ganache/package.json
packages/hardhat-network-helpers/package.json
packages/hardhat-shorthand/package.json
packages/hardhat-solhint/package.json
packages/hardhat-solpp/package.json
packages/hardhat-toolbox/package.json
packages/hardhat-truffle4/package.json
packages/hardhat-truffle5/package.json
packages/hardhat-vyper/package.json
packages/hardhat-waffle/package.json
packages/hardhat-web3-legacy/package.json
packages/hardhat-web3/package.json
yarn.lock

---
Due to the way hardhat registers tasks, v3 can't support ESM (as I outlined at https://github.com/NomicFoundation/hardhat/pull/1994#issuecomment-972459102); however, TypeScript added ESM support and many projects are converting to ESM-only. The ts-node team added support for the `.cts` extension in https://github.com/TypeStrong/ts-node/pull/1694, which allows individual files to be resolved as commonjs (see https://github.com/TypeStrong/ts-node#module-type-overrides).
This change should allow a monorepo to become `"type": "module"` and still use hardhat in commonjs mode. 🎉

feat: Support .cts extension with ts-node 10+

---

packages/hardhat-core/src/internal/core/project-structure.ts
packages/hardhat-core/test/builtin-tasks/run.ts
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/.gitignore
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/assert-hardhat-arguments.js
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/async-script.js
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/contracts/a.sol
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/env-var-script.js
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/failing-script.js
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/hardhat.config.cjs
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/package.json
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/params-script.js
packages/hardhat-core/test/fixture-projects/esm-project-with-scripts/successful-script.js
packages/hardhat-core/test/fixture-projects/esm-project/hardhat.config.cjs
packages/hardhat-core/test/fixture-projects/esm-project/package.json
packages/hardhat-core/test/internal/core/config/config-loading.ts
packages/hardhat-core/test/internal/core/project-structure.ts
packages/hardhat-core/test/internal/util/scripts-runner.ts

---
Due to the way hardhat registers tasks, v3 can't support ESM (as I outlined at https://github.com/NomicFoundation/hardhat/pull/1994#issuecomment-972459102); however, you can load `.cjs` files inside an ESM project. Since many projects are converting to ESM-only, it is helpful to be able to run hardhat in those contexts. 
This change should allow a monorepo to become `"type": "module"` and still use hardhat in commonjs mode. 🎉 
This support is in parallel to my other PR (#3017) which adds this support for TypeScript. There are follow up PRs to allow loading of ESM tasks and scripts.

feat: Load hardhat.config.cjs to partially support ESM projects

---

.github/workflows/comment-on-linter-error.yml
.github/workflows/e2e-ci.yml
.github/workflows/hardhat-chai-matchers-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-etherscan-ci.yml
.github/workflows/hardhat-ganache-ci.yml
.github/workflows/hardhat-network-forking-ci.yml
.github/workflows/hardhat-network-helpers-ci.yml
.github/workflows/hardhat-network-tracing-ci.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-toolbox-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/hardhat-waffle-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml
.github/workflows/lint.yml
.github/workflows/release.yml

Use `$default-branch` instead of master, and `**` instead of `*`. From [the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet):
```
*: Matches zero or more characters, but does not match the / character. For example, Octo* matches Octocat.
**: Matches zero or more of any character.
```

Fix GH workflows filters

---

.changeset/pink-dodos-obey.md
packages/hardhat-etherscan/src/ChainConfig.ts

This PR updates the Optimism Testnet endpoint from Kovan to Goerli.
Optimism's Kovan testnet has been [deprecated](https://community.optimism.io/docs/useful-tools/networks/#test-eth) and replaced with the [Goerli testnet](https://community.optimism.io/docs/useful-tools/networks/#optimism-goerli).
I am aware that hardhat team is not going to support any additional network but i think we need Optimism Goerli instead of Optimism Kovan. This PR addresses #3172 .

Update Optimism testnet support from deprecated Kovan to Goerli

---

packages/hardhat-etherscan/src/ChainConfig.ts
packages/hardhat-etherscan/test/unit/ChainConfig.ts

---
xdaichain is now [Gnosis](https://www.gnosischain.com), with native integration with Etherscan ([gnosisscan.io](https://gnosisscan.io))

xdai to gnosis

---

docs/redirects.config.js
docs/src/config.ts
docs/src/content/hardhat-network/docs/reference/index.md
docs/src/content/hardhat-runner/docs/advanced/building-plugins.md
docs/src/content/hardhat-runner/docs/advanced/create-task.md
docs/src/content/hardhat-runner/docs/advanced/hardhat-runtime-environment.md
docs/src/content/hardhat-runner/docs/guides/getting-help.md
docs/src/content/hardhat-runner/docs/other-guides/truffle-testing.md
docs/src/content/hardhat-runner/plugins/index.md
docs/src/content/tutorial/testing-contracts.md
docs/src/model/markdown.tsx

Closes #3244.
The most important thing here is that the "Help us improve this page" link at the end of the docs pages is not working because of the `master -> main` change.
The rest are typos, more renaming of `master` to `main`, and changing `nomiclabs` to `NomicFoundation`.

Website fixes

---

.github/workflows/hardhat-network-tracing-all-solc-versions.yml
.github/workflows/hardhat-network-tracing-ci.yml
.github/workflows/pre-release.yml
packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilation.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts

Some improvements for the stack traces tests:
- Make testing all solc versions opt-in instead of opt-out. This makes tests take less time locally and in ome workflows (like the pre-release one) that don't need to test all versions.
- Use native solc instead of solcjs
- Put all the artifacts in a common directory instead of having a different one for each test.

Stack traces tests improvements

---

.changeset/hot-pans-doubt.md
packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
packages/hardhat-core/src/internal/util/global-dir.ts

When I changed the compiler downloader I tried to reuse previously downloaded compilers. This was a mistake, as the validation of those is now skipped. This lead to a situation where some users couldn't compile without cleaning the global cache.
On top of that, I realized that the criteria we use to pick the version of solc that we download is seriously wrong, and I added a TODO explaining that.

Fix compiler downloader

---

.changeset/twelve-bags-collect.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/solidity/parse.ts
yarn.lock

This small PR fixes two errors related to `solidity-analyzer`:
1. It bumps it to `0.1.0`. As we were using `^` and `0.0.x`, Hardhat wasn't getting any dependency update.
2. It detects NPM's issue #4828 and prints a clear error message explaining how to fix it.
Fixes #3176

Fix two `solidity-analyzer`-related errors

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Replaces #3262.
Adds two missing plugins, and three new plugins, from the `@solidstate` namespace.

add solidstate plugins to list

---

.changeset/tall-llamas-remember.md
packages/hardhat-core/src/internal/solidity/compiler/downloader.ts

Use `util.promisify` instead of implementing our own handling of the `execFile` result. This fixes #3195 because of some very fun reasons.
The previous implementation wasn't handling the case were the `ChildProcess` instance emitted an `"error"` event. You would expect that this would hang the process forever, but you would be wrong (I know I was).
The reason it was erroring is that, in an alpine-based docker image, the solc binary couldn't even be executed. This caused an error instead of emitting an `"exit"` event with a non-zero code.
The problem here is a combination of two weird things I had no idea about.
First, when you download a solc native binary in an alpine-based docker container, the file cannot be executed. The fun part is that `execFile` errors with a `ENOENT` error, and …

Fix how native solc is checked after download

---

.changeset/twelve-camels-peel.md
packages/hardhat-ethers/README.md
packages/hardhat-ethers/src/internal/helpers.ts
packages/hardhat-ethers/test/index.ts

This PR undoes the changes introduced in #2916. This broke smock and there surely are other scenarios where this is not a good idea.

Don't check that address is a contract in getContractAt

---

.changeset/nine-kangaroos-marry.md
packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
packages/hardhat-core/src/internal/hardhat-network/provider/transactions/ReadOnlyValidUnknownTypeTransaction.ts

Process transactions with unknown tx types

---

.changeset/mean-mice-tell.md
packages/hardhat-core/src/internal/solidity/compiler/compiler-input.ts
packages/hardhat-core/test/builtin-tasks/compile.ts
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/.gitignore
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/contracts/A.sol
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/contracts/B.sol
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/hardhat.config.js
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/node_modules/dependency/contracts/Dep1.sol
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/node_modules/dependency/contracts/Dep2.sol
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/node_modules/dependency/package.json

I manually verified that this fixes the problem in the Balancer repo.
I tried to create a fixture project with a synthetic example that reproduces the issue, but it turned out to be way harder than I expected, so I don't have tests for this.
**Update**: I want to give another try to having a test for this, please don't merge yet.
**Update 2**: I added a test that triggered the bug. This is ready for review now.

Sort files when creating the solc input

---

CONTRIBUTING.md
packages/common/package.json
packages/e2e/package.json
packages/hardhat-chai-matchers/package.json
packages/hardhat-docker/README.md
packages/hardhat-docker/package.json
packages/hardhat-ethers/package.json
packages/hardhat-etherscan/package.json
packages/hardhat-etherscan/src/ChainConfig.ts
packages/hardhat-ganache/package.json
packages/hardhat-network-helpers/package.json
packages/hardhat-shorthand/package.json
packages/hardhat-solhint/package.json
packages/hardhat-solpp/package.json
packages/hardhat-toolbox/package.json
packages/hardhat-truffle4/README.md
packages/hardhat-truffle4/package.json
packages/hardhat-truffle5/README.md
packages/hardhat-truffle5/package.json
packages/hardhat-vyper/package.json
packages/hardhat-waffle/README.md
packages/hardhat-waffle/package.json
packages/hardhat-web3-legacy/package.json
packages/hardhat-web3/package.json

---
I was reading the [Getting Started doc](https://hardhat.org/hardhat-runner/docs/getting-started#overview) and noticed that the **Help Us Improve this Page** link returned 404. I cloned the repo and did a find and replace for 'master' with 'main' and went through each link 1-by-1 to ensure the replacement was correct. I also noticed that nomiclabs repos have seemingly been transfered to NomicFoundation, but that update seemed a bit larger effort than I was willing to take on at the moment.
- Fix 404s in docs.
- Fix links to GitHub showing "Branch master was renamed to main."

chore: replace master with main

---

.changeset/silly-geese-fold.md
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/solidity/resolver.ts
packages/hardhat-core/src/internal/util/packageInfo.ts
packages/hardhat-core/src/utils/source-names.ts
packages/hardhat-core/test/fixture-projects/project-with-hardhat-directory/package.json
packages/hardhat-core/test/internal/solidity/resolver.ts
packages/hardhat-core/test/utils/source-names.ts

Verifies that a solidity file import doesn't contain the own package's name. See the linked issue for further details.
The PR is still missing tests. I wanted some feedback before I spend more time on it.
close #1500 
Closes HH-763

don't allow own package name in solidity file import

---

.changeset/large-ties-smash.md
packages/hardhat-core/src/internal/core/providers/accounts.ts
packages/hardhat-core/src/internal/util/keys-derivation.ts
packages/hardhat-core/test/internal/util/keys-derivation.ts

---
Fixes https://github.com/NomicFoundation/hardhat/issues/3223
I fixed the logic to derive a private key from the mnemonic that included newline character or space character.
If a newline or space character is included, it is trimmed.

possible to derive private key from mnemonic included space character

---

.changeset/nine-starfishes-grab.md
docs/src/content/hardhat-chai-matchers/docs/reference.md
packages/hardhat-chai-matchers/src/internal/reverted/revertedWith.ts
packages/hardhat-chai-matchers/src/types.ts
packages/hardhat-chai-matchers/test/reverted/revertedWith.ts

This PR should provide the ability for the developer to use regular expressions in the revertedWith function within the hardhat-chai-matchers plugin.
Issue [Add support RegExp in the revertedWith function #3241](https://github.com/NomicFoundation/hardhat/issues/3241)
We enter a regular expression and the function revertedWith will perform the necessary tests based on the given expression as in the example below:
```js
it("Should returns error role access",  async () => {
const { stablecoin, addr1, } = await loadFixture(deployStablecoin);
await expect(stablecoin.connect(addr1).pause()).to.be.revertedWith(/AccessControl: account .* is missing role .*/)
});
```

add regular expressions in revertedWith

---

.changeset/warm-ghosts-rescue.md
packages/hardhat-network-helpers/src/helpers/takeSnapshot.ts
packages/hardhat-network-helpers/src/loadFixture.ts
packages/hardhat-network-helpers/test/loadFixture.ts

---
Please check this issue https://github.com/NomicFoundation/hardhat/issues/3249 for more details and discussion.
The way that loadFixture is working now is that allows situations like this:
```
Load fixture 1
...
Load fixture n - 1
Load fixture n
```
Up until this point every loadFixture takes a snapshot and store it in snapshots array. If loadFixture is called for any `n-i` it will work because it reverts the state to previous state. However, it also allows this, which fails because it tries to revert from previous to future state:
```
Load fixture 1
...
Load fixture n 
Load fixture n - i
Load fixture n -> fails with invalid snapshot error
```
My proposal is to remove all snapshots that have snapshot id bigger than snapshot being restored. This way it will ensure that every time …

Fix load fixture issue when reverting to future state

---

packages/hardhat-ethers/README.md

Closes #3355. I didn't add the overloaded versions to keep it simple.

Add deployContract to hardhat-ethers readme

---

packages/hardhat-etherscan/package.json
packages/hardhat-etherscan/src/solc/metadata.ts
yarn.lock

`@types/cbor` has been deprecated.
`cbor` provides its own type definitions now.

Upgrade cbor and fix cbor import type

---

.changeset/sour-onions-knock.md
packages/hardhat-etherscan/src/index.ts

Adds an optional --no-compile flag to the verify task, which does what you'd expect it to do.

Add no-compile flag to etherscan verify task

---

.changeset/stale-donkeys-punch.md
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/src/types/artifacts.ts
packages/hardhat-core/test/internal/artifacts.ts

I needed a synchronized version of **getBuildInfo** (like readArtifactSync) in a Hardhat plugin I am developing.
It would be nice to have a synchronized version to use in the constructor as well.

Add getBuildInfoSync

---

.changeset/real-donuts-hope.md
packages/hardhat-core/src/internal/core/jsonrpc/types/output/metadata.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/web3.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeForkClient.ts
packages/hardhat-core/test/fixture-projects/non-default-chainid/hardhat.config.js
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts

Adds a new `hardhat_metadata` RPC method. This method is meant to be used by other tools, like wallets or deployment systems, to get information about the instance of the network.

Add hardhat_metadata RPC method

---

packages/hardhat-core/test/fixture-projects/consistent-build-info-names/contracts/A.sol
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/contracts/B.sol
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/hardhat.config.js
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/node_modules/dependency/contracts/Dep1.sol
packages/hardhat-core/test/fixture-projects/consistent-build-info-names/node_modules/dependency/contracts/Dep2.sol
packages/hardhat-core/test/fixture-projects/project-with-scripts/contracts/a.sol

This PR:
- Adds some licenses/pragmas to prevent some solc warnings in the test output
- Disables the compilation result log in a test that runs 100 compilations, by overriding a subtask in the fixture project. We can't just use `quiet: true` here because because the test is compiled fresh (after a `hh clean`).

Reduce noise in test output

---

.changeset/big-meals-mate.md
packages/hardhat-etherscan/src/config.ts

Putting the etherscan config within `networks` instead of doing it at the root of the config seems to be a common mistake (see comments in [this issue](https://github.com/NomicFoundation/hardhat/issues/2351)).
This PR adds a warning when there's no top-level etherscan configuration but there is a `networks.etherscan` object.
In theory, this could be annoying to someone that has a valid `etherscan` network (for some reason?). In that case, the workaround would simply be to add `etherscan: {}` to the config.

Show warning when etherscan config is within networks

---

.changeset/rich-berries-confess.md
packages/hardhat-core/src/builtin-tasks/flatten.ts
packages/hardhat-core/src/internal/solidity/dependencyGraph.ts
packages/hardhat-core/test/builtin-tasks/flatten.ts

Fixes #3390.
Ideally this should be fixed in the `DependencyGraph` class itself, but the way the graph is built (side-effects based) makes it a bit hard. So I just fixed this in the flatten task itself.

Make the flatten task deterministic

---

packages/hardhat-core/src/internal/cli/cli.ts

- [] I didn't do anything of this.
---
Based on [this discussion ](https://github.com/NomicFoundation/hardhat/issues/3226), the check for local installation is not valid in all cases. In this PR I've simply added an env variable to skip this check. I would highly advise that the check is removed entirely as the current implementation is not correct. Having the hardhat package.json within the sub-directory of the cwd does not capture all cases of local installation. 
Additionally this is purely predicting that there'll be a future error and preventing cli from running. It might be best to allow the cli to run until an error case is hit

Allow skipping of local installation check

---

.changeset/sixty-zoos-explain.md
packages/hardhat-core/src/internal/core/providers/gas-providers.ts
packages/hardhat-core/test/internal/core/providers/mocks.ts

Closes #3395.
Bigints are not serializable, so the call to `eth_feeHistory` was always failing.
This is hard to test, so I just added a statement stringifying the params in the `MockProvider` used by the tests. This makes the request fail if the params are not serializable, which is a bit more realistic. The relevant tests failed with that change, and the fix made them pass again.

Fix bug in AutomaticGasPriceProvider

---

docs/src/content/tutorial/deploying-to-a-live-network.md

Removing the Chainlink faucet as they no longer send test ethers.
---
Updating faucet links

Updating relevant Goerli faucet

---

.github/workflows/add-issue-to-project.yml
.github/workflows/add-label-to-new-issue.yml

Add two new workflows:
- One adds new issues to the GH project
- The other one adds a proper `status:triaging` label unless the issue already has a label that starts with `status:`

Add workflows for new issues

---

.github/workflows/add-issue-to-project.yml

Use the `pull_request_target` event instead of `pull_request`. `pull_request_target` runs in the target repository of the PR (which almost always means the `main` branch) and has write permissions and access to secrets. The "Add to project" workflow needs access to secrets, because it needs a token with org-level project permissions, and these are not available in the `GITHUB_TOKEN` secret.
Using `pull_request_target` is dangerous [in some scenarios](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/), but I believe it's safe in this case: we are only running a single job with a single step that uses an official action.

Use pull_request_target as the workflow trigger

---

.github/workflows/hardhat-network-tracing-all-solc-versions.yml
docs/next.config.js
docs/src/content/hardhat-vscode/docs/overview.md
docs/src/content/tutorial/creating-a-new-hardhat-project.md

Hey,
This tiny PR will fix : 
- 1 typo in `.github/workflows/hardhat-network-tracing-all-solc-versions.yml`
- 1 typo in `docs/next.config.js`
- 1 typo in `docs/src/content/hardhat-vscode/docs/overview.md`
- 1 typo in `docs/src/content/tutorial/creating-a-new-hardhat-project.md`
Cheers! :robot:

docs: fix typos

---

.changeset/healthy-fishes-mix.md
.changeset/wise-moose-know.md
packages/hardhat-core/src/internal/util/download.ts
packages/hardhat-vyper/src/downloader.ts

This PR aims to fix the timeouts when downloading the vyper compiler, as reported by @nventuro
Apparently there are two sources of errors:
1) Plain timeouts when the download takes more than 10s (!)
2) A rate limit that github applies
This PR bumps the timeout, and copies a clever trick that `vvm` uses when running on github actions.

Fix vyper compiler download timeouts

---

packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/putGenesisBlock.ts

Avoids usage of an ethereumjs-specific state trie and instead uses the `VMAdapter` interface.

misc: cleanup ethereumjs-specific code

---

.changeset/early-parrots-attend.md
docs/src/content/hardhat-network/docs/reference/index.md
packages/hardhat-core/scripts/test-debug-trace-transaction.ts
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/evm.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/putGenesisBlock.ts
packages/hardhat-core/src/types/config.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/evm.ts
packages/hardhat-core/test/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/utils/runFullBlock.ts
packages/hardhat-network-helpers/src/helpers/time/increase.ts
packages/hardhat-network-helpers/src/helpers/time/increaseTo.ts
packages/hardhat-network-helpers/src/helpers/time/setNextBlockTimestamp.ts
packages/hardhat-network-helpers/src/utils.ts
packages/hardhat-network-helpers/test/fixture-projects/allow-blocks-same-timestamp/hardhat.config.js
packages/hardhat-network-helpers/test/helpers/time/increase.ts
packages/hardhat-network-helpers/test/helpers/time/increaseTo.ts
packages/hardhat-network-helpers/test/helpers/time/setNextBlockTimestamp.ts

This PR adds a new `allowBlocksWithSameTimestamp` option to Hardhat Network that doesn't force the timestamp of new blocks to be different than the last one.
The first commit in this PR should be reviewed on its own to make things simpler. It's a refactor that I think it was long due: it changes the constructor of `HardhatNetworkProvider` so that it receives most of its parameters in an object. This makes the code easier to read and change in several places. I also removed the "network name" parameter, since it wasn't used anywhere.
The rest of the changes adds the new option, modifies the network helpers to not check the timestamp (instead letting Hardhat itself throw an error if there's a wrong argument), update the docs and add tests.
Closes #2560.
Closes #3045.

Add option to allow mining blocks with the same timestamp

---

.changeset/dry-guests-count.md
.changeset/few-flies-drum.md
docs/src/content/hardhat-runner/docs/troubleshooting/common-problems.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/core/providers/http.ts
packages/hardhat-core/src/internal/util/download.ts
packages/hardhat-core/src/internal/util/proxy.ts
packages/hardhat-core/test/internal/util/download.ts
packages/hardhat-etherscan/src/etherscan/EtherscanService.ts
packages/hardhat-etherscan/src/solc/version.ts
packages/hardhat-etherscan/src/undici.ts
yarn.lock

This PR:
- Adds support for the `http_proxy` environment variable both for downloading the compiler and for the HTTP provider. This means that both forking and connecting to networks via JSON-RPC should use the proxy.
- Adds support for using `http_proxy` in `hardhat-etherscan`.
As part of this, I'm technically introducing a breaking change: the `HTTP_PROXY` and `HTTPS_PROXY` variables don't work anymore for the compiler download. The first one (all uppercase) is not the most commonly used, for [fun historical reasons](https://everything.curl.dev/usingcurl/proxies/env#http_proxy-in-lower-case-only). And the second one is misleading: we use the same proxy for both http and https.

Improve proxy support

---

.changeset/few-sheep-drive.md
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/cli/cli.ts

Fixes https://github.com/NomicFoundation/hardhat/issues/680
---
Before:
After:
Opening as a Draft because as you can see there are other errors which are still printed entirely colored. Changing that would be more effort but it would look more consistent. Let me know your thoughts.
Note this may conflict with a potential future Solidity feature: https://github.com/ethereum/solidity/issues/11507
To-do:

Improve colors when printing compiler errors

---

docs/src/components/DocumentationLayout.tsx
docs/src/components/landingBlocks/HeroBlock.tsx

---
I changed the `z-index` of the hero element so this doesn't happen:
And configured the sidebar to not have a scrollbar when one isn't necessary, like so:

Website UI improvements: hero x-index order and sidebar scrollbar

---

docs/src/assets/trustedTeamsLogos/logos.ts
docs/src/components/LandingFooter.tsx
docs/src/content/home.ts

---
Solves issue #3697 
This PR merely changes the footer copyright year from _hard-coded_ 2022 to 2023 using `Date()` module. This will remove the need for yearly updates on the landing page.

updates copyright year at the footer using Date module

---

crates/rethnet_evm/src/state/debug.rs
crates/rethnet_evm/src/state/layered_state.rs

docs(rethnet): clarify that modify_account operates on empty accounts

---

.changeset/lazy-seas-exercise.md
packages/eslint-plugin/onlyHardhatErrorRule.js

Most of the PR changes are just things our own linting auto-fixed, but the main change is a small tweak to the logic for the hardhat plugin error linter to make it possible to use the lint rule for error classes that extend the `HardhatPluginError` class (i.e. `IgnitionError`)

allow linting classes that extend the HardhatPluginError class

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
[hardhat-contract-clarity](https://www.npmjs.com/package/hardhat-contract-clarity) A plugin to use chatGPT3 API to summarize contract (in text description), create a readme and ask about an error msg the powerful OpenAI ChatGPT
[transaction-retry-tool](https://www.npmjs.com/package/transaction-retry-tool) A tool to retry a transaction hash with a higher gas price

add 2 plugins (hardhat-contract-clarity and transaction-retry-tool)

---

.changeset/twenty-toys-wave.md
packages/hardhat-core/src/internal/core/providers/http.ts

Prior to this change, the error message is not visible when the exception is thrown.
Before:
```
npx hardhat run --network goerli scripts/deploy_big_contract.js
ProviderError: HttpProviderError
at HttpProvider.request (/Users/user/research/tmp/hh-test1/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
at LocalAccountsProvider.request (/Users/user/research/tmp/hh-test1/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at EthersProviderWrapper.send (/Users/user/research/tmp/hh-test1/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```
After:
```
npx hardhat run --network goerli scripts/deploy_big_contract.js
ProviderError: max code size exceeded
at …
```

Propagate HttpProviderError exception message

---

.changeset/dull-files-dream.md
packages/hardhat-core/sample-projects/typescript/tsconfig.json

I think `"resolveJsonModule": true` should be added to sample project tsconfig because it's a pretty common case to import ABI from JSON files in tests. By far, i've been adding this setting manually to all the projects bootstrapped with hardhat. I believe that it would be better include it by default.

Set "resolveJsonModule": true in sample tsconfig

---

.changeset/healthy-cups-march.md
.changeset/quiet-queens-talk.md
.github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/pre-release.yml
packages/hardhat-vyper/.mocharc.json
packages/hardhat-vyper/README.md
packages/hardhat-vyper/src/constants.ts
packages/hardhat-vyper/src/downloader.ts

Previously we were downloading directly from Github, which is unstable and rate-limited. 
I created [a mirror of the releases page](https://github.com/NomicFoundation/vyper-releases-mirror) using github actions and vercel, and this PR uses it.

Use our mirror to download the Vyper compilers

---

.changeset/strange-drinks-cry.md
packages/hardhat-solhint/package.json
packages/hardhat-solhint/src/index.ts
packages/hardhat-solhint/test/tests.ts
yarn.lock

---
Fixes #3724.
The error described in the aforementioned issue comes from https://github.com/protofire/solhint/pull/380, which updated ESLint from v5 to v8 in Solhint 3.4.0. In ESLint v8, `eslint/lib/formatters/${formatterName}` is no longer a valid path. However, Solhint is now shipping the formatters, so we can use `solhint/lib/formatters/${formatterName}` instead.

Fix hardhat-solhint plugin error with solhint 3.4.0

---

.changeset/fix-getContractFactory-signer.md
packages/hardhat-ethers/src/internal/helpers.ts

- [ X ] Because this PR includes a **bug fix**, relevant tests have been included.
---
The current instanceof check will fail for ethers.Wallets that are imported from another ethers outside hardhat.
Consider this code that deploys a test contract from a clean wallet (to achieve deterministic addresses):
```typescript
import { ethers } from "hardhat"
import { Wallet, utils } from "ethers"
async function deployMyContract(deployer: Wallet) {
return (await ethers.getContractFactory("MyContract", deployer)).deploy()
}
async function deployContracts() {
const [admin] = await ethers.getSigners() as unknown as Wallet[]
const cleanWallet = new Wallet(utils.id("testing"), admin.provider)
await (await admin.sendTransaction({ to: cleanWallet.address, value: parseEther("1") })).wait()
await …
```

fix: ethers.Signer check in getContractFactory

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Hardhat plugin for Uniswap V2 (pancakeswap protocol) testing and deployment. You can use it to test features such as pair creation, liquidity provisioning, and swaps.
https://github.com/onmychain/hardhat-uniswap-v2-deploy-plugin

Added hardhat-uniswap-v2-deploy-plugin

---

crates/rethnet_evm/Cargo.toml
crates/rethnet_evm/benches/state.rs
crates/rethnet_evm/src/state/hybrid.rs
crates/rethnet_evm/src/state/layered.rs

Fixes https://github.com/NomicFoundation/rethnet/issues/71

feat: assorted synthetic benchmarks for `SyncState`

---

crates/rethnet_evm/benches/state.rs

It wasn't even doing anything at all!

fix: bug in benchmark of `StateRef::basic()`

---

.changeset/lazy-hornets-clap.md
packages/hardhat-chai-matchers/src/internal/emit.ts
packages/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
packages/hardhat-chai-matchers/test/events.ts
packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts

Fix .withArgs when arrays have different length

---

.cargo-husky/hooks/pre-commit
crates/rethnet/Cargo.toml

given that we've just made a bunch of changes to the CI test scripts, it was bothering me that the `pre-commit` git hook wasn't matching up with those recent changes.

chore: sync pre-commit hook to CI

---

packages/hardhat-ethers/src/internal/ethers-utils.ts
packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
packages/hardhat-ethers/src/signers.ts

This fixes our latest-dependencies CI workflow.

Use more future-proof type imports from ethers

---

.changeset/cuddly-grapes-wink.md
packages/hardhat-verify/src/errors.ts
packages/hardhat-verify/src/etherscan.ts
packages/hardhat-verify/src/index.ts
packages/hardhat-verify/test/integration/index.ts
packages/hardhat-verify/test/unit/index.ts

Changes:
- Update the error class name to match the plugin's name.
- Do not compile when running the task and remove the `--no-compile` flag. Update the tests accordingly.
Closes #3969

Rename error class & avoid compiling

---

docs/src/content/hardhat-runner/docs/other-guides/truffle-testing.md
packages/hardhat-truffle5/README.md
packages/hardhat-web3/README.md

This PR pins the `web3` version in the installation guide of `hardhat-truffle5` and `hardhat-web3`. The reason is that `web3` version `4.0.1` just got released (https://github.com/web3/web3.js/releases/tag/v4.0.1) and `npm` targets this version now which I think is incompatible with the current `hardhat-truffle5` and `hardhat-web3` versions.
I don't think this PR deserves a changeset, but lmk if you want one.

Pin `web3` version in installation guides

---

.changeset/polite-mugs-cry.m
packages/hardhat-verify/src/chain-config.ts

Aurora team dropped support of the previous domain names. This change is needed to fix verification on Aurora.

fix aurora browser urls

---

.changeset/fluffy-papayas-reflect.md
docs/src/content/hardhat-runner/docs/advanced/scripts.md
docs/src/content/hardhat-runner/docs/reference/_dirinfo.yaml
docs/src/content/hardhat-runner/docs/reference/environment-variables.md
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/cli/project-creation.ts

Closes #4012.
Adds a new `HARDHAT_DISABLE_TELEMETRY_PROMPT` variable that, if set to true, will prevent Hardhat from showing the telemetry consent prompt the first time it's run, or during the project initialization.
I also wrote an "Environment variables" reference page, which was long overdue.

Add HARDHAT_DISABLE_TELEMETRY_PROMPT envvar

---

.changeset/silver-meals-tan.m
.changeset/silver-meals-tan.md
packages/hardhat-verify/src/index.ts
packages/hardhat-verify/src/task-names.ts
packages/hardhat-verify/test/integration/index.ts
packages/hardhat-verify/test/unit/index.ts

---
Fixes: #4023 
A new task was added for listing the supported networks and it was used to list them without having to pass an address as a parameter.

hardhat-verify: fix list supported networks issue

---

.changeset/tidy-points-arrive.md
packages/hardhat-verify/src/index.ts
packages/hardhat-verify/test/integration/index.ts

---
Modify the success message for a more generic one. 
The `on Etherscan` statement was changed by `the block explorer` being consistent with similar message on https://github.com/NomicFoundation/hardhat/blob/c21648d99ce333718dbedb7703f933d63236a23e/packages/hardhat-verify/src/index.ts#L477-L480
Fixes #3960

Hardhat-verify: more generic success message

---

packages/hardhat-core/test/console/console.ts
packages/hardhat-core/test/fixture-projects/memory-safe-console/.gitignore
packages/hardhat-core/test/fixture-projects/memory-safe-console/contracts/Test.sol
packages/hardhat-core/test/fixture-projects/memory-safe-console/hardhat.config.js
packages/hardhat-core/test/fixture-projects/memory-safe-console/package.json

Add a fixture project that doesn't compile if `console.sol` is not memory safe, and a test that just compiles that project.

Add test for memory-safe console.sol

---

packages/hardhat-ledger/src/internal/with-spinners.ts

---
Adds a [hardhat-ledger] prefix to spinner logs of the hardhat ledger package

Add a prefix to the ledger spinner messages

---

packages/hardhat-core/package.json

This adds removal of compiler-input and compiler-output artifacts to the hardhat-core/clean script.

Remove compilation artifacts in the hardhat-core/clean script

---

.changeset/grumpy-pigs-complain.md
packages/hardhat-verify/src/chain-config.ts
packages/hardhat-verify/test/unit/config.ts

This PR removes the networks `rinkeby`, `ropsten`, and `kovan` from `hardhat-verify` since those are deprecated in the meantime.

♻️ Remove Deprecated Test Networks from `hardhat-verify`

---

.changeset/tricky-parents-warn.md
packages/hardhat-core/src/internal/util/download.ts

This is a workaround for an issue related to node v18.16.0 (and v18.16.1), the stream module and undici. See https://github.com/nodejs/undici/issues/2173 for the details.
Fixes #3877.

Consume downloads instead of piping them

---

packages/hardhat-core/test/internal/hardhat-network/jsonrpc/client.ts

Re-enable test that was skipped because of a bug in Alchemy, [see bug here](https://github.com/NomicFoundation/hardhat/issues/3712).

Re-enable test skipped because of Alchemy bug

---

.changeset/seven-shrimps-tell.md
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/test/builtin-tasks/compile.ts
packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/.gitignore
packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/contracts/A.sol
packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/contracts/C.sol
packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/contracts/E.sol
packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/hardhat.config.js
packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/node_modules/dependency/contracts/console.sol
packages/hardhat-core/test/fixture-projects/compilation-contract-with-deps/node_modules/dependency/package.json

Bug reproduction steps:
1. Create a contract that imports a dependency (can be local or external).
2. Compile the project.
3. Rename the contract, only changing the contract name (filename remains the same).
4. Compile again without using `--force` or `hh clean`.
5. Go to the artifacts folder. The debug file of the renamed contract will reference a valid build-info file. However, the imported dependency's debug file will point to a missing build-info file.
This issue occurs because the renamed contract is recompiled while the imported contract remains unchanged (which is correct). However, during the artifact cleanup, the original build-info file, which is still pointed by the imported contract, is mistakenly deleted. Two possible fixes are:
1. Ensure that every debug file points to the …

Fix deletion of valid build-info file

---

packages/hardhat-ethers/test/contracts.ts
yarn.lock

[`ethers@6.6.3`](https://github.com/ethers-io/ethers.js/releases/tag/v6.6.3) fixed a problem that was causing Hardhat to hang when `contract.once` was used.
This PR re-enables a test that was skipped for some reason. I also updated the `yarn.lock` so that ethers v6.6.3 is used locally.

Re-enable hardhat-ethers test

---

.changeset/healthy-poems-talk.md
packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeForkClient.ts
packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkBlockchain.ts

The code line: `const lastSafeBlock = latestBlock - maxReorg;` could result in a negative value when maxReorg > latestBlock.
Fix: add check, when the difference is a negative number then use latestBlock.

Negative block number queried when forked network block number is near zero

---

.github/workflows/check-changeset-added.yml

This will prevent the changesets check to run in PRs like [this one](https://github.com/NomicFoundation/hardhat/pull/3857).

Don't run changesets check in changesets PR

---

.changeset/five-colts-remain.md
packages/hardhat-vyper/README.md
packages/hardhat-vyper/package.json
packages/hardhat-vyper/src/parser.ts
packages/hardhat-vyper/test/fixture-projects/compilation-single-file-test-directive/contracts/A.vy
packages/hardhat-vyper/test/fixture-projects/compilation-single-file-test-directive/hardhat.config.js
packages/hardhat-vyper/test/tests.ts

Our vyper plugin only compiles things in test mode, which is dangerous, as it can leave things like this in production deployments.
[See issue here](https://github.com/NomicFoundation/hardhat/issues/2540).
Example:
```
#@ if mode == "test":
@external
def _mint_for_testing(_to: address, _token_id: uint256):
self._mint(_to, _token_id)
#@ endif
```
Solution: 
throw an error explaining that we currently do not support this feature if a test directive is found in the code.

[hardhat-vyper] Warn when test mode directive is present in contract sources

---

packages/hardhat-core/src/internal/core/jsonrpc/types/input/debugTraceTransaction.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/debug.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts

When calling `debug_traceTransaction` passing a `tracer` parameter that is not supported an error should be thrown.  [See issue here](https://github.com/NomicFoundation/hardhat/issues/3973).

debug_traceTransaction ignores "tracer" param

---

.github/workflows/test-slow-imports-rule.yml

Add a workflow that runs a simple smoke test to validate that our slow-imports eslint rule works as expected.
This will run once per day. The alternative was to try to figure out which file changes could break this (probably any change in the rules source and any change in `yarn.lock`), but I think once per day is simpler and good enough.

Test slow-imports rule

---

.changeset/chilly-meals-enjoy.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/cli/analytics.ts
yarn.lock

---
The solution to https://github.com/NomicFoundation/hardhat/issues/4110. Removed abort-controller dependency that was recommended by docs of the package node-fetch, which is no longer being used. Now core will use the native AbortController API included in node versions 15+, which is a direct replacement. No additional changes are needed (see https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

removed abort-controller dependency from core

---

packages/hardhat-truffle4/.mocharc.json

Doing this to see if it stops the CI false negatives for this package on windows.

Increase test timeout in hh-truffle4

---

crates/rethnet/tests/cli.rs
crates/rethnet_eth/src/remote.rs
crates/rethnet_eth/src/remote/methods.rs
crates/rethnet_eth/tests/integration_tests.rs
crates/rethnet_evm/src/state/hybrid.rs
crates/rethnet_rpc_server/src/lib.rs
crates/rethnet_rpc_server/tests/integration_tests.rs
packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/spawnRethnetProvider.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
packages/hardhat-core/test/setup.ts

Fixes https://github.com/NomicFoundation/rethnet/issues/94

test: Add Rethnet provider as JSON-RPC provider in Hardhat tests

---

.github/workflows/compile-with-typescript-v4.yml
package.json
packages/hardhat-chai-matchers/package.json
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/hardhat-network/provider/fork/rpcToTxData.ts
packages/hardhat-core/src/internal/util/unsafe.ts
packages/hardhat-ethers/package.json
packages/hardhat-foundry/package.json
packages/hardhat-ledger/package.json
packages/hardhat-network-helpers/package.json
packages/hardhat-shorthand/package.json
packages/hardhat-solhint/package.json
packages/hardhat-solpp/package.json
packages/hardhat-toolbox/package.json
packages/hardhat-truffle4/package.json
packages/hardhat-truffle5/package.json
packages/hardhat-verify/package.json
packages/hardhat-vyper/package.json
packages/hardhat-web3-legacy/package.json
packages/hardhat-web3/package.json
yarn.lock

We'll need this to be able to use viem.
@alcuadrado important things here:
- I'm using `~5.0.0` as the version range in all packages (even the toolbox).
- [This commit](https://github.com/NomicFoundation/hardhat/pull/4184/commits/999c5ea64f15b2873650676c8279e2807721c037) is the one that fixes the two compilation errors that showed up after upgrading.
- I added a workflow to compile the whole repository with typescript v4. I also pushed a temporary commit to double-check that the workflow fails as expected (see [here](https://github.com/NomicFoundation/hardhat/actions/runs/5620956258/job/15230842149)).

Upgrade to typescript v5

---

.changeset/chilly-llamas-sniff.md
packages/hardhat-core/src/builtin-tasks/flatten.ts
packages/hardhat-core/test/builtin-tasks/flatten.ts
packages/hardhat-core/test/fixture-projects/flatten-task/no-contracts/hardhat.config.js

[Link to main issue](https://github.com/NomicFoundation/hardhat/issues/1499).
- Improve the formatting for warning messages
- Add a check to avoid errors when the flattened file metadata are null

Make flatten task smarter: improve warning messages and add check for null metadata

---

.changeset/little-pianos-suffer.md
packages/hardhat-vyper/README.md

Change the ```vy into ```py in the vyper docs.
With ```vy the " character is escaped into &quot;
Error:
Expected:

Fix escaped double quote in vyper docs

---

crates/rethnet_eth/src/remote/client.rs
crates/rethnet_evm/benches/state/util.rs
crates/rethnet_evm/src/state/fork.rs
crates/rethnet_rpc_server/tests/integration_tests.rs

This is a follow up from https://github.com/NomicFoundation/hardhat/pull/4294 to change `#[allow(dead_code)]` annotations for the test temp dir to prefixed names.

refactor: change allow dead code to underscore prefix for tempdir

---

packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/estimateGas.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts
packages/hardhat-verify/src/internal/etherscan.ts
yarn.lock

Fixes https://github.com/NomicFoundation/hardhat/issues/4249.
In the latest version of `undici`, the type of `body.json()` is `Promise<unknown>` instead of `Promise<any>`. This change just uses an explicit `any` type in the places that were relying on that behavior.

Add explicit any type to some undici responses

---

packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-debug-tracer.ts
packages/hardhat-core/test/fixture-debug-traces/elongatedMemoryRegressionTestTrace.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts

[Link to issue](https://github.com/NomicFoundation/hardhat/issues/3858)
When calling the method debug_traceTransaction a large amount of 0s is retuned inside the memory property. This is wrong.
E.g.: 
The memory should stop after the 5th line, the one that starts with "0x82b429...."

Elongated memory data for debug_traceTransaction

---

.cargo-husky/hooks/pre-commit

This removes the run of `--no-default-features` from the commit hooks and changes the order to run lightweight commands first

chore(hooks): simplify pre-commit hooks

---

crates/rethnet_eth/Cargo.toml
crates/rethnet_eth/src/remote/cacheable_method_invocation.rs
crates/rethnet_eth/src/remote/client.rs

This PR contains changes that are a prerequisite for https://github.com/NomicFoundation/rethnet/issues/88:
- Per call cache resolution of batch requests
- Store only the call results instead of the JSON-RPC responses in the on-disk cache
- Some refactoring to simplify things

feat: cache batch requests per method call

---

Cargo.lock
crates/rethnet_defaults/src/lib.rs
crates/rethnet_eth/Cargo.toml
crates/rethnet_eth/src/receipt.rs
crates/rethnet_eth/src/remote/client.rs
crates/rethnet_eth/src/remote/eth.rs
crates/rethnet_eth/src/serde.rs
crates/rethnet_eth/tests/receipt.rs
crates/rethnet_evm/Cargo.toml
crates/rethnet_evm/benches/state/database_commit.rs
crates/rethnet_evm/src/blockchain/remote.rs
crates/rethnet_evm/tests/blockchain.rs

This PR started out as a quickfix for `Block<Transaction>` deserialization that was blocking @Wodann , but then some new issues popped up for which I also included fixes. Specifically, this PR contains:
- Make it possible for `Block<Transaction>` to be deserialized from `serde_json::Value`
- Make it possible for `TypedReceipt<Log>` to be deserialized from `serde_json::Value`
- Fix deserialization for `yParity` in `Block`. Geth recently [started to return](https://github.com/ethereum/go-ethereum/pull/27744) `yParity` alongside the `v` parameter for EIP-2930 and EIP-1559 transactions even though these should only contain the `yParity` parameter in theory. I discovered this when fetching blocks from Infura.
- Join some remote tests in the rpc client to reduce requests to avoid getting rated …

fix: rpc result serde and avoid rate limits

---

Cargo.lock
crates/rethnet_eth/Cargo.toml
crates/rethnet_eth/src/remote/client.rs

Add retry logic for the rpc client to help without rate limiting. 
In addition to 429 responses, it also handles 5xx responses and request timeouts.
Testing strategy: without this change the local test suite fails on my machine with rate limit errors, with this change, it succeeds.

feat: retry for rpc client

---

crates/rethnet_eth/src/block.rs
crates/rethnet_eth/src/block/reorg.rs
crates/rethnet_eth/src/remote/cacheable_method_invocation.rs
crates/rethnet_eth/src/remote/client.rs
crates/rethnet_evm/src/blockchain/forked.rs
crates/rethnet_evm/src/blockchain/remote.rs
crates/rethnet_evm/src/state/remote.rs
crates/rethnet_evm/src/state/remote/cached.rs

This PR disables in-memory caching for unsafe block numbers. 
I'm not 100% sure if this is the right approach, but figured it's easiest to discuss in the context of a PR.

fix: disable in-memory cache for unsafe block number

---

crates/rethnet_defaults/src/lib.rs
crates/rethnet_eth/src/block.rs
crates/rethnet_eth/src/block/reorg.rs
crates/rethnet_eth/src/remote/client.rs
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts

Fixes failure 2 in https://github.com/NomicFoundation/rethnet/issues/175 by caching block numbers for validation purposes for the block time interval.
This change brings down the running time of the tests from ~2 minutes to ~75 seconds (before the CI broke, these tests took around ~45 seconds). This is still over the initial 50 second timeout. If I disable the block number checks for in memory caches, the running time goes back to the initial ~45 seconds. Some slow down is to be expected here since the previous version of the code cached all block numbers, so I increased the timeout to 80 seconds. As an alternative we could pin the tests to a safe block number.
Do note however that these [tests run in <5 seconds](https://github.com/NomicFoundation/hardhat/actions/runs/6013413577/job/163108 …

fix: cache block numbers for block time duration

---

crates/rethnet_evm/benches/state/state_debug.rs
crates/rethnet_evm/src/state/fork.rs
packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts

`ForkState` does not currently calculate an accurate account storage root as we have no easy way of combining historic account storage with the local one.
As this is line with Hardhat, we'll for now opt to just return a KECCAK hash of the null RLP-encoding.
If people request the feature for Hardhat (or EDR), we might add proper support in the future.

fix: WETH contract test

---

packages/hardhat-core/src/internal/hardhat-network/provider/utils/reorgs-protection.ts

When implementing the Rethnet RPC cache we [decided](https://github.com/NomicFoundation/rethnet/issues/88#issuecomment-1690506457) to use a more conservative safe reorg depth than Hardhat Network. This PR changes the Hardhat Network reorg depth numbers to match the ones in [Rethnet.](https://github.com/NomicFoundation/hardhat/blob/db287b4463e4b3cedade1f315edc0903ddbe2645/crates/rethnet_eth/src/block/reorg.rs#L57)
The motivation for this PR is that if no fork block number is provided in the `hardhat-core` tests, they’ll use a fallback fork block number [calculated](https://github.com/NomicFoundation/hardhat/blob/db287b4463e4b3cedade1f315edc0903ddbe2645/packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts#L42) with the Hardhat Network logic and [pass …

fix: align Hardhat Network safe reorg depth with Rethnet

---

.github/workflows/hardhat-core-ci.yml
packages/hardhat-core/src/internal/hardhat-network/provider/utils/reorgs-protection.ts

Add a CI job for running `hardhat-core` tests in `rethnet` mode that retains the Rethnet RPC cache.
Resolves https://github.com/NomicFoundation/rethnet/issues/87
https://github.com/NomicFoundation/hardhat/pull/4375 should be merged first.

ci: add test provider with EDR RPC cache job

---

docs/src/content/hardhat-network/docs/overview/index.md

[See issue here](https://github.com/NomicFoundation/hardhat/issues/4390)
Remove `Ethereum Studio` from docs.

Ethereum Studio is no longer available

---

Cargo.lock
crates/rethnet_eth/Cargo.toml
crates/rethnet_eth/src/remote/client.rs

Fix RPC cache when `tmp` is on different filesystem by using a temporary directory under the RPC cache dir instead of the system default `tmp` directory. The downside of this approach is that left-over files won't be cleared up in case we crash between creating a temporary file and moving it into its place. This is an acceptable trade-off imo.
Closes https://github.com/NomicFoundation/edr/issues/196

fix: fix RPC cache when tmp is on different filesystem

---

crates/rethnet_evm/src/debug_trace.rs
crates/rethnet_evm/src/lib.rs
crates/rethnet_evm_napi/src/debug_trace.rs
packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
yarn.lock

Add EDR support for `debug_traceCall`. Please note that the base branch is https://github.com/NomicFoundation/hardhat/pull/4410.

feat: debug trace call

---

packages/hardhat-core/package.json

The `edr` package version got pinned by accident in https://github.com/NomicFoundation/hardhat/pull/4415, this PR fixes that.

chore: fix edr package version in hardhat-core

---

packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts

Re-enable tests related to max initcode size. Fixes https://github.com/NomicFoundation/edr/issues/103
As it turns out, the tests are passing without making a change to REVM, since REVM derives max initcode size from the contract code size and we're setting the contract code size to the maximum when `allowUnlimitedContractSize` is set to true in the EDR.

test: re-enable tests related to max initcode size

---

Cargo.lock
crates/rethnet_eth/Cargo.toml
crates/rethnet_evm/Cargo.toml
crates/rethnet_evm_napi/index.d.ts
crates/rethnet_evm_napi/src/cast.rs
crates/rethnet_evm_napi/src/config.rs
packages/hardhat-core/src/internal/hardhat-network/provider/context/rethnet.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts

Follow up from https://github.com/NomicFoundation/hardhat/pull/4448 for https://github.com/NomicFoundation/edr/issues/103

feat: allow configuring max initcode size

---

crates/rethnet_evm/src/trace.rs
crates/rethnet_evm_napi/index.d.ts
crates/rethnet_evm_napi/src/trace.rs
packages/hardhat-core/src/internal/hardhat-network/provider/context/rethnet.ts
packages/hardhat-core/src/internal/hardhat-network/provider/miner/rethnet.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts

Add [`solidity-coverage`](https://github.com/sc-forks/solidity-coverage/tree/master) support for Hardhat network in EDR mode. Resolves https://github.com/NomicFoundation/edr/issues/44
I had to make [changes](https://github.com/sc-forks/solidity-coverage/pull/817) in `solidity-coverage` as the property layout of the EthereumJS VM changed after the dual mode changes from
```
node._vm.evm.events
```
to 
```
node._context._vm._vm.evm.events
```
I tested the changes in this PR by running the `solidity-coverage` test suite in [my fork](https://github.com/agostbiro/solidity-coverage/tree/agostbiro/hardhat-dual-vm-mode-compat) against a local version of `hardhat` with `HARDHAT_EXPERIMENTAL_VM_MODE=rethnet` and `HARDHAT_EXPERIMENTAL_VM_MODE=ethereumjs`.

feat: solidity coverage support in EDR mode

---

packages/hardhat-core/src/internal/hardhat-network/provider/context/edr.ts
packages/hardhat-core/src/internal/hardhat-network/provider/miner.ts
packages/hardhat-core/src/internal/hardhat-network/provider/miner/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/miner/edr.ts
packages/hardhat-core/src/internal/hardhat-network/provider/miner/hardhat.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/edr.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/proxy-vm.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts

WIP. I implemented the step handler for both ethereumjs and edr modes, and verified that it works. I also implemented the `_vm.stateManager` part of this, which smock needs.
Pending here is the `beforeMessage`/`afterMessage` handlers, for both ethereumjs and edr modes.

refactor: replace vm stub in adapters with vm proxy in node

---

packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts

Fixes https://github.com/NomicFoundation/edr/issues/205 and all outstanding test failures in the `openzeppelin-contracts` repo when ran against `rethnet/main` except for: https://github.com/NomicFoundation/edr/issues/206.
Co-authored with @Wodann .

fix: unmatched edr exceptional halt

---

.changeset/unlucky-pens-melt.md
packages/hardhat-core/src/internal/util/download.ts

The compiler downloader was broken because it was trying to write an `ArrayBuffer` to a file. This commit fixes it by converting the `ArrayBuffer` to a `Buffer` before writing it to the file.
This was working before because undici was returning a `Uint8Array` under the hood, but this was fixed in [the latest version](https://github.com/nodejs/undici/releases/tag/v5.26.4).

Fix compiler download
