src/builtin-tasks/compile.ts
src/builtin-tasks/help.ts
src/builtin-tasks/test.ts
src/builtin-tasks/utils/cache.ts
src/cli/InteractiveDeployer.ts
src/core/project-structure.ts
src/core/tasks/builtin-tasks.ts
src/core/truffle.ts
src/util/glob.ts

This PR fixes some `require` calls that we missed during the TS migration and creates a `glob.ts` file to avoid promisifying the same thing all the time

Fix requires

---

src/config-dsl.d.ts

I accidentally introduced an error in the latest TypeScript PR, this fixes it.

Fix error in src/config-dsl.d.ts

---

.travis.yml

This is normally a merge commit, and we base branches from those. If we
don't test them Codecov won't have stats to compare PR's results.

Make travis test the latest commit in master.

---

src/builtin-tasks/compile.ts
src/solidity/dependencyGraph.ts
src/solidity/resolver.ts
test/solidity/dependencyGraph.ts

Test dependency graph

---

src/core/providers/ethereum.ts
src/core/providers/web3x-ethereum.ts
test/core/providers/web3x-ethereum.ts

I spotted some Unhandled Promise Rejections in the tests due to a few bugs fixed here

Fix some bugs in the provider wrappers

---

src/builtin-tasks/flatten.ts
src/cli/ArgumentsParser.ts
src/cli/HelpPrinter.ts
src/cli/cli.ts
src/core/config/config-env.ts
src/core/params/buidler-params.ts
src/core/params/env-variables.ts
src/core/runtime-environment.ts
src/core/tasks/dsl.ts
src/core/tasks/task-definitions.ts
src/lib/buidler-lib.ts
src/solidity/resolver.ts
src/types.ts
test/cli/ArgumentsParser.ts
test/core/runtime-environment.ts
test/core/tasks/task-defintions.ts
test/fixture-projects/plugin-project/plugins/example.ts
test/helpers/environment.ts

This PR must be merged after #126

Remove cyclic dependencies

---

src/lib/buidler-lib.ts
test/helpers/environment.ts
test/lib/buidler-lib.ts

This PR must be merged after #128

Make Buidler lib a CommonJS module

---

src/lib/buidler-lib.ts
test/helpers/environment.ts
test/lib/buidler-lib.ts

The previous PR was accidentally merged into a feature branch

Export the BuidlerRuntimeEnvironment as a CJS export

---

src/builtin-tasks/help.ts
src/internal/cli/project-creation.ts
src/internal/constants.ts

We where using the package name, but it's scoped now.

Get Buidler's and bin's names from constants.

---

src/internal/util/lazy.ts

Proxies have to respect a few invariants, which we were violating in some cases. We now respect them by reflecting any change and initial property from the real target in the dummy target.

Preserve Proxy invariants in lazyObject and lazyFunction

---

src/builtin-tasks/test.ts
src/internal/solidity/compiler/index.ts

* Fix bug in test task glob pattern
* Make the Compiler bypass any require hook

Fix two bugs

---

docs/.gitignore
docs/package.json
docs/typedoc.json
docs/yarn.lock
src/internal/artifacts.ts
src/internal/core/config/config-env.ts
src/internal/core/config/config-resolution.ts
src/internal/core/errors.ts
src/internal/core/params/argumentTypes.ts
src/internal/core/runtime-environment.ts
src/internal/core/tasks/dsl.ts
src/internal/core/tasks/task-definitions.ts
src/types.ts

To generate the api docs you should run:
```
yarn install
yarn docs:apidocs
```

Add documentation for the public API

---

README.md
src/internal/core/typescript-support.ts

A `return` was missing 😩, and I simplified the logic

Change the TS support detection logic

---

packages/buidler-core/src/internal/solidity/dependencyGraph.ts
packages/buidler-core/test/fixture-projects/cyclic-dependencies-project/contracts/A.sol
packages/buidler-core/test/fixture-projects/cyclic-dependencies-project/contracts/B.sol
packages/buidler-core/test/internal/solidity/dependencyGraph.ts
packages/buidler-core/test/internal/solidity/resolver.ts

Add support for cyclic dependencies

---

packages/buidler-core/src/internal/solidity/resolver.ts
packages/buidler-core/test/fixture-projects/scoped-dependency-project/contracts/A.sol
packages/buidler-core/test/fixture-projects/scoped-dependency-project/node_modules/@scope/package/contracts/File.sol
packages/buidler-core/test/fixture-projects/scoped-dependency-project/node_modules/@scope/package/package.json
packages/buidler-core/test/internal/solidity/resolver.ts

Add support for scoped packages

---

packages/buidler-core/src/internal/core/typescript-support.ts

[core] Automatically add TS_NODE_FILES=true if not present

---

packages/buidler-core/src/internal/core/typescript-support.ts

Print a warning when ts-node fails to load

---

packages/buidler-core/src/internal/artifacts.ts
packages/buidler-core/test/internal/artifacts.ts

[core] saveArtifact artifact ensures that the artifacts' dir exists

---

packages/buidler-core/src/internal/cli/ArgumentsParser.ts
packages/buidler-core/test/internal/cli/ArgumentsParser.ts

Fix ArgumentParser bug

---

CONTRIBUTING.md
packages/buidler-core/README.md
packages/buidler-core/package-lock.json
packages/buidler-core/package.json
packages/buidler-core/src/builtin-tasks/compile.ts
packages/buidler-core/src/internal/cli/cli-with-a-typo.ts
packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/cli/project-creation.ts
packages/buidler-core/src/internal/core/typescript-support.ts

[core] Migrate from ansi-color to chalk

---

docs/documentation/README.md
packages/buidler-core/src/internal/core/runtime-environment.ts
packages/buidler-core/src/types.ts
packages/buidler-core/test/internal/core/tasks/dsl.ts
packages/buidler-core/test/internal/core/tasks/task-definitions.ts
packages/buidler-solhint/src/index.ts

Fixes #320 
@jjant what do you think about the first commit in this PR?

Fix buidler-solhint

---

packages/buidler-core/src/builtin-tasks/console.ts
packages/buidler-core/src/builtin-tasks/run.ts
packages/buidler-core/src/internal/cli/analytics.ts
packages/buidler-core/src/internal/cli/cli.ts
packages/buidler-core/src/internal/lib/buidler-lib.ts
packages/buidler-core/src/register.ts

This PR:
* Normalizes some logger names
* Let users enable verbose mode in register and lib
* Adds log messages to `run` and `console` tasks

Logging improvements

---

docs/.vuepress/plugins.js

https://github.com/rhlsthrm/buidler-typechain

Add my TypeChain plugin to the directory

---

packages/buidler-solhint/src/index.ts

Require eslint formatters from solhint's eslint

---

packages/buidler-core/src/internal/buidler-evm/provider/modules/eth.ts
packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/test/internal/buidler-evm/provider/modules/evm.ts

This PR fixes a bug in our snapshots implementation: they didn't manage block filters at all.
Now when a snapshot is reverted, the state of every filter is restored, and the filter ids generation logic is also restored to its previous state.

[Buidler EVM] Make snapshots aware of block filters

---

CONTRIBUTING.md
package.json

Install project just running `npm install` at root folder.
✅ tested on Windows 10.

Installing enhancement

---

.github/workflows/CI.yml

This PR changes our CI workflow to only trigger on pushes to master and new PRs

Deduplicate GitHub Actions

---

packages/buidler-core/src/builtin-tasks/utils/cache.ts

Fix bug in the compilation cache

---

packages/buidler-core/src/internal/cli/project-creation.ts

This PR:
1. Prevents the project creation module to automatically install dependencies on windows. We should investigate what's going on there.
2. Improves the recommended commands section.

Sample project creation improvements

---

packages/buidler-core/src/internal/buidler-evm/provider/modules/eth.ts
packages/buidler-core/src/internal/buidler-evm/provider/provider.ts

This PR introduces two minor improvements.

RPC log improvements

---

docs/getting-started/README.md
docs/guides/create-task.md
docs/troubleshooting/verbose-logging.md
packages/buidler-core/src/internal/cli/HelpPrinter.ts

Added missing `npx` before `buidler help [task]` (docs + cli)

Add missing npx

---

.github/workflows/CI.yml
packages/buidler-core/package.json
packages/buidler-docker/package.json
packages/buidler-ethers/package.json
packages/buidler-etherscan/package.json
packages/buidler-ganache/package.json
packages/buidler-solhint/package.json
packages/buidler-solpp/package.json
packages/buidler-truffle4/package.json
packages/buidler-truffle5/package.json
packages/buidler-vyper/package.json
packages/buidler-waffle/package.json
packages/buidler-web3-legacy/package.json
packages/buidler-web3/package.json

* Fix `npm run test` commands for all packages that were not working properly in Linux and Mac
* Improve CI actions hook to run on any "push" event instead of just pushes to master/development, or creating a PR

Fix CI test run

---

packages/buidler-core/src/internal/buidler-evm/provider/modules/eth.ts
packages/buidler-core/src/internal/buidler-evm/provider/output.ts

Fix linter and add a comment about a workaround

---

docs/.vuepress/components/Plugins.vue
docs/.vuepress/plugins.js
docs/.vuepress/style.styl
packages/buidler-waffle/README.md

- Add missing Waffle plugin to list
- Add new Aragon plugin to list
- Change list order so Waffle and Ethers read first 
- Add author to plugin list
- Fix Waffle plugin README title

[docs] Some plugin improvements

---

docs/.vuepress/components/Plugins.vue
docs/.vuepress/style.styl
docs/.vuepress/theme/styles/colors.styl

This PR adds some styles and uncomments the author on /plugins list (which was added on [PR 516](https://github.com/nomiclabs/buidler/pull/516))

[docs] Show author on plugins list

---

docs/tutorial/README.md
docs/tutorial/deploying-to-a-live-network.md
docs/tutorial/testing-contracts.md

- Grl fixes and clarifications
- Improve "Deploying to a live net" section
- Mention Metamask as pre-requisite

[tutorial] Fixes and clarifications

---

packages/buidler-core/src/internal/buidler-evm/stack-traces/compiler-to-model.ts
packages/buidler-core/src/internal/buidler-evm/stack-traces/source-maps.ts

See: https://github.com/ethereum/solidity/issues/9133 and #593

Fix sourcemaps parsing

---

docs/config/README.md

I tried to include the parts of the configuration that I think people are more likely to want. I also removed the part of it being a "complete configuration" to avoid confusion.
I also added some internal links for each property that has its own section.

Add internal links and configuration example

---

packages/buidler-core/src/types.ts

Export CommonNetworkConfig and BuidlerNetworkAccount.

Export missing interfaces

---

packages/buidler-core/src/internal/solidity/resolver.ts

Closes #674.
Works in linux and windows.

Resolve buidler dependencies on global installations

---

packages/buidler-core/src/internal/buidler-evm/provider/node.ts
packages/buidler-core/src/internal/buidler-evm/provider/provider.ts
packages/buidler-core/src/internal/buidler-evm/stack-traces/contracts-identifier.ts
packages/buidler-core/src/internal/buidler-evm/stack-traces/vm-trace-decoder.ts
packages/buidler-core/src/internal/buidler-evm/stack-traces/vm-tracer.ts
packages/buidler-core/src/internal/core/params/env-variables.ts
packages/buidler-core/test/internal/buidler-evm/buidler.config.js

Fix Buidler config loading

---

packages/buidler-core/src/internal/buidler-evm/provider/modules/buidler.ts
packages/buidler-core/src/internal/buidler-evm/provider/node-types.ts
packages/buidler-core/src/internal/buidler-evm/provider/provider.ts
packages/buidler-core/src/internal/buidler-evm/provider/utils/makeForkClient.ts
packages/buidler-core/src/internal/core/providers/construction.ts
packages/buidler-core/src/types.ts
packages/buidler-core/test/internal/buidler-evm/helpers/useProvider.ts

This is a quick and dirty PR just to put out an RC. I'll come back to this later today.

Initial config of Buidler EVM's fork

---

packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/core/params/argumentTypes.ts
packages/hardhat-core/src/internal/core/runtime-environment.ts
packages/hardhat-core/src/internal/core/tasks/task-definitions.ts
packages/hardhat-core/src/types.ts
packages/hardhat-core/test/internal/core/errors.ts

Use HH instead of BDLR as error code

Use HH as error code

---

packages/hardhat-core/.mocharc.json
packages/hardhat-core/test/mocha.opts
packages/hardhat-docker/.mocharc.json
packages/hardhat-docker/test/mocha.opts
packages/hardhat-ethers/.mocharc.json
packages/hardhat-ethers/test/mocha.opts
packages/hardhat-etherscan/.mocharc.json
packages/hardhat-ganache/.mocharc.json
packages/hardhat-ganache/test/mocha.opts
packages/hardhat-solhint/.mocharc.json
packages/hardhat-solhint/test/mocha.opts
packages/hardhat-solpp/.mocharc.json
packages/hardhat-solpp/test/mocha.opts
packages/hardhat-truffle4/.mocharc.json
packages/hardhat-truffle4/test/mocha.opts
packages/hardhat-truffle5/.mocharc.json
packages/hardhat-truffle5/test/mocha.opts
packages/hardhat-vyper/.mocharc.json
packages/hardhat-vyper/test/mocha.opts
packages/hardhat-waffle/.mocharc.json
packages/hardhat-waffle/test/mocha.opts
packages/hardhat-web3-legacy/.mocharc.json
packages/hardhat-web3-legacy/test/mocha.opts
packages/hardhat-web3/.mocharc.json
packages/hardhat-web3/test/mocha.opts

You win, mocha warning.
Closes #568.

Replace mocha.opts with .mocharc.json

---

docs/advanced/building-plugins.md
docs/guides/create-task.md
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/builtin-tasks/flatten.ts
packages/hardhat-core/src/builtin-tasks/test.ts
packages/hardhat-core/src/internal/cli/ArgumentsParser.ts
packages/hardhat-core/src/internal/cli/HelpPrinter.ts
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/core/config/config-env.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/core/tasks/dsl.ts
packages/hardhat-core/src/internal/core/tasks/task-definitions.ts
packages/hardhat-core/src/types/runtime.ts
packages/hardhat-core/test/internal/core/config/config-loading.ts
packages/hardhat-core/test/internal/core/tasks/dsl.ts
packages/hardhat-core/test/internal/core/tasks/task-definitions.ts
packages/hardhat-solhint/src/index.ts
packages/hardhat-solpp/src/index.ts
packages/hardhat-truffle4/src/index.ts
packages/hardhat-truffle5/src/index.ts
packages/hardhat-vyper/src/index.ts

This should be merged after #818.

Rename internalTask to subtask.

---

package.json
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/builtin-tasks/node.ts
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/core/runtime-environment.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/plugins.ts
packages/hardhat-core/src/types/artifact.ts
packages/hardhat-core/src/types/runtime.ts
packages/hardhat-core/test/internal/core/runtime-environment.ts
packages/hardhat-ethers/src/helpers.ts
packages/hardhat-ethers/test/index.ts
packages/hardhat-etherscan/src/index.ts
packages/hardhat-etherscan/src/solc/bytecode.ts
packages/hardhat-truffle4/src/artifacts.ts
packages/hardhat-truffle4/src/index.ts
packages/hardhat-truffle4/src/type-extensions.ts
packages/hardhat-truffle4/test/tests.ts
packages/hardhat-truffle5/src/artifacts.ts
packages/hardhat-truffle5/src/index.ts
packages/hardhat-truffle5/src/type-extensions.ts
packages/hardhat-truffle5/test/tests.ts
packages/hardhat-vyper/src/compilation.ts
packages/hardhat-vyper/src/index.ts
packages/hardhat-vyper/test/tests.ts

#835 got a lot of conflicts after #818. I created a new branch from 2.0 cherry-picked the relevant commits.

Add artifacts to hre, second try

---

packages/hardhat-truffle4/src/artifacts.ts
packages/hardhat-truffle4/test/hardhat-project-ambiguous-names/.gitignore
packages/hardhat-truffle4/test/hardhat-project-ambiguous-names/contracts/Greeter.sol
packages/hardhat-truffle4/test/hardhat-project-ambiguous-names/contracts/Greeter2.sol
packages/hardhat-truffle4/test/hardhat-project-ambiguous-names/hardhat.config.js
packages/hardhat-truffle4/test/hardhat-project-ambiguous-names/test/truffle-fixture.js
packages/hardhat-truffle4/test/linking.ts
packages/hardhat-truffle5/src/artifacts.ts
packages/hardhat-truffle5/test/hardhat-project-ambiguous-names/.gitignore
packages/hardhat-truffle5/test/hardhat-project-ambiguous-names/contracts/Greeter.sol
packages/hardhat-truffle5/test/hardhat-project-ambiguous-names/contracts/Greeter2.sol
packages/hardhat-truffle5/test/hardhat-project-ambiguous-names/hardhat.config.js
packages/hardhat-truffle5/test/hardhat-project-ambiguous-names/test/truffle-fixture.js
packages/hardhat-truffle5/test/linking.ts

Depends on #850.
@alcuadrado I'm not sure about this approach, wdyt?

Handle ambiguous contract names when linking with truffle

---

packages/hardhat-core/src/builtin-tasks/compile.ts

This errors are becoming really common, and a normal source of frustration, cause solidity fails to format them, so you get an error message with 0 information and impossible to google.
This PR just formats them in our compilation pipeline. It doesn't add that much info, but at least a file and line number in Solidity's source code, which can be used as an identifier to google the error.
For more info, see: https://github.com/ethereum/solidity/issues/9926

Properly format Solidity's ICEs

---

packages/hardhat-core/src/internal/core/params/hardhat-params.ts
packages/hardhat-core/src/types/runtime.ts

This PR just reserves an argument name for Hardhat.

Add --tsconfig as a Hardhat argument

---

packages/hardhat-core/sample-project/hardhat.config.js
packages/hardhat-core/src/builtin-tasks/utils/solidity-files-cache.ts
packages/hardhat-core/src/builtin-tasks/utils/watch.ts
packages/hardhat-core/src/config.ts
packages/hardhat-core/src/internal/cli/project-creation.ts
packages/hardhat-core/src/internal/core/config/config-resolution.ts
packages/hardhat-core/src/internal/core/config/config-validation.ts
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/core/providers/util.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/disk-cache.ts
packages/hardhat-core/src/types/config.ts
packages/hardhat-core/test/internal/core/config/config-resolution.ts
packages/hardhat-core/test/internal/core/config/config-validation.ts
packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts
packages/hardhat-etherscan/src/type-extensions.ts
packages/hardhat-solpp/src/type-extensions.ts
packages/hardhat-truffle4/src/fixture.ts
packages/hardhat-truffle5/src/fixture.ts
packages/hardhat-vyper/src/compilation.ts
packages/hardhat-vyper/src/type-extensions.ts

Pretty much an automatic rename of all the `User<Thing>Config` types to `<Thing>UserConfig`

Rename user config types

---

CONTRIBUTING.md
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/types/provider.ts

Note that this doesn't include the ones in the docs

Delete or remove all the TODO-HHs form the codebase.

---

package.json
packages/hardhat-core/package.json
packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
packages/hardhat-core/test/internal/util/lazy.ts
packages/hardhat-docker/package.json
packages/hardhat-ethers/package.json
packages/hardhat-etherscan/package.json
packages/hardhat-ganache/package.json
packages/hardhat-ganache/src/index.ts
packages/hardhat-solhint/package.json
packages/hardhat-solpp/package.json
packages/hardhat-truffle4/package.json
packages/hardhat-truffle5/package.json
packages/hardhat-vyper/package.json
packages/hardhat-waffle/package.json
packages/hardhat-web3-legacy/package.json
packages/hardhat-web3/package.json
yarn.lock

Just a upgrades 2 dev dependencies and bumps every version.

Prepare RC versions

---

docs/guides/project-setup.md
docs/guides/scripts.md
docs/guides/truffle-testing.md

Update the scritps, tuffle and project setup guides.

Misc updates

---

packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/logger.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts

Fix the hardhat_setLoggingEnabled RPC method

---

packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeForkClient.ts

Read the comment in the diff for more info.

Increase the forking http client timeout

---

docs/config/README.md

This updates the configuration documentation.
This shouldn't be merged before #917 since it references part of the forking documentation.
The same goes for #920.

Update configuration documentation.

---

packages/hardhat-etherscan/src/index.ts
packages/hardhat-etherscan/src/solc/bytecode.ts
packages/hardhat-etherscan/test/integration/PluginTests.ts

Fix out of memory error while verifying big projects.

---

docs/.vuepress/plugins.js
docs/guides/migrate-from-buidler.md

+ Add hardhat-gas-reporter to plugins list
+ Move buidler-gas-reporter to migrated list

Update docs for hardhat-gas-reporter

---

packages/hardhat-ganache/src/ganache-options-ti.ts
packages/hardhat-ganache/src/ganache-service.ts
packages/hardhat-ganache/test/fixture-projects/hardhat-project/.gitignore
packages/hardhat-ganache/test/fixture-projects/hardhat-project/contracts/EVMInspector.sol
packages/hardhat-ganache/test/fixture-projects/hardhat-project/hardhat.config.ts
packages/hardhat-ganache/test/fixture-projects/hardhat-project/test/test.js
packages/hardhat-ganache/test/index.ts

Add hardfork options istanbul and muirGlacier to hardhat-ganache.

---

packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth.ts

Always return at least 32 bytes in eth_getStorageAt

---

docs/guides/mainnet-forking.md

Fixes a broken code snippet under impersonating accounts

Fixes Code Snippet

---

packages/hardhat-ethers/src/helpers.ts
packages/hardhat-ethers/test/index.ts

Fix getContractAt for unlinked contracts in hardhat-ethers.

---

docs/.vuepress/plugins.js
docs/guides/migrate-from-buidler.md

Hi, this is finally done in solidity-coverage `v0.7.12` 🙂 
(@fvictorio - thanks so much for all the work you did on that synthetix PR - it was invaluable to test with and caught a lot of problems on my side).

Update docs for solidity-coverage plugin

---

packages/hardhat-core/src/internal/hardhat-network/provider/output.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth.ts

Add mixHash to block in JSON-RPC output.

---

packages/hardhat-waffle/package.json
packages/hardhat-waffle/src/index.ts
packages/hardhat-waffle/src/matchers.ts
packages/hardhat-waffle/src/waffle-chai.ts
packages/hardhat-waffle/test/fixture-projects/hardhat-project/.gitignore
packages/hardhat-waffle/test/fixture-projects/hardhat-project/cache/solidity-files-cache.json
packages/hardhat-waffle/test/fixture-projects/hardhat-project/contracts/Contract.sol
packages/hardhat-waffle/test/fixture-projects/hardhat-project/contracts/Token.sol
packages/hardhat-waffle/test/fixture-projects/hardhat-project/hardhat.config.js
packages/hardhat-waffle/test/fixture-projects/hardhat-project/test/test-with-explicit-chai-use.js
packages/hardhat-waffle/test/fixture-projects/hardhat-project/test/tests.js
packages/hardhat-waffle/test/index.ts
yarn.lock

Looks like these functions weren't explicitly imported. I went ahead and added the four functions for ether and token balance changes. I would like to add some unit tests, but I don't know enough metaprogramming to check the matchers without actually writing a test against the smart contract.

Bugfix for #1020 and #1061

---

packages/hardhat-core/src/internal/cli/autocomplete.ts
packages/hardhat-core/src/internal/util/lang.ts
packages/hardhat-core/test/fixture-projects/autocomplete/overriden-task/hardhat.config.js
packages/hardhat-core/test/fixture-projects/autocomplete/overriden-task/package.json
packages/hardhat-core/test/internal/cli/autocomplete.ts

This is not the correct solution, but I'm opening this PR so that it's easier to discuss what's the best approach here. See inline comment.

Handle overriden tasks in autocomplete

---

packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth.ts

Use index for remote logs

---

packages/hardhat-core/src/internal/hardhat-network/provider/fork/Account.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth.ts

Set deleted storage slots to null

---

docs/.vuepress/plugins.js
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/test/internal/artifacts.ts

As the title suggests, adding [hardhat-tenderly](https://github.com/Tenderly/hardhat-tenderly) to the list of Hardhat plugins.

Added hardhat-tenderly to the list of plugins

---

.github/workflows/CI.yml
packages/hardhat-core/.gitignore
packages/hardhat-core/test/internal/hardhat-network/provider/node.ts

Add regression test that runs a full block in forked hardhat

---

docs/hardhat-network/README.md
packages/hardhat-core/console.sol
packages/hardhat-core/scripts/console-library-generator.js
packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/logger.ts

Make console.sol work with solc 0.8.x

---

package.json
packages/hardhat-core/package.json
yarn.lock

This PR upgrades the solidity parser, and also users yarn's resolutions to make the repo installable with node 10.

Upgrade the solidity parser and fix antlr's version

---

docs/guides/deploying.md

related to this chat: https://github.com/nomiclabs/hardhat/issues/1142

doc: add more details to deplyoing guide

---

docs/getting-started/README.md

This is #1205 but in a single commit.

Update hardhat version and missing accounts task

---

docs/.vuepress/plugins.js

Update hardhat react to https://github.com/symfoni/symfoni-monorepo/tree/master/packages/hardhat-react

update plugins.js - Hardhat react, correct git rep

---

packages/hardhat-vyper/package.json
packages/hardhat-vyper/src/index.ts
packages/hardhat-vyper/src/task-names.ts
packages/hardhat-vyper/test/fixture-projects/mixed-language/contracts/Greeter.sol
packages/hardhat-vyper/test/fixture-projects/mixed-language/contracts/test.vy
packages/hardhat-vyper/test/fixture-projects/mixed-language/hardhat.config.js
packages/hardhat-vyper/test/tests.ts

Fixes mixed-language environments to support compiling Solidity and Vyper in the same project.

Support projects with Solidity and Vyper files

---

docs/.vuepress/plugins.js

Adds the hardhat-erc1820 plugin to the list.

Add hardhat-erc1820 plugin

---

packages/common/ganache-provider.js
packages/common/run-with-ganache.js
packages/hardhat-core/.mocharc.json
packages/hardhat-core/test/internal/hardhat-network/jsonrpc/client.ts
packages/hardhat-core/test/internal/hardhat-network/provider/forked-provider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/interval-mining-provider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/logs.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/evm.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/net.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/web3.ts
packages/hardhat-core/test/utils/workaround-windows-ci-failures.ts
scripts/run-tests.js

This applies the lessons learned in #1268. Fingers crossed, this should make the CI work again.
I opened a new PR because rebasing is hard.

Fix windows CI

---

packages/hardhat-core/src/internal/hardhat-network/provider/node.ts

Relax how we check if an error is a VmError

---

packages/hardhat-core/src/internal/core/providers/http.ts

We are assuming that the array returned from a batch request has the same order as the array of requests. This is not always the case. ArchiveNode.io, for example, seems to return them (sometimes) in a different order.
This PR fixes this, by using the `id` field to sort the responses.
No tests for this yet. Maybe we could have a couple of fork tests that run on ArchiveNode? But not all of them because the CI is already too slow as it is, and it wouldn't be nice to add that load to them either.

Sort batched responses by id

---

packages/hardhat-core/src/internal/hardhat-network/provider/HardhatStateManager.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/AccountState.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts
packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkStateManager.ts

Fix issue with `selfdestruct`

---

docs/.vuepress/plugins.js

I think I somehow messed up with the rebase, so easier to just do another PR...

Add ethernal plugin

---

packages/hardhat-etherscan/src/network/prober.ts

Adding FTMScan for the Fantom mainnet

add ftmscan for fantom mainnet

---

docs/guides/waffle-testing.md

prefix `hardhat-waffle` with `@nomiclabs` to be more explicit
[related](https://mobile.twitter.com/HardhatHQ/status/1362866790695641094)

prefix package name

---

docs/.vuepress/plugins.js

**Description**
Fix typo
I think it related with https://github.com/ethereum-optimism/smock/pull/45

[docs] fix typo optimisim

---

docs/.vuepress/plugins.js

Happy to bikeshed anything. Thanks

add hardhat-circom plugin

---

packages/hardhat-core/src/internal/core/config/config-validation.ts
packages/hardhat-core/test/internal/core/config/config-validation.ts

Fix Awful error when account balance:
1. Contains hex string
2. Have invalid decimal string

Fix awful error for balance

---

packages/hardhat-core/src/internal/core/errors-list.ts

Users don't seem to quite understand the message as it is. This should make it a little more clear.

Explicit mention hardhat module

---

packages/hardhat-core/src/internal/constants.ts
packages/hardhat-core/src/internal/core/providers/http.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-ethers/src/internal/provider-proxy.ts
packages/hardhat-ethers/test/index.ts

Reset ethers provider after evm_revert

---

packages/hardhat-etherscan/src/network/prober.ts

Added OPTIMISM mainnet and kovan tesnet id's and URLs
https://github.com/ethereum-optimism/optimism/issues/983
Also, @smartcontracts says hi 👋 ❤

Add Optimism mainnet and kovan networks

---

packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkStateManager.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-waffle/src/waffle-chai.ts

Forked provider tests were failing.  See specific commit messages to understand which fixes were required for which failures.

Fixes for irregular states with forked provider

---

docs/tutorial/hackathon-boilerplate-project.md

Thanks @tuncatunc for suggesting this change.

Add MetaMask Chain Id fix to tutorial

---

packages/hardhat-core/src/internal/hardhat-network/provider/utils/reorgs-protection.ts

Another take on #1483
Note https://github.com/nomiclabs/hardhat/pull/1483#issuecomment-862587187 and @igorbarinov from xdai teams recommendation for block number

add xDai to reorgs whitelist

---

packages/hardhat-core/sample-project/contracts/Greeter.sol
packages/hardhat-core/sample-project/hardhat.config.js

---
Update solidity version to 0.8 since it's already supported in the latest version.

Update solidity version in sample project

---

docs/guides/mainnet-forking.md

---
Add docs of newly added RPC methods

Update mainnet forking guide

---

docs/.vuepress/plugins.js

Hardhat storage layout plugin

---

packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts

Disable hardhat_setMinGasPrice when EIP-1559 is active

---

docs/guides/create-task.md

Added the `run` function to the example `hello-world` task so it will compile.

Added run function to hello-world example task

---

packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts

Implement `hardhat_setNextBlockBaseFeePerGas`

---

docs/.vuepress/plugins.js

Add hardhat-change-network to plugin list

---

packages/hardhat-core/src/internal/core/jsonrpc/types/output/receipt.ts
packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts
packages/hardhat-core/src/internal/hardhat-network/provider/output.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByBlockNumberAndIndex.ts

Fixes #1603
Fixes #1604
Fixes #1605

Update Transaction, Receipt and Block rpc output for London

---

packages/hardhat-core/src/internal/core/jsonrpc/types/input/callRequest.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendRawTransaction.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts

This PR updates the validations and default values of these methods, and tests them.
Fixes #1599 
Fixes #1600

London updates to eth_sendTransaction and eth_sendRawTransaction

---

packages/hardhat-core/src/internal/core/jsonrpc/types/base-types.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/hardforks.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/feeHistory.ts

Implement `eth_feeHistory`

---

packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/core/providers/accounts.ts
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/core/providers/gas-providers.ts
packages/hardhat-core/test/internal/core/providers/accounts.ts
packages/hardhat-core/test/internal/core/providers/construction.ts
packages/hardhat-core/test/internal/core/providers/gas-providers.ts

This is a very simplistic version of the `AutomaticGasProvider` that handles EIP-1559.

London-enabled AutomaticGasPriceProvider and LocalAccountsProvider

---

docs/config/README.md
docs/hardhat-network/README.md

This PR updates these things in preparation for the London hardfork.
(1) Hardhat Network's config fields.
(2) Hardhat Network's supported methods.

Hardhat Network docs: London hardfork changes

---

packages/hardhat-core/src/internal/hardhat-network/provider/TxPool.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/logger.ts
packages/hardhat-core/test/internal/hardhat-network/provider/TxPool.ts

We had the same bug that caused the chain split in ropsten.

Fix EIP-1559 tx validation in TxPool

---

packages/hardhat-core/package.json

Bump hardhat-core to 2.5.0

---

packages/hardhat-docker/README.md

Updating hardhat-docker plugin documentation

---

docs/_redirects

Fix broken mainnet-forking redirect

---

.github/PULL_REQUEST_TEMPLATE.md

Tweak PR template wording

---

docs/tutorial/testing-contracts.md

---
Minor fix of comment with the numbers of tokens. The Token.sol actually deposits 1000000 tokens to owner's account, not 1000.

Fix confusing comment

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/bug_fix.md
.github/PULL_REQUEST_TEMPLATE/documentation_change.md
.github/PULL_REQUEST_TEMPLATE/new_feature.md

Reverts nomiclabs/hardhat#1751
See https://github.com/nomiclabs/hardhat/pull/1751#issuecomment-892840995

Revert "Split PR template into multiple templates"

---

packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/useHelpers.ts
packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
packages/hardhat-core/test/internal/hardhat-network/provider/forked-provider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/logs.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/call.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/gasPrice.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/index.ts

Fixes after london hardfork

---

packages/hardhat-core/recommended-gitignore.txt

---
**Description:**
I have made changes to `recommended-gitignore.txt` file as per the issue #1636

added .env to recommended-gitignore.txt file

---

packages/hardhat-docker/src/hardhat-docker.ts

Fix typo in hardhat-docker

---

docs/guides/waffle-testing.md

---
Add line breaks to properly show the comparison table

docs: fix table formatting on Waffle testing guide

---

docs/.vuepress/plugins.js
docs/guides/typescript.md

Improve documentation related to TypeChain and TypeScript

---

docs/.vuepress/plugins.js

---
This PR adds a plugin to help manipulating block mining process when testing

chore: added hardhat-time-n-mine plugin

---

.changeset/sweet-parents-compete.md
.changeset/wise-buses-deny.md

This PR adds changest files for two old but unreleased changes.

Add changesets for existing unreleased changes

---

docs/.vuepress/plugins.js

docs: list hardhat-proxy in plugins list

---

packages/hardhat-core/src/internal/core/config/config-loading.ts

Drop a stray double quote

---

.changeset/early-pillows-bathe.md
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/test/builtin-tasks/compile.ts
packages/hardhat-core/test/fixture-projects/old-solidity-versions/contracts/Foo.sol
packages/hardhat-core/test/fixture-projects/old-solidity-versions/old-solidity-version-in-override.js
packages/hardhat-core/test/fixture-projects/old-solidity-versions/old-solidity-version-multiple-compilers.js
packages/hardhat-core/test/fixture-projects/old-solidity-versions/old-solidity-version.js
packages/hardhat-core/test/helpers/environment.ts

Throw error for old solc versions

---

.changeset/chilled-cooks-listen.md
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/core/providers/accounts.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/personal.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/test/internal/core/providers/accounts.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/personal.ts

Add personal_sign RPC method

---

.changeset/smooth-turkeys-grab.md
docs/reference/solidity-support.md
packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidityTracer.ts
packages/hardhat-core/test/fixture-projects/solidity-config-warnings/multiple-unsupported-solc.js
packages/hardhat-core/test/fixture-projects/solidity-config-warnings/unsupported-new-solc.js
packages/hardhat-core/test/fixture-projects/solidity-config-warnings/unsupported-solc-in-override.js
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/user-defined-value-types/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/user-defined-value-types/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts

Support Solidity 0.8.8

---

.changeset/rude-lemons-turn.md
packages/hardhat-core/src/internal/core/config/config-validation.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/test/internal/core/config/config-validation.ts

extra tests for privkey validation

---

CONTRIBUTING.md

Added colons at necessary places in CONTRIBUTING.md , as per issue #2049

added colons at necessary places in CONTRIBUTING.md

---

packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/types/config.ts

Addresses review comment https://github.com/nomiclabs/hardhat/pull/1928#discussion_r746783321

PR to a PR: Change hardfork name config type from `internal/.../HardforkName` to `string`

---

.github/ISSUE_TEMPLATE.md
.github/workflows/autoassign-issues.yml
CONTRIBUTING.md

This PR adds a github actions workflow that automatically assign issues.

Add autoassign-issues workflow

---

.changeset/brown-bulldogs-invent.md
packages/hardhat-etherscan/src/network/prober.ts

Moonriver verify support

---

.changeset/wicked-lizards-wait.md

See https://github.com/nomiclabs/hardhat/issues/1247#issuecomment-974554469

Add missing changeset for hardhat-ethers

---

docs/hardhat-network/explanation/mining-modes.md
docs/hardhat-network/reference/README.md

This PR documents the changes introduce by #1559

Document the FIFO mempool mode

---

docs/.vuepress/plugins.js

See https://github.com/nomiclabs/hardhat/pull/2058#issuecomment-989833535

Fix package name of hardhat-yul plugin

---

packages/hardhat-ethers/src/internal/index.ts

Remove outdated comment as discussed in #2147

Remove outdated comment

---

packages/hardhat-core/src/internal/cli/project-creation.ts

A very very small change :D

---

packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/core/errors-list.ts

This PR fixes #1408
@aftermathdigital, @fvictorio WDYT?

Show a special error when outside of a project on windows

---

docs/.vuepress/plugins.js

Fixed the npm link to the time-n-mine plugin

Fix link to time-n-mine plugin in docs

---

docs/.vuepress/plugins.js

---
Plugin description:
Hardhat plugin for solidity contract verification on Blockscout block explorer. This plugin helps you to flatten the contract and use Blockscout API to verify the contract.

Add hardhat-blockscout-verify plugin

---

docs/getting-started/README.md

---
docs some options are missing on `getting getting-started/README.md` on triggering `npx hardhat` 
issue #2249

added missing options on `npx hardhat` #2249

---

.changeset/cuddly-poems-live.md
config/eslint/eslintrc.js
packages/hardhat-ethers/src/types/index.ts
packages/hardhat-truffle5/src/artifacts.ts

Fix imports with hardhat/src

---

docs/.vuepress/plugins.js

This PR removes a plugin that was deprecated by its author and adds a bunch of plugins that were not present.

Update plugin list

---

packages/hardhat-core/src/internal/core/tasks/task-definitions.ts

Fix typo in task-definitions.ts

---

.changeset/rude-suns-speak.md
docs/_redirects
docs/reference/stability-guarantees.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/cli/cli.ts

warn on node version greater than current LTS

---

packages/hardhat-core/sample-projects/advanced-ts/README.md

Fix deployment command

---

.github/workflows/LATEST_DEPENDENCY_VERSIONS.yml

This PR adds a Slack notification to the LATEST_DEPENDENCY_VERSIONS.yml workflow.

Add slack notifications to a GH Action workflow

---

docs/hardhat-network/reference/README.md

---
It's very hard to find the docs for `evm_snapshot` and I think they should be included in your docs as well. I copied them verbatim from Ganache's docs.

Add docs for evm_snapshot

---

docs/guides/project-setup.md

---
docs some options are missing on `[getting getting-started/README.md` ](https://hardhat.org/guides/project-setup.html) on triggering `npx hardhat` 
issue #2249

added missing options on npx hardhat

---

.github/workflows/autoassign-issues-and-prs.yml

Use the latest commit, which includes a fix that makes the action work with PRs.

Update auto-assign-issue action version

---

.changeset/dull-numbers-learn.md
docs/config/README.md
docs/hardhat-network/reference/README.md
packages/hardhat-core/src/internal/core/config/config-validation.ts
packages/hardhat-core/src/internal/core/config/default-config.ts
packages/hardhat-core/src/internal/core/providers/accounts.ts
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/core/providers/util.ts
packages/hardhat-core/src/internal/util/keys-derivation.ts
packages/hardhat-core/src/types/config.ts
packages/hardhat-core/test/fixture-projects/mnemonic-with-passphrase/hardhat.config.js
packages/hardhat-core/test/fixture-projects/mnemonic-without-passphrase/hardhat.config.js
packages/hardhat-core/test/internal/core/config/config-resolution.ts
packages/hardhat-core/test/internal/core/config/config-validation.ts
packages/hardhat-core/test/internal/core/providers/accounts.ts
packages/hardhat-core/test/internal/core/providers/construction.ts
packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts
packages/hardhat-core/test/internal/util/keys-derivation.ts

---
Support passphrase for bip39 HD Wallet.

support bip39 passphrase

---

.changeset/shaggy-hotels-wave.md
packages/hardhat-etherscan/README.md
packages/hardhat-etherscan/src/ChainConfig.ts
packages/hardhat-etherscan/src/types.ts

---
Adds aurorascan details for verifying contracts on aurora chain
JSPN-RPC: https://mainnet.aurora.dev/
Funds deposited: https://aurorascan.dev/address/0x4444c3F7D7d3153Dc0773C31ae10cf9B5495d4Bb

add aurora to hardhat-etherscan

---

docs/hardhat-network/reference/README.md

Add unit to gasPrice entry in the docs

---

.github/workflows/e2e-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-etherscan-ci.yml
.github/workflows/hardhat-ganache-ci.yml
.github/workflows/hardhat-network-forking-ci.yml
.github/workflows/hardhat-network-tracing-ci.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/hardhat-waffle-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml
.github/workflows/lint.yml

We are not running the forking tests before releasing. We can do that locally, but it's really slow if you are in the southern hemisphere. So as an alternative, we can push to `pre-release-testing-branch` to run all our tests in the CI.

Run tests in the `pre-release-testing-branch` branch

---

.github/workflows/hardhat-vyper-ci.yml
CONTRIBUTING.md
scripts/run-tests.js

- just removing a few places where docker was referenced in the context of being needed for vyper, since it no longer is needed
- also updated the github actions workflow for vyper to no longer pull the docker compiler unnecessarily

removed missed docker references

---

docs/.vuepress/plugins.js

---
Add https://github.com/d3or/hardhat-gas-trackooor to plugins list.

Add hardhat-gas-trackoor to plugins list

---

.changeset/itchy-houses-report.md
packages/hardhat-solpp/package.json
yarn.lock

Upgrade solpp dependency in hardhat-solpp

---

packages/hardhat-core/src/internal/util/download.ts

Addresses review comment https://github.com/NomicFoundation/hardhat/pull/2370#discussion_r814036287

compiler downloader: rm unnecessary condition

---

.changeset/fast-papayas-crash.md
packages/hardhat-etherscan/src/etherscan/EtherscanService.ts

Add Content-Type header to etherscan request

---

.changeset/twelve-coats-rhyme.md
packages/hardhat-core/src/builtin-tasks/node.ts

allow node task logging to be configurable

---

docs/guides/parallel-tests.md

Add a note about mocha.parallel option

---

docs/.vuepress/plugins.js

Update description for hardhat-tracer plugin

---

docs/.vuepress/plugins.js

Adding hardhat-forta community plugin

Add hardhat-forta community plugin

---

.changeset/dull-impalas-grin.md
packages/hardhat-core/src/.npmignore
packages/hardhat-ethers/src/.npmignore
packages/hardhat-solhint/src/.npmignore

Stop publishing tsconfig.json files

---

packages/hardhat-core/src/internal/core/errors-list.ts

---
Small fix for error description typo

DOCS: Fix error list typo

---

docs/tutorial/setting-up-the-environment.md

Update nodejs version to Active LTS (v16) to prevent complaint `You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.`.
https://nodejs.org/en/about/releases/

DOC: Update required nodejs version to v16 in setup document

---

docs/hardhat-network/reference/README.md

---
Fix broken documentation links.

Fix invalid documentation links

---

docs/.vuepress/plugins.js

`hardhat-test-utils` is a plugin provides a set of various utility functions for testing solidity smart contracts that in a Hardhat project. It exposes utilities including mining any number of blocks, simulating the passing of time, changing address balance, snapshot network state, etc.

Add `hardhat-test-utils` plugin

---

docs/tutorial/deploying-to-a-live-network.md

old one was expired. i successfully used the portland state one
---

update ropsten faucet links

---

.github/workflows/hardhat-chai-matchers-ci.yml
packages/hardhat-chai-matchers/src/changeTokenBalance.ts
packages/hardhat-chai-matchers/src/hardhatChaiMatchers.ts
packages/hardhat-chai-matchers/src/types.ts
packages/hardhat-chai-matchers/test/changeTokenBalance.ts
packages/hardhat-chai-matchers/test/fixture-projects/hardhat-project/contracts/Token.sol
packages/hardhat-core/src/internal/artifacts.ts

Add support for changeTokenBalance and changeTokenBalances matchers

---

packages/hardhat-core/src/builtin-tasks/node.ts

Hardhat Node: checksum addresses before outputting

---

docs/src/components/DesktopAnimation.tsx
docs/src/components/landingBlocks/HeroBlock.tsx
docs/src/components/landingBlocks/ToolsBlock.styled.tsx
docs/src/components/landingBlocks/WhyHardhatBlock.tsx

- animation texture z-index fix
- tools block margin fix

fix: fix animation texture z-index and tools block margins

---

.github/workflows/LATEST_DEPENDENCY_VERSIONS.yml

Also, enable the fast exit option.

Add retry to latest-dependency-versions workflow

---

docs/.vuepress/plugins.js

Hello Team
adding here the [0xweb-org/hardhat](https://github.com/0xweb-org/hardhat) to plugins list.
Best, Alex.

Adding 0xWeb/Hardhat community plugin

---

docs/scripts/prepare-error-list.ts
docs/src/components/mdxComponents/Title.tsx

- add custom ids to errors page headings to implement scrolling to anchors feature

add custom ids to errors page headings

---

docs/src/content/plugins/plugins.ts

Same as https://github.com/NomicFoundation/hardhat/pull/2768, which got lost during migration to the new site.

Add (community plugin) 0xweb/hardhat

---

docs/src/content/plugins/plugins.ts

---
- Renames uniswap-v3-deploy-plugin to @uniswap/hardhat-v3-deploy.
- Adds jest-environment-hardhat, a test environment for jest that runs a hardhat node.

Update Uniswap Labs community plugins

---

docs/src/content/hardhat-network/guides/mainnet-forking.md
packages/hardhat-core/src/internal/core/config/config-resolution.ts
packages/hardhat-core/src/internal/core/jsonrpc/types/input/hardhat-network.ts
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node-types.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeForkClient.ts
packages/hardhat-core/src/types/config.ts
packages/hardhat-core/test/internal/core/config/config-resolution.ts

- Fixes #1588
I haven't tested this except for running `npm run watch` (0 errors). I'm happy to contribute more by adding tests, but I'm helplessly overwhelmed by the code base's size. Pls guide me thx.

Add httpHeaders to forking config

---

docs/src/components/DocumentationLayout.tsx
docs/src/components/LandingLayout.tsx
docs/src/components/PluginsLayout.tsx
docs/src/themes.tsx

If you want to check fix locally don't forget to delete `.next` folder before using `yarn dev` command in order to clean cache.
In order to enable theming on Landing page find `TODO-LANDING-THEMING` comment in `docs/src/themes.tsx` file and follow the instructions.

fix: disable dark theme on landing page

---

docs/src/content/hardhat-runner/docs/other-guides/waffle-testing.md

Depends on #2825.
I updated the first part of the guide. I only skimmed the second part about migrating from an existing Waffle project; it looks like it's still correct.

Update waffle testing guide

---

docs/src/content/hardhat-runner/docs/getting-started/index.md
docs/src/content/hardhat-vscode/docs/features.md
docs/src/content/hardhat-vscode/docs/overview.md
docs/src/model/markdown.tsx
docs/temp/tabsConfig.json

The new getting started guide, using the new sample projects.
Can you review it, @feuGeneA?
Closes HH-792

New getting started guide

---

docs/src/content/hardhat-runner/docs/guides/getting-help.md

Please review this, @fvictorio @feuGeneA 
Closes HH-692

Getting help guide

---

docs/src/content/hardhat-runner/docs/advanced/_dirinfo.yaml
docs/src/content/hardhat-runner/docs/advanced/artifacts.md
docs/src/content/hardhat-runner/docs/advanced/multiple-solidity-versions.md
docs/src/content/hardhat-runner/docs/guides/compile-contracts.md

I split this guide into three:
1. The existing guide
2. An advanced guide about artifacts
3. An advanced guide about using multiple versions of solidity
I think (2) and (3) are advanced, and at the same time need more visibility in the sidebar.
Note for the reviewer: I mostly moved content around.
Also closes HH-802

Update Compiling your contracts guide

---

.changeset/plenty-balloons-bake.md
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/core/providers/gas-providers.ts
packages/hardhat-core/test/internal/core/providers/construction.ts
packages/hardhat-core/test/internal/core/providers/gas-providers.ts

---
Removed GanacheGasMultiplierProvider. This provider was generating an error on the Kiln network.
As discussed with @alcuadrado the fix requires to remove this provider.
All related tests have been removed.
All tests are passing

Removed all GanacheGasMultiplierProvider refs

---

docs/src/content/hardhat-chai-matchers/docs/migrate-from-waffle.md
docs/src/content/hardhat-chai-matchers/docs/overview.md
docs/src/content/hardhat-network-helpers/docs/overview.md
docs/src/content/hardhat-runner/docs/advanced/create-task.md
docs/src/content/hardhat-runner/docs/advanced/hardhat-runtime-environment.md
docs/src/content/hardhat-runner/docs/advanced/vscode-tests.md
docs/src/content/hardhat-runner/docs/getting-started/index.md
docs/src/content/hardhat-runner/docs/guides/command-line-completion.md
docs/src/content/hardhat-runner/docs/guides/compile-contracts.md
docs/src/content/hardhat-runner/docs/guides/hardhat-console.md
docs/src/content/hardhat-runner/docs/guides/project-setup.md
docs/src/content/hardhat-runner/docs/other-guides/ganache-tests.md
docs/src/content/hardhat-runner/docs/other-guides/truffle-migration.md
docs/src/content/hardhat-runner/plugins/index.md
docs/src/content/hardhat-runner/plugins/plugins.ts

Closes HH-834
Closes HH-835
Closes HH-836
Closes HH-804

Multiple tiny improvements to the new docs

---

docs/src/content/docs-landing/index.md
docs/src/pages/docs/index.tsx

This page is really important, so I'm open to any suggestion to improve it, @fvictorio @feuGeneA @morgansliman

Documentation landing page

---

docs/src/content/hardhat-runner/docs/advanced/vscode-tests.md
docs/src/content/hardhat-runner/docs/getting-started/index.md
docs/src/content/hardhat-runner/docs/guides/project-setup.md
docs/src/content/tutorial/setting-up-the-environment.md

More npm 7+ and Hardhat VSCode mentions

---

docs/src/content/home.ts

Fix the Tool links in the landing page

---

packages/hardhat-chai-matchers/package.json
packages/hardhat-chai-matchers/src/internal/changeEtherBalance.ts
packages/hardhat-chai-matchers/src/internal/changeEtherBalances.ts
packages/hardhat-chai-matchers/src/internal/changeTokenBalance.ts
packages/hardhat-chai-matchers/src/internal/emit.ts
packages/hardhat-chai-matchers/src/internal/hexEqual.ts
packages/hardhat-chai-matchers/src/internal/properAddress.ts
packages/hardhat-chai-matchers/src/internal/properHex.ts
packages/hardhat-chai-matchers/src/internal/properPrivateKey.ts
packages/hardhat-chai-matchers/src/internal/reverted/revertedWith.ts
packages/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
packages/hardhat-chai-matchers/src/internal/reverted/revertedWithPanic.ts
packages/hardhat-chai-matchers/src/internal/withArgs.ts
packages/hardhat-chai-matchers/test/changeEtherBalance.ts
packages/hardhat-chai-matchers/test/changeEtherBalances.ts
packages/hardhat-chai-matchers/test/changeTokenBalance.ts
packages/hardhat-chai-matchers/test/events.ts
packages/hardhat-chai-matchers/test/hexEqual.ts
packages/hardhat-chai-matchers/test/properAddress.ts
packages/hardhat-chai-matchers/test/properHex.ts
packages/hardhat-chai-matchers/test/properPrivateKey.ts
packages/hardhat-chai-matchers/test/reverted/revertedWith.ts
packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts
packages/hardhat-chai-matchers/test/reverted/revertedWithPanic.ts
packages/hardhat-network-helpers/src/errors.ts
packages/hardhat-network-helpers/src/utils.ts
yarn.lock

Per https://www.notion.so/nomiclabs/Hardhat-Test-Utils-Error-Messages-Copy-Review-a43c4461c9d64861bd5759149a1d6298

Revise test utils error messages

---

docs/src/content/docs-landing/index.md
docs/src/content/hardhat-network-helpers/docs/overview.md
docs/src/content/hardhat-network/docs/overview/index.md
docs/src/content/hardhat-runner/docs/getting-started/index.md
docs/src/content/hardhat-vscode/docs/overview.md
docs/src/content/home.ts

For https://linear.app/nomic-foundation/issue/HH-862/normalize-the-description-of-each-component-and-create-a-notion

Normalize product description briefs

---

docs/src/content/tutorial/debugging-with-hardhat-network.md
docs/src/content/tutorial/deploying-to-a-live-network.md
docs/src/content/tutorial/writing-and-compiling-contracts.md

See individual commits. The last one might not be an improvement, I'm OK with dropping it.

Small tutorial improvements

---

docs/src/content/hardhat-runner/docs/getting-started/index.md
docs/src/content/tutorial/final-thoughts.md
packages/hardhat-core/src/internal/cli/project-creation.ts

I based this PR on https://github.com/NomicFoundation/hardhat/pull/2867

Prompt new users to star our repo

---

docs/redirects.config.js

This PR fixes some broken redirects

Fix redirects

---

docs/src/content/tutorial/creating-a-new-hardhat-project.md

Update spelling mistake tun -> run

---

docs/src/content/tutorial/creating-a-new-hardhat-project.md

docs: fix typo

---

docs/src/content/hardhat-network-helpers/docs/reference.md
docs/src/content/hardhat-network/docs/explanation/mining-modes.md
docs/src/content/hardhat-network/docs/guides/forking-other-networks.md
docs/src/content/hardhat-network/docs/reference/index.md
packages/hardhat-ethers/README.md
packages/hardhat-network-helpers/src/helpers/dropTransaction.ts

Use network helpers in the Hardhat Network docs

---

docs/src/content/hardhat-runner/docs/getting-started/index.md

Update index.md - corrected command to `npx hardhat run`

---

docs/src/content/hardhat-runner/docs/guides/test-contracts.md

The sample test doesn't compile due to import errors. Fixed it to use correct imports.
---

Fix sample test

---

packages/hardhat-core/sample-projects/javascript/test/Lock.js
packages/hardhat-core/sample-projects/typescript/test/Lock.ts

fix typo in doc locks

---

docs/src/content/tutorial/writing-and-compiling-contracts.md

applications instead of aplications
---

typo found

---

.changeset/popular-fishes-doubt.md
packages/hardhat-core/src/internal/hardhat-network/provider/return-data.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/error-inferrer.ts

Show selector in "unrecognized custom error" msg

---

docs/README.md

---
Fixed some grammatical errors in the README.md file found in docs/

fix grammatical errors in docs/README.md

---

packages/hardhat-core/src/internal/solidity/compilation-job.ts

Eighth and last compilation optimization PR.
Depends on #3094

Change the version range were solc's bug #9573 is present

---

docs/src/content/hardhat-runner/docs/guides/typescript.md
packages/e2e/.eslintignore
packages/e2e/test/fixture-projects/type-error-in-config/.gitignore
packages/e2e/test/fixture-projects/type-error-in-config/hardhat.config.ts
packages/e2e/test/fixture-projects/type-error-in-config/package.json
packages/e2e/test/fixture-projects/type-error-in-script/.gitignore
packages/e2e/test/fixture-projects/type-error-in-script/hardhat.config.ts
packages/e2e/test/fixture-projects/type-error-in-script/package.json
packages/e2e/test/fixture-projects/type-error-in-script/script.ts
packages/e2e/test/fixture-projects/type-error-in-test/.gitignore
packages/e2e/test/fixture-projects/type-error-in-test/hardhat.config.ts
packages/e2e/test/fixture-projects/type-error-in-test/package.json
packages/e2e/test/fixture-projects/type-error-in-test/test/test.ts
packages/e2e/test/helpers.ts
packages/e2e/test/index.ts
packages/e2e/tsconfig.json
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/core/params/hardhat-params.ts
packages/hardhat-core/src/internal/core/typescript-support.ts
packages/hardhat-core/src/internal/util/scripts-runner.ts
packages/hardhat-core/src/register.ts
packages/hardhat-core/src/types/runtime.ts
packages/hardhat-core/test/internal/cli/autocomplete.ts

Fixes #2945 for https://linear.app/nomic-foundation/issue/HH-959/make-typechecking-opt-in-instead-of-opt-out

Make typechecking opt-in instead of opt-out

---

.changeset/breezy-geese-sleep.md

We forgot to include a changeset in https://github.com/NomicFoundation/hardhat/pull/2879

Add hardhat-vyper changeset

---

packages/hardhat-core/src/types/artifacts.ts

Fix linkReferences type

---

.changeset/heavy-dolls-change.md
packages/hardhat-core/src/internal/hardhat-network/provider/BlockchainData.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/putGenesisBlock.ts

Skip consensus validation in all fromBlockData calls

---

docs/README.md

Docs: fix typo & grammar

---

.changeset/clever-hairs-shake.md
packages/hardhat-core/src/builtin-tasks/compile.ts

Fix wasmDownloader usage

---

docs/src/content/hardhat-chai-matchers/docs/overview.md

doc fix: s/occurr/occur

---

.changeset/hungry-peas-jog.md
packages/hardhat-core/src/types/config.ts
packages/hardhat-core/test/types/config.ts

This PR fixes a breaking change introduced in bd2bbc0ef3. Thanks @nventuro for reporting it.

Fix breaking change introduced in Hardhat 2.9.8

---

.changeset/big-cooks-decide.md
packages/hardhat-core/src/internal/core/jsonrpc/types/base-types.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getStorageAt.ts

Make eth_getStorageAt more permissive

---

docs/src/content/hardhat-runner/plugins/plugins.ts

I added hardhat [kriptonio](https://kriptonio.com/) plugin to the list of available plugins.

add kriptonio to plugins.ts

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Adds the following plugins to the list of community plugins.
- [hardhat-storage-layout-changes](https://github.com/zemse/hardhat-storage-layout-changes)
- [hardhat-live-fork](https://github.com/zemse/hardhat-live-fork)

Add two community plugins

---

docs/src/content/tutorial/index.md

---
Just correcting a small grammatical mistake that I noticed while going through the tutorial.

Correct a small grammatical mistake

---

packages/hardhat-core/src/builtin-tasks/flatten.ts
packages/hardhat-core/src/internal/cli/ArgumentsParser.ts
packages/hardhat-core/src/internal/core/errors-list.ts
packages/hardhat-core/src/internal/core/errors.ts
packages/hardhat-core/src/internal/core/runtime-environment.ts
packages/hardhat-core/test/internal/cli/ArgumentsParser.ts
packages/hardhat-core/test/internal/core/runtime-environment.ts

for https://linear.app/nomic-foundation/issue/HH-1152/add-task-name-to-hh306

Include task name in HH306 (MISSING_TASK_ARGUMENT)

---

.changeset/sour-bees-brush.md
packages/hardhat-chai-matchers/src/internal/misc/account.ts
packages/hardhat-chai-matchers/src/internal/properAddress.ts
packages/hardhat-chai-matchers/src/internal/properPrivateKey.ts
packages/hardhat-chai-matchers/test/properAddress.ts
packages/hardhat-chai-matchers/test/properPrivateKey.ts

Fix properAddress and properPrivateKey regex

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Synthetix has had these very well maintained and portable hardhat plugins for a while now, and its probably time we actually put them on the official "community plugins" list :laughing:

add synthetix CC plugins to community list

---

.changeset/quiet-dolls-do.md
packages/hardhat-etherscan/src/ChainConfig.ts

Add Arbitrum Goerli and fix Optimism Goerli URLs

---

docs/src/content/hardhat-runner/docs/other-guides/ganache-tests.md

Hi,
By travelling your documentation, I've noticed some broken links. This pull request integrates fixes for those broken links. 
Thanks a lot for your great work !

Fixing broken links

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
Added the new hardhat-chainlink-plugin to the documentation. This plugin allows users to run a chainlink node directly from the console and interact with it.

Added hardhat-chainlink-plugin to docs

---

docs/src/content/tutorial/final-thoughts.md

Hey there - love this tutorial as a way to get started using HardHat. I work for Alchemy and our developers tell us they find this library of content useful when they're getting started. One thing is that they've mentioned they also wanted to know how to interact with the smart contract once it's deployed and how to submit it to Etherscan to log. As such, we created these tutorials using HardHat to address this need and they've been some of our top views. Adding them here in the tutorial closing section in case HardHat readers also had the same questions and find it useful as they are natural next steps. Lmk of any questions / any better place to put it, thanks!
---

Added other Hardhat tutorials

---

docs/src/content/hardhat-runner/docs/guides/test-contracts.md

fix #3352
Change `begginning ` to `beginning `

Fix typo in Testing Contacts docs

---

packages/hardhat-core/src/internal/hardhat-network/provider/BlockchainData.ts
packages/hardhat-core/src/internal/hardhat-network/provider/filter.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/bloom.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder.ts
packages/hardhat-core/test/internal/hardhat-network/provider/utils/bloom.ts

Closes https://github.com/NomicFoundation/rethnet/issues/18

Vendor bloom implementation

---

packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/vm-adapter.ts

I only implemented the ethereumjs part of this. I will add relevant comments inline.

feat: print debug traces if results don't match

---

docs/src/content/hardhat-network/docs/guides/forking-other-networks.md

Use "recent block" instead of "latest" in the forking docs

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Add [hardhat-finder](https://www.npmjs.com/package/hardhat-finder) plugin to docs.

Add hardhat-finder plugin to docs

---

packages/hardhat-core/recommended-gitignore.txt

---
A space is generally added after a line comment delimiter.

Better comment styling for recommended .gitignore

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
Add [hardhat-migrate](https://www.npmjs.com/package/@dlsl/hardhat-migrate) plugin to the community plugins list.

Add hardhat-migrate plugin to the community plugins list

---

docs/src/content/hardhat-runner/plugins/plugins.ts

add plugin hardhat notifier

---

docs/src/content/hardhat-network/docs/reference/index.md
docs/src/content/hardhat-runner/plugins/plugins.ts
packages/hardhat-core/src/internal/core/jsonrpc/types/output/metadata.ts

Also, remove plugins that reference buidler.

Document hardhat_metadata

---

.changeset/curly-toys-repair.md
packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-stack-trace.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts

---
Relates to https://github.com/NomicFoundation/hardhat/issues/2948

Custom error with selector in `solidity-errors.ts`

---

crates/rethnet_eth/Cargo.toml
crates/rethnet_eth/src/access_list.rs
crates/rethnet_eth/src/account.rs
crates/rethnet_eth/src/block.rs
crates/rethnet_eth/src/lib.rs
crates/rethnet_eth/src/receipt.rs
crates/rethnet_eth/src/signature.rs
crates/rethnet_eth/src/state.rs
crates/rethnet_eth/src/transaction.rs
crates/rethnet_eth/src/trie.rs
crates/rethnet_eth/src/utils.rs

Resolves https://github.com/NomicFoundation/rethnet/issues/3
Todo:

feat: foundational Eth types

---

crates/rethnet_evm/src/db/layered_db.rs
crates/rethnet_evm/src/db/request.rs
crates/rethnet_evm/src/db/sync.rs
crates/rethnet_evm/src/debug.rs
crates/rethnet_evm_napi/src/state.rs
crates/rethnet_evm_napi/test/evm/StateManager.ts
packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts

Depends on fix in #3443 for the tests to succeed, but this makes it easier to review

feat: account storage root API and validation in dual adapter

---

crates/rethnet_evm_napi/src/block/builder.rs
crates/rethnet_evm_napi/src/lib.rs
packages/hardhat-core/src/internal/hardhat-network/provider/utils/bloom.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToRethnet.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts

Requires rebase on `rethnet/main` once #3443 has been merged. Couldn't split the two commits as they would generate conflicts. Only need to review the last commit

feat: calculate bloom for Rethnet logs and validate against ethereumjs

---

docs/src/content/hardhat-runner/docs/advanced/create-task.md
docs/src/content/hardhat-runner/docs/advanced/scripts.md
docs/src/content/hardhat-runner/docs/advanced/vscode-tests.md
docs/src/content/hardhat-runner/docs/guides/tasks-and-scripts.md
docs/src/content/hardhat-runner/docs/troubleshooting/common-problems.md

---
Just a bunch of issues I found while reading the docs.

Docs fixes

---

docs/src/model/markdown.tsx

Fix edit link in errors list page

---

.changeset/warm-radios-cross.md
packages/hardhat-core/src/internal/hardhat-network/stack-traces/error-inferrer.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/sendTransaction.ts

Show return data of unrecognized custom errors

---

.changeset/afraid-timers-shout.md
packages/hardhat-core/package.json
packages/hardhat-core/test/internal/util/download.ts
packages/hardhat-docker/package.json
packages/hardhat-etherscan/package.json
yarn.lock

---
Fixed https://github.com/NomicFoundation/hardhat/issues/3448

fix: reenabled tests

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
I just created a new plugin for Hardhat that allows using Jest as a task easily! and added it to the community plugins list.
Thanks.

Added hardhat-jest plugin

---

.changeset/nasty-maps-hang.md
docs/src/content/hardhat-runner/docs/advanced/_dirinfo.yaml
docs/src/content/hardhat-runner/docs/advanced/flattening.md
packages/hardhat-core/src/builtin-tasks/flatten.ts
packages/hardhat-core/test/internal/cli/autocomplete.ts

Closes #1049.
I also added a minor clarification to the flatten task help.

Add guide about flattening contracts

---

.github/workflows/test-recent-mainnet-block.yml
docs/src/content/hardhat-network/docs/guides/forking-other-networks.md
docs/src/content/hardhat-runner/docs/guides/verifying.md
docs/src/content/tutorial/deploying-to-a-live-network.md
docs/src/content/tutorial/final-thoughts.md
packages/hardhat-core/scripts/test-recent-mainnet-block.ts
packages/hardhat-core/test/fixture-projects/hardhat-network-fork-from-old-block/hardhat.config.js
packages/hardhat-core/test/fixture-projects/hardhat-network-fork-tangerine-whistle/hardhat.config.js
packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkBlockchain.ts
packages/hardhat-core/test/internal/hardhat-network/provider/fork/ForkStateManager.ts
packages/hardhat-core/test/internal/hardhat-network/provider/forked-provider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/hardhat-network-options.ts
packages/hardhat-core/test/internal/hardhat-network/provider/interval-mining-provider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/debug.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/test/internal/hardhat-network/provider/node.ts

Also: recommend it as an alternative to Alchemy in our docs.

Use infura in test suite

---

packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/creation.ts

Closes https://github.com/NomicFoundation/rethnet/issues/34.

Add an envar to select the vm

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
Add [hardhat-gobind](https://www.npmjs.com/package/@dlsl/hardhat-gobind) plugin to the community plugins list.

Add hardhat-gobind plugin to the community plugins list

---

.changeset/big-icons-boil.md
packages/hardhat-core/src/internal/cli/project-creation.ts
packages/hardhat-core/src/internal/cli/prompt.ts
packages/hardhat-core/src/internal/cli/types.ts

---
This PR will resolve #3549.

feat: support create project using pnpm as package manager

---

.changeset/plenty-comics-bow.md
packages/hardhat-core/src/internal/hardhat-network/jsonrpc/handler.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/websocket.ts

Hello Team, 
fixing here the #1324 issue. BatchRequests are now supported also via WebSockets. Unit tests are attached.

Fix #1324 (WebSocket BatchRequest) supports Batch requests via WebSockets

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Add hardhat scilla plugin to community plugins list.

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Add [hardhat-insight](https://www.npmjs.com/package/hardhat-insight) plugin to the docs.

add hardhat-insight plugin to docs

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
The `name` field is misleading. Seems like it's used to create node package URL as well.

Fix scilla plugin URL.

---

docs/src/content/hardhat-runner/plugins/plugins.ts

doc: add hardhat-flat-exporter plugin to community plugins list

---

.github/workflows/e2e-ci.yml
crates/rethnet_evm/Cargo.toml
crates/rethnet_evm/src/db.rs
crates/rethnet_evm/src/db/remote.rs
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-etherscan/src/ABITypes.ts

Fixes https://github.com/NomicFoundation/rethnet/issues/49

feat: read-only database for querying the blockchain

---

docs/src/content/tutorial/testing-contracts.md

Made capitalization consistent

Made capitalization consistent

---

.changeset/cyan-knives-study.md
config/eslint/eslintrc.js
packages/eslint-plugin/index.js
packages/eslint-plugin/onlyHardhatErrorRule.js

Added an ESLint rule for HardhatPluginErrors too, mostly for Ignition.

add eslint rule for hardhat plugin errors

---

.changeset/brave-steaks-sort.md
packages/hardhat-core/src/internal/core/config/config-env.ts
packages/hardhat-core/src/internal/core/runtime-environment.ts
packages/hardhat-core/src/internal/core/tasks/dsl.ts
packages/hardhat-core/src/internal/core/tasks/task-definitions.ts
packages/hardhat-core/src/types/runtime.ts
packages/hardhat-core/test/internal/core/runtime-environment.ts

---
This PR adds an optional third argument to the `hre.run` function which enables to override subtask arguments.

Overriding subtask parameters

---

.changeset/chilly-papayas-dance.md
packages/hardhat-core/sample-projects/javascript/scripts/deploy.js
packages/hardhat-core/sample-projects/typescript/scripts/deploy.ts

---
for #3607 
Changed the amount of eth sent in the script.

Corrected a too hight amount of eth sent to example Lock.

---

docs/src/content/tutorial/final-thoughts.md
docs/src/content/tutorial/writing-and-compiling-contracts.md

Hey there - Shelley from Alchemy here. When through your documents and think they're great. As the linked tutorial with HardHat is one of most popular tutorials by views, I added it here in case it's useful for HardHat readers who are trying to build and learn more.

Included another HardHat smart contract tutorial

---

.changeset/stupid-mangos-raise.md
packages/hardhat-etherscan/src/ChainConfig.ts

Adding Chiado

---

docs/src/content/hardhat-chai-matchers/docs/overview.md
docs/src/content/hardhat-chai-matchers/docs/reference.md
docs/src/content/hardhat-network/docs/reference/index.md

docs: fix typos

---

packages/hardhat-core/src/internal/core/errors-list.ts

docs: wording improvement

---

.changeset/rare-guests-listen.md
packages/hardhat-core/src/internal/core/config/config-loading.ts

---
Fixes https://github.com/NomicFoundation/hardhat/issues/3700
Tests fail in irrelevant places, unsure why.

Deduplicate unsupported versions

---

crates/rethnet_evm/src/evm.rs
crates/rethnet_evm/src/inspector.rs
crates/rethnet_evm/src/trace.rs

feat: add trace when a custom inspector is used

---

crates/rethnet_evm_napi/Cargo.toml
crates/rethnet_evm_napi/src/config.rs

bump: upgrade napi to 2.11.1

---

crates/rethnet_evm/src/state/layered_db.rs

fix(rethnet): remove second LayeredDatabase::remove_account function

---

crates/rethnet_evm_napi/src/account.rs
crates/rethnet_evm_napi/src/cast.rs
crates/rethnet_evm_napi/src/state.rs
packages/hardhat-core/src/internal/hardhat-network/provider/RethnetState.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts

refactor: combine code and hash in bytecode

---

crates/rethnet_evm/src/lib.rs
crates/rethnet_evm/src/state.rs
crates/rethnet_evm/src/state/debug.rs
crates/rethnet_evm/src/state/layered_state.rs
crates/rethnet_evm/src/state/request.rs
crates/rethnet_evm/src/state/sync.rs
crates/rethnet_evm_napi/src/state.rs

refactor: rename state-related files

---

docs/src/content/hardhat-runner/plugins/plugins.ts

https://github.com/fireblocks/hardhat-fireblocks
https://www.npmjs.com/package/@fireblocks/hardhat-fireblocks

Add Fireblocks plugin

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
Removes the deprecated Georacle plugin.

plugins: remove deprecated plugin

---

.changeset/moody-plants-speak.md
packages/hardhat-core/src/internal/solidity/resolver.ts

feat: support importing a sol from a project in the monorepo

---

.changeset/polite-mugs-cry.m
packages/hardhat-etherscan/src/ChainConfig.ts

---
Current api url for Aurora was deprecated

Fix aurora api url

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
I'd like to get my hardhat plugin listed on the Hardhat plugins page

Add hardhat-deal amongst hardhat plugins

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
This PR adds the @truffle/dashboard-hardhat-plugin to the list of community plugins

Add community plugin @truffle/dashboard-hardhat-plugin

---

.changeset/plenty-melons-smoke.md
docs/src/content/hardhat-network/docs/reference/index.md
packages/hardhat-core/src/internal/core/config/default-config.ts

We should merge and release this on Wednesday.

Set Shanghai as the default hardfork

---

docs/src/content/hardhat-network/docs/metamask-issue/index.md
docs/src/content/hardhat-network/docs/overview/index.md
docs/src/content/hardhat-runner/docs/getting-started/index.md
docs/src/content/hardhat-runner/docs/guides/verifying.md
docs/src/content/tutorial/boilerplate-project.md
docs/src/content/tutorial/deploying-to-a-live-network.md
docs/src/content/tutorial/index.md

This should be merged along with https://github.com/NomicFoundation/hardhat-boilerplate/pull/89

Add coinbase wallet to docs

---

packages/hardhat-core/src/internal/hardhat-network/provider/TxPool.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
packages/hardhat-core/test/internal/hardhat-network/provider/TxPool.ts

fix: remove self references in Hardhat objects

---

crates/rethnet_eth/src/remote.rs
crates/rethnet_evm/Cargo.toml
crates/rethnet_evm/src/block/builder.rs
crates/rethnet_evm/src/blockchain/sync.rs
crates/rethnet_evm/src/evm.rs
crates/rethnet_evm/src/lib.rs
crates/rethnet_evm/src/runtime.rs
crates/rethnet_evm/src/state/debug.rs
crates/rethnet_evm/src/state/layered_state.rs
crates/rethnet_evm/src/state/remote.rs
crates/rethnet_evm/src/state/request.rs
crates/rethnet_evm/src/state/sync.rs
crates/rethnet_evm_napi/Cargo.toml
crates/rethnet_evm_napi/package.json
crates/rethnet_evm_napi/src/blockchain.rs
crates/rethnet_evm_napi/src/lib.rs
crates/rethnet_evm_napi/src/logger.rs
crates/rethnet_evm_napi/src/runtime.rs
crates/rethnet_evm_napi/src/state.rs
crates/rethnet_evm_napi/src/tracer.rs
crates/rethnet_evm_napi/src/tracer/js_tracer.rs
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/hardhat-network/provider/TxPool.ts
packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/ethereumjs.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/rethnet.ts
packages/hardhat-core/test/internal/hardhat-network/provider/TxPool.ts

feat: add tracing instrumentation

---

packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts

Use shanghai in stack traces tests

---

crates/rethnet_evm/benches/state.rs

Fixes https://github.com/NomicFoundation/rethnet/issues/73

feat: `StateRef::storage()` worst case benchmark

---

crates/rethnet_evm/benches/state.rs

Fixes https://github.com/NomicFoundation/rethnet/issues/72

feat: add worst-case benchmark for `StateRef::code_by_hash`

---

.github/workflows/hardhat-chai-matchers-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-foundry-ci.yml
.github/workflows/hardhat-network-helpers-ci.yml
.github/workflows/hardhat-network-tracing-all-solc-versions.yml
.github/workflows/hardhat-network-tracing-ci.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-toolbox-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-verify-ci.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml

This fixes the false negatives due to solc download timeouts caused by [this issue](https://github.com/nodejs/node/issues/47555).

Use node 18.15 in CI

---

docs/src/content/tutorial/deploying-to-a-live-network.md

---
**ISSUE:**  https://github.com/NomicFoundation/hardhat/issues/3906
**Description:**  Docs update.
Adding url to Infura faucet, https://www.infura.io/faucet/sepolia to docs.
**Article:**
https://hardhat.org/tutorial/deploying-to-a-live-network

Add Infura Sepolia Faucet to docs #3906

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
This PR adds the Gelato Network Web3 Functions to the listed community plugins

Gelato w3f plugin

---

crates/rethnet_evm/Cargo.toml
crates/rethnet_evm/benches/state.rs
crates/rethnet_evm/benches/state_debug.rs
crates/rethnet_evm/benches/state_history.rs
crates/rethnet_evm/benches/util.rs

Fixes https://github.com/NomicFoundation/rethnet/issues/78

test: `StateHistory` worst case benchmarks

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Gelato w3f plugin update link

---

.changeset/fluffy-walls-sip.md
packages/hardhat-ethers/package.json
packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
packages/hardhat-ethers/test/contracts.ts
packages/hardhat-ethers/test/helpers.ts

Fix waitForDeployment in non-automined networks

---

packages/hardhat-core/src/builtin-tasks/compile.ts

---
Hi, there seems to be an array with no purpose.

This removes an useless array

---

crates/rethnet_eth/src/remote.rs
crates/rethnet_eth/src/remote/client.rs
crates/rethnet_eth/src/remote/jsonrpc.rs
crates/rethnet_rpc_server/Cargo.toml
crates/rethnet_rpc_server/src/lib.rs
crates/rethnet_rpc_server/src/methods.rs

Fixes https://github.com/NomicFoundation/rethnet/issues/92

Implement JSON-RPC server library

---

docs/redirects.config.js
packages/hardhat-toolbox/README.md

Fix broken link to hardhat-ethers

Fix broken link to hardhat-ethers

---

.changeset/three-yaks-reply.md
packages/hardhat-ethers/package.json
packages/hardhat-ethers/src/internal/errors.ts
packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
packages/hardhat-ethers/test/contracts.ts
packages/hardhat-ethers/test/helpers.ts
packages/hardhat-ethers/test/provider-events.ts
yarn.lock

Add support for `contract.on`

---

packages/hardhat-core/test/internal/core/providers/errors.ts
packages/hardhat-ethers/test/error-messages.ts
packages/hardhat-ethers/test/fixture-projects/error-messages/.gitignore
packages/hardhat-ethers/test/fixture-projects/error-messages/contracts/Contract.sol
packages/hardhat-ethers/test/fixture-projects/error-messages/hardhat.config.js

Closes #3581.
Apparently this is working fine now, but I added tests to prevent this from happening again in the future.

Add tests for provider error messages

---

.changeset/wicked-squids-obey.md
packages/hardhat-verify/src/chain-config.ts

Add support for Base Goerli testnet

---

.changeset/chilly-meals-enjoy.md

I wrote the changset for #4155, and forgot to thank the author. This fixes it.

Add credit to a changeset

---

.changeset/ten-hairs-attend.md
packages/hardhat-core/src/internal/core/providers/http.ts
packages/hardhat-core/test/internal/core/providers/http.ts

Handle 429 responses withouto retry-after header

---

crates/rethnet_eth/src/remote/client.rs
crates/rethnet_eth/src/remote/eth.rs
crates/rethnet_eth/src/remote/serde_with_helpers.rs
crates/rethnet_eth/src/spec.rs

fix: Block & Transaction RPC types

---

.changeset/slimy-dots-prove.md
packages/hardhat-core/console.sol
packages/hardhat-core/scripts/console-library-generator.js
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/version-independent/pure-console-log/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/version-independent/pure-console-log/test.json

This PR makes `console.sol` work in pure functions.
Fixes #3905

Pure console.sol

---

crates/rethnet_eth/src/remote/methods.rs
crates/rethnet_eth/tests/integration_tests.rs

Fixes https://github.com/NomicFoundation/rethnet/issues/127

feat: Add `personal_sign` alias for `eth_sign`

---

docs/src/content/hardhat-runner/plugins/plugins.ts

add `hardhat-deployed-records` plugin

add `hardhat-deployed-records` plugin

---

crates/rethnet/tests/cli.rs
crates/rethnet_eth/src/remote.rs
crates/rethnet_eth/src/remote/filter.rs
crates/rethnet_eth/src/remote/methods.rs
crates/rethnet_eth/tests/integration_tests.rs
crates/rethnet_rpc_server/src/filter.rs
crates/rethnet_rpc_server/src/lib.rs
crates/rethnet_rpc_server/tests/integration_tests.rs

Fixes https://github.com/NomicFoundation/rethnet/issues/113

feat: Port Hardhat Node basic filters

---

crates/rethnet/tests/cli.rs
crates/rethnet_rpc_server/src/lib.rs
crates/rethnet_rpc_server/tests/integration_tests.rs

Fixes https://github.com/NomicFoundation/rethnet/issues/133

feat: Impersonation of accounts

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Adding new community hardhat-plugin for deploying contracts without gas using Gas station network.

feat: adding new plugin `hardhat-gasless-deployer`

---

docs/src/content/tutorial/deploying-to-a-live-network.md

---
This PR presents a small change that adds the Chainstack Sepolia faucet among the options present on deploying-to-a-live-network.md - this also slightly changes the wording on this document to account for the multiple faucet choices present properly.

Adds the Chainstack Sepolia faucet to docs

---

.changeset/gorgeous-foxes-swim.md
packages/hardhat-verify/src/internal/chain-config.ts

---
conforming to the prior base-goerli PR #4109 
- basescan url https://basescan.org/
- basescan api docs https://basescan.org/apis
- chainId https://chainlist.org/chain/8453

feat: add Base network support

---

.changeset/tasty-monkeys-talk.md
packages/hardhat-foundry/src/foundry.ts

Remove node_modules from remapping results

---

.github/workflows/test-slow-imports-rule.yml

Fix cron in test-slow-imports-rule workflow

---

.changeset/ten-trees-smoke.md
packages/hardhat-core/src/internal/artifacts.ts
packages/hardhat-core/src/utils/contract-names.ts
packages/hardhat-core/test/internal/artifacts.ts
packages/hardhat-verify/src/index.ts

Fix: artifactExists returns false for missing artifacts

---

docs/src/content/hardhat-runner/docs/guides/command-line-completion.md

Adding to the docs what I said in [this comment](https://github.com/NomicFoundation/hardhat/issues/4282#issuecomment-1674339616).

Add extra information to hh troubleshooting section

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
Updated existing Distributed Lab plugins to point to the new NPM packages. Added [hardhat-smart-compare](https://www.npmjs.com/package/@solarity/hardhat-smart-compare) plugin.

Update Distributed Lab plugins

---

crates/rethnet/src/config.rs
crates/rethnet/src/lib.rs
crates/rethnet/tests/cli.rs
crates/rethnet_eth/src/remote/methods.rs
crates/rethnet_eth/tests/integration_tests.rs
crates/rethnet_evm/src/blockchain.rs
crates/rethnet_evm/src/blockchain/local.rs
crates/rethnet_evm/src/lib.rs
crates/rethnet_evm/src/mempool.rs
crates/rethnet_evm/src/miner.rs
crates/rethnet_rpc_server/src/config.rs
crates/rethnet_rpc_server/src/hardhat_methods.rs
crates/rethnet_rpc_server/src/lib.rs
crates/rethnet_rpc_server/tests/integration_tests.rs

feat: implement mining json rpc methods

---

packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts

This should be cherry-picked to `main`

fix: hardhat fork blockchain transaction type

---

book/src/01_getting_started/03_test.md

Testing instruction improvements for the book.

docs: improve testing instructions

---

crates/rethnet_evm/src/state/remote/cached.rs

This PR fixes the first CI failure in https://github.com/NomicFoundation/rethnet/issues/175 by making sure that a code hash property of an `AccountInfo` returned by calling `<CachedRemoteState as State>::basic` can be always used to fetch the code with `<CachedRemoteState as State>::code_by_hash`.

fix: make sure code can be fetched by hash

---

.cargo-husky/hooks/pre-commit
.github/workflows/hardhat-core-ci.yml
crates/rethnet_eth/src/remote/client.rs

Workaround for https://github.com/NomicFoundation/rethnet/issues/174. 
Tested locally and in the CI with code that intentionally fails both `cargo check` and custom clippy rules.

ci: fix clippy custom rules not applied

---

packages/hardhat-verify/src/index.ts
packages/hardhat-verify/src/internal/errors.ts
packages/hardhat-verify/src/internal/etherscan.ts
packages/hardhat-verify/src/internal/sourcify.ts
packages/hardhat-verify/src/internal/task-names.ts
packages/hardhat-verify/src/internal/tasks/etherscan.ts
packages/hardhat-verify/src/internal/tasks/sourcify.ts
packages/hardhat-verify/src/internal/undici.ts
packages/hardhat-verify/src/sourcify.ts
packages/hardhat-verify/src/types.ts
packages/hardhat-verify/test/fixture-projects/hardhat-project/hardhat.config.js
packages/hardhat-verify/test/integration/index.ts
packages/hardhat-verify/test/integration/mocks/sourcify.ts
packages/hardhat-verify/test/unit/sourcify.ts

Add the basic functions, tasks and tests to provide Sourcify verification

Add basic Sourcify verification

---

docs/src/components/mdxComponents/CodeBlocks.stories.tsx
docs/src/content/hardhat-runner/docs/advanced/hardhat-and-foundry.md
docs/src/content/hardhat-runner/docs/advanced/scripts.md
docs/src/content/hardhat-runner/docs/advanced/using-esm.md
docs/src/content/hardhat-runner/docs/getting-started/index.md
docs/src/content/hardhat-runner/docs/guides/project-setup.md
docs/src/content/hardhat-runner/docs/guides/typescript.md
docs/src/content/hardhat-runner/docs/other-guides/truffle-testing.md
docs/src/content/hardhat-runner/docs/other-guides/waffle-testing.md
docs/src/content/tutorial/creating-a-new-hardhat-project.md
packages/hardhat-core/README.md

**THIS PR SHOULD BE MERGED AFTER THAT THE INIT CODE IS RELEASED!**
Update docs for the new CLI command `init`. It will be used to initialize new Hardhat projects.
Example:
```
npx hardhat init
```
[Link to issue](https://github.com/NomicFoundation/hardhat/issues/2594)
[Link to the code logic PR](https://github.com/NomicFoundation/hardhat/pull/4384)

Update docs for the new CLI command `init`

---

docs/redirects.config.js

This PR adds a redirect to the website

Redirect /ignition-discord to a channel-specific invite

---

.github/workflows/hardhat-core-ci.yml

Resolves https://github.com/NomicFoundation/edr/issues/163

ci: remove uncached test fork job

---

.github/workflows/hardhat-core-ci.yml

Enable EthereumJS mode tests in CI.

ci: enable ethereumjs mode tests

---

book/src/01_getting_started/03_test.md

@Wodann I'm wondering if we need to update anywhere else?

docs: update book to switch from rethnet to edr mode

---

crates/tools/src/benchmark.rs
crates/tools/src/main.rs

Adds a benchmark command to the tools that lets us run a command multiple times in a directory and measure each execution time.

misc: add benchmark CLI

---

docs/src/content/hardhat-runner/plugins/plugins.ts

add plugin hardhat-logger

---

docs/src/content/ignition/docs/advanced/execution.md

Restructure within paragraphs and fix minor spelling mistakes.

docs: update the `Module execution` page of the Ignition docs

---

packages/hardhat-verify/src/index.ts
packages/hardhat-verify/src/internal/errors.ts
packages/hardhat-verify/src/internal/etherscan.ts
packages/hardhat-verify/src/internal/sourcify.ts
packages/hardhat-verify/src/internal/task-names.ts
packages/hardhat-verify/src/internal/tasks/etherscan.ts
packages/hardhat-verify/src/internal/tasks/sourcify.ts
packages/hardhat-verify/src/internal/undici.ts
packages/hardhat-verify/src/sourcify.ts
packages/hardhat-verify/src/types.ts
packages/hardhat-verify/test/fixture-projects/hardhat-project/hardhat.config.js
packages/hardhat-verify/test/integration/index.ts
packages/hardhat-verify/test/integration/mocks/sourcify.ts
packages/hardhat-verify/test/unit/sourcify.ts

Hardhat verify add sourcify

---

docs/src/content/ignition/docs/advanced/deployments.md
docs/src/content/ignition/docs/advanced/reconciliation.md
docs/src/content/ignition/docs/advanced/versioning.md

Update the Ignition docs advanced section, specifically:
* advanced/deployments.md
* advanced/reconciliation.md
* advanced/versioning.md

docs: ignition docs advanced

---

.changeset/fast-windows-search.md
.changeset/funny-cats-sing.md

These are the changes from https://github.com/NomicFoundation/hardhat/pull/4435, which we merged to a wrong branch.

Report ignition deploy to GA

---

Cargo.lock
crates/edr_rpc_server/Cargo.toml
crates/edr_rpc_server/src/lib.rs
crates/edr_rpc_server/src/node.rs

WIP https://github.com/NomicFoundation/edr/issues/141
TODOs left:
- Add more node tests
- Reuse node fixture in integration tests
- Port more methods
Submitting now for ease of review.

refactor: move server methods to node

---

docs/src/content/hardhat-runner/plugins/plugins.ts

add plugin "hardhat-contract-signatures"

add plugin hardhat-contract-signatures

---

.changeset/real-coins-tease.md
packages/hardhat-verify/src/internal/solc/artifacts.ts
packages/hardhat-verify/src/internal/sourcify.ts

Normalized user-input addresses from CLI and libraries file for correct comparison.

Normalize input addresses to lowercase for comparison

---

.changeset/friendly-ways-beg.md
packages/hardhat-verify/src/internal/chain-config.ts

I would want to add the polygon zkEVM chains on hardhat verify.
Let me know if i have to update another files ^^

Add Polygon zkEVM chain config on hardhat verify

---

.changeset/soft-lobsters-rush.md
packages/hardhat-core/recommended-gitignore.txt

The reason I'm sending this PR is that ignition creates an `artifacts` folder that you may want to commit, and our `.gitignore` was making that tricky.
---

Use relative paths in the recommended .gitignore

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
Adding the `hardhat-web3-v4` plugin

added hardhat-web3-v4 plugin

---

crates/edr_eth/src/remote/client.rs
crates/edr_provider/src/data.rs

Fix overwriting genesis account nonces and code in fork mode by reinstating the previous approach of fetching the account info from the remote: https://github.com/NomicFoundation/hardhat/blob/e822bd0e01b1b14653f2ac58ebc28743264ef3d7/crates/rethnet_evm/src/state/fork.rs#L48
Note that in addition to nonces we also reinstate code now for completeness as we only want to allow overwriting the balance.

fix: overwrite genesis account nonces and code in fork mode

---

docs/temp/tabsConfig.json

This PR reverts an accidental change to `docs/tmp/tabsConfig.json`.

Revert a change to tabsConfig.json

---

.changeset/bright-plums-watch.md
packages/hardhat-verify/README.md
packages/hardhat-verify/src/internal/config.ts
packages/hardhat-verify/src/internal/sourcify.ts
packages/hardhat-verify/src/internal/tasks/sourcify.ts
packages/hardhat-verify/src/types.ts
packages/hardhat-verify/test/unit/config.ts
packages/hardhat-verify/test/unit/sourcify.ts

Continuation of https://github.com/NomicFoundation/hardhat/pull/4683 because I can't push to the branch of that PR.

hardhat-verify: add apiUrl and browserUrl in sourcify options

---

.changeset/three-boxes-divide.md
docs/redirects.config.js
docs/src/config.ts
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/cli/project-creation.ts

Add solidity survey banner and message

---

crates/edr_provider/src/data.rs
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getCode.ts

Enable and fix `eth_getCode` integration tests.

test: enable and fix `eth_getCode` integration tests

---

.changeset/modern-fishes-look.md
packages/hardhat-core/src/internal/core/providers/gas-providers.ts

fix(gas_provider): Prevent submitting transactions with 0 priority fee.

---

docs/README.md
docs/src/content/ignition/docs/guides/creating-modules.md
packages/hardhat-chai-matchers/src/internal/emit.ts
packages/hardhat-chai-matchers/test/events.ts
packages/hardhat-core/src/internal/util/fs-utils.ts
packages/hardhat-core/test/internal/core/providers/gas-providers.ts

fix: typos

---

.changeset/beige-ladybugs-confess.md
docs/redirects.config.js
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/cli/version-notifier.ts
pnpm-lock.yaml

Show a notification on new versions of Hardhat.
Also, show a message a limited number of times whenever the next major is out

Notify of new hardhat versions

---

.changeset/twelve-mails-heal.md
packages/hardhat-verify/src/index.ts
packages/hardhat-verify/src/internal/tasks/etherscan.ts
packages/hardhat-verify/src/internal/tasks/sourcify.ts

[Link to issue](https://github.com/NomicFoundation/hardhat/issues/4543)

Add support for programmatic verification in Sourcify

---

docs/src/content/hardhat-runner/docs/advanced/create-task.md
docs/src/content/hardhat-runner/docs/advanced/migrating-from-hardhat-waffle.md
docs/src/content/hardhat-runner/docs/guides/typescript.md
docs/src/content/hardhat-runner/docs/other-guides/waffle-testing.md
docs/src/content/tutorial/creating-a-new-hardhat-project.md
packages/hardhat-chai-matchers/README.md

---
Locks `chai` to version 4. [See conversation]( https://github.com/NomicFoundation/hardhat/issues/4733)

Docs: Update to lock chai at version 4

---

.changeset/chatty-ravens-decide.md
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/solidity/compiler/index.ts

[Link to issue](https://github.com/NomicFoundation/hardhat/issues/4290)

Make sure that solc default import callback is not being used

---

docs/src/content/hardhat-runner/plugins/plugins.ts

https://github.com/fireblocks/hardhat-fireblocks
https://www.npmjs.com/package/@fireblocks/hardhat-fireblocks

Fix broken link

---

docs/.npmrc

Closes https://github.com/NomicFoundation/hardhat/issues/4798

Run pre/post scripts for docs

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
Add `@bonadocs/docgen` to the plugins directory. It enables users to generate an interactive documentation website featuring the bonadocs widget that allows developers to interact with the smart contracts directly from within the documentation.

Add @bonadocs/docgen

---

.github/workflows/e2e-tests.yml
e2e/clean.sh
e2e/fixture-projects/clean/test.sh
e2e/fixture-projects/compile-fail/test.sh
e2e/fixture-projects/compile/test.sh
e2e/fixture-projects/flatten/test.sh
e2e/fixture-projects/gas-reporter/test.sh
e2e/fixture-projects/help/test.sh
e2e/fixture-projects/solidity-coverage/test.sh
e2e/fixture-projects/test/test.sh
e2e/fixture-projects/vars/test.sh
e2e/helpers.sh
e2e/run-fixture-projects.sh
e2e/test-project-initialization.sh

[Link to issue](https://github.com/NomicFoundation/hardhat/issues/4759)

Fix e2e issues

---

docs/src/content/hardhat-runner/docs/advanced/multiple-solidity-versions.md

---
- fixes issue with broken path to custom solidity compiler. Tested.

Docs[Fix]: Broken Path to Custom Solc Guide

---

docs/src/content/hardhat-runner/docs/supporter-guides/oracles.md

---
Adding the [Kleros Oracle](https://kleros.io/oracle) to the list of available oracles in the Supporter Guide documentation.

Docs: added the kleros oracle to the supporter guide

---

docs/src/content/ignition/docs/guides/deploy.md

Documents changes in this ignition PR: https://github.com/NomicFoundation/hardhat-ignition/pull/698

Update module parameters docs to include bigint example

---

docs/src/content/hardhat-runner/docs/advanced/building-plugins.md
docs/src/content/hardhat-vscode/docs/formatting.md
docs/src/content/ignition/docs/guides/error-handling.md

chore: fix typos

---

.changeset/olive-kiwis-guess.md
packages/hardhat-verify/src/internal/chain-config.ts

Hey! we migrate our previous testnet on goerli, to this new official testnet on sepolia. Here's the PR to update the chain info ^^
Sorry the inconveniences!

Update polygon zkevm cardona testnet

---

.changeset/thick-cycles-attend.md
crates/edr_evm/src/mempool.rs
crates/edr_provider/tests/issue_325.rs

Fixes https://github.com/NomicFoundation/edr/issues/325

fix: remove empty pending and future transaction lists

---

.changeset/red-snails-fix.md
crates/edr_eth/src/remote/client.rs
crates/edr_evm/tests/issue_4974.rs
crates/edr_evm/tests/optimism.rs

Fixes https://github.com/NomicFoundation/hardhat/issues/4974 & https://github.com/NomicFoundation/edr/issues/323

fix: set content-type and user-agent in RPC client

---

.changeset/fair-lies-cough.md
crates/edr_evm/benches/state/state_debug.rs
crates/edr_evm/src/block/builder.rs
crates/edr_evm/src/state/debug.rs
crates/edr_evm/src/state/fork.rs
crates/edr_evm/src/state/trie.rs
crates/edr_evm/tests/issues.rs
crates/edr_evm/tests/mem_pool.rs
crates/edr_provider/src/data.rs

Fixes https://github.com/NomicFoundation/hardhat/issues/4984

fix: retrieve code for forked accounts when modifying state

---

.changeset/quiet-goats-remember.md
crates/edr_evm/benches/state/state_debug.rs
crates/edr_evm/benches/state/util.rs
crates/edr_evm/src/state/debug.rs
crates/edr_evm/src/state/fork.rs
crates/edr_evm/src/state/trie.rs
crates/edr_provider/src/data.rs

This should be merged after https://github.com/NomicFoundation/hardhat/pull/5000

refactor: clean up set_account_storage_slot

---

docs/src/content/hardhat-runner/docs/advanced/building-plugins.md

---
```ts
- await hre.network.request({method: "eth_estimateGas" /*{ method arguments }*/}); // This line of code has error
```
```ts
+ await hre.network.provider.request({method: "eth_estimateGas" /*{ method arguments }*/}); // This line of code work correct.
```

docs: repair doc

---

packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/feeHistory.ts
packages/hardhat-solpp/test/fixture-projects/hardhat-project/contracts/B.sol
packages/hardhat-viem/src/internal/clients.ts

chore: fix some comments

---

.changeset/short-rats-double.md
crates/edr_eth/src/remote/client.rs

Increase rate limiting retries in an attempt to fix the issues with Infura reported in https://github.com/NomicFoundation/edr/issues/345

fix: increase rate limiting retries

---

.github/workflows/hardhat-core-ci.yml
crates/edr_eth/src/transaction/request.rs
crates/edr_evm/src/blockchain/forked.rs
crates/edr_evm/src/transaction.rs
crates/edr_evm/src/transaction/executable.rs
crates/edr_provider/src/error.rs

I got tired of seeing this in PRs:

Fix cargo doc warnings

---

packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/core/tasks/task-definitions.ts

chore: fix some typos

---

packages/hardhat-core/test/internal/hardhat-network/provider/error-object.ts

This PR just updates some tests with extra checks. I was expecting to reproduce a problem that @alcuadrado noticed in the Ignition tests, but I couldn't do it. But since these extra assertions are good to have anyway, I think we should include them.

Check that error object doesn't have unexpected fields

---

.github/workflows/edr-npm-release.yml

Fix bug introduced in #5090 that caused the pre-release tag never getting applied.

ci: fix application of pre-release tag

---

docs/src/content/ignition/docs/guides/modifications.md

Feature issue: https://github.com/NomicFoundation/hardhat-ignition/issues/649

Add documentation for the `--reset` flag

---

packages/hardhat-core/recommended-gitignore.txt

[See issue here](https://github.com/NomicFoundation/hardhat-ignition/issues/719)

Add ignition/deployment to gitignore

---

docs/src/content/hardhat-chai-matchers/docs/overview.md

[Link to issue](https://github.com/NomicFoundation/hardhat/issues/4871)

Clarify in the documentation that hardhat-chai-matchers is not compatible with hardhat-viem

---

packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionReceipt.ts

I tested this fix locally and it resolved the sporadic failure seen in CI (e.g. [here](https://github.com/NomicFoundation/hardhat/actions/runs/8659971546/job/23746996612?pr=5108#step:11:3025))

fix: sporadic test failure in CI

---

.changeset/selfish-bottles-cross.md
packages/hardhat-ledger/README.md
packages/hardhat-ledger/src/errors.ts
packages/hardhat-ledger/src/index.ts
packages/hardhat-ledger/src/internal/create-ledger-provider.ts
packages/hardhat-ledger/src/provider.ts
packages/hardhat-ledger/src/type-extensions.ts
packages/hardhat-ledger/src/types.ts
packages/hardhat-ledger/test/errors.ts
packages/hardhat-ledger/test/internal/create-ledger-provider.ts
packages/hardhat-ledger/test/provider.ts

- [x ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
---
First pass at feature discussed in #4790

Legacy ledger derivation path support in hardhat-ledger

---

.github/workflows/hardhat-chai-matchers-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-foundry-ci.yml
.github/workflows/hardhat-ledger-ci.yml
.github/workflows/hardhat-network-helpers-ci.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-toolbox-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-verify-ci.yml
.github/workflows/hardhat-viem-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml
.github/workflows/hardhat-web3-v4-ci.yml

[Link to issue](https://github.com/NomicFoundation/hardhat/issues/4834)

Re-enable macos CI tests

---

.changeset/friendly-papayas-drum.md
crates/edr_evm/src/block/builder.rs
crates/edr_evm/src/miner.rs
crates/edr_provider/src/test_utils.rs
crates/edr_provider/tests/issue_384.rs

Fixes https://github.com/NomicFoundation/edr/issues/384

fix: mining blocks when forking non-eth chains

---

.changeset/clever-peaches-obey.md
packages/hardhat-core/src/internal/core/params/argumentTypes.ts
packages/hardhat-core/test/internal/core/params/argumentTypes.ts

Add `BigInt` task argument type

---

.changeset/dry-flowers-help.md
packages/hardhat-core/package.json
pnpm-lock.yaml

This also stops using the workspace version.

Bump EDR dependency to 0.3.7

---

docs/src/content/ignition/docs/guides/_dirinfo.yaml
docs/src/content/ignition/docs/guides/ledger.md

fixes https://github.com/NomicFoundation/hardhat-ignition/issues/598
requires https://github.com/NomicFoundation/hardhat-ignition/pull/731 to be merged first

Guide for using Ledger devices with Ignition

---

.github/dependabot.yml

This should open a PR bumping EDR after we release a new version.

Update EDR using dependabot

---

packages/hardhat-core/sample-projects/typescript-viem/hardhat.config.ts

these are only used as types
---

fix(ts): import type adjustments

---

docs/README.md

fix typos in README.md

---

.changeset/dull-spies-hope.md
packages/hardhat-solhint/src/index.ts
packages/hardhat-solhint/test/fixture-projects/solhintignore-project/.solhint.json
packages/hardhat-solhint/test/fixture-projects/solhintignore-project/.solhintignore
packages/hardhat-solhint/test/fixture-projects/solhintignore-project/contracts/Greeter.sol
packages/hardhat-solhint/test/fixture-projects/solhintignore-project/contracts/Greeter2.sol
packages/hardhat-solhint/test/fixture-projects/solhintignore-project/contracts/Greeter3.sol
packages/hardhat-solhint/test/fixture-projects/solhintignore-project/hardhat.config.js
packages/hardhat-solhint/test/tests.ts

Recreated https://github.com/NomicFoundation/hardhat/pull/3741 since I messed up the rebase. 
Fixes https://github.com/NomicFoundation/hardhat/issues/1665.

feat(@nomiclabs/hardhat-solhint): load .solhintignore file

---

.changeset/strange-ladybugs-end.md
packages/hardhat-chai-matchers/src/internal/changeEtherBalance.ts
packages/hardhat-chai-matchers/src/internal/changeEtherBalances.ts
packages/hardhat-chai-matchers/src/internal/changeTokenBalance.ts
packages/hardhat-chai-matchers/src/types.ts
packages/hardhat-chai-matchers/test/bigNumber.ts
packages/hardhat-chai-matchers/test/changeEtherBalance.ts
packages/hardhat-chai-matchers/test/changeEtherBalances.ts
packages/hardhat-chai-matchers/test/changeTokenBalance.ts
packages/hardhat-chai-matchers/test/reverted/revertedWithPanic.ts

This is a rebased and updated copy of https://github.com/NomicFoundation/hardhat/pull/3751.

Accept predicate functions in balance and token balance change matchers

---

v-next/hardhat-build-system/src/internal/builtin-tasks/utils/solidity-files-cache.ts
v-next/hardhat-build-system/src/internal/solidity/compiler/downloader.ts
v-next/hardhat-build-system/src/internal/tasks.ts
v-next/hardhat-build-system/src/internal/types/artifacts.ts
v-next/hardhat-build-system/src/internal/utils/artifacts.ts
v-next/hardhat-build-system/src/internal/utils/download.ts
v-next/hardhat-build-system/src/internal/utils/global-dir.ts
v-next/hardhat-build-system/src/internal/utils/package-info.ts
v-next/hardhat-build-system/test/helpers.ts
v-next/hardhat-build-system/test/internal/utils/artifacts.ts

Replace "fs-extra" with hh utils methods

---

.github/workflows/review-approved-slack-notification.yml
.github/workflows/review-requested-slack-notification.yml

Adding some automation related to reviews. I'll merge this without a review as it can only be tested after merged.

Notify through Slack when a review is requested or approved

---

v-next/core/src/internal/tasks/builders.ts
v-next/core/src/internal/tasks/utils.ts
v-next/core/src/types/common.ts
v-next/core/src/types/tasks.ts
v-next/core/test/internal/tasks/builders.ts
v-next/core/test/internal/tasks/utils.ts
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat-errors/src/errors.ts

This should be easy to review if you go commit by commit instead of looking at the files.

Tasks builders implementation and testing

---

.github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
.github/workflows/check-docs-site.yml
.github/workflows/comment-on-linter-error.yml
.github/workflows/e2e-tests.yml
.github/workflows/hardhat-chai-matchers-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-foundry-ci.yml
.github/workflows/hardhat-ledger-ci.yml
.github/workflows/hardhat-network-helpers-ci.yml
.github/workflows/hardhat-network-tracing-all-solc-versions.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-toolbox-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-verify-ci.yml
.github/workflows/hardhat-viem-ci.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml
.github/workflows/hardhat-web3-v4-ci.yml
.github/workflows/lint.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/test-slow-imports-rule.yml
pnpm-lock.yaml

This PR migrates `main` into pnpm 9

Migrate to pnpm 9

---

.github/workflows/LATEST_DEPENDENCY_VERSIONS.yml
.github/workflows/check-docs-site.yml
.github/workflows/comment-on-linter-error.yml
.github/workflows/e2e-tests.yml
.github/workflows/hardhat-chai-matchers-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-foundry-ci.yml
.github/workflows/hardhat-ledger-ci.yml
.github/workflows/hardhat-network-helpers-ci.yml
.github/workflows/hardhat-network-tracing-all-solc-versions.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-toolbox-ci.yml
.github/workflows/hardhat-verify-ci.yml
.github/workflows/hardhat-viem-ci.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/hardhat-web3-v4-ci.yml
.github/workflows/lint.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/test-slow-imports-rule.yml
.github/workflows/v-next-ci.yml
pnpm-lock.yaml
v-next/hardhat-build-system/package.json

This PR migrates `v-next` into pnpm 9

[v-next] Upgrade to pnpm 9

---

v-next/core/src/internal/tasks/task-manager.ts
v-next/core/test/internal/plugins/resolve-plugin-list.ts
v-next/core/test/internal/tasks/task-manager.ts

NOTES:
- Read note at the top on why I'm testing this through `createHardhatRuntimeEnvironment` and not directly.
- There is some duplication in the tests, but I avoided extracting it to keep things simple. 
- Technically, we could repeat many of the tests with config tasks, but that seemed like overkill.

Added tests to task manager 

---

v-next/core/src/internal/tasks/builders.ts
v-next/core/src/types/common.ts
v-next/core/src/types/tasks.ts
v-next/hardhat/src/internal/cli/main.ts

- Improves typings.
- Makes `isParameterValueValid` work with arrays (for variadic parameters). This will be used for validation in the `run` function.

Improve task types & validation

---

v-next/core/src/internal/configuration-variables.ts
v-next/core/test/internal/configuration-variables/configuration-variables.ts
v-next/hardhat-errors/src/descriptors.ts

Implement and test config variable resolution

---

v-next/hardhat-utils/src/ci.ts
v-next/hardhat-utils/src/lang.ts
v-next/hardhat-utils/src/string.ts
v-next/hardhat-utils/test/ci.ts
v-next/hardhat-utils/test/lang.ts
v-next/hardhat-utils/test/string.ts

Closes https://github.com/NomicFoundation/hardhat/issues/5305
A follow-up PR will replace the usage in `v-next`

Utils additions

---

v-next/core/src/internal/tasks/builders.ts
v-next/core/src/internal/tasks/resolved-task.ts
v-next/core/src/types/tasks.ts
v-next/core/test/internal/tasks/builders.ts
v-next/core/test/internal/tasks/fixture-projects/file-actions/action-fn.js
v-next/core/test/internal/tasks/fixture-projects/file-actions/no-default-fn.js
v-next/core/test/internal/tasks/fixture-projects/file-actions/no-default.js
v-next/core/test/internal/tasks/fixture-projects/file-actions/no-run-super.js
v-next/core/test/internal/tasks/task-manager.ts
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/example.config.ts

Task run implementation

---

v-next/core/src/internal/hook-manager.ts
v-next/hardhat-errors/src/errors.ts
v-next/hardhat-utils/package.json
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/helpers/config-loading.ts

Follow-up to https://github.com/NomicFoundation/hardhat/pull/5349

Use isObject & kebabToCamelCase in v-next

---

.github/workflows/v-next-ci.yml
pnpm-lock.yaml
scripts/check-v-next-npm-scripts.js
v-next/example-project/.gitignore
v-next/example-project/LICENSE
v-next/example-project/README.md
v-next/example-project/hardhat.config.ts
v-next/example-project/package.json
v-next/example-project/tsconfig.json

Add example project to run hardhat locally

Example project

---

v-next/core/src/config.ts
v-next/core/src/internal/tasks/builders.ts
v-next/core/src/types/tasks.ts
v-next/core/test/internal/tasks/builders.ts
v-next/core/test/internal/tasks/task-manager.ts

Closes https://github.com/NomicFoundation/hardhat/issues/5302

Add empty task builder

---

v-next/core/src/internal/tasks/task-manager.ts
v-next/core/src/types/tasks.ts
v-next/core/test/internal/tasks/task-manager.ts

Closes https://github.com/NomicFoundation/hardhat/issues/5333

Add root tasks getter

---

v-next/core/src/internal/tasks/task-manager.ts
v-next/core/test/internal/tasks/task-manager.ts
v-next/hardhat-errors/src/descriptors.ts

Closes https://github.com/NomicFoundation/hardhat/issues/5335

Add validation for positional parameter clashes with global parameters

---

v-next/core/src/internal/parameters.ts
v-next/core/src/internal/tasks/builders.ts
v-next/core/src/internal/tasks/resolved-task.ts
v-next/core/src/types/common.ts
v-next/core/test/internal/parameters.ts

Closes https://github.com/NomicFoundation/hardhat/issues/5303
Closes https://github.com/NomicFoundation/hardhat/issues/5304

Refactor parameter fns

---

v-next/example-project/hardhat.config.ts
v-next/hardhat-errors/README.md
v-next/hardhat-errors/src/errors.ts
v-next/hardhat-errors/src/index.ts
v-next/hardhat-errors/test/errors.ts
v-next/hardhat/package.json
v-next/hardhat/src/plugins.ts

Docs: https://www.notion.so/nomicfoundation/Community-Plugin-Error-f554a62cc8be4cc395e607725b8ab5b4
Part of https://github.com/NomicFoundation/hardhat/issues/5389

Add HardhatPluginError

---

docs/src/content/hardhat-runner/plugins/plugins.ts

Add @yankeguo/hardhat-trezor
---
I made a Hardhat plugin for integration with Trezor hardware wallet, thought that will be useful

Update plugins.ts, add @yankeguo/hardhat-trezor

---

v-next/hardhat/src/internal/cli/helpers/utils.ts
v-next/hardhat/test/internal/cli/helpers/getGlobalHelpString.ts
v-next/hardhat/test/internal/cli/helpers/getHelpString.ts
v-next/hardhat/test/internal/cli/helpers/utils.ts
v-next/hardhat/test/internal/cli/main.ts

Merge after https://github.com/NomicFoundation/hardhat/pull/5494
Closes https://github.com/NomicFoundation/hardhat/issues/5422

Sort help messages

---

v-next/core/src/internal/arguments.ts
v-next/core/test/internal/arguments.ts

allow empty arrays as default values for variadic arguments

---

v-next/core/test/internal/global-options.ts
v-next/hardhat-utils/src/string.ts
v-next/hardhat-utils/test/string.ts
v-next/hardhat/src/internal/cli/helpers/utils.ts
v-next/hardhat/test/internal/cli/helpers/utils.ts

Closes https://github.com/NomicFoundation/hardhat/issues/5465

Add camelToKebabCase to hardhat-utils

---

.changeset/rude-suits-add.md
packages/hardhat-core/src/internal/core/errors-list.ts

Small fix to fix confusing error message.

fix message for HH206

---

docs/src/content/hardhat-runner/docs/advanced/artifacts.md

Update artifacts.md to fix typos

---

.changeset/warm-beans-tie.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/hardhat-network/jsonrpc/handler.ts
pnpm-lock.yaml

Big JSON response fix for issue #3272

Add streaming response

---

v-next/example-project/viem-scketch-plugin.ts
v-next/hardhat-node-test-runner/package.json
v-next/hardhat/src/cli.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/hre.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/core/plugins/detect-plugin-npm-dependency-problems.ts

A few small optimizations in bootstrap time.
They can be reviewed 1 commit at the time.

Bootstrap time optimizations

---

.changeset/late-camels-bow.md
packages/hardhat-core/sample-projects/javascript-esm/ignition/modules/Lock.js
packages/hardhat-core/sample-projects/javascript/ignition/modules/Lock.js
packages/hardhat-core/sample-projects/typescript-viem/ignition/modules/Lock.ts
packages/hardhat-core/sample-projects/typescript/ignition/modules/Lock.ts

This is just an idea, feel free to rephrase or close.

Add link to Ignition docs in sample projects

---

docs/src/content/hardhat-runner/docs/guides/verifying.md
docs/src/content/ignition/docs/guides/create2.md
docs/src/content/ignition/docs/guides/ledger.md
docs/src/content/ignition/docs/guides/verify.md
docs/src/content/tutorial/deploying-to-a-live-network.md

---
This PR adds the [QuickNode Faucet](https://faucet.quicknode.com/) as an option faucet within the docs.

Add QuickNode Faucet

---

v-next/hardhat-test-utils/src/fs.ts
v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts

---
I found it helpful during the draft implementation of https://github.com/NomicFoundation/hardhat/pull/5774. I was also able to apply it to the tests of the console action, which is included in this PR.

feat: expose getTmpDir helper from the test utils

---

packages/hardhat-foundry/README.md
packages/hardhat-solpp/README.md

Hello
I fixed 2 minor spelling issues .
Br, Elias.

docs: fix spelling issues

---

docs/src/content/ignition/docs/guides/deploy.md

Supports https://github.com/NomicFoundation/hardhat-ignition/pull/819
I also added a small snippet about `JSON5` support

Add global parameters to docs

---

v-next/hardhat/src/config.ts
v-next/hardhat/src/hre.ts
v-next/hardhat/src/index.ts
v-next/hardhat/src/types/plugins.ts

Added an import statement to load type-extensions when the user imports hardhat/types/plugins.

Load type-extensions when the user imports hardhat/types/plugins

---

pnpm-lock.yaml
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
v-next/hardhat/test/internal/builtin-plugins/solidity-test/helpers.ts

---
This PR implements the suggestion from https://github.com/NomicFoundation/hardhat/pull/5829#issuecomment-2428688864 if we decide to proceed with it.

chore: simplify the test artifact discovery filter

---

.changeset/neat-moose-compare.md
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts

Fixes #5845 
A test validating the fix was added in https://github.com/NomicFoundation/edr/pull/710

fix: pass HTTP to EDR

---

v-next/hardhat-node-test-reporter/src/reporter.ts

---
This is a follow-up to the discussion that emerged under https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1729529455497859

chore: explicitly opt-in to node test events

---

v-next/hardhat/src/internal/builtin-plugins/artifacts/index.ts
v-next/hardhat/src/internal/builtin-plugins/clean/index.ts
v-next/hardhat/src/internal/builtin-plugins/console/index.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/index.ts
v-next/hardhat/src/internal/builtin-plugins/run/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts

This a cleanup PR, normalizing the name of the builtin plugins.

Normalize the builtin plugin names

---

v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat-test-utils/src/errors.ts
v-next/hardhat-test-utils/src/index.ts
v-next/hardhat-test-utils/test/errors.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
v-next/hardhat/test/internal/builtin-plugins/run/task-action.ts

This PR deletes some dead code and lets the errors thrown by the script bubble up. Previously we were catching them, just hiding useful info.

Small polishing changes

---

v-next/hardhat-ethers/src/internal/hardhat-ethers-provider/hardhat-ethers-provider.ts
v-next/hardhat-ethers/src/internal/signers/signers.ts
v-next/hardhat-ethers/src/types.ts
v-next/hardhat-ethers/test/plugin-functionalities.ts

Add the missing types `HardhatEthersProvider` and `HardhatEthersSigner` and modify code accordingly

Add missing interfaces for hardhat-ethers

---

v-next/hardhat/console.sol
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts

Fixes #5904
This is a quickfix, we should improve it after the alpha.

[quickfix] Add console.sol support

---

v-next/hardhat-zod-utils/src/index.ts
v-next/hardhat-zod-utils/test/index.ts

Workaround of https://github.com/colinhacks/zod/issues/2940#issuecomment-2380836931
This is not a complete workaround, but good enough for what we need.

Fix the unionType zod helper

---

v-next/hardhat/src/internal/cli/error-handler.ts
v-next/hardhat/src/internal/cli/init/init.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/cli/node-version.ts

This PR improves some error messages and situations that can be common during the alpha

Errors and messages improvements

---

pnpm-lock.yaml
v-next/hardhat/package.json

---
https://nomicfoundation.slack.com/archives/C03UN893ZT4/p1730368126071559
This release contains a fix for - https://github.com/NomicFoundation/edr/issues/701

chore: upgrade edr to v0.6.4-alpha.1

---

v-next/hardhat/templates/node-test-runner-viem/README.md
v-next/hardhat/templates/node-test-runner-viem/hardhat.config.ts
v-next/hardhat/templates/node-test-runner-viem/scripts/deploy-counter-contract.ts
v-next/hardhat/templates/node-test-runner-viem/scripts/send-op-tx.ts

Pull across the example script showing sending a tx against Optimism into the viem template.

chore: add optimism example script to viem template

---

.changeset/five-eagles-confess.md
packages/hardhat-core/package.json
pnpm-lock.yaml

Bump EDR to 0.6.5 (https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%40). 
This fixes the following issue:
* https://github.com/NomicFoundation/edr/issues/727

fix: bump EDR to 0.6.5

---

docs/src/content/ignition/docs/guides/error-handling.md

Fixing a small typo in the hardhat ignition documentation

fixed small typo

---

docs/pnpm-lock.yaml
docs/src/content/ignition/docs/reference/_dirinfo.yaml
docs/src/content/ignition/docs/reference/cli-commands.md

resolves https://github.com/NomicFoundation/hardhat-ignition/issues/831
Added reference docs for the CLI commands available within Hardhat Ignition

Add reference docs for CLI commands

---

docs/src/content/ignition/docs/guides/ledger.md

---
The suggested import statement for typescript does not work. A space was missing after the import token.

fix ts import for hardhat-ledger package

---

docs/src/content/hardhat-runner/plugins/plugins.ts
e2e/fixture-projects/vars/test.sh

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `Debuggin` to `Debugging`
Corrected `compilcation` to `compilation`
Corrected `configuartion` to `configuration`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

.changeset/flat-hornets-yell.md
packages/hardhat-verify/src/internal/chain-config.ts

---
Ink Mainnet information to allow Ink developers to build on Ink while using Hardhat

Adding in Ink Mainnet network information

---

v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/subprocess.ts

---
Closes #6222
TODOs:
- See https://github.com/NomicFoundation/hardhat/pull/6225#discussion_r1941965616 for more details.
Follow-up work items:
- Only Sentry team admins/moderators can set up alerts and I am not one. 
- The alerting rule should be added here: https://nomic-labs.sentry.io/alerts/rules/?project=4507685793103872&statsPeriod=1h&utc=true
- It should be similar to the one we have configured for Hardhat v2: https://nomic-labs.sentry.io/alerts/rules/buidler/1079337/details/

feat: hook up global exception handler in Hardhat 3

---

v-next/hardhat/src/internal/cli/node-version.ts
v-next/hardhat/test/internal/cli/node-version.ts

Fixed the version check logic and added some tests.
Closes #6013

Fix node version check

---

v-next/hardhat/src/internal/cli/init/init.ts
v-next/hardhat/src/internal/cli/init/prompt.ts
v-next/hardhat/test/internal/cli/init/init.ts

feat: turn package into esm on init

---

v-next/hardhat/src/internal/builtin-plugins/flatten/index.ts
v-next/hardhat/src/internal/cli/init/prompt.ts
v-next/hardhat/test/internal/cli/main.ts

This PR:
* Changes the default value of the prompt to set the project as esm.
* Shortens the description of `flatten` so that it fits in a single line

Two small improvements

---

.github/ISSUE_TEMPLATE/hardhat-3-alpha.yml
docs/src/config.ts

Turn off the Solidity Developer Survey banner.

chore: switch the website banner back from survey to hiring

---

v-next/hardhat/src/internal/cli/init/init.ts

---
https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1739875490755799

fix: prompt to turn the project into esm

---

v-next/hardhat/src/internal/cli/init/prompt.ts

chore: remove duplicate package.json from the esm prompt

---

v-next/hardhat-ignition/src/index.ts
v-next/hardhat-ignition/src/internal/tasks/visualize.ts
v-next/hardhat-ignition/test/plan/index.ts

We will bring this back with the bug fix.

chore: set visualize as not implemented

---

v-next/hardhat-utils/src/internal/request.ts
v-next/hardhat-utils/test/request.ts

fix: return only origin in sanitizeUrl to prevent leaks

---

package.json
packages/hardhat-ignition-ui/package.json
pnpm-lock.yaml

this fixes https://github.com/NomicFoundation/hardhat/issues/6291 but for v2

Update mermaid version (v2)

---

.changeset/olive-lobsters-carry.md
pnpm-lock.yaml
v-next/hardhat-ignition-ui/package.json
v-next/hardhat-ignition/src/index.ts
v-next/hardhat-ignition/src/internal/tasks/visualize.ts

fixes https://github.com/NomicFoundation/hardhat/issues/6291

update mermaid version and re-enable visualize task (v3)

---

packages/hardhat-core/src/internal/core/config/default-config.ts
packages/hardhat-web3-v4/README.md

This PR addresses the following issues:
- Fixed a broken link in `default-config.ts` related to the EthereumJS monorepo.
- Updated a broken link in the `README.md` for the `hardhat-web3-v4` plugin documentation.

fix: 404 links

---

.changeset/slow-lobsters-watch.md
v-next/hardhat-ignition-ui/src/main.css

fixes https://github.com/NomicFoundation/hardhat/issues/6409 for v3

Fix for mermaid centering on v3

---

v-next/hardhat/src/internal/cli/init/init.ts
v-next/hardhat/test/internal/cli/init/init.ts

---
This is a follow-up based on the comment here - https://github.com/NomicFoundation/hardhat/pull/6426#discussion_r1979582780

fix: test the shouldUpdateDependency helper thoroughly

---

.changeset/metal-kings-hide.md
packages/hardhat-ignition-ui/src/main.css

fixes https://github.com/NomicFoundation/hardhat/issues/6409

Override max-width to fix ignition graph centering

---

packages/hardhat-ledger/README.md

Hey, I read the documentation and found a non-working link - fixed

fix dead link README.md

---

.changeset/smooth-pigs-sniff.md
scripts/setup.sh
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts

Fix infinite loop in `SolcConfigSelector`

---

.changeset/angry-panthers-brush.md
v-next/hardhat/src/internal/config-loading.ts

Fixes https://github.com/NomicFoundation/hardhat/issues/6407.

Hardhat v3 not compatible with vitest

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers-array.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/hd-wallet-handler.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts

---
This resolves https://github.com/NomicFoundation/hardhat/issues/6211. The agreed resolution is to leave the imports as is for now and add comments warning about adding more imports of the handlers that are expensive to import.

chore: add comments explaining slow handlers imports

---

.github/config/regression-tests.yml
.github/workflows/regression-tests.yml
.gitignore

This is needed to enable the workflow added in #6500.

feat: implement automated regression tests (cherry-pick on the default branch)

---

.changeset/silly-seals-provide.md
packages/hardhat-ignition-core/src/internal/chain-config.ts

adds arbitrum sepolia to ignition chain config

Add arbitrum sepolia to chain config

---

.changeset/serious-rice-invent.md
v-next/hardhat-utils/src/fs.ts
v-next/hardhat-utils/test/fs.ts
v-next/hardhat-utils/test/lang.ts

---
- Added `retryDelay: 300` to the remove function to prevent Windows GitHub Action EBUSY errors
- added test
resolve #5602

test: add busy error handling for remove funtion on Windows platform

---

.changeset/funny-points-prove.md
v-next/hardhat/.gitignore
v-next/hardhat/src/internal/builtin-plugins/coverage/index.ts
v-next/hardhat/src/internal/builtin-plugins/coverage/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/coverage/type-extensions.ts
v-next/hardhat/test/internal/cli/main.ts
v-next/hardhat/test/internal/hre-intialization.ts

---
Resolves https://github.com/NomicFoundation/hardhat/issues/6579
This PR defines a global --coverage flag and removes unused coverage task.
It is a part of coverage support initiative - https://github.com/NomicFoundation/hardhat/issues/5648

feat: add a global --coverage flag which enables coverage

---

.changeset/weak-starfishes-brush.md
pnpm-lock.yaml
v-next/hardhat-zod-utils/src/index.ts
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-context.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/hardfork.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/hardfork.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
v-next/hardhat/src/types/utils.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts

Updates to @ignored/edr-optimism@0.10.0-alpha.1

build: upgrade to @ignored/edr-optimism@0.10.0-alpha.1

---

.changeset/slimy-pots-applaud.md
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/src/internal/cli/init/init.ts
v-next/hardhat/test/internal/cli/init/init.ts

Fixes https://github.com/NomicFoundation/hardhat/issues/6545

Create folder if not exists during `--init` 

---

.changeset/famous-cooks-leave.md
v-next/hardhat/src/internal/builtin-plugins/node/json-rpc/handler.ts
v-next/hardhat/test/internal/builtin-plugins/node/json-rpc/handler.ts

resolves https://github.com/NomicFoundation/hardhat/issues/6532

Allow undefined params in JSON RPC handler

---

.changeset/orange-beans-buy.md
v-next/hardhat-ignition/src/internal/tasks/deploy.ts
v-next/hardhat-ignition/test/deploy/build-profile.ts
v-next/hardhat-ignition/test/fixture-projects/create2-bad-config/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/create2-exists-chain/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/create2-not-exists-chain/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/lock/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/minimal/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/multiple-contracts-with-same-name/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/reset-flag/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/user-modules/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/verify-no-api-key/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/with-config/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/with-invalid-config/hardhat.config.js
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/tasks/compile.ts
v-next/hardhat/test/internal/hre-initialization.ts

resolves https://github.com/NomicFoundation/hardhat/issues/6313

Default to production builds for ignition deploy 

---

.changeset/sixty-sloths-cheer.md
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/main.ts

resolves https://github.com/NomicFoundation/hardhat/issues/6671

Support options with equals signs

---

v-next/hardhat-node-test-reporter/integration-tests/README.md
v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/assert-test/assert.ts
v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/assert-test/result.svg
v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/assert-test/result.txt

---
Related to https://github.com/NomicFoundation/hardhat/issues/6688
This adds an integration test to our node test reporter which showcases the outputs produced by different types of assertions.
Please note, it does not address the related issue, it only adds a test case that uses the constructs mentioned in the issue to provide the base for the analysis.

test: add integration test for assertions in node test reporter

---

.github/workflows/release.yml

---
This addresses the issue found in https://github.com/NomicFoundation/hardhat/actions/runs/15024744516/job/42222613409

ci: grant release workflow id-token write permission

---

.changeset/sixty-socks-roll.md
v-next/hardhat-utils/src/fs.ts
v-next/hardhat-utils/test/fs.ts

Just a tiny PR that I'll use in another one.

Add a `directoryFilter` param to `getAllFilesMatching`

---

pnpm-lock.yaml
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts

I upgraded to `@ignored/edr-optimism` v0.13.0-alpha.3, which overhauls the `ProviderConfig` and `ForkConfig` to conform to allow HH3 to change which configuration options are exposed (see [diff](https://github.com/NomicFoundation/edr/pull/910/files#diff-3d66d48b2152de2af1c1180a75611835ab6f70c0e448f4a53acf1e128f52000f)).

build: upgrade to edr-0.13.0-alpha.3

---

.changeset/eight-buckets-know.md

---
Changesets action panics when it finds a changeset for ignored packages - see https://github.com/NomicFoundation/hardhat/actions/runs/15189994595/job/42767540652
As a follow-up, we should ensure that this is caught by the PR checks i.e. in a PR, we should not only check that a changeset exists, but also if it is valid. Here's the issue for this: https://github.com/NomicFoundation/hardhat/issues/6737

chore: remove ignored packages from changesets

---

.changeset/sixty-beans-pretend.md

Improve the text of the changesets in preparation for release.

chore: update the changelog text in preparation for release

---

.changeset/chilly-nails-return.md
v-next/hardhat/src/internal/core/tasks/builders.ts
v-next/hardhat/src/types/tasks.ts
v-next/hardhat/test/internal/core/tasks/builders.ts

Fixes: https://github.com/NomicFoundation/hardhat/issues/6719

emptyTask should not require a description

---

packages/hardhat-ethers/src/internal/type-extensions.ts

delete wrong comment

---

.changeset/nine-rivers-promise.md
v-next/hardhat/eslint.config.js
v-next/hardhat/package.json
v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
v-next/hardhat/templates/01-node-test-runner-viem/test/Counter.ts
v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
v-next/hardhat/templates/02-mocha-ethers/test/Counter.ts

Enabled linting for template projects. Prettier formatting was already enabled.
I've overriden a few rules that made sense, I'm open to feedback on these.
Closes #6715

Linting for template projects

---

.changeset/nervous-gorillas-mix.md
v-next/hardhat-viem-assertions/src/internal/assertions/emit/emit-with-args.ts
v-next/hardhat-viem-assertions/test/internal/assertions/emit/emit-with-args.ts

Fixes https://github.com/NomicFoundation/hardhat/issues/6771

Viem assertion viem.assertions.emitWithArgs only looks at the first event

---

.changeset/nervous-gorillas-mix.md
.changeset/nine-rivers-promise.md
.changeset/witty-pots-fold.md

Update the changeset's text in preparation for the next release.

chore: update the text of the latest changesets

---

v-next/hardhat-ignition/test/test-helpers/wait-for-pending-txs.ts
v-next/hardhat-keystore/test/loaders/keystore-file-loader.ts
v-next/hardhat-network-helpers/test/index.ts
v-next/hardhat-toolbox-mocha-ethers/test/fixture-projects/toolbox/scripts/script.ts
v-next/hardhat-toolbox-viem/test/fixture-projects/toolbox/scripts/script.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compiler/solcjs-runner.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/gas/automatic-gas-price-handler.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/gas/fixed-gas-handler.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/gas/fixed-gas-price-handler.ts
v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/solc-config-selection.ts
v-next/hardhat/test/internal/cli/init/init.ts
v-next/hardhat/test/utils.ts

Fixed multiple floating promises

Debugging CI issue #6848

---

.changeset/clean-spies-fail.md
v-next/hardhat-keystore/src/index.ts
v-next/hardhat-keystore/src/internal/tasks/path.ts
v-next/hardhat-keystore/test/integration/tasks.ts
v-next/hardhat-keystore/test/tasks/path.ts

Fixes https://github.com/NomicFoundation/hardhat/issues/6872

Add task to hardhat-keystore to show path to keystore file

---

.changeset/gold-cows-provide.md
v-next/hardhat-mocha/src/hookHandlers/test.ts
v-next/hardhat-mocha/test/registerFileForTestRunner.ts
v-next/hardhat-node-test-runner/src/hookHandlers/test.ts
v-next/hardhat-node-test-runner/test/fixture-projects/test-project/hardhat.config.ts
v-next/hardhat-node-test-runner/test/fixture-projects/test-project/package.json
v-next/hardhat-node-test-runner/test/fixture-projects/test-project/test/test.ts
v-next/hardhat-node-test-runner/test/registerFileForTestRunner.ts

Allow js/ts test runners to run test files outside their configured paths

---

.changeset/fluffy-glasses-beam.md

Fix a changeset that includes a private package.

Fix a changeset

---

.changeset/loud-buses-wave.md
v-next/hardhat/src/internal/builtin-global-options.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/help/get-global-help-string.ts
v-next/hardhat/test/internal/cli/main.ts

---
As per https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1751544724288539

feat: allow requesting help via the -h flag

---

.changeset/common-planes-enjoy.md

fix: change the changeset level to patch on edr version bump

---

.changeset/green-hornets-joke.md
.changeset/long-bats-nail.md
.changeset/loud-buses-wave.md
.changeset/sixty-phones-juggle.md
.changeset/tough-rice-jam.md
.changeset/twenty-lies-destroy.md

Update changesets in preparation for release.

chore: update changesets in prep for release

---

.github/workflows/regression-tests.yml

---
These changes allow:
- forcing output colorization (we're using it to visually test test ui, see https://github.com/NomicFoundation/hardhat/actions/runs/16570254685/job/46860391744)
- passing task arguments to supported commands (e.g. `hardhat test solidity -vvvvv` is now accepted and executed as `hardhat test solidity` would, just with an extra argument)

ci: regression tests framework improvements

---

.changeset/fuzzy-peas-occur.md
packages/hardhat-viem/src/internal/chains.ts
packages/hardhat-viem/src/internal/errors.ts
packages/hardhat-viem/test/chains.ts

Closes https://github.com/NomicFoundation/hardhat/issues/7065

Fixed "Multiple networks with chain id found" error when multiple chains share the same chain id

---

CONTRIBUTING.md

`CONTRIBUTE.md` updated to reflect the V3 code. Small checklist added for contributing new changes.

Contributing update v3

---

.changeset/pink-crabs-bow.md
v-next/hardhat-ignition-core/test/helpers/execution-result-fixtures.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-profiles.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/config.ts
v-next/hardhat/test/internal/builtin-plugins/solidity/config.ts

This PR improves how build profiles are created. Key changes:
- Removed unused profiles.  
- Added `outputSelection` to all `SolcConfig` settings to ensure consistency.  
- For the `production` profile, added optimization defaults to the `SolcConfig`.  
- Updated how production profiles are derived from the default profile, ensuring only the `version` is carried over.

Solidity Config Resolution Enhancements

---

.changeset/green-peas-grow.md
v-next/hardhat/src/internal/cli/telemetry/sentry/anonymize-paths.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/anonymizer.ts
v-next/hardhat/test/internal/cli/telemetry/sentry/anonymize-paths.ts
v-next/hardhat/test/internal/cli/telemetry/sentry/anonymizer.ts

Improves how we anonymize paths, so that we maintain as much non-private information as possible, especially from dependency files.

Better path anonymization

---

.github/config/regression-tests.yml

---
This PR updates regression tests config after `solidityTest` hardhat config key was renamed to `test.solidity`.
In preparation of the PR, I removed the test exclusions that I applied before when the suite was running effectively without solidity test config and reapplied only the exclusions that were still needed.
Noteworthy, we no longer see OOM in solady, timeouts in lockup nor fs access related errors.

ci: update regression tests config

---

v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts

---
As a follow up from https://github.com/NomicFoundation/hardhat/pull/7196, relax the FFI error message check to make it compatible with an upcoming change in EDR that removes the reference to CLI flag:
https://github.com/NomicFoundation/edr/pull/1054

chore: relax ffi error check

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts

Fixes: https://github.com/NomicFoundation/hardhat/issues/7235
Task created to track the lack of tests for EDR configuration: https://github.com/NomicFoundation/hardhat/issues/7250

loggingEnabled is ignored by EDR

---

.github/workflows/release.yml

chore: fix changeset PR creation

---

.changeset/hip-knives-pull.md
archive/hardhat-ledger/README.md
v-next/example-project/hardhat.config.ts
v-next/hardhat-keystore/src/index.ts
v-next/hardhat/src/internal/builtin-global-options.ts
v-next/hardhat/src/internal/builtin-plugins/clean/index.ts
v-next/hardhat/src/internal/builtin-plugins/console/index.ts
v-next/hardhat/src/internal/builtin-plugins/flatten/index.ts
v-next/hardhat/src/internal/builtin-plugins/node/index.ts
v-next/hardhat/src/internal/builtin-plugins/run/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/index.ts
v-next/hardhat/src/internal/builtin-plugins/telemetry/index.ts
v-next/hardhat/src/internal/builtin-plugins/test/index.ts
v-next/hardhat/test/fixture-projects/run-js-script/hardhat.config.js
v-next/hardhat/test/fixture-projects/run-ts-script/hardhat.config.ts
v-next/hardhat/test/internal/cli/help/get-global-help-string.ts
v-next/hardhat/test/internal/cli/main.ts
v-next/hardhat/test/internal/example-mock-artifacts-plugin-using-test.ts

Unify the phrasing of help messages for commands and options in the Hardhat CLI UI.

Descriptions unified for built-in commands and options

---

.changeset/add-linea-chain-support.md
v-next/hardhat-ignition-core/src/internal/chain-config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/chain-descriptors.ts

---
#7357 #7370 Add Linea network support for contract verification (Chain IDs: 59144 mainnet, 59141 Sepolia testnet)

feat: add Linea network support for contract verification
