NomicFoundation/hardhat

packages/hardhat-core/src/internal/hardhat-network/provider/context/edr.ts
packages/hardhat-core/src/internal/hardhat-network/provider/miner/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/block-builder/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/dual.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/edr.ts
yarn.lock

I noticed while doing performance testing that the global EDR context is initialized even in `ethereumjs` mode. This is undesirable as we don't want to run Rust code unless the experimental VM flag is set to `edr`. I fixed it by making the global EDR context initialization lazy.

fix: lazy init global edr context

---

docs/src/content/ignition/docs/guides/creating-modules.md
docs/src/content/ignition/docs/guides/tests.md

We use both _method_ and _function_ in the Hardhat Ignition docs. We apply the rule:
* If referring to a Solidity contract the term is `function`
* If referring to a JS standalone function the term is `function`
* If referring to a JS function accessed through an object (e.g. `ignition.deploy`) the term is `method`

docs: use the word function/method consistently

---

docs/src/content/hardhat-runner/docs/guides/deploying.md

The deploying contracts guide has been changed to suggest Hardhat Ignition rather than Hardhat deploy.
We have a tip at the start to encourage use of Hardhat Ignition.

docs: add Ignition tip to deploying contracts guide

---

docs/src/content/ignition/docs/guides/creating-modules.md

This PR modifies the file: docs/src/content/ignition/docs/guides/creating-modules.md
Added the square brackets that were missing for the arguments while deploying the contract.

added missing square brackets for args

---

crates/edr_rpc_server/src/node.rs
crates/edr_rpc_server/src/server.rs

Refactor the RPC handler to move values from the request to the handlers thus eliminating some unnecessary clones.

refactor: eliminate unnecessary clones during request handling

---

.changeset/tough-geese-tie.md
packages/hardhat-vyper/src/downloader.ts

The latest releases of Vyper include tag names like "v0.3.10rc5" which are not valid semver strings. This was causing the downloder to fail when calling semver.eq. This fixes this by previously checking that the tag_name is a valid semver string.
EDIT: that kind of version string is valid for [PEP 440](https://peps.python.org/pep-0440/) but it's not for semver.
[PEP 440](https://peps.python.org/pep-0440/#pre-release-separators):
> Pre-releases should allow a ., -, or _ separator between the release segment and the pre-release segment. The normal form for this is without a separator.
[Semver](https://semver.org/#spec-item-9):
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

Fix vyper downloader

---

packages/hardhat-vyper/src/downloader.ts

Cherry picking the fix from https://github.com/NomicFoundation/hardhat/pull/4552 to `edr/main` to fix CI failures such as https://github.com/NomicFoundation/hardhat/actions/runs/6728124285/job/18294392642?pr=4553

fix: vyper downloader in `edr/main`

---

packages/hardhat-verify/README.md

---
Add the Sourcify snippet example in "Advanced Usage: Using the Etherscan and Sourcify classes from another plugin" into the `hardhat-verify`'s readme

add Sourcify example in "Advanced Usage" in readme

---

packages/hardhat-core/test/internal/cli/vars/vars.ts

PROBLEM
4 tests are failing in the GitHub CI because a few messages are only printed when 'process.stdout.isTTY' is true.
And in the CI this condition is false.
SOLUTION
Also add the 'process.stdout.isTTY' check in the tests.
Related to PR: https://github.com/NomicFoundation/hardhat/pull/4446

Configuration variables: fix the failing CI tests caused by process.stdout.isTTY

---

.changeset/eleven-pears-accept.md
packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
packages/hardhat-ethers/test/hardhat-ethers-provider.ts

Fixed blockTag bug on contract lookup

---

.changeset/small-crews-kiss.md
packages/hardhat-core/src/builtin-tasks/compile.ts
packages/hardhat-core/src/internal/solidity/compiler/downloader.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/compilation.ts
packages/hardhat-core/test/internal/solidity/compiler/downloader.ts
packages/hardhat-core/test/internal/solidity/compiler/index.ts

See issue: https://github.com/NomicFoundation/hardhat/issues/4490
PROBLEM
If multiple requests to download the same version of a compiler are sent, the download occurs multiple times.
SOLUTION
Modify the existing mutex logic to check if a compiler of a specific version has already been downloaded or is currently being downloaded.

Bug in compilation when multiple versions are used with many contracts 

---

crates/edr_eth/src/access_list.rs
crates/edr_eth/src/remote/eth.rs
crates/edr_eth/src/transaction/signed.rs
crates/edr_evm/src/transaction/pending.rs
crates/edr_provider/src/data.rs
crates/edr_provider/src/lib.rs
crates/edr_provider/src/requests/eth/transactions.rs

Add `eth_getTransactionByHash` to the EDR provider:
- Follows Hardhat RPC logic.
- The provider implementation is tested, the RPC logic is waiting to be tested with Hardhat integration tests once those are wired in.
- Some tangential, but necessary changes included.

feat: add `eth_getTransactionByHash` support

---

.changeset/old-phones-live.md
packages/hardhat-core/src/internal/core/providers/gas-providers.ts
packages/hardhat-core/test/internal/core/providers/gas-providers.ts

Closes #4190.
If the computation over the `eth_feeHistory` result results in a max priority fee of 0, we try to use the result of `eth_maxPriorityFeePerGas`. If that method doesn't exist, we use 1.
I should mention that I _couldn't_ reproduce this issue, because right now Base goerli has enough activity to not trigger this. But this change is low-risk, since the new code is only executed when the inferred max priority fee is 0.
Another way in which this is not ideal is that we are only using `eth_maxPriorityFeePerGas` when the estimation is 0. Perhaps ideally we should always use it? But this is a way bigger change that I can't investigate right now. I'm going to create follow-up issues for this.

Avoid using a maxPriorityFeePerGas of 0

---

docs/src/content/hardhat-runner/docs/reference/stability-guarantees.md

Fix dead link to node releases

Update stability-guarantees.md: fix broken link

---

.github/dependabot.yml
.github/workflows/check-docs-site.yml
.github/workflows/compile-with-typescript-v4.yml
.npmrc
docs/package.json
package.json

Some things we missed when we migrated to pnpm.
Some comments:
- I removed the `only-allow` script because it adds 6 seconds to each installation. This can be improved by adding `only-allow` as a dev dependency itself, so that this cost is only paid the first time... but I'd rather just remove it; I don't think it's worth it.
- Dependabot supports pnpm, but (as far as I understand) it auto-detects it; the setting has to be `npm` anyway because the setting is about the ecosystem, not about the package manager.

Fixes related to the pnpm migration

---

crates/edr_eth/src/remote/client.rs
crates/edr_evm/src/blockchain.rs
crates/edr_evm/src/blockchain/forked.rs
crates/edr_evm/src/blockchain/local.rs
crates/edr_provider/src/data.rs
crates/edr_provider/src/error.rs
crates/edr_provider/src/lib.rs
crates/edr_provider/src/requests/eth/blockchain.rs
crates/edr_provider/src/requests/eth/web3.rs
crates/edr_provider/src/requests/hardhat.rs
crates/edr_provider/src/requests/hardhat/config.rs
crates/edr_rpc_hardhat/src/lib.rs
crates/edr_rpc_hardhat/src/metadata.rs
crates/edr_rpc_hardhat/tests/hardhat.rs

As part of this change, I made the `network_id` a `u64` as there was no need for it to support up to `U256`. It's represented as a string decimal in the JSON-RPC. The `U64` allows deserialization of these values too, making it a convenient helper.

feat: add hardhat config RPC methods

---

crates/edr_eth/src/remote/client.rs

Follow up from https://github.com/NomicFoundation/hardhat/pull/4588 to prevent cache entries with an invalid type permanently crashing the application. A cache item can have an invalid type for example if we add a new field to a cached type. 
The PR fixes this by deleting cache items with an invalid type upon deserialization. Single calls make a remote query if this happens. Batch calls fail first, but in subsequent batch calls, it'll be a cache miss and work on the second try. We cannot do better for batch calls without major refactoring due to the logical separation between fetching batch items and deserializing them (which is done in order to let us support heterogeneous calls in a fairly straightforward way).
I also removed some client tests that seemed superfluous in order to save on …

fix: delete cache entry for invalid type entries

---

crates/edr_eth/src/remote.rs
crates/edr_eth/src/remote/client.rs
crates/edr_eth/src/remote/eth.rs
crates/edr_eth/src/remote/methods.rs
crates/edr_eth/tests/integration_tests.rs
crates/edr_eth/tests/receipt.rs
crates/edr_eth/tests/transaction.rs
crates/edr_evm/benches/state/util.rs
crates/edr_evm/src/block.rs
crates/edr_evm/src/block/local.rs
crates/edr_evm/src/block/remote.rs
crates/edr_evm/src/blockchain/remote.rs
crates/edr_evm/src/state/fork.rs
crates/edr_evm/src/state/remote.rs
crates/edr_provider/src/data.rs
crates/edr_provider/src/error.rs
crates/edr_provider/src/lib.rs
crates/edr_provider/src/requests/eth.rs
crates/edr_provider/src/requests/eth/blocks.rs
crates/edr_provider/src/requests/eth/transactions.rs

Adds `eth_getBlockByNumber` support to the EDR provider, matching the Hardhat implementation. 
Hardhat integration tests are passing up to the point where they need `eth_sendTransaction`.

feat: add `eth_getBlockByNumber` support

---

crates/edr_eth/src/remote/methods.rs
crates/edr_eth/tests/integration_tests.rs
crates/edr_provider/src/data.rs
crates/edr_provider/src/lib.rs
crates/edr_provider/src/requests/eth/blocks.rs

Add support for 
- eth_getBlockByHash ([source](https://github.com/NomicFoundation/hardhat/blob/7dd2586cf5be393492f70adb176ab85a6e79b792/packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts#L500))
- eth_getBlockTransactionCountByHash ([source](https://github.com/NomicFoundation/hardhat/blob/7dd2586cf5be393492f70adb176ab85a6e79b792/packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts#L564))
- eth_getBlockTransactionCountByNumber ([source](https://github.com/NomicFoundation/hardhat/blob/7dd2586cf5be393492f70adb176ab85a6e79b792/packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts#L583))

Add get block by hash and block transaction count methods

---

crates/edr_provider/src/requests/eth/blocks.rs
crates/edr_provider/src/requests/eth/transactions.rs

There is no point of passing the entire `data` anymore to `transaction_to_rpc_result` so just pass the spec id.

refactor: pass spec id instead of data to transaction to rpc result

---

docs/redirects.config.js

Closes https://github.com/NomicFoundation/hardhat/issues/4623
This broke after I moved the guide from the normal guides to the advanced guides.

Add redirect for hh-waffle guide

---

.changeset/friendly-dryers-mix.md
.changeset/shaggy-hornets-exercise.md
packages/hardhat-core/src/builtin-tasks/test.ts
packages/hardhat-core/src/internal/core/project-structure.ts
packages/hardhat-core/src/internal/core/typescript-support.ts

This is part of the effort to support ESM in TypeScript projects. As the Hardhat config file needs to be a CommonJS module, users will need to change the extension to `.cts`. This PR enables Hardhat to read the config from a `.cts` file.

Add experimental support for using ESM modules with TypeScript

---

.changeset/dry-moose-draw.md
packages/hardhat-core/src/internal/artifacts.ts

Resolved an issue where `artifacts/package.json` was mistakenly identified and pruned as an artifact in the `TASK_COMPILE_REMOVE_OBSOLETE_ARTIFACTS` subtask. This update ensures the file is preserved, as it is required to provide ESM support in `hardhat-viem`.

Exclude artifacts/package.json from artifacts in getArtifactPaths

---

.changeset/odd-cooks-wait.md
packages/hardhat-viem/src/internal/contracts.ts
packages/hardhat-viem/src/types.ts

This PR fixes this issue - https://github.com/NomicFoundation/hardhat/issues/4624
I want to configure client with `hre.viem.getWalletClient` and then get contract API with `hre.viem.getContractAt` by passing `GetContractAtConfig` from `@nomicfoundation/hardhat-viem/src/types`
It's possible to configure only `walletClient` in `GetContractAtConfig` but for `watchEvent` method it's required to have `publicClient` configured.
If you are trying to use hardhat without specifying `--network` - you won't get any events
Add `publicClient` to `getContractAtConfig` and use this client in `getContractAt` function. This would allow to use read methods of the contract with any configuration.

Add configurable public client to getContractAt, deployContract and sendDeploymentTransaction

---

Cargo.lock
crates/edr_evm/src/block/builder.rs
crates/edr_evm/src/debug_trace.rs
crates/edr_evm/src/evm.rs
crates/edr_evm/src/inspector.rs
crates/edr_evm/src/miner.rs
crates/edr_evm/src/runtime.rs
crates/edr_evm/src/transaction.rs
crates/edr_napi/index.d.ts
crates/edr_napi/src/miner.rs
crates/edr_napi/src/provider.rs
crates/edr_napi/src/runtime.rs
crates/edr_napi/src/threadsafe_function.rs
crates/edr_provider/Cargo.toml
crates/edr_provider/src/data.rs
crates/edr_provider/src/data/inspector.rs
crates/edr_provider/src/lib.rs
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts

- Supports collecting `console.log` calls from Solidity in the EDR provider when mining a block or running a call.
- The call data is passed as a buffer to a JS callback. Decoding, formatting and logging is handled on the JS side.
- There are automated tests on the Rust side to make sure that the `console.log` calls are recorded.
- We tested the JS side manually.

feat: collect solidity `console.log` messages

---

docs/src/content/ignition/docs/guides/deploy.md

there is a small typo (igntion) in this command "npx hardhat igntion deploy ignition/modules/MyModule.js"
---

fix typo of ignition

---

docs/src/content/ignition/docs/getting-started/index.md
docs/src/content/ignition/docs/guides/_dirinfo.yaml
docs/src/content/ignition/docs/guides/tests.md
docs/src/content/ignition/docs/guides/viem.md

Add a guide to installing and using the `@nomicfoundation/hardhat-ignition-viem` package and its support for returning Viem contract instances from the Ignition Helper.

docs: add a `using viem` guide to Ignition

---

docs/src/content/hardhat-runner/docs/config/index.md

As title. I wanted to understand Hardat's default values for the Solidity settings and realised it's still pointing to an old version that doesn't entail attributes like `viaIR` etc.

Update Standard JSON Input Link

---

packages/hardhat-core/.prettierignore
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/isEdrProvider.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/retrieveCommon.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/web3.ts

Enable Web3 module tests. After discussion with @fvictorio we settled on returning version strings of this format for the EDR provider: `HardhatNetwork/2.19.0/@nomicfoundation/edr/0.2.0-dev`

ci: enable web3 module tests

---

crates/edr_eth/src/remote.rs
crates/edr_eth/src/remote/cacheable_method_invocation.rs
crates/edr_eth/src/remote/client.rs
crates/edr_eth/src/remote/eth.rs
crates/edr_eth/src/remote/eth/call_request.rs
crates/edr_eth/src/remote/eth/get_logs.rs
crates/edr_eth/src/remote/methods.rs
crates/edr_eth/src/remote/request_methods.rs
crates/edr_eth/tests/integration_tests.rs
crates/edr_provider/src/requests/eth/call.rs
crates/edr_provider/src/requests/validation.rs

Add client request type as the first step towards https://github.com/NomicFoundation/edr/issues/256
I ended up naming the client request type `RequestMethod` instead of the discussed `Request`, as the latter conflicts with the name of the struct that represents a JSON-RPC request (version + method + id) in the client.

refactor: add client request type

---

docs/src/content/hardhat-chai-matchers/docs/reference.md

The sample code for .emit that uses .withArgs was incorrect, so it has been corrected.
What should have been written as .emit was instead written as .revertedWithCustomError.

Update reference.md to correct mistakes in sample code.

---

packages/hardhat-core/src/internal/hardhat-network/stack-traces/solidity-errors.ts

Adapt the `SolidityCallSite` class to properly implement the latest version of `NodeJS.CallSite`.
Notice that there are three different changes here:
- A change in the return value of `getScriptNameOrSourceURL`. This function wasn't even present in the type definition of `@types/node@16` so I'm not sure why it was there. Maybe it was removed and re-added with a different return type? Anyway, I think we can assume no one was using it.
- New methods (`getScriptHash`, `getEnclosingColumnNumber` and `getEnclosingLineNumber`). If some consumer was calling those methods, then that would've resulted in an error, so we can assume that they were not being used. (You could argue that maybe someone was checking if they existed, but that's a long shot, especially for such an internal object.)
- An …

Fix compilation error with latest @types/node

---

docs/src/content/hardhat-runner/docs/getting-started/index.md

---
The code provided for `scripts/deploy.ts` has the `lockedAmount` set to `0.001`. However, the example output provided shows this as `1 ETH` instead of `0.001ETH`.

Docs: update lockedAmount

---

crates/edr_evm/src/transaction/pending.rs
crates/edr_provider/src/data.rs
crates/edr_provider/src/data/call.rs
crates/edr_provider/src/data/gas.rs
crates/edr_provider/src/requests/eth/call.rs
crates/edr_provider/src/requests/eth/gas.rs
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/estimateGas.ts

Add `eth_estimateGas` support for EDR provider and enable relevant tests. 
Implementation matches Hardhat behavior, except for logging as that's blocked by https://github.com/NomicFoundation/edr/issues/129. 
Follow up issue: https://github.com/NomicFoundation/edr/issues/267

feat: add `eth_estimateGas` support

---

crates/edr_evm/src/block.rs
crates/edr_evm/src/block/remote.rs
crates/edr_evm/src/blockchain.rs
crates/edr_evm/src/blockchain/forked.rs
crates/edr_evm/src/blockchain/remote.rs

I went over `expect`s in the forked blockchain implementation to change panics to errors to avoid panicking if the remote responds with unexpected data. 
I introduced a new `ForkedBlockchainError` error type as I didn't want to add errors that can only occur for a forked blockchain to the `BlockchainError` type. I also moved errors from `BlockchainError` that can only occur for a forked blockchain to `ForkedBlockchainError`.

fix: change panics to errors in forked blockchain

---

docs/src/content/hardhat-runner/plugins/plugins.ts

A new @dgma/hardhat-sol-bundler plugin has been added to the community plugins list. We use this plugin internally in Dogma Labs and would like to open-source it.

added @dgma/hardhat-sol-bundler plugin

---

.changeset/modern-clocks-leave.md
packages/hardhat-verify/src/internal/chain-config.ts

Closes https://github.com/NomicFoundation/hardhat/issues/4582
Closes https://github.com/NomicFoundation/hardhat/issues/4473
> ⚠️ Important note: Ethereum Goerli was deprecated in Q1 2023 but will be supported until Q1 2024. We are currently phasing out the usage of Arbitrum Goerli. Support for Arbitrum Goerli will cease prior to the conclusion of Ethereum Goerli.
> ⚠️` The old testnet RinkArby was deprecated on December 20th, 2022.
https://docs.arbitrum.io/for-devs/concepts/public-chains#arbitrum-goerli

Update hardhat-verify: add holesky & arbitrumSepolia, remove arbitrumTestnet & Goerli

---

crates/edr_napi/index.d.ts
crates/edr_provider/src/interval.rs
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/providers.ts
packages/hardhat-core/test/internal/hardhat-network/provider/interval-mining-provider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/websocket.ts

This removes `Sinon` from the interval mining tests, which was used to control the clock. As we don't offer this functionality in EDR, we're sleeping the thread instead.

test: enable remaining Hardhat tests

---

crates/edr_provider/src/error.rs

Fixes https://github.com/NomicFoundation/edr/issues/281

fix: handle unknown selector error

---

crates/edr_provider/src/error.rs
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts

Fixes https://github.com/NomicFoundation/edr/issues/282
This mimics the behaviour of Hardhat:
https://github.com/NomicFoundation/hardhat/blob/edr/main/packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts#L378-L383
This should be merged after https://github.com/NomicFoundation/hardhat/pull/4811

fix: https://github.com/NomicFoundation/edr/issues/282

---

crates/edr_provider/src/data.rs
crates/edr_provider/src/error.rs
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts

When block timestamps were equal, we weren't incrementing the offset by.
The corresponding code in Hardhat is here:
https://github.com/NomicFoundation/hardhat/blob/edr/main/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L382-L384

fix: block timestamp calculation

---

book/src/02_development/02_verdaccio.md
book/src/02_development/03_local_release.md
crates/edr_provider/src/error.rs

Should be merged after https://github.com/NomicFoundation/hardhat/pull/4811
Updates the docs to reflect usage of `pnpm` and notes that publishing EDR NPM packages has special instructions (to avoid confusion)

doc: update Verdaccio docs

---

.changeset/poor-nails-walk.md
packages/hardhat-ledger/src/internal/with-spinners.ts

---
I am attempting to use `npx hardhat console` in conjunction with `hardhat-ledger`. When doing so, after sending any transaction, `hardhat console` exits. This behaviour is related, either unintentionally or not, to the [default value of `discardStdin`](https://github.com/sindresorhus/ora/issues/220). This PR changes the value used.
There is a slight behavioral change in the console, which is that, as you might expect, keyboard input while the spinner is running is not discarded. This feels more acceptable than exiting after every transaction.
It does not seem to me that additional tests are required here, but open to guidance on that front.

Fix hardhat-ledger to work with hardhat console

---

.changeset/rare-boats-fetch.md
packages/hardhat-chai-matchers/src/internal/emit.ts
packages/hardhat-chai-matchers/src/internal/reverted/revertedWithCustomError.ts
packages/hardhat-chai-matchers/test/events.ts
packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts

Resolves: #3603
This PR asserts that .revertedWithCustomError only receives 2 arguments

Assert .revertedWithCustomError and .emit only receives 2 arguments

---

.gitignore
Cargo.lock
crates/edr_evm/Cargo.toml
crates/edr_evm/src/block/builder.rs
crates/edr_evm/src/blockchain/local.rs
crates/edr_evm/src/blockchain/storage/reservable.rs
crates/edr_evm/src/upcast.rs
crates/edr_napi/Cargo.toml
crates/edr_napi/src/provider.rs
crates/edr_provider/Cargo.toml
crates/edr_provider/src/config.rs
crates/edr_provider/src/data.rs
crates/edr_provider/src/interval.rs
crates/edr_provider/src/lib.rs
crates/edr_provider/src/requests/debug.rs
crates/edr_provider/src/requests/eth/blockchain.rs
crates/edr_provider/src/requests/eth/blocks.rs
crates/edr_provider/src/requests/eth/call.rs
crates/edr_provider/src/requests/eth/gas.rs
crates/edr_provider/src/requests/eth/mine.rs
crates/edr_provider/src/requests/eth/state.rs
crates/edr_provider/src/requests/eth/transactions.rs
crates/edr_provider/src/requests/hardhat/state.rs
crates/edr_provider/src/snapshot.rs
crates/tools/Cargo.toml
packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
packages/hardhat-core/test/internal/hardhat-network/provider/interval-mining-provider.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts

Avoid recomputing states by caching them for later use. 
This change brings a 100x improvement on the Rocketpool scenario that makes heavy use of snapshots.

fix: cache block contexts

---

crates/edr_napi/src/provider.rs
crates/edr_provider/src/lib.rs

In https://github.com/NomicFoundation/hardhat/pull/4815 we inadvertently introduced changes that caused tokio worker threads to be blocked. This PR fixes that.

fix: avoid blocking worker threads

---

crates/edr_provider/src/data.rs

Reduce state size cache to avoid swapping when executing https://github.com/neptune-mutual-blue/protocol tests. Memory consumption remains below 8gb in that repo.
This change leads to a 20% slowdown on the Rocketpool scenario which is I think acceptable.

fix: reduce state size cache

---

.changeset/new-rocks-report.md
.github/workflows/hardhat-network-helpers-ci.yml
packages/hardhat-core/src/internal/hardhat-network/provider/node.ts
packages/hardhat-core/test/internal/hardhat-network/provider/modules/hardhat.ts

The latest version of ethereumjs fails if you modify the storage of an account that doesn't exist yet. This only happens for `setStorageAt` but I added tests for the other setters too (nonce, balance and code).

Fix setStorageAt in untouched addresses

---

.changeset/modern-pugs-watch.md
packages/hardhat-viem/src/internal/errors.ts

Fixed broken viem link to supported networks in the error text related to unsupported networks with a valid link from [docs](https://viem.sh/docs/chains/introduction)

Fix 404 supported chains link

---

crates/edr_eth/src/remote/eth/call_request.rs
crates/edr_provider/src/requests/eth/call.rs
crates/edr_provider/tests/eth_request_serialization.rs

Needed to make https://github.com/ProjectOpenSea/seaport/ tests pass in EDR mode.

fix: add type field to call request

---

crates/edr_eth/src/remote/eth.rs
crates/edr_eth/src/remote/eth/call_request.rs
crates/edr_eth/src/remote/jsonrpc.rs
crates/edr_eth/src/transaction.rs

Remove `deny_unknown_fields` from RPC types to match Hardhat behavior of accepting additional fields.

fix: remove `deny_unknown_fields` from RPC types

---

.github/workflows/edr-npm-release.yml
crates/edr_napi/package.json

After we build NAPI binaries in the CI, we test them on their respective platforms using the `node` Docker image.
In https://github.com/NomicFoundation/hardhat/pull/4831 we made a change to make `pnpm test` trigger `pnpm build`. This caused testing to fail in `node` Docker containers as the Rust toolchain is not available there.
This PR fixes this by adding a `testNoBuild` command that is executed in the CI.
Closes https://github.com/NomicFoundation/edr/issues/293

fix: don't build edr_napi before testing in CI

---

.changeset/proud-peas-sort.md
.github/dependabot.yml
packages/hardhat-viem/README.md
packages/hardhat-viem/package.json
packages/hardhat-viem/src/internal/contracts.ts
packages/hardhat-viem/src/types.ts
packages/hardhat-viem/test/integration.ts
pnpm-lock.yaml

This PR represents the first part of adding support for `viem@2`. A subsequent PR will update `hardhat-toolbox-viem` and the dependencies in `packages/hardhat-core/src/internal/cli/project-creation.ts`.
[Link to second PR](https://github.com/NomicFoundation/hardhat/pull/4876).

Upgrade hardhat-viem to support viem@2

---

.changeset/cold-cobras-carry.md

Removing EDR changeset so we can release hardhat-viem without releasing hardhat.

Temporarily remove EDR changeset

---

crates/edr_evm/src/blockchain.rs
crates/edr_evm/src/blockchain/forked.rs
crates/edr_evm/src/blockchain/local.rs
crates/edr_evm/src/blockchain/remote.rs
crates/edr_evm/src/blockchain/storage.rs
crates/edr_evm/src/blockchain/storage/reservable.rs
crates/edr_evm/src/blockchain/storage/sparse.rs

This PR fixes a bug where we were inserting twice into `SparseBlockchainStorage::transaction_hash_to_block`. I also made the unsafe unchecked insertions fallible to help us when debugging sporadic failures in third-party repos.

fix: avoid inserting transactions twice

---

.github/workflows/edr-npm-release.yml

Pin NAPI-rs Docker images to avoid failures if the images are upgraded.

ci: pin napi-rs docker images

---

crates/edr_napi/package.json
packages/hardhat-core/package.json

The previous attempt didn't work because GitHub ignored the commit during the rebase? Maybe because it was empty.
But I hadn't bumped the version on the `package.json` so it was not going to work anyway.

edr-0.2.0-alpha.2

---

docs/src/content/ignition/docs/guides/creating-modules.md

Added missing brackets around `after` params in an ignition example.

Add missing brackets to "after" example

---

crates/edr_eth/src/transaction.rs
crates/edr_eth/src/transaction/fake_signature.rs
crates/edr_eth/src/transaction/request.rs
crates/edr_eth/src/transaction/request/eip155.rs
crates/edr_eth/src/transaction/request/eip1559.rs
crates/edr_eth/src/transaction/request/eip2930.rs
crates/edr_eth/src/transaction/request/eip4844.rs
crates/edr_eth/src/transaction/request/legacy.rs
crates/edr_eth/src/transaction/signed.rs
crates/edr_eth/src/transaction/signed/eip155.rs
crates/edr_eth/src/transaction/signed/eip1559.rs
crates/edr_eth/src/transaction/signed/eip2930.rs
crates/edr_eth/src/transaction/signed/eip4844.rs
crates/edr_eth/src/transaction/signed/legacy.rs
crates/edr_evm/src/transaction/executable.rs
crates/edr_provider/src/data.rs
crates/edr_provider/src/requests/eth/transactions.rs

Make sure we're not trying to recover the address from fake signatures. Fixes https://github.com/NomicFoundation/edr/issues/294

fix: use custom address recovery for fake signature

---

crates/edr_provider/src/data.rs

Needed to avoid swapping in the `synthetix` repo.

fix: reduce max cached state count

---

.github/workflows/test-recent-mainnet-block.yml
crates/edr_napi/index.js
crates/edr_provider/src/data.rs
crates/edr_provider/src/test_utils.rs
packages/hardhat-core/test/internal/hardhat-network/helpers/constants.ts

Previously, we were using the provider but the mem pool logic of the provider is not advanced enough to deal with blocks that transfer funds to an empty account and then subtract those funds, as it only takes the current state into consideration.

fix: use block builder to replay blocks

---

packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts

This fixes an OOM issue and noticeably improves performance.

Don't run async event handlers if there are no listeners

---

.changeset/gold-comics-do.md
docs/src/content/hardhat-network/docs/reference/index.md
packages/hardhat-core/src/internal/core/config/default-config.ts
packages/hardhat-core/test/internal/core/config/default-config.ts
packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts
packages/hardhat-core/test/internal/hardhat-network/provider/forking-different-hardfork.ts

Set cancun as the default config for the hardfork used in Hardhat network.

feat: set cancun as default hardfork

---

docs/src/content/ignition/docs/guides/_dirinfo.yaml
docs/src/content/ignition/docs/guides/create2.md

resolves https://github.com/NomicFoundation/hardhat-ignition/issues/670
depends on https://github.com/NomicFoundation/hardhat-ignition/pull/626

Add a guide for using the create2 strategy

---

.changeset/dull-pigs-pay.md
packages/hardhat-core/src/internal/cli/cli.ts

Solves https://github.com/NomicFoundation/hardhat/issues/4950

Create env before args are parsed

---

.changeset/perfect-insects-hide.md
crates/edr_eth/src/spec.rs
packages/hardhat-core/test/internal/hardhat-network/provider/baseFeePerGas.ts

This adds detection of `Cancun` blocks on mainnet, when using the default hardfork activation detection.

feat: add Cancun activation block number

---

crates/edr_eth/src/access_list.rs
packages/hardhat-core/test/internal/solidity/resolver.ts

chore: fix some comments

---

.changeset/neat-apes-mix.md
crates/edr_provider/src/requests/methods.rs
crates/edr_provider/src/requests/serde.rs
crates/edr_provider/tests/issue_346.rs

Adds workaround for https://github.com/NomicFoundation/edr/issues/346

fix: support hex string in `eth_signTypedData_v4` salt

---

.changeset/neat-readers-beam.md
packages/hardhat-core/package.json
pnpm-lock.yaml

Bump EDR version to 0.3.3 which includes some bug fixes: https://github.com/NomicFoundation/hardhat/blob/main/crates/edr_napi/CHANGELOG.md#033

fix: bump EDR version to 0.3.3

---

.changeset/itchy-walls-suffer.md
packages/hardhat-ledger/src/internal/with-spinners.ts
packages/hardhat-ledger/src/provider.ts
packages/hardhat-ledger/test/internal/with-spinners.ts

Note: This RPC method is intended for internal usage and may change without notice.
Usage:
```javascript
try {
// Disable the default ledger output by calling `hardhat_setLedgerOutputEnabled`
await hre.network.provider.send("hardhat_setLedgerOutputEnabled", [false]);
// Subscribe to hardhat-ledger events and manually handle the output
hre.network.provider.once("connection_start", () => console.log("IGNITION: [hardhat-ledger] Connecting wallet"));
hre.network.provider.once("connection_success", () => console.log("[🗸] IGNITION: [hardhat-ledger] Connecting wallet"));
hre.network.provider.once("connection_failure", () => console.log("[x] IGNITION: [hardhat-ledger] Connecting wallet"));
// confirmation_start
// confirmation_success
// confirmation_failure
// derivation_start
// …
```

Add custom rpc method to toggle ledger feedback

---

.changeset/tame-apples-admire.md
packages/hardhat-core/src/common/napi-rs.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/provider/utils/convertToEdr.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-tracer.ts
packages/hardhat-core/src/internal/solidity/parse.ts

I created a `requireNapiRsModule` wrapper function to use both when requiring `solidity-analyzer` and EDR. The rest of the changes should be self-explanatory.

Throw CORRUPTED_LOCKFILE error when requiring EDR fails

---

.cargo/config
Cargo.lock
crates/edr_napi/Cargo.toml
crates/edr_provider/Cargo.toml
crates/edr_provider/src/data.rs
crates/tools/Cargo.toml
crates/tools/src/scenario.rs

This PR:
- adds the `cargo scenario` and `cargo scenario-with-tracing` shortcuts, to make it easier to execute those tools.
- sets the `cargo replay-block` command to build in release mode

feat: add support for tracing to scenario runner

---

.changeset/brave-scissors-train.md
Cargo.lock
crates/edr_eth/Cargo.toml
crates/edr_eth/src/remote/client.rs
crates/edr_eth/src/remote/client/reqwest_error.rs

Only log the host instead of the full URL in RPC errors to avoid leaking api keys in CI.

fix: remove api keys from RPC error messages

---

Cargo.lock
crates/edr_napi/Cargo.toml
crates/edr_napi/src/lib.rs
crates/edr_napi/src/provider.rs

```
All Scenarios:
main: 3860524 ms
rpmalloc: 1967738 ms (-49.0%)
mimalloc: 2014802 ms (-47.8%)
neptune-mutual-blue-protocol_8db6480:
main: 828637 ms
rpmalloc: 329130 ms (-60.3%)
mimalloc: 296993 ms (-64.2%)
openzeppelin-contracts_8b12f83a:
main: 87280 ms
rpmalloc: 74892 ms (-14.2%)
// openzeppelin was updated to fix an issue with their tests, so we have a new baseline!
openzeppelin-contracts_0a5fba7a:
main: 116951 ms
mimalloc: 101088 ms (-13.6%)
rocketpool_6a9dbfd8:
main: 73792 ms
rpmalloc: 66911 ms (-9.3%)
mimalloc: 67996 ms (-7.9%)
safe-contracts_914d0f8: 
main: 3829 ms
rpmalloc: 3194 ms (-16.6%)
mimalloc: 3465 ms (-9.5%)
seaport_4f4e7c20:
main: 17918 ms
rpmalloc: 17100 ms (-4.6%)
mimalloc: 17347 ms (-3.2%)
synthetix_9a3a109f:
main: 2805315 ms
rpmalloc: 1436761 ms (-48.8%)
mimalloc: …
```

refactor: use mimalloc as global allocator

---

docs/src/content/hardhat-runner/plugins/plugins.ts

This PR simply adds all the plugins that compose ethernaut-cli as standalone plugins to the list of plugins that can be found on the documentation at https://hardhat.org/hardhat-runner/plugins

List ethernaut-cli plugins to docs

---

crates/edr_evm/src/transaction.rs
crates/edr_evm/src/transaction/executable.rs
crates/edr_provider/src/data.rs
packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/methods/getTransactionByHash.ts

Alchemy has deprecated Goerli: https://www.alchemy.com/blog/ethereum-goerli-testnet-deprecation

ci: change goerli tests to sepolia

---

.changeset/friendly-steaks-travel.md
crates/edr_eth/src/remote/filter.rs
crates/edr_provider/src/requests/eth/filter.rs
crates/edr_provider/tests/issue_361.rs

Fixes https://github.com/NomicFoundation/edr/issues/361

fix: remove hardfork restriction on eth_getLogs

---

.github/workflows/edr-npm-release.yml

Previously the EDR NPM release tagged the package as `next` if there is anything after the version in the release commit, e.g. commit message `edr-0.1.2` gets tagged as `latest`, but `edr-0.1.2-alpha` gets tagged as `next`. But this lead to `edr-0.3.4 (#5088)` getting tagged as `next` which is undesirable.
This PR changes the regexes to allow white space after the version triplet for `latest` release commits and require a hyphen after the version triplet to be tagged as `next`. This is in line with the semver [spec.](https://semver.org/#spec-item-9)

ci: allow trailing space in EDR release commit

---

e2e/test-project-initialization.sh

The e2e workflow should fail with this change. For some reason, `npx hardhat coverage` doesn't work with the viem-based sample project. As part of this PR, we should fix that.

Run gas report and coverage in e2e

---

config/eslint/eslintrc.js
packages/hardhat-chai-matchers/package.json
packages/hardhat-chai-matchers/test/bigNumber.ts
packages/hardhat-chai-matchers/test/events.ts
packages/hardhat-chai-matchers/test/reverted/revertedWithCustomError.ts
packages/hardhat-core/package.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts
packages/hardhat-ethers/package.json
packages/hardhat-foundry/package.json
packages/hardhat-ledger/package.json
packages/hardhat-network-helpers/package.json
packages/hardhat-shorthand/package.json
packages/hardhat-solhint/package.json
packages/hardhat-solpp/package.json
packages/hardhat-solpp/test/tests.ts
packages/hardhat-toolbox-viem/package.json
packages/hardhat-toolbox/package.json
packages/hardhat-truffle4/package.json
packages/hardhat-truffle5/package.json
packages/hardhat-verify/package.json
packages/hardhat-viem/package.json
packages/hardhat-vyper/package.json
packages/hardhat-vyper/test/tests.ts
packages/hardhat-web3-legacy/package.json
packages/hardhat-web3-v4/package.json
packages/hardhat-web3/package.json
pnpm-lock.yaml

Continuation of https://github.com/NomicFoundation/hardhat/pull/5086
Using this plugin also lets us remove the `eslint-plugin-no-only-tests` package and replace it with a rule from `eslint-plugin-mocha`.

Add eslint rule to forbid describes with async functions

---

config/v-next/eslint.cjs
config/v-next/tsconfig.json
config/v-next/tsconfig.node20.json
packages/eslint-plugin-hardhat-internal-rules/.eslintrc.js
packages/eslint-plugin-hardhat-internal-rules/package.json
packages/eslint-plugin-slow-imports/.eslintrc.js
packages/eslint-plugin-slow-imports/lib/rules/no-top-level-external-import.js
packages/eslint-plugin-slow-imports/package.json
packages/template-package/.eslintrc.cjs
packages/template-package/.gitignore
packages/template-package/.prettierignore
packages/template-package/LICENSE
packages/template-package/README.md
packages/template-package/package.json
packages/template-package/src/index.ts
packages/template-package/src/other-entry-point.ts
packages/template-package/src/utils/string.ts
packages/template-package/test/index.ts
packages/template-package/test/other-entry-point.ts
packages/template-package/tsconfig.json
pnpm-lock.yaml
scripts/check-dependencies.js

This PR introduces a new template package with updated setups for node, typescript, `package.json`, `eslint`, etc.
It includes a few example files and tests, using `node:test`. It doesn't have any assertion library installed though, except for `expect-type` for type-level tests. We still need to pick one, or use `node:assert`, which we should use in the meantime.
Something that's important to note is that now imports, even ts imports, have to end in `.js`. TBH it doesn't look good, but it's the currently recommended approach to use TS with native esm.
This PR doesn't change the global config files, but introduces new ones instead, to avoid breaking all other packages.

Introduce a template package

---

docs/src/content/ignition/docs/config/index.md

As this is a per-network config option the configuration page had to be restructured to support both global and per-network config.

docs(ignition): include config option `maxFeePerGasLimit`

---

.changeset/short-pillows-march.md
packages/hardhat-viem/src/internal/contracts.ts

In the latest version of viem, the `contractAddress` field of the receipt can be both `null` or `undefined`, which causes our build to fail (and the latest dependencies workflow to fail). This fixes that.
I don't know in which cases this `undefined` can show up though.

Fix build with latest viem dependency

---

.changeset/nervous-tips-grow.md
Cargo.lock
crates/edr_eth/Cargo.toml
crates/edr_eth/src/block/reward.rs
crates/edr_eth/src/lib.rs
crates/edr_eth/src/remote/block_spec.rs
crates/edr_eth/src/remote/eth/call_request.rs
crates/edr_eth/src/remote/filter.rs
crates/edr_eth/src/serde.rs
crates/edr_eth/src/transaction/request/eip1559.rs
crates/edr_eth/src/transaction/request/eip2930.rs
crates/edr_eth/src/transaction/request/eip4844.rs
crates/edr_eth/src/transaction/request/legacy.rs
crates/edr_eth/src/transaction/signed.rs
crates/edr_eth/src/transaction/signed/eip155.rs
crates/edr_eth/src/transaction/signed/eip1559.rs
crates/edr_eth/src/transaction/signed/eip2930.rs
crates/edr_eth/src/transaction/signed/eip4844.rs
crates/edr_eth/src/transaction/signed/legacy.rs
crates/edr_evm/Cargo.toml
crates/edr_evm/src/block/builder.rs
crates/edr_evm/src/lib.rs
crates/edr_evm/src/mempool.rs
crates/edr_evm/src/trace.rs
crates/edr_evm/src/transaction/executable.rs
crates/edr_evm/tests/issue_364.rs
crates/edr_napi/Cargo.toml
crates/edr_provider/Cargo.toml
crates/edr_provider/src/data.rs
crates/edr_provider/src/test_utils.rs

In the process of fixing this, I also updated all Rust dependencies to ensure that we could use the latest version of `revm` (v8.0.0)
**Depends on**

fix: add missing KZG point evaluation precompile

---

.changeset/large-phones-relax.md
packages/hardhat-verify/src/internal/chain-config.ts

Currently, Base Sepolia is not in the list of chains for the hardhat verify plugin. This PR adds support for verifying smart contracts on the Base Sepolia network.

Update chain-config.ts : Added Base Sepolia chain

---

.changeset/itchy-maps-film.md
crates/edr_evm/src/blockchain/forked.rs
crates/edr_provider/src/data.rs

Closes https://github.com/NomicFoundation/edr/issues/366

Use remote chain id in fork metadata

---

.changeset/twelve-ducks-exercise.md
crates/edr_napi/src/context.rs

Fixes https://github.com/NomicFoundation/edr/issues/385

fix: avoid panic when re-setting global default subscriber

---

.changeset/friendly-papayas-drum.md
.changeset/tall-cats-learn.md
.changeset/twelve-ducks-exercise.md

To avoid releasing EDR while doing a more general Hardhat release we are turning off two changesets. These will be added back in after the release.
Also add in a changeset to document the `0.3.5` upgrade.

chore: remove edr changesets

---

.changeset/cyan-cheetahs-add.md
packages/hardhat-foundry/src/index.ts

closes #5043
Not sure how to test this because the plugin directory is not a Hardhat project.

use absolute path for foundry sources

---

docs/src/content/ignition/docs/config/index.md

Documents the `maxPriorityFeePerGas` as a config value for network configuration.

docs(ignition): add `maxPriorityFeePerGas` to config

---

.changeset/friendly-papayas-drum.md
.changeset/new-coins-eat.md
.changeset/tough-students-compare.md
.changeset/twelve-ducks-exercise.md
.changeset/two-suits-admire.md
.changeset/wicked-walls-itch.md

These were added before the repo migration, and they were already released.
The one that is modified comes from an optimization on the Hardhat side, which hasn't been released yet.

Remove EDR changesets

---

.changeset/new-books-marry.md
packages/hardhat-verify/src/internal/chain-config.ts

With the deprecation of Polygon Mumbai to Polygon Amoy, I've done this little PR because I need it for one of my projects.

Update chain-config.ts : Replace Mumbai by Amoy

---

.changeset/pink-goats-jam.md
packages/hardhat-verify/src/index.ts
packages/hardhat-verify/src/internal/errors.ts
packages/hardhat-verify/src/internal/etherscan.ts
packages/hardhat-verify/src/internal/tasks/etherscan.ts
packages/hardhat-verify/test/integration/index.ts
packages/hardhat-verify/test/unit/index.ts

---
That PR adds the `--force` verification flag described in https://github.com/NomicFoundation/hardhat/issues/5122, which allows the re-verification of already verified contracts (for blockscout-based explorers).
Notice that sometimes, an underlying explorer may return an error saying that the contract has already been verified. For blockscout-based explorers that happens if the contract is already verified with a [full match](https://docs.sourcify.dev/docs/full-vs-partial-match/), while for etherscan that is the only possible option for verified contracts. The PR considers those cases as errors and fails with a corresponding error message. I don't know if that is what is expected, though.
Also I plan to add some test cases, but would be glad to get some suggestions to start with

Enforce contract verification

---

.changeset/smart-hotels-fold.md
packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts
packages/hardhat-ethers/test/hardhat-ethers-provider.ts

Update `getFeeData` to match the `ethers` algorithm, specifically don't just assume `1_000_000_000n` as the `maxPriorityFeePerGas`. Instead call `eth_maxPriorityFeePerGas`, and only fall back to `1_000_000_000n`, if there is no response.
Fixes #5093

fix: use `eth_maxPriorityFeePerGas` for determing gas

---

.changeset/little-bananas-thank.md
packages/hardhat-core/src/internal/solidity/compilation-job.ts

---
`transitiveDependenciesVersionPragmas` is a 2d array of strings. When you add it in a Set to dedup the values on the following lines, the dedup doesn't work because the Set is evaluating arrays and not their underlying string. Flattening 
`transitiveDependenciesVersionPragmas` to make it a regular string array allows for the intended behavior, which is for the Set to dedup all repetitive pragma versions.
No other part of the code than the following Set is relying on `transitiveDependenciesVersionPragmas`.
before
```js
const transitiveDependenciesVersionPragmas = [
[ '^0.8.20' ],
[ '^0.8.20' ],
[ '^0.8.20' ],
[ '^0.8.20' ],
[ '^0.8.20' ],
[ '^0.8.20' ],
[ '^0.8.20' ]
]
const versionRange = "^0.8.20 ^0.8.20 ^0.8.20 ^0.8.20 ^0.8.20 ^0.8.20"
```
after
```js
const …
```

fix: flatten 2d array

---

packages/eslint-plugin-hardhat-internal-rules/.eslintrc.js
packages/eslint-plugin-hardhat-internal-rules/package.json
packages/eslint-plugin-slow-imports/.eslintrc.js
packages/eslint-plugin-slow-imports/package.json
pnpm-lock.yaml

---
Ref: https://github.com/NomicFoundation/hardhat/issues/4824
I was exploring the hardhat repo and thought about picking a couple of low hanging fruits to get to know the repository and the team :) this one seemed to be quite straightforward? Do you need me to update anything else?
Thanks!
Stefano

chore: replace unmaintained eslint-plugin-node with eslint-plugin-n

---

.changeset/happy-mails-impress.md
packages/hardhat-core/src/internal/hardhat-network/stack-traces/source-maps.ts

---
If we compile the following function with solcx version: `'0.8.14'`
```solidity
pragma solidity ^0.8.14;
contract FunctionSelector {
/*
"transfer(address,uint256)"
0xa9059cbb
"transferFrom(address,address,uint256)"
0x23b872dd
*/
function getSelector(string calldata _func) external pure returns (bytes4) {
return bytes4(keccak256(bytes(_func)));
}
}
```
We will get the following:
- bytecode
```
0x608060405234801561001057600080fd5b506004361061002b5760003560e01c806380a003ff14610030575b600080fd5b61004a600480360381019061004591906100f1565b610060565b6040516100579190610179565b60405180910390f35b600082826040516100729291906101d3565b6040518091039020905092915050565b600080fd5b600080fd5b600080fd5b600080fd5b600080fd5b60008083601f8401126100b1576100b061008c565b5b8235905067ffffffffffffffff8111156100ce5761 …
```

fix: Stack Trace Source Maps - corrected typo in indexing

---

.changeset/clever-hairs-happen.md
packages/hardhat-verify/src/internal/errors.ts
packages/hardhat-verify/src/internal/etherscan.ts
packages/hardhat-verify/src/internal/sourcify.ts
packages/hardhat-verify/src/internal/tasks/etherscan.ts
packages/hardhat-verify/test/integration/index.ts

**Changes in this PR:**
- Removed `UnexpectedError` from `hardhat-verify`.
- Functions that make API calls are no longer enclosed in a broad try/catch block. Instead, calls to `undici` are specifically wrapped, and now throw a new `NetworkRequestError`.
- Replaced generic `Error` instances with `VerificationAPIUnexpectedMessageError` to better indicate API-related issues. The error message no longer instruct users to report issues to the Hardhat team.
- Added a correction in `HardhatVerifyError` to address an problem introduced by `NomicLabsHardhatPluginError`. This fix resolves an issue causing the `instanceof` operator to work incorrectly.
Closes https://github.com/NomicFoundation/hardhat/issues/5166

Hardhat verify fixes

---

.changeset/thick-beers-tie.md
packages/hardhat-verify/src/internal/utilities.ts
packages/hardhat-verify/test/unit/utilities.ts

---
1. Added detection of parameters when passing arguments to the constructor. Currently, the detection is done on the backend, which makes it difficult to distinguish between strings and numbers in the tool. Therefore, a new feature has been submitted to address this issue.
This is the contract code:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
contract MyContract {
string public url;
uint256 public add;
constructor(string memory _url, uint256 _add) {
url = _url;
add = _add;
}
function setUrl(string memory _url) public {
url = _url;
}
}
```
Parameter passing file:
```js
module.exports = [
123,
123
];
```
Using the command:
```bash
npx hardhat verify --contract contracts/MyToken.sol:MyContract [ADDRESS] --constructor-args scripts/arguments.js
```

feat: check check constructor args type

---

config-v-next/eslint.cjs
v-next/hardhat-build-system/src/internal/solidity/compiler/downloader.ts
v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
v-next/hardhat-build-system/src/internal/solidity/parse.ts
v-next/hardhat-build-system/src/internal/utils/fs-utils.ts
v-next/hardhat-build-system/src/internal/utils/multi-process-mutex.ts
v-next/hardhat-build-system/test/helpers.ts
v-next/hardhat/src/cli.ts

This PR introduces two new rules that:
1. Forbids doing `} catch (e: <Type>) {`, hinting you to use `ensureError()` or `HardhatError.isHardhatError()` instead.
2. Forces you to do `.catch((e : unknown) =>` instead of just `.catch(e =>`, as the latter is an `any`.

Enable eslint rules to make catching errors safer

---

.github/workflows/e2e-tests.yml

Disable E2E tests on Windows

---

.changeset/wise-cheetahs-confess.md
packages/hardhat-network-helpers/src/errors.ts
packages/hardhat-network-helpers/src/helpers/reset.ts
packages/hardhat-network-helpers/src/loadFixture.ts
packages/hardhat-network-helpers/test/helpers/reset.ts

- [x ] Because this PR includes a **bug fix**, relevant tests have been included.
---
i have changed the error message for the issue #4151 and i've also added a function deleteOnReset() which resets the snapshots array.
let me know what other changes I need to make on this issue.

adding a function and editing the error message for the issue #4151

---

docs/src/content/ignition/docs/advanced/_dirinfo.yaml
docs/src/content/ignition/docs/advanced/migrating.md

resolves https://github.com/NomicFoundation/hardhat-ignition/issues/758

Bring migration guide to docs

---

v-next/core/src/internal/plugins/resolve-plugin-list.ts
v-next/core/test/nop.ts
v-next/core/test/plugins/resolve-plugin-list.ts
v-next/hardhat-errors/src/descriptors.ts

Add tests on the dependency resolution of plugins.
Resolve #5254.

test: add resolve-plugin-list tests

---

config-v-next/eslint.cjs
v-next/core/test/plugins/resolve-plugin-list.ts
v-next/hardhat-build-system/test/helpers.ts
v-next/hardhat-build-system/test/index.ts
v-next/hardhat-build-system/test/internal/utils/artifacts.ts

This PR adds an eslint rule so that we use `node:assert/strict` and not `node:assert`. 
The one exception is when you import `AssertionError`, which needs to come from `node:assert`.

Add eslint rules to enforce `node:assert/strict`

---

v-next/hardhat/src/index.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/hre-singleton.ts
v-next/hardhat/test/hre/index.ts
v-next/hardhat/test/index.ts

resolves #5236 
- added a singleton hre instance for both CLI and programmatic hardhat API
- added a test for the above
- added a test to ensure builtin plugins are included in initialization

Add and test a singleton hre instance

---

pnpm-lock.yaml
v-next/core/package.json
v-next/core/src/internal/plugins/plugin-validation.ts
v-next/core/test/plugins/fixture-projects/installed-package/README.md
v-next/core/test/plugins/fixture-projects/installed-package/node_modules/example/package.json
v-next/core/test/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/README.md
v-next/core/test/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/node_modules/peer1/package.json
v-next/core/test/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/node_modules/peer2/package.json
v-next/core/test/plugins/fixture-projects/installed-peer-deps-as-sub-node-modules/node_modules/example/package.json
v-next/core/test/plugins/fixture-projects/installed-peer-deps/README.md
v-next/core/test/plugins/fixture-projects/installed-peer-deps/node_modules/example/package.json
v-next/core/test/plugins/fixture-projects/installed-peer-deps/node_modules/peer1/package.json
v-next/core/test/plugins/fixture-projects/installed-peer-deps/node_modules/peer2/package.json
v-next/core/test/plugins/fixture-projects/not-installed-package/README.md
v-next/core/test/plugins/fixture-projects/not-installed-peer-dep/README.md
v-next/core/test/plugins/fixture-projects/not-installed-peer-dep/node_modules/example/package.json
v-next/core/test/plugins/fixture-projects/not-installed-peer-dep/node_modules/peer1/package.json
v-next/core/test/plugins/fixture-projects/peer-dep-with-wrong-version/README.md
v-next/core/test/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/example/package.json
v-next/core/test/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/peer1/package.json
v-next/core/test/plugins/fixture-projects/peer-dep-with-wrong-version/node_modules/peer2/package.json
v-next/core/test/plugins/plugin-validation.ts
v-next/core/test/plugins/resolve-plugin-list.ts
v-next/hardhat-build-system/package.json
v-next/hardhat-errors/src/descriptors.ts

Validates the plugins provided through the initial config object.
If the plugin comes from an npm package check that the package has been installed.
If the plugin is present further confirm that peer dependencies have been installed. It then checks that the installed version falls within the range of the originating package.
This leverages the node require mechanism based on `process.cwd()` as the starting directory.
Resolves #5256
While 21 files are changed, most of these are fixture files for the small number of tests. The core change is in:
* `v-next/core/src/internal/plugins/plugin-validation.ts`
* `v-next/core/test/plugins/plugin-validation.ts`

feat: plugin install validation

---

v-next/core/src/internal/hook-manager.ts
v-next/core/src/internal/hre.ts
v-next/core/src/internal/plugins/plugin-validation.ts
v-next/core/src/internal/plugins/resolve-plugin-list.ts
v-next/core/src/types/plugins.ts
v-next/core/test/plugins/plugin-validation.ts
v-next/core/test/plugins/resolve-plugin-list.ts
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/src/hre.ts
v-next/hardhat/src/internal/cli/main.ts

Alter `HardhatPlugin` to use lazily loaded dependencies. This guards against failed installs as deps can have the form:
```ts
{
id: "example",
npmPackage: "my-plugin",
dependencies: [
() => import("another-plugin")
]
}
```
Several moves were made to support this:
1. The `HardhatPlugin` type was updated
2. Validation of plugin installs was moved into the plugin resolution logic. The dependency load is tried first, on exception a validation of the plugin installation is attempted. If there are no installation issue a generic dependency loading failed error is thrown.
3. The base path for npm resolution (the directory of the hardhat config file in v2) is now exposed through the `resolvePluginList` signature.

v-next/lazy-plugin-loading

---

v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/package.json
v-next/hardhat/src/index.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/helpers/config-loading.ts
v-next/hardhat/src/internal/hre-singleton.ts
v-next/hardhat/test/fixture-projects/config-js/nested-folder/index.js
v-next/hardhat/test/fixture-projects/config-ts/nested-folder/index.js
v-next/hardhat/test/fixture-projects/loaded-config/hardhat.config.js
v-next/hardhat/test/helpers/project.ts
v-next/hardhat/test/hre/index.ts

Config loading

---

config-v-next/tsconfig.json

This PR disables these compilation settings. It doesn't modify the linter config, as the rule to forbid unused variables was already enabled 😅

Disable compilation errors on unused variables

---

v-next/hardhat-build-system/src/internal/solidity/compiler/downloader.ts
v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat-errors/src/errors.ts
v-next/hardhat-errors/test/errors.ts

This PR modifies `HardhatError` so that its constructor and its `messageArguments` property are type-safe.
This introduces two extra changes:
1. The error message template system now uses `{variable}` instead of `%variable%`, as that dramatically simplified this PR.
2. The constructor only takes two parameters now if the message template doesn't use any variable. Those are the descriptor and the optional cause.

Type-safe `HardhatError`

---

v-next/core/package.json
v-next/core/src/internal/async-mutex.ts
v-next/core/src/internal/user-interruptions.ts
v-next/core/test/internal/user-interruptions/async-mutex.ts
v-next/core/test/internal/user-interruptions/user-interruptions-manager.ts
v-next/hardhat/package.json

resolves #5233 
resolves #5235 
added tests for `UserInterruptionsManagerImplementation` and `AsyncMutex`

Add tests for user interruptions

---

v-next/core/src/internal/tasks/builders.ts
v-next/core/src/internal/tasks/task-manager.ts
v-next/core/src/internal/tasks/utils.ts
v-next/core/test/internal/tasks/builders.ts
v-next/hardhat-errors/src/descriptors.ts

This PR may be hard to read as there are a bunch of changes to the same file and the diff doesn't look good. Here's a summary of the most important changes:
- Replaced all Errors with HardhatErrors. Added error descriptors for each error.
- Added validation to the task builders to account for empty IDs (either empty string or empty array), along with tests.
- Added comments to make the code more legible.
- Since most errors can be thrown by a task added by the user or by a plugin, I've added a `getActorFragment` helper to avoid some of the branching and to prevent having different descriptors for the same error type.
- Used `assertHardhatInvariant` to avoid the non-null assertion in `getTask`.
- Updated `#insertTask` by moving the successful case to the end and handling errors first if …

TaskManagerImplementation improvements

---

v-next/core/src/internal/plugins/detect-plugin-npm-dependency-problems.ts
v-next/core/src/internal/plugins/resolve-plugin-list.ts
v-next/core/test/internal/plugins/detect-plugin-npm-dependency-problems.ts
v-next/hardhat-errors/src/descriptors.ts

This is a follow up PR on the npm plugin dependency validation.
It does two things:
1. Renames the plugin installation validation function to `detectPluginNpmDependencyProblems`
2. Expands some of the related error messages to provide more details.
Resolves #5287

refactor: rename from validation to detection

---

pnpm-lock.yaml
v-next/hardhat-build-system/package.json
v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
v-next/hardhat-build-system/src/internal/solidity/compiler/solcjs-runner.ts
v-next/hardhat-errors/src/descriptors.ts

I discovered that the hardhat-build-systems weren't working anymore locally (maybe after recreating my devcontainer?), because they don't work on ARM+linux. The reason is that on ARM you need to use solcjs, and that wasn't ported to ESM.
Note: This just copied the logic from v2 and ESM-ified it.

Make the build-system work with solcjs

---

.github/workflows/close-stale-issues.yml

---
Solves https://github.com/NomicFoundation/hardhat/issues/5306.
This pull request introduces a GitHub Actions workflow that automatically closes issues labeled with `status:needs-more-info` if there has been no follow-up for a specified period of time. This helps maintain a clean and manageable issue tracker by closing inactive support cases that require additional information from the reporter.
Following considerations are had for the current implementation:
1. The workflow runs daily at midnight UTC to check for stale issues
2. The workflow can also be triggered manually from the GitHub Actions tab using the `workflow_dispatch` event
3. Issues labeled with `status:needs-more-info` will be marked as stale after 7 days of inactivity
4. Once marked as stale, the issue will be …

Add stale issues Github Actions Workflow

---

v-next/hardhat-utils/package.json
v-next/hardhat-utils/src/ci.ts
v-next/hardhat-utils/test/ci.ts

Implement a function to check if the process is running in GitHub CI. 
The logic combines the code from [pnpm](https://pnpm.io/cli/install#--frozen-lockfile) and the [hardhat code](https://github.com/NomicFoundation/hardhat/blob/bdd04d37f2ee41f68943f60bf0fd3ac5546a05ad/packages/hardhat-core/src/internal/util/ci-detection.ts#L20) in hh-core

Add function in hh-utils to check if process is running in the CI

---

config-v-next/eslint.cjs
v-next/hardhat/src/internal/helpers/config-loading.ts

This PR enables a linter rule so that we can't import from one package to the other using its relative path, which vscode sometimes does.

Enable import/no-relative-packages and fix an instance of it

---

v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/main.ts

This PR fixes [this bug](https://github.com/NomicFoundation/hardhat/issues/5353).
PROBLEM
To parse global and task parameters, the same function was used. However, the logic should have been slightly different. If a parameter is not found in the global parameters map when parsing the CLI arguments, no error should be thrown because it might be a task parameter. But when a parameter is not found in the task parameters map when parsing the CLI arguments, an error must be thrown because, at this point, everything should be parsed. The old logic was throwing an error when not finding a match for a global parameter.
SOLUTION
Add a flag in the function definition (default to false) to specify global parameter behavior (do not throw if missing) or task parameter behavior (throw if missing).

Task parameters are treated as unrecognized global parameters

---

v-next/core/src/internal/plugins/detect-plugin-npm-dependency-problems.ts
v-next/core/src/internal/tasks/resolved-task.ts
v-next/core/test/internal/tasks/task-manager.ts

Also added the default specified in the JSDoc for `basePathForNpmResolution` in `detectPluginNpmDependencyProblems` (double checked with Pato).

Check for missing dependencies when failing to import a file action

---

v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/cli/version.ts
v-next/hardhat/src/internal/utils/package.ts
v-next/hardhat/test/internal/cli/main.ts

[Task description](https://github.com/NomicFoundation/hardhat/issues/5360)
[This PR](https://github.com/NomicFoundation/hardhat/pull/5380) should be merged first.
CHANGES:
- add a function to console.log the Hardhat version
- add a function to get the Hardhat version in the 'hardhat package'  at the path src/internal/utils/package.ts. For this function no test has been added because not very useful: a test would repeat the same logic in the test file as the original function because the hh package version cannot be hardcoded, since it constantly changes

Implement logic for the --version cli global argument

---

.changeset/shiny-wasps-invite.md
.github/workflows/hardhat-chai-matchers-ci.yml
.github/workflows/hardhat-core-ci.yml
.github/workflows/hardhat-ethers-ci.yml
.github/workflows/hardhat-foundry-ci.yml
.github/workflows/hardhat-ledger-ci.yml
.github/workflows/hardhat-network-helpers-ci.yml
.github/workflows/hardhat-network-tracing-all-solc-versions.yml
.github/workflows/hardhat-shorthand-ci.yml
.github/workflows/hardhat-solhint-ci.yml
.github/workflows/hardhat-solpp-ci.yml
.github/workflows/hardhat-toolbox-ci.yml
.github/workflows/hardhat-truffle4-ci.yml
.github/workflows/hardhat-truffle5-ci.yml
.github/workflows/hardhat-verify-ci.yml
.github/workflows/hardhat-viem-ci.yml
.github/workflows/hardhat-vyper-ci.yml
.github/workflows/hardhat-web3-ci.yml
.github/workflows/hardhat-web3-legacy-ci.yml
.github/workflows/hardhat-web3-v4-ci.yml
docs/src/content/hardhat-runner/docs/reference/stability-guarantees.md
docs/src/content/tutorial/setting-up-the-environment.md
packages/hardhat-core/src/internal/cli/bootstrap.ts
packages/hardhat-core/src/internal/cli/constants.ts
packages/hardhat-core/src/internal/cli/is-node-version-to-warn-on.ts
packages/hardhat-core/test/internal/cli/is-node-version-to-warn-on.ts

This PR does three things:
1. Adds Node.js v22 support
2. Updates the stability guarantees text in our docs to clarify our version support policy
3. Updates the logic for displaying the unsupported version warning
The [node releases repo](https://github.com/nodejs/Release) indicate that node 22 is in the _Current_ release status. So we should support it.
We are updating our stability guarantees text to indicate that we will support **even numbered major versions** with a status of either:
* Current
* Active LTS
* Maintentance LTS
This is based on the node releases: https://nodejs.org/en/about/previous-releases and https://github.com/nodejs/Release
Previously, Hardhat showed a version warning for any unsupported version:
1. All odd numbered major version numbers
4. All versions before the …

update node versions supported to include node 22

---

.changeset/unlucky-tips-jam.md
packages/hardhat-core/src/internal/core/config/default-config.ts

Fixes https://github.com/NomicFoundation/edr/issues/447.
We don't have hardfork activation histories for optimism and arbitrum. This means that if you fork one of those networks and immediately make a call, you'll get a "No known hardfork for execution on historical block..." error, because those calls are executed in the forked block, which uses the remote hardfork.
A scenario that doesn't work and is easier to understand is a call executed in a block before the forked block, for the same reason, but this is rarely done.
You might be wondering "why aren't more people complaining about this? Surely there are many users forking optimism and arbitrum", and I think the answer is that normally you send a transaction before making a call, which mines a new block and then the subsequent calls …

Add hardfork histories for opt and arb mainnet/sepolia

---

v-next/core/src/config.ts
v-next/core/src/internal/global-parameters.ts
v-next/core/src/types/global-parameters.ts
v-next/core/test/internal/global-parameters.ts
v-next/core/test/internal/tasks/task-manager.ts

Part of https://github.com/NomicFoundation/hardhat/issues/5379
This should be easy to review by going through it commit by commit.

buildGlobalParameterDefinition implementation & testing

---

v-next/core/src/index.ts
v-next/core/src/internal/global-parameters.ts
v-next/core/src/internal/hre.ts
v-next/core/src/internal/tasks/task-manager.ts
v-next/core/src/types/cli.ts
v-next/core/src/types/global-parameters.ts
v-next/core/test/internal/global-parameters.ts
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/main.ts

Part of https://github.com/NomicFoundation/hardhat/issues/5379
This should be easy to review by going through it commit by commit.
Merge this after https://github.com/NomicFoundation/hardhat/pull/5390

buildGlobalParametersMap implementation & testing

---

v-next/core/src/internal/hook-manager.ts
v-next/core/test/internal/fixture-plugins/config-plugin.ts
v-next/core/test/internal/hook-manager.ts
v-next/hardhat-errors/src/descriptors.ts

Add unit tests around the `HookManager` in `./v-next/core/src/internal/Hook-Manager.ts`.
It applies some small refactoring to the `HookManager` swapping in assertion instead of conditionals throwing errors, and replacing a plain `Error` with a specific `HardhatError`.
Resolves #5231.

hook manager tests

---

docs/src/content/ignition/docs/guides/_dirinfo.yaml
docs/src/content/ignition/docs/guides/upgradeable-proxies.md

Follows along with the example added in [here](https://github.com/NomicFoundation/hardhat-ignition/pull/655)

Added a guide for using upgradeable proxies with hardhat ignition

---

v-next/hardhat-node-test-reporter/integration-tests/index.ts

This PR fixes the test runner's integration tests, which had stopped passing with the release of Node v22.3.0.
The reason they were failing was that the stack traces have some references to Node's internals and those change across versions.
This PR removes those references before comparing the expected results.

Make the test reporter's integration tests more robust across node versions

---

packages/hardhat-network-helpers/test/helpers/reset.ts

This PR changes `hardhat-network-helper`'s tests from Goerli to Sepolia

Change network helpers' tests to Sepolia

---

.changeset/lovely-kiwis-hang.md
packages/hardhat-core/package.json
pnpm-lock.yaml

- [ x  ] Because this PR includes a **bug fix**, relevant tests have been included.
in [hardhat/packages/hardhat-core/src/internal/solidity/compiler/solcrunner.js](https://github.com/NomicFoundation/hardhat/blob/91f6e21c0c1a2ed3b42f9b8c6d1069d169efe7d7/packages/hardhat-core/src/internal/solidity/compiler/solcjs-runner.js#L26), the previously offending package `solc` is used.  this is `solc`'s only appearance in this ENTIRE project.  By bumping the solc version from 0.7.3 to 0.8.26, `rimraf` is no longer a dependency, and one instance of an outdated `glob` being used has also been removed.  
resolves #5427

changed solc version to 0.8.26 - resolves #5427

---

v-next/core/src/internal/global-options.ts
v-next/core/src/internal/parameters.ts
v-next/core/src/types/global-options.ts
v-next/core/test/internal/global-options.ts
v-next/core/test/utils.ts
v-next/hardhat-utils/src/string.ts
v-next/hardhat-utils/test/string.ts
v-next/hardhat/src/internal/cli/main.ts

Part of https://github.com/NomicFoundation/hardhat/issues/5379
This should be easier to review by reviewing each commit individually.
Merge this after https://github.com/NomicFoundation/hardhat/pull/5399

resolveGlobalArguments implementation & testing

---

v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/main.ts

Fixes https://github.com/NomicFoundation/hardhat/issues/5410
Ideally, this PR would split the tests into appropriate tests of `parseTask` and `parseTaskArguments`, however, there are many tests and the logic for testing both is deeply intertwined in both. Since the underlying logic is the same, I decided to simply make `parseTaskAndArguments` a test-only function abstraction since I don't think it's worth the dev time right now to fully break out all the tests.

move parseTaskAndArguments into the tests as a temporary fix for tests

---

scripts/check-v-next-dependencies.js

This PR fixes the v-next workflow to enforce consistent dependency versions across packages. It now doesn't take private packages into account.

Don't check dependencies of private packages

---

.changeset/config.json
config-v-next/eslint.cjs
pnpm-lock.yaml
v-next/core/.eslintrc.cjs
v-next/core/package.json
v-next/hardhat-build-system/.eslintrc.cjs
v-next/hardhat-build-system/package.json
v-next/hardhat-build-system/src/internal/solidity/parse.ts
v-next/hardhat-build-system/src/internal/solidity/resolver.ts
v-next/hardhat-build-system/src/internal/tasks.ts
v-next/hardhat-build-system/src/internal/utils/artifacts.ts
v-next/hardhat-build-system/src/internal/utils/fs-utils.ts
v-next/hardhat-build-system/src/internal/utils/source-names.ts
v-next/hardhat-errors/.eslintrc.cjs
v-next/hardhat-errors/package.json
v-next/hardhat-node-test-reporter/.eslintrc.cjs
v-next/hardhat-node-test-reporter/package.json
v-next/hardhat-utils/.eslintrc.cjs
v-next/hardhat-utils/package.json
v-next/hardhat-zod-utils/.eslintrc.cjs
v-next/hardhat-zod-utils/package.json
v-next/hardhat/.eslintrc.cjs
v-next/hardhat/package.json
v-next/template-package/.eslintrc.cjs
v-next/template-package/package.json

The two eslint rule packages are the only packages that are referenced in v-next.
To simplify in infra and lives we are going to switch off those rules in v-next for the moment. They can be re-added later.
Specifically this allows us to add the eslint rules to the ignore list of changeset.
Resolves #5447.

chore: remove eslint rules from packages in v-next

---

config-v-next/eslint.cjs
v-next/hardhat/src/cli.ts
v-next/hardhat/src/index.ts

This PR adds a rule to eslint to forbid top-level-await.
We use it in two files, but we shouldn't use it anywhere else. They are the client's entry point and the index of `hardhat`, both initialize instances of the HRE.

Forbid top-level-await

---

config-v-next/tsconfig.json
v-next/core/tsconfig.json
v-next/example-project/tsconfig.json
v-next/hardhat-build-system/tsconfig.json
v-next/hardhat-errors/tsconfig.json
v-next/hardhat-node-test-reporter/tsconfig.json
v-next/hardhat-utils/tsconfig.json
v-next/hardhat-zod-utils/tsconfig.json
v-next/hardhat/tsconfig.json
v-next/template-package/tsconfig.json

TS 5.5 added a `${configDir}` variable that you can use in shared configs to define values relative to the actual config dir. This allows you to simplify the shared configurations. This PR takes advantage of that.

Simplify `tsconfig.json` files with ${configDir}

---

packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/message-trace.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/vm-tracer.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts

---
Rather than defining the callbacks at the provider instantiation time for the entire lifetime of the provider, this allows for a more granular control of injecting the trace event listener (VMTracer), thus simplifying how the information flows. In the test logic, we no longer tightly couple two classes but have to keep them side by side and we can stop observing the EVM if needed, without paying the runtime cost.
While technically it's a standalone improvement, the https://github.com/NomicFoundation/edr/pull/531 can nicely build on top if it as it will also allow us to conveniently observe the trace whenever needed all at once in Rust (with the Rust port of `VmTracer` in that PR); it also removes some dead code.

Clean up the VMTracer and trace events interface in TS

---

v-next/core/test/internal/configuration-variables/configuration-variables.ts
v-next/core/test/internal/hook-manager.ts
v-next/core/test/internal/plugins/detect-plugin-npm-dependency-problems.ts
v-next/core/test/internal/plugins/resolve-plugin-list.ts
v-next/core/test/internal/tasks/builders.ts
v-next/hardhat-build-system/src/internal/error-descriptors.ts
v-next/hardhat-build-system/src/internal/solidity/compiler/downloader.ts
v-next/hardhat-build-system/src/internal/solidity/compiler/index.ts
v-next/hardhat-build-system/src/internal/solidity/dependencyGraph.ts
v-next/hardhat-build-system/src/internal/solidity/parse.ts
v-next/hardhat-build-system/src/internal/solidity/resolver.ts
v-next/hardhat-build-system/src/internal/tasks.ts
v-next/hardhat-build-system/src/internal/utils/artifacts.ts
v-next/hardhat-build-system/src/internal/utils/contract-names.ts
v-next/hardhat-build-system/src/internal/utils/source-names.ts
v-next/hardhat-build-system/test/index.ts
v-next/hardhat-build-system/test/internal/utils/artifacts.ts
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/test/hre/index.ts
v-next/hardhat/test/internal/builtin-plugins/run/runScriptWIthHardhat.ts

This PR removes the build system's descriptors to avoid copying over multiple unnecessary ones.
I did this by copying the required descriptors into the package itself and then deleting everything that was not needed. After removing many descriptors, I also had to reorder them. Reviewing commit by commit may be simpler. 
Also, while fixing some errors, I ensured that we weren't using `assert.throws` or `assert.rejects` with error messages. Because of that, too many tests were failing after this refactor.

Isolate the build-system package errors

---

config-v-next/eslint.cjs
v-next/core/src/internal/hre.ts
v-next/hardhat-build-system/.eslintrc.cjs
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat-utils/.eslintrc.cjs

This PR introduces a `no-restricted-syntax` rule that forbids throwing any error except for:
- `throw new HardhatError(...)`
- `throw variableName` within `catch` clauses. — The rationale here is to allow re-throwing of the error that was caught.
We could later improve this with a custom rule to:
- Allow subclasses of `HardhatError`
- Only allow `throw variable` when the variable is the one in the `catch (variable)`.
I believe that `no-restricted-syntax` isn't expressive enough for these things, as they are semantic conditions and not entirely syntactic. Still, I think this is a good trade-off.
PS: This depends on #5460 just for convenience and to avoid merge conflicts.

New only-hardhat-error rule

---

packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts

---
Seems to be a leftover from #4747 and it looks to be unused now as we create a new instance of `EdrProviderEventAdapter` explicitly in `create()` and move it into lambda.
Feel free to disregard if that's not true and/or we want to keep it.

Remove leftover `_eventAdapter` from `EdrProviderWrapper`

---

.changeset/wet-cars-sin.md
packages/hardhat-vyper/src/constants.ts
packages/hardhat-vyper/src/index.ts
packages/hardhat-vyper/test/fixture-projects/compilation-with-vyper-output-breakable-version/contracts/A.vy
packages/hardhat-vyper/test/fixture-projects/compilation-with-vyper-output-breakable-version/contracts/B.vy
packages/hardhat-vyper/test/fixture-projects/compilation-with-vyper-output-breakable-version/hardhat.config.js
packages/hardhat-vyper/test/tests.ts

---
Here's the refactored sentence with the additional details:
The new vyper version 0.4.0 returns output with source path instead of source name, so we need to address this on the plugin side. This PR will resolve some already created issues:
- https://github.com/NomicFoundation/hardhat/issues/5463
- https://github.com/matter-labs/hardhat-zksync/issues/1203

fix: support for vyper version 0.4.0 with the new output identifiers

---

packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/call-message/multiple-modifiers-require/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/call-message/multiple-modifiers-require/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/create-message/multiple-modifiers-require/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/modifiers/create-message/multiple-modifiers-require/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/between-statements/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/between-statements/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/no-other-statements/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/no-other-statements/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/statement-after/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/statement-after/test.json
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/statement-before/c.sol
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files/0_8/revert-without-message/revert-without-message/within-receive/statement-before/test.json

Avoid unconditional reverts in stack traces tests

---

.changeset/fuzzy-mangos-behave.md
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts

Now and then, there are some timeouts in EDR Hardhat tests ([example](https://github.com/NomicFoundation/edr/actions/runs/9759246239/job/26935518228?pr=537)) related to the provider initialization in a `beforeEach` hook.
This seems super weird to me. That before each only has two async operations: [a call to `createHardhatNetworkProvider`](https://github.com/NomicFoundation/edr/blob/dfdd38047d7a41b061abfad5fe8676c391dfd2b3/hardhat-tests/test/internal/hardhat-network/helpers/useProvider.ts#L81) and a `server.listen()` call a bit below that. I'm completely sure that the alchemy provider (which is the one with the timeout) doesn't use the server, so the only async operation is the provider creation.
But `createHardhatNetworkProvider` is async just because it calls the `makeTracingConfig` …

Add debug logs for provider creation

---

v-next/core/src/internal/parameters.ts
v-next/core/test/internal/global-options.ts
v-next/core/test/internal/tasks/builders.ts
v-next/example-project/hardhat.config.ts
v-next/hardhat/src/internal/builtin-options.ts
v-next/hardhat/src/internal/cli/helpers/getGlobalHelpString.ts
v-next/hardhat/src/internal/cli/helpers/utils.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/helpers/getGlobalHelpString.ts
v-next/hardhat/test/internal/cli/main.ts

See https://github.com/NomicFoundation/hardhat/issues/5418#issuecomment-2201166033 for details. This can be reviewed commit by commit.

Updates to RESERVED_PARAMETER_NAMES and GLOBAL_OPTIONS

---

v-next/core/src/config.ts
v-next/core/src/internal/global-options.ts
v-next/core/src/internal/tasks/builders.ts
v-next/core/src/internal/tasks/resolved-task.ts
v-next/core/src/types/global-options.ts
v-next/core/src/types/tasks.ts
v-next/core/test/internal/global-options.ts
v-next/core/test/internal/tasks/builders.ts
v-next/core/test/internal/tasks/task-manager.ts
v-next/hardhat/src/internal/builtin-options.ts
v-next/hardhat/src/internal/cli/helpers/utils.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/helpers/getGlobalHelpString.ts
v-next/hardhat/test/internal/cli/helpers/getHelpString.ts
v-next/hardhat/test/internal/cli/helpers/utils.ts
v-next/hardhat/test/internal/cli/main.ts

Closes https://github.com/NomicFoundation/hardhat/issues/5415

Normalize naming of parameter type

---

v-next/core/src/index.ts
v-next/core/src/internal/global-options.ts
v-next/core/src/internal/hre.ts
v-next/core/src/internal/tasks/task-manager.ts
v-next/core/src/types/cli.ts
v-next/core/src/types/global-options.ts
v-next/core/test/internal/global-options.ts
v-next/hardhat/src/internal/cli/helpers/getGlobalHelpString.ts
v-next/hardhat/src/internal/cli/helpers/utils.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/helpers/getGlobalHelpString.ts
v-next/hardhat/test/internal/cli/main.ts

Closes https://github.com/NomicFoundation/hardhat/issues/5416
Part of https://github.com/NomicFoundation/hardhat/issues/5420

Rename globalOptionsMap to globalOptionDefinitions

---

v-next/hardhat/.eslintrc.cjs
v-next/hardhat/src/hre.ts
v-next/hardhat/src/index.ts
v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/index.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/hre-singleton.ts
v-next/hardhat/test/fixture-projects/run-ts-script/scripts/success.ts
v-next/hardhat/test/hre/index.ts
v-next/hardhat/test/internal/builtin-plugins/run/runScriptWIthHardhat.ts
v-next/hardhat/test/internal/cli/main.ts

This PR fixes a bug I found, that prevented the builtin plugins from being loaded when a user was initializing the HRE with `import "hardhat"`. This PR fixes that by ensuring that the HRE is always initialized using `hardhat/hre`.
The changes introduced here are, in order:
- Introduced a failing test, showing the bug.
- Refactor the initialization process to always use the `hardhat/hre` module.
- Fix some unrelated failing test after the refactor.
- Added an eslint rule to `hardhat` to avoid repeating that mistake.

Fix `hre` initialization

---

pnpm-lock.yaml
v-next/hardhat-build-system/package.json
v-next/hardhat-build-system/tsconfig.json
v-next/hardhat-test-utils/.eslintrc.cjs
v-next/hardhat-test-utils/.gitignore
v-next/hardhat-test-utils/.prettierignore
v-next/hardhat-test-utils/LICENSE
v-next/hardhat-test-utils/README.md
v-next/hardhat-test-utils/package.json
v-next/hardhat-test-utils/src/hardhat-error.ts
v-next/hardhat-test-utils/src/index.ts
v-next/hardhat-test-utils/test/hardhat-error.ts
v-next/hardhat-test-utils/tsconfig.json
v-next/hardhat-zod-utils/package.json
v-next/hardhat-zod-utils/tsconfig.json
v-next/hardhat/package.json
v-next/hardhat/tsconfig.json
v-next/template-package/package.json
v-next/template-package/tsconfig.json

This PR introduces a new private package, `@nomicfoundation/hardhat-test-utils`, and installs it in all the `v-next` packages that are compatible with it (i.e. not dendencies of it).
This PR only introduces helpers for `HardhatError` related assertions, but it doesn't change any existing test.
A follow-up PR will change the existing tests to use the new utilities.

Add `hardhat-test-utils` package

---

pnpm-lock.yaml
v-next/core/package.json
v-next/core/src/global-dir.ts
v-next/core/test/global-dir.ts

[Link to task](https://github.com/NomicFoundation/hardhat/issues/5490)

Add file in hh-core to handle hardhat configuration paths

---

config-v-next/eslint.cjs
pnpm-lock.yaml
v-next/core/package.json
v-next/core/test/internal/configuration-variables/configuration-variables.ts
v-next/core/test/internal/global-options.ts
v-next/core/test/internal/hook-manager.ts
v-next/core/test/internal/plugins/detect-plugin-npm-dependency-problems.ts
v-next/core/test/internal/plugins/resolve-plugin-list.ts
v-next/core/test/internal/tasks/builders.ts
v-next/core/test/internal/tasks/task-manager.ts
v-next/core/tsconfig.json
v-next/hardhat-test-utils/.eslintrc.cjs
v-next/hardhat-test-utils/src/hardhat-error.ts
v-next/hardhat/test/hre/index.ts
v-next/hardhat/test/internal/builtin-plugins/run/runScriptWIthHardhat.ts
v-next/hardhat/test/internal/cli/init/init.ts
v-next/hardhat/test/internal/cli/main.ts

This PR adds new `eslint` rules to forbid the error-related assertions that `node:assert/strict` has, and forces us to use our own instead.
It also fixies all the new linter errors, so it's a large and repetitive PR.

Use `hardhat-test-utils`' functions

---

.changeset/fuzzy-eyes-collect.md
packages/hardhat-verify/src/internal/tasks/etherscan.ts

---
There is a bug in blockscout's latest releases. It has been around for quite a while. Unfortunately it only happens in certain situations. The [issue](https://github.com/blockscout/blockscout/issues/9001) is that an `isVerified` check will fail if the backend is put into a certain state. The easy way around this would simply be to include that set of errors / states to be ignored when provided a force flag. 
I do not think that hardhat verify should cover all of the quirks of the many backends that are bound to emerge into eternity, however, I think that the force flag being more comprehensive (less narrowly applied) than it currently is could be a reasonable middle ground, provided that it does not run afoul of any eip's.

Adds logic for forcing through verification when is verified check fails

---

v-next/core/src/config.ts
v-next/core/src/internal/global-options.ts
v-next/core/src/internal/tasks/builders.ts
v-next/core/src/internal/tasks/resolved-task.ts
v-next/core/src/types/arguments.ts
v-next/core/src/types/global-options.ts
v-next/core/src/types/plugins.ts
v-next/core/src/types/tasks.ts
v-next/core/test/internal/tasks/builders.ts
v-next/core/test/internal/tasks/task-manager.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/fixture-projects/cli/parsing/tasks-and-subtasks/hardhat.config.ts
v-next/hardhat/test/internal/cli/main.ts

Merge after https://github.com/NomicFoundation/hardhat/pull/5495
Closes https://github.com/NomicFoundation/hardhat/issues/5419

Make options optional

---

v-next/core/src/internal/tasks/builders.ts
v-next/core/src/internal/tasks/resolved-task.ts
v-next/core/src/internal/tasks/task-manager.ts
v-next/core/src/internal/tasks/utils.ts
v-next/core/src/internal/tasks/validations.ts
v-next/core/src/types/arguments.ts
v-next/core/test/internal/tasks/task-manager.ts
v-next/core/test/internal/tasks/utils.ts

This PR includes 3 unrelated fixes for tasks that were discussed with Pato in a previous PR. These can be reviewed commit by commit:
1. Ensure the `taskArguments` provided to the `run` method are not modified. Previously, this could happen when a default value was assigned to a missing argument.
2. Fix a type error in the `OptionDefinition`.
3. Validate the task object in the `TaskManager`. This is needed because the user can provide a plain task object instead of using the builders, skipping the validations.

Task fixes

---

v-next/example-project/hardhat.config.ts

This is a small PR fixing some compilation errors in the example config file.

Fix the example project's config file

---

.changeset/great-crabs-hug.md
.changeset/modern-points-cover.md
docs/src/content/hardhat-network/docs/reference/index.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/core/providers/construction.ts
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/provider/vm/exit.ts
packages/hardhat-core/src/types/config.ts
packages/hardhat-core/test/internal/hardhat-network/helpers/useProvider.ts
packages/hardhat-core/test/internal/hardhat-network/stack-traces/execution.ts
pnpm-lock.yaml

This PR upgrades EDR to v0.5 which includes support for EIP-7212.
Closes https://github.com/NomicFoundation/edr/issues/523.

Upgrade to EDR v0.5 and add `enableRip7212` option

---

docs/src/content/ignition/docs/advanced/migrating.md

Fixes this in the [Migrating from hardhat-deploy](https://hardhat.org/ignition/docs/advanced/migrating) guide:
I also added some other minor cosmetic fixes/changes in the file, check individual commits.

Fix numbered list in docs

---

v-next/core/src/index.ts
v-next/core/src/internal/hook-manager.ts
v-next/core/src/internal/hre.ts
v-next/core/src/internal/plugins/detect-plugin-npm-dependency-problems.ts
v-next/core/src/internal/plugins/resolve-plugin-list.ts
v-next/core/src/internal/tasks/resolved-task.ts
v-next/core/src/types/config.ts
v-next/core/test/internal/configuration-variables/configuration-variables.ts
v-next/core/test/internal/hook-manager.ts
v-next/core/test/internal/plugins/detect-plugin-npm-dependency-problems.ts
v-next/core/test/internal/plugins/resolve-plugin-list.ts
v-next/core/test/internal/user-interruptions/user-interruptions-manager.ts
v-next/hardhat-utils/src/package.ts
v-next/hardhat-utils/test/package.ts
v-next/hardhat/src/hre.ts
v-next/hardhat/src/index.ts
v-next/hardhat/src/internal/cli/main.ts

This PR revamps how we manage the project root resolution and how it impacts other parts of the system.
The project root in Hardhat v3 will be the root of the npm package containing the Hardhat config file, or the one containing the CWD if an instance of the HRE is initialized without using a config file.
This PR touches several files, so here's a summary of the changes:
- The base HRE constructor in the `core` package now accepts an optional projectRoot.
- There's now a `resolveProjectRoot`  helper exposed in `core`.
- Plugin installation error detection is now run based on the project root, as plugins and their dependencies should all be installed in the npm package containing the project.
- I added that same error detection logic to the hook manager, because loading actions can fail.
- …

[WIP] Project root resolution

---

v-next/core/src/global-dir.ts
v-next/core/src/internal/hre.ts
v-next/core/src/types/config.ts
v-next/core/test/internal/configuration-variables/configuration-variables.ts
v-next/core/test/internal/hook-manager.ts
v-next/core/test/internal/user-interruptions/user-interruptions-manager.ts
v-next/hardhat/src/internal/builtin-plugins/clean/index.ts
v-next/hardhat/src/internal/builtin-plugins/clean/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/index.ts
v-next/hardhat/test/internal/builtin-plugins/clean/task-action.ts
v-next/hardhat/test/internal/builtin-plugins/run/task-action.ts
v-next/hardhat/test/internal/cli/main.ts

This PR requires https://github.com/NomicFoundation/hardhat/pull/5527 ~and https://github.com/NomicFoundation/hardhat/pull/5517.~
The logic to create the `cache` and `artifacts` paths is missing, as it's outside the scope of this issue. Because of this, the tests are somewhat "manual" – we handle the folders manually to simulate different scenarios. However, this should be acceptable.
~The build is currently failing because it needs [PR #5517](https://github.com/NomicFoundation/hardhat/pull/5517) and some additional code (e.g., adding the `cache` and `artifacts` properties in `v-next/core/test/internal/hook-manager.ts`).~
The task might require additional steps, such as calling `artifacts.clearCache?.()`, which depends on how the new build system works.

Clean task

---

.changeset/breezy-chairs-relax.md
.changeset/early-laws-trade.md
CONTRIBUTING.md
packages/hardhat-solhint/package.json
packages/hardhat-solhint/src/index.ts
packages/hardhat-solhint/test/fixture-projects/no-errors-project/.solhint.json
packages/hardhat-solhint/test/fixture-projects/no-errors-project/contracts/Greeter.sol
packages/hardhat-solhint/test/fixture-projects/no-errors-project/hardhat.config.js
packages/hardhat-solhint/test/tests.ts
pnpm-lock.yaml

---
Resolves https://github.com/NomicFoundation/hardhat/issues/5057
This PR modifies the `hardhat-solhint` plugin.
It changes the `check` task behaviour. After the changes, when `solhint` reports **any** errors (note, this does not apply to warnings), the task exists with error code 1.
The updated behaviour is in line with how `solhint` behaves as a standalone CLI tool.
Please note that this is, currently, a breaking change since it's modifying solhint plugin/check task behaviour. I will update the changesets and mark the PR as "ready for review", once we align on the open questions I outline below.
1. ~~Should we update `solhint` to the most recent version `v5.0.2`?~~ Yes
2. ~~Should we control the newly added behaviour via configuration? If so, we could also support failing the check …

fix: exit check task with exit code 1 when solhint raises errors

---

.github/workflows/v-next-changesets-release.yml
.github/workflows/v-next-ci.yml

---
This PR is a subset of #5301 and, unlike the original, it targets the `v-next` branch.
In this PR, I update GitHub actions to the latest versions. I reviewed the changelogs to ensure there are no breaking changes announcements that would affect us.
I also reviewed the workflow triggers to ensure we don't use invalid syntax (e.g. `$default-branch`) and that we use them consistently.
I will propose improvements to the caching setup and work deduplication in separate PRs to minimise the diffs.

ci(v3): update GitHub actions and review workflow triggers

---

pnpm-lock.yaml
v-next/core/package.json
v-next/hardhat-utils/package.json
v-next/hardhat-utils/src/debug.ts
v-next/hardhat/package.json
v-next/hardhat/src/internal/cli/main.ts

- added basic debug logging throughout the main CLI function
- added a `withDebugLogs` decorator to core to easily enable debug logging to any class method
- added this decorator to some class methods that I thought would be helpful, but it can always be added to others in the future as well
fixes #5363 
I would add a screenshot of the output, but there's A Lot. Recommend pulling the branch and testing inside `v-next/example-project`

Basic debug logging

---

.changeset/shaggy-bags-work.md
packages/hardhat-core/src/internal/core/providers/http.ts
packages/hardhat-core/test/internal/core/providers/http.ts

---
Resolves #5406
The goal of this PR is to suppress `hardhat_setLedgerOutputEnabled - Method not supported` warnings from the local hardhat node logs. They appear there when one performs a deployment against a node and does not use `hardhat-ledger` plugin.
The approach presented in this PR is a "quick fix". It assumes that if a message with `hardhat_setLedgerOutputEnabled` method reaches an HTTP provider, it should be treated as an error and not processed further (otherwise, it would have been consumed by the ledger provider before it could reach the http provider). This ensures that if `hardhat-ledger` plugin is not used, the `hardhat_setLedgerOutputEnabled` message will never reach a running node. Hence, a warning will not be printed out by the node.
This is not an ideal solution as …

chore: do not send hardhat_setLedgerOutputEnabled over http

---

pnpm-lock.yaml

---
I noticed that the pnpm lockfile is broken on the `v-next` currently. This is likely because I merged https://github.com/NomicFoundation/hardhat/pull/5574 which brought in `main` into `v-next` so it naturally had a lot of changes (including having to rewrite pnpm lock) and then https://github.com/NomicFoundation/hardhat/pull/5541 got merged which likely got tested before and, later, the conflict was too obscure for GitHub to notice.
To fix the lockfile, I just ran `pnpm install` in the root.

fix: run pnpm install to fix the lockfile

---

v-next/core/src/types/hooks.ts

I fixed some typos and removed the dash after the parameter names since VS Code already adds a dash in the tooltips. The extra dash was being interpreted as a bullet point, which caused it to look odd.

chore: cleanup comments in hook types

---

package.json
pnpm-lock.yaml

---
We use `${configDir}` template variable in our `tsconfig.json` on `v-next` (e.g. https://github.com/NomicFoundation/hardhat/blob/bae09d38603cc31b7257c43b9d3abc768384abd4/config-v-next/tsconfig.json#L4) which has only been released in TypeScript 5.5 (https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#the-configdir-template-variable-for-configuration-files).
I've noticed it only, because I had my VSCode configured to use the workspace version of TypeScript, and when browsing files in `v-next`, it'd fail to resolve types.

chore: upgrade typescript to ~5.5.0

---

v-next/hardhat/src/internal/builtin-plugins/console/index.ts
v-next/hardhat/src/internal/builtin-plugins/console/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/index.ts
v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts
v-next/hardhat/test/internal/cli/main.ts

---
Resolves #5575
This PR adds a `console` task to the next version of `hardhat`. Here's how it looks like:
```
$ # Show console task's help
$ 
$ pnpm hardhat console --help
Opens a hardhat console
Usage: hardhat [GLOBAL OPTIONS] console [--history <STRING>] [--no-compile] [--] [commands]
OPTIONS:
--history         Path to a history file
--no-compile      Don't compile before running this task
POSITIONAL ARGUMENTS:
commands          Commands to run in the console
For global options help run: hardhat --help
$ 
$ # Run the console task and preview the `hre` context variable
$ 
$ pnpm hardhat console
> .help
.break    Sometimes you get stuck, this gets you out
.clear    Break, and also clear the local context
.editor   Enter editor mode
.exit     Exit the REPL
.help     Print this help …
```

feat: add a built-in console task

---

.changeset/popular-ways-whisper.md
packages/hardhat-ethers/src/internal/helpers.ts
packages/hardhat-ethers/test/index.ts

Erigon now responds that `eth_accounts` is deprecated when we make an RPC call. Instead of erroring we now return an empty set of accounts from `hre.ethers.getSigners` if `eth_accounts` is deprecated. Effectively we fall back with no unlocked accounts available from the node.
Fixes #5572.
This was tested by running a local [Erigon node in dev mode](https://github.com/erigontech/erigon/blob/release/2.60/DEV_CHAIN.md), connecting to it via a Hardhat script and invoking `hre.ethers.getSigners()`.

fix: return no accounts if `eth_accounts` is deprecated

---

.changeset/loud-cooks-obey.md
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts

In https://github.com/NomicFoundation/hardhat/pull/5478 I added some debug logs to investigate a false negative we have now and then on EDR's CI. But I forgot to await the provider creation, so these logs are pretty useless as they are.
This PR just adds the proper await.

Add await in provider creation

---

v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts

---
I have noticed that the console task test that I recently added is flaky, e.g. https://github.com/NomicFoundation/hardhat/actions/runs/10484622700/job/29039290910
```
1) console/task-action
test/internal/builtin-plugins/console/task-action.ts:
Error: Unable to deserialize cloned data due to invalid or unsupported version.
at #proccessRawBuffer (node:internal/test_runner/runner:319:20)
at FileTest.parseMessage (node:internal/test_runner/runner:255:28)
at Socket.<anonymous> (node:internal/test_runner/runner:353:15)
at Socket.emit (node:events:520:28)
at addChunk (node:internal/streams/readable:559:12)
at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
at Readable.push (node:internal/streams/readable:390:5)
at Pipe.onStreamRead …
```

ci: do not pipe output to stdout during console test

---

.github/workflows/v-next-ci.yml

---
This is an alternative to https://github.com/NomicFoundation/hardhat/pull/5675 which ensures we run `ci` and `lint` on every PR to `v-next`. 
We could consider extracting `check_*` jobs out of the workflow since neither `ci` nor `lint` depend on it but I don't think that's strictly necessary.

ci: trigger v-next ci on pull requests to v-next branch

---

v-next/hardhat/src/cli.ts
v-next/hardhat/src/internal/cli/main.ts

This is a small PR that changes how we load `tsx` in the CLI, to follow [its documentation](https://tsx.is/dev-api/register-esm).

Change how we load tsx

---

.github/workflows/v-next-ci.yml
v-next/core/.gitignore
v-next/example-project/.gitignore
v-next/hardhat-build-system/.gitignore
v-next/hardhat-errors/.gitignore
v-next/hardhat-node-test-reporter/.gitignore
v-next/hardhat-test-utils/.gitignore
v-next/hardhat-utils/.gitignore
v-next/hardhat-zod-utils/.gitignore
v-next/hardhat/.gitignore
v-next/template-package/.gitignore

---
Resolves #5366 
This PR implements the solution to dependency tracking initiative proposed in https://www.notion.so/nomicfoundation/Hardhat-Dependency-Tracking-4da1bbd17a7443b7a2ab9f9da1931903?pvs=4
The newly added job posts "sticky" comments on PRs, ensuring that there is no more than 1 comment generated by the job per PR.
An example of a comment - https://github.com/NomicFoundation/hardhat/pull/5653#issuecomment-2298481372

ci: start tracking hardhat dependencies

---

.github/workflows/v-next-ci.yml

---
This PR fixes the following two issues:
- If `pnpm-lock.yaml` was NOT modified, we should not post a comment. Currently, we're posting a comment that looks like this - https://github.com/NomicFoundation/hardhat/pull/5681#issuecomment-2312898202. To fix this, I added a check to see whether the bundle aggregate downloaded any bundles or not.
- An uploaded bundle artifact should include `node_modules`. After https://github.com/pnpm/pnpm/pull/8465, in our setup, `pnpm deploy` started producing two `node_modules` dirs at two different locations (only one of them being inside the bundle path). To quickly fix this, I added a loop which moves the links from the "wrong" `node_modules` directory to the correct one.
TODO:

ci: fix hardhat dependencies reporting

---

v-next/hardhat-mocha-test-runner/src/task-action.ts
v-next/hardhat-node-test-runner/src/task-action.ts

---
This is a follow-up to the discussions in https://github.com/NomicFoundation/hardhat/pull/5584#discussion_r1731096110 and https://nomicfoundation.slack.com/archives/C05MKFQJBCH/p1724801183793089?thread_ts=1724682710.005219&cid=C05MKFQJBCH
This PR ensures that both node:test and mocha test runner plugins set the process exit code to 1 instead of a number of failures when they encounter test failures. This ensures our exit code usage is along what's commonly expected, e.g. https://tldp.org/LDP/abs/html/exitcodes.html

chore: set exit code to 1 on test failures

---

config-v-next/eslint.cjs
v-next/hardhat-mocha-test-runner/src/hookHandlers/config.ts
v-next/hardhat-zod-utils/src/index.ts
v-next/hardhat-zod-utils/test/index.ts
v-next/hardhat-zod-utils/tsconfig.json
v-next/hardhat/src/internal/builtin-plugins/hardhat-foo/hook-handlers/config.ts
v-next/hardhat/src/internal/cli/telemetry/analytics/subprocess.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/subprocess.ts

This PR introduces a few improvements to the zod utils package and how we use it:
- It disables `isolatedModules` in that package as it's super inconvenient and just an internal package.
- It introduces a `unionType` helper, equivalent to `z.union` but with a custom error message.
- It introduces a `sensitiveUrlType,` which is a variant of `sensitiveStringType.`
- It adds linter rules to prevent us from using `z.union` in the future.
While building this, I discovered a misconfiguration in `eslint`, so I fixed the config and every new linter error I found after that.

Zod utils improvements

---

.changeset/bright-falcons-impress.md
.changeset/lovely-onions-notice.md
.changeset/olive-comics-kick.md
.changeset/pink-bees-search.md
.changeset/six-colts-cover.md

We release packages via pnpm, version 9.4.0 incorrectly swapped out `workspace:^2.0.0` as `^2.22.92.0.0` in some of our packages for the hardhat peer dependency.
See `hardhat-ethers@3.0.7` code tab on npm as an example:
https://www.npmjs.com/package/@nomicfoundation/hardhat-ethers?activeTab=code
I have went pack through our releases since the start of the year identifying packages where the latest version has a corrupted `peerDependency`.
We are adding patch changesets to trigger new release using the latest version of pnpm, for:
- hardhat-ethers
- hardhat-solhint
- hardhat-verify
- hardhat-vyper
- hardhat-viem
See this discussion thread on the pnpm issue: https://github.com/pnpm/pnpm/pull/8261
And the follow on fix: https://github.com/pnpm/pnpm/pull/8383
Fixes #5694.

fix: correct peer dependency for Hardhat

---

docs/src/content/hardhat-runner/plugins/plugins.ts

This PR adds a new plugin named hardhat-switch-network which is used to enable on-the-fly network switching within Hardhat scripts, tests and tasks.
It can be found on this: https://github.com/0xNeshi/hardhat-switch-network
It's npm repo: https://www.npmjs.com/package/hardhat-switch-network
It is supposed so replace the now-unmaintained package [hardhat-change-network](https://www.npmjs.com/package/hardhat-change-network), which is also listen in the the _plugins.ts_ file [here](https://github.com/fwx5618177/hardhat/blob/main/docs/src/content/hardhat-runner/plugins/plugins.ts#L282)

Add hardhat-switch-network plugin

---

v-next/example-project/hardhat.config.ts

Fix building error caused by [this PR](https://github.com/NomicFoundation/hardhat/pull/5702).
The property `privateKey` should have been deleted in the example-project because it was added by the temporary `hardhatFoo plugin`. 
The plugin has been removed so the property is no longer available

Remove unused plugin property

---

v-next/hardhat/src/internal/builtin-plugins/console/index.ts

This PR removes the `.help` command as the default one to be run when we start the console.
The reason here is that the help message is generic about Node.js, and that can confuse, given that users expect a "hardhat console" and most probably hardhat-related help.
We can consider adding a hardhat-specific help command later.
I also reworded the description of the `commands` params, to make it clear that it's run at the beginning, vs them being the only commands run.

No `.help` on console start

---

v-next/hardhat-test-utils/src/fs.ts
v-next/hardhat-test-utils/src/index.ts
v-next/hardhat/src/internal/cli/prompt/prompt.ts
v-next/hardhat/src/internal/cli/telemetry/telemetry-permissions.ts
v-next/hardhat/src/internal/constants.ts
v-next/hardhat/src/internal/global-dir.ts
v-next/hardhat/test/internal/cli/telemetry/telemetry-permissions.ts

This PR adds many (temporary) logs to the telemetry consent workflow, as I suspect there's a bug somewhere.
While doing that, I discovered and fixed a bug: If the user canceled a prompt, we'd still wait 10 seconds.

Fix two bugs in the telemetry consent workflow

---

v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
v-next/hardhat/test/fixture-projects/run-ts-script/scripts/throws-hardhat-error.ts
v-next/hardhat/test/internal/builtin-plugins/run/task-action.ts

When using `hardhat run` I noticed that we were "encapsulating" any `HardhatError` thrown by the script in another `HardhatError`. This PR changes that to rethrow it instead. 
The reasoning here is that if we throw the error, we want it to reach the user as is.

Re-throw hardhat errors from scripts

---

pnpm-lock.yaml
v-next/hardhat-utils/package.json
v-next/hardhat-utils/src/crypto.ts
v-next/hardhat/package.json

This PR introduces two changes:
- It unpins the version of `ethereum-cryptography` in `hardhat`, which had no reason to be pinned.
- It uses `ethereum-cryptography` in `hardhat-utils` to be consistent with the dependencies that we use, hence decreasing the total number of dependencies.

`ethereum-cryptography` cleanup

---

v-next/hardhat-utils/test/subprocess.ts

The test to verify that the subprocess functionality works correctly is structured as follows:
1 -  the main test process starts and call the subprocess util function 
2- a subprocess is spawned, which writes specific data to a JSON file (this data is used to test that the subprocess was executed correctly)
3 - the main test process sets an interval and waits for the file to be ready
4 - once the file is ready, the main test process verifies that the data within it is accurate
Problem: 
There are cases where the file is created, prompting the main test process to access it. However, the data might not be fully written yet, leading to an error because the JSON file is improperly formatted.
Solution: 
During the interval that checks whether the JSON file has been created, also validate the …

hh-utils flaky subprocess test: ensure the JSON file is fully written before attempting to read it

---

docs/src/content/hardhat-runner/plugins/plugins.ts

The plugin is unmaintained, [asked if it should be removed](https://github.com/NomicFoundation/hardhat/pull/5703#issuecomment-2325571462) and got an [affirmative response](https://github.com/NomicFoundation/hardhat/pull/5703#issuecomment-2327205196).

Remove hardhat-change-network plugin

---

docs/src/content/hardhat-chai-matchers/docs/migrate-from-waffle.md
docs/src/content/hardhat-chai-matchers/docs/overview.md
docs/src/content/hardhat-network-helpers/docs/overview.md
docs/src/content/hardhat-runner/docs/advanced/create-task.md
docs/src/content/hardhat-runner/docs/advanced/migrating-from-hardhat-waffle.md
docs/src/content/hardhat-runner/docs/advanced/using-esm.md
docs/src/content/hardhat-runner/docs/getting-started/index.md
docs/src/content/hardhat-runner/docs/guides/project-setup.md
docs/src/content/hardhat-runner/docs/supporter-guides/oracles.md
docs/src/content/ignition/docs/advanced/migrating.md
docs/src/content/ignition/docs/getting-started/index.md
docs/src/content/ignition/docs/guides/ledger.md
docs/src/content/ignition/docs/guides/upgradeable-proxies.md
docs/src/content/ignition/docs/guides/viem.md
docs/src/content/tutorial/creating-a-new-hardhat-project.md
docs/temp/tabsConfig.json

---
- Add `pnpm` to document
- Change 'frameborder' to 'frameBorder' to resolve terminal warning.
~~By default, pnpm does not automatically install peer dependencies. To enable this behavior, users must set auto-install-peers=true in the .npmrc file. So I need to list all packages as I would when using yarn.~~
Update: pnpm is automatically install peer dependencies, if user want use the package in code, user  need to add it as a dependency

docs: add pnpm to document

---

v-next/example-project/package.json
v-next/hardhat-build-system/package.json
v-next/hardhat-errors/package.json
v-next/hardhat-mocha-test-runner/package.json
v-next/hardhat-node-test-reporter/package.json
v-next/hardhat-node-test-runner/package.json
v-next/hardhat-test-utils/package.json
v-next/hardhat-utils/package.json
v-next/hardhat-zod-utils/package.json
v-next/hardhat/package.json
v-next/template-package/package.json

---
While trying to replicate https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1725284046675349, I discovered that the described issue was most likely caused by not running `pnpm install` after a switch to a branch which added new dependencies.
For `pnpm test`, we were already ensuring that `pnpm build` is run before the test command. This makes it quite obvious when dependencies are missing because the build process fails.
We weren't doing the same for `pnpm test:only`, which resulted in more cryptic errors coming from tests. In this PR, I'm proposing to add the pre step for that task, too.
I'm also removing `prepublishOnly` since we do not define `publishOnly` task.
To replicate the issue that this PR is trying to address:
1. Check out `galargh/promise-await` branch …

fix: pnpm build before pnpm test:only

---

.changeset/kind-radios-begin.md
packages/hardhat-viem/src/internal/clients.ts
packages/hardhat-viem/src/internal/type-extensions.ts
packages/hardhat-viem/src/types.ts
packages/hardhat-viem/test/clients.ts
packages/hardhat-viem/test/mocks/provider.ts

added some small type changes to allow for more extensibility, as well ensuring there are 0 retries when on developer networks to avoid wasting time when testing for errors
- added initialisation of `ContractTypesMap` as empty so it can be referenced without an initial contract compiled (e.g. for an external lib)
- moved the types under `HardhatRuntimeEnvironment.viem` to their own interface `HardhatViemHelpers` which allows the `viem` object to be extended with other types
the default `retryCount` on the custom transport is 3, meaning in most cases RPC requests are retried 3 times.
when writing tests with expected reverts from write calls this is ok, since the `sendTransaction` function specifies a retry count of 0. however, when testing read calls with expected reverts this isn't the …

fix(hardhat-viem): type consistency + retryCount 0 on devnet

---

.changeset/ninety-trainers-rush.md
packages/hardhat-chai-matchers/src/internal/reverted/reverted.ts
packages/hardhat-chai-matchers/src/internal/reverted/utils.ts
packages/hardhat-chai-matchers/test/reverted/reverted.ts

---
Add when receipt is null, check if value is a byte32 string. minimal changes were in PRto resolve #4725 
I see the following comment in the code
```js
// If the subject of the assertion is not connected to a transaction
// (hash, receipt, etc.), then the assertion fails.
// Since we use `false` here, this means that `.not.to.be.reverted`
// assertions will pass instead of always throwing a validation error.
// This allows users to do things like:
//   `expect(c.callStatic.f()).to.not.be.reverted`
assert(false, "Expected transaction to be reverted");
```
So i think maybe we can change the check to :
```js
if (
isTransactionResponse(value) ||
(typeof value === "string" && isValidTransactionHash(value))
) {
const hash = typeof value === "string" ? value : value.hash;
// if …
```

fix: hardhat-chai-matchers - add check byte32 string to reverted matcher

---

.changeset/warm-tables-dress.md
packages/hardhat-core/package.json
pnpm-lock.yaml

---
I bumped Chokidar to v4 from v3, which removed 11 dependencies and glob support, which Hardhat is not using. It still depends on mocha which depends on v3.5, so I will create a subsequent PR to bump it there

hardhat-core: upgrade chokidar to v4

---

config-v-next/eslint.cjs
pnpm-lock.yaml
v-next/hardhat-mocha-test-runner/src/hookHandlers/config.ts
v-next/hardhat-node-test-runner/src/hookHandlers/config.ts
v-next/hardhat-zod-utils/package.json
v-next/hardhat-zod-utils/src/index.ts
v-next/hardhat-zod-utils/test/index.ts
v-next/hardhat-zod-utils/tsconfig.json

This PR adds a new helper to our zod utils.
I originally planned to remove the old `unionType`, but it's still valid.
I also introduced another helper that's meant to be used with `conditionalUnionType`: `incompatibleFieldType`. See its docs.

Introduce the Zod `conditionalUnionType` helper

---

.changeset/chilled-sheep-buy.md
packages/hardhat-core/src/internal/core/providers/lazy-initialization.ts
packages/hardhat-core/test/internal/core/providers/lazy-initialization.ts

Provider events are not working when `provider.init` is called explicitly, instead of the provider being implicitly initialized with the first request. The problem was that the events were only forwarded in the `_getOrInitProvider` function instead of that being done in `init`. This PR fixes this and adds a test for that scenario.

Fix provider events when init is called

---

docs/src/content/hardhat-runner/docs/getting-started/index.md

Docs update config to allow access to rpc from external ip on specific port using hostname flag

---

v-next/hardhat/src/internal/core/hook-manager.ts
v-next/hardhat/src/types/hooks.ts
v-next/hardhat/test/internal/core/hook-manager.ts

The plugin reverse ordering of handlers makes sense for the chained
running of hooks but is wrong for the sequential running, where
dependent plugins should run before the dependee.
We make several moves:
- remove the `getHandlers` method from the API as it is only used
internally to the hook manager
- create equivalents to `getHandlers` with explicit logic for reversing
the plugin order for chained running, and keeping the dependency order
for sequential.
This PR should be reviewed a commit at a time to avoid the jitter from the test restructuring.

fix: rework `runSequentialHandlers` plugin ordering

---

v-next/hardhat/src/internal/core/hre.ts
v-next/hardhat/src/types/hooks.ts
v-next/hardhat/test/internal/core/hook-manager.ts

This PR addresses a limitation in Hardhat's core architecture discovered by @ChristopherDedominici.
Chris is working on the first few hook handlers that use the builtin plugins, and in particular, the extensions to the `HRE` that they make.
This was problematic, as `HookHandler`s don't receive the `HRE`, but a `HookContext` instead. The problem was that any extension to the `HRE` wasn't reflected in the `HookContext`.
The' HookContext' intends to prevent `HookHandler`'s from accessing the `TaskManager` and running tasks, as these are separate concerns in v3, and not to prevent them from accessing the builtin plugins.
This solution has a type-level and runtime-level component.
Instead of defining the `HookContext` as a separate interface, define it as a derived type of the `HRE`:
```ts …
```

Define the `HookContext` as a partial view of the `HRE`

---

v-next/hardhat-zod-utils/src/index.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/http-provider.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/network-connection.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/test/utils.ts

This PR addresses most of the tasks outlined in [this document](https://www.notion.so/nomicfoundation/Network-Manager-M1-missing-work-2d207a7d96944978a9cc13c4839a6a0a?pvs=4), except for the "Types" section, which will be addressed in a separate PR. I suggest reviewing one commit at a time for an easier review process.
Summary:
- Added tests for:
- All config hooks (`extendUserConfig`, `validateUserConfig`, `resolveUserConfig`).
- `HTTPProvider`: `jsonRpcWrapper` and `close` functions.
- `NetworkManager`: `connect` function and all network hooks (`newConnection`, `closeConnection`, `onRequest`).
- `NetworkConnection`: class initialization and `close` function (through `NetworkManager`)
- Fixed bugs found during testing.
- Refactored code for better readability and to facilitate testing.

Network Manager M1 remaining tasks

---

.changeset/soft-poets-grab.md
packages/hardhat-core/package.json
pnpm-lock.yaml

This bumps EDR to a new patch version ([0.6.2](https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.6.2)), which includes:
-   [af56289](https://github.com/NomicFoundation/edr/commit/af562899df38f028145276234c2786ba2acef610): fix(tracing): Decode unmapped instructions only at the opcode boundary
-   [debac88](https://github.com/NomicFoundation/edr/commit/debac88a3957ff4b9ba89727ae317a8cfc816333): fix(tracing): Use correct subtrace when detecting error error propagation across delegatecall
-   [e96b403](https://github.com/NomicFoundation/edr/commit/e96b403430680b2290abf30634577d2bcb83b862): fix: Handle nullptr JS TypedArrays by bumping napi to 2.6.11
These are all the issues we ran into so far when testing the new Solidity tracing logic across 3rd party …

chore: Bump EDR to 0.6.2 that includes fixes to tracing logic

---

docs/src/content/hardhat-runner/plugins/plugins.ts

---
This PR adds https://github.com/MEDGA-eth/hardhat-clone into the community plugin list.
@medga/hardhat-clone is a plugin that takes the address of a verified contract deployed on the blockchain (any EVM-compatible blockchain, e.g., Ethereum, Binanace Smart Chain, Optimism, etc.) and clone the contract source into the current Hardhat project. The cloned contracts are reorganized such that it can be compiled together with other contracts in the Hardhat project.

Add @medga/hardhat-clone plugin

---

v-next/hardhat-test-utils/src/global.ts
v-next/hardhat-test-utils/src/index.ts

---
I found it helpful during the draft implementation of https://github.com/NomicFoundation/hardhat/pull/5774. 
The idea is to override the global reference to fetch with a function that always throws an error. This is a very crude approach to simulating network connectivity issues when using fetch. We can explore this area further in the future if needed. However, at this time, this met my needs.

feat: add doNotUseFetch helper to the test utils

---

pnpm-lock.yaml
v-next/example-project/.gitignore
v-next/example-project/contracts/Counter.sol
v-next/example-project/contracts/Counter.t.sol
v-next/example-project/contracts/Rocket.sol
v-next/hardhat-build-system/package.json
v-next/hardhat-build-system/src/internal/solidity/compiler/compiler-input.ts
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/artifacts/artifacts-manager.ts
v-next/hardhat/src/internal/builtin-plugins/artifacts/hook-handlers/hre.ts
v-next/hardhat/src/internal/builtin-plugins/compile/index.ts
v-next/hardhat/src/internal/builtin-plugins/compile/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/test/internal/cli/main.ts
v-next/hardhat/tsconfig.json

Add a skeleton Solidity Test built-in plugin using `@ignored/edr` with its Solidity Test Runner, to add a `npx hardhat test:solidity` task.
This PR comes in two commits:
- temporary hack to add `compile` task based on old build system and extend ArtifactsManager to read from artifacts directory
- skeleton builtin plugin for Solidity Test, leveraging the _hacked_ artifacts manager to read the compiled artifacts and pass that meta-info into EDR's Solidity Test Runner
```
pnpm install
cd ./v-next/example-project
pnpm build
pnpm hardhat test:solidity
```

add skeleton EDR Solidity Testing integration

---

.changeset/healthy-pets-poke.md
packages/hardhat-core/package.json
pnpm-lock.yaml

Bump EDR to [0.6.3](https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.6.3) which has the following fixes:
- https://github.com/NomicFoundation/edr/commit/a1cee4fb3aa544b6caef7f952841be2a1e61fddc: fix(tracing): Make sure to correctly 0x-prefix hex encoded strings in custom error message
- https://github.com/NomicFoundation/edr/commit/7047e6cd584e172c3b640a87b39fbaa83d5842bd: Fixed panic from unknown opcode in stack traces

chore: bump EDR to 0.6.3

---

v-next/hardhat-test-utils/src/console.ts
v-next/hardhat-test-utils/src/index.ts
v-next/hardhat/test/internal/cli/init/init.ts

---
As explored in https://github.com/NomicFoundation/hardhat/pull/5804, I have found that testing function that use `console.log` (i.e. write to `stdout`) can lead to `Unable to deserialize cloned data due to invalid or unsupported version.` errors.
In this PR, I introduce a helper function, which disables `console.log`/`console.warn`/`console.dir` (the `console` function which interact with either `stdout` or `stderr` directly). I also described how we could expand the helper in the future if needed.
An alternative I considered was overwriting the `process.stdout` and `process.stderr` streams directly, however I found that this can interfere with the reporter's output.

fix: disable console for init tests

---

.changeset/stupid-paws-sort.md
packages/hardhat-core/package.json
pnpm-lock.yaml

Bump EDR to 0.6.4 which fixed an error due to remote nodes not returning total difficulty by adding fallback value. Related issues:
- https://github.com/NomicFoundation/hardhat/discussions/5814
- https://github.com/NomicFoundation/hardhat/issues/5816

fix: bump EDR to 0.6.4

---

v-next/hardhat-node-test-reporter/src/reporter.ts

---
As per the comment, node v22.10.0 added a new test event type. 
Follow up tasks: 
- remove the ts ignore comment once @types/node knows about the new test event type, 
- make use of the new `test:summary` event in the reporter,
- make the integration test of the reporter optional as they often break with node version upgrades.

fix: ignore new node test event type added in v22.10.0

---

v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/formatters.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/runner.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/types.ts

---
This PR introduces a custom hardhat solidity test reporter in place of the spec reporter that we used to use.
It is an implementation of the design outline in https://www.notion.so/nomicfoundation/Runner-Reporter-Design-11f578cdeaf580b8b01ddc43ae589f05
This PR doesn't change the output formatting.
The runner/reporter setup have been tested manually. It would be great to introduce a more formalised E2E testing for the solidity testing task, but it is left as a follow-up for now.

feat: replace spec with a custom hardhat solidity test reporter

---

v-next/example-project/contracts/Counter.t.sol
v-next/hardhat/src/internal/builtin-plugins/solidity-test/formatters.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts

---
This PR builds up on https://github.com/NomicFoundation/hardhat/pull/5809 and introduces custom output formatting described in https://www.notion.so/nomicfoundation/Reporter-Output-Formatting-11f578cdeaf580408d12fb03e7799e81.
It has been tested manually and visually verified.
The the reporter produces for the example project after the changes:

feat: format the solidity test output better

---

.changeset/chilled-cycles-judge.md
packages/hardhat-web3/package.json
pnpm-lock.yaml

A new version of `@types/bignumber.js` was breaking our ci

Fix a dependency error in hardhat-web3

---

v-next/hardhat-utils/src/hex.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts

---
This is a follow-up to https://github.com/NomicFoundation/hardhat/pull/5828#discussion_r1813556874

chore: format buffers in solidity test output as hex strings

---

.github/workflows/v-next-ci.yml

As we move towards polishing the next version, we are probably going to be creating a ton of chained/dependent PRs.
Currently, `v-next-ci` doesn't run for those, leading to undetected errors until you merge some PRs.
In this PR I changed how we filter which PRs to run this workflow on. The workflow always runs, but I first check if the `./v-next` folder exists. If it doesn't exist, I skip the main jobs, leading to all the jobs being skipped.

Run `v-next`'s CI on chained PRs

---

.github/workflows/hardhat-core-ci.yml
packages/hardhat-core/test/internal/hardhat-network/stack-traces/README.md
packages/hardhat-core/test/internal/hardhat-network/stack-traces/test.ts

---
This PR restores the ability to run the tests for all solc versions in CI on demand. It doesn't change the default of running the tests only for the compiler versions marked as latest. 
Here's an example run - https://github.com/NomicFoundation/hardhat/actions/runs/10846884277 
Note that it currently fails with OOM errors :( These are the standard machines sizes - https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories Do you think we should act on it?

ci: add test-all-solc-versions input to the core ci

---

pnpm-lock.yaml
v-next/example-project/contracts/WithForge.t.sol
v-next/example-project/hardhat.config.ts
v-next/example-project/package.json
v-next/example-project/scripts/viem-plugin-example.ts
v-next/hardhat-mocha-test-runner/src/index.ts
v-next/hardhat-mocha-test-runner/src/task-action.ts
v-next/hardhat-mocha-test-runner/test/index.ts
v-next/hardhat-node-test-runner/src/index.ts
v-next/hardhat-node-test-runner/src/task-action.ts
v-next/hardhat/src/cli.ts
v-next/hardhat/src/internal/builtin-plugins/console/index.ts
v-next/hardhat/src/internal/builtin-plugins/console/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/index.ts
v-next/hardhat/src/internal/builtin-plugins/run/index.ts
v-next/hardhat/src/internal/builtin-plugins/run/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
v-next/hardhat/src/internal/builtin-plugins/test/index.ts
v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/fixture-projects/cli/parsing/default-values/hardhat.config.ts
v-next/hardhat/test/fixture-projects/run-js-script/hardhat.config.js
v-next/hardhat/test/fixture-projects/run-js-script/scripts/success.js
v-next/hardhat/test/fixture-projects/run-ts-script/hardhat.config.ts
v-next/hardhat/test/fixture-projects/run-ts-script/scripts/success.ts
v-next/hardhat/test/internal/builtin-plugins/console/task-action.ts
v-next/hardhat/test/internal/builtin-plugins/run/task-action.ts
v-next/hardhat/test/internal/cli/main.ts

This is a PR with some small improvements to have a first iteration of a unified test workflow for the alpha. This will be improved later.
It does a few things:
1. Set proper names to the `node:test` and `mocha` plugins.
2. Introduces a `builtin:test` plugin, which defines a `test` task, which runs all of its subtasks.
3. Updates the `mocha`, and `node:test` plugins so that they define subtasks — This allows them to coexist 🥳 /cc @kanej 
4. Sets the solidity test runner as a subtask.
5. Fix a bug in the solidity test runner that made the task return before the output was printed.
6. Sets all the required `dependencies:` in the builtin plugins.
Unrelated improvements:
1. Fix `pnpm run clean` in the example project.
2. Fix a viem example in the example project.
3. Implement `noCompile` …

Unified test workflow and small improvements

---

v-next/example-project/hardhat.config.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/dependency-graph-building.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/types.ts

This PR fixes a bug that could happen if a user remapped an npm package to one of its internal folders and, at the same time, used one of its files as a root.
For example, if you had a remapping `foo/=foo/src/` and also treated `foo/src/A.sol` as a project root, that needs to be compiled.

[build-system] Fix potential clash between user remappings and npm roots

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/automatic-sender-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/fixed-sender-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/accounts/sender.ts

This PR fixes the automatic sender hook handler, as it didn't support the case where no account was present.
@ChristopherDedominici can you take a look?
Also, some hook handlers throw errors where they should return JSON-RPC response with `InternalError`s.

Fix automatic sender hook handler

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts

This is a small PR to that I put in place to be able to enable forking in EDR networks. It is not complete, though.
It does just a few things:
1. Changes the EDR network config resolution so that `chainType` can be left `undefined`, as that's important to be able to change them during connection.
2. Resolved the `chainType` during connection.
3. Added the `forkConfig` to the resolved network config, without any actual resolution.
4. Sparkled some TODOs.
The reason this PR is important is that optimism needs to be tested in forked mode.

Small improvements to the config resolution of EDR networks

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts

If we don't resolve it ourselves, EDR creates an unexpected folder in the CWD

Resolve the EDR cache path config

---

v-next/example-project/hardhat.config.ts
v-next/hardhat-viem/test/fixture-projects/default-ts-project/hardhat.config.ts
v-next/hardhat/templates/empty-typescript/hardhat.config.ts
v-next/hardhat/templates/typescript-with-examples/hardhat.config.ts
v-next/hardhat/templates/typescript-with-examples/package.json

Change the import path to `@ignored/hardhat-vnext/config` in the template projects (i.e. the projects created by `npx hardhat3 --init`) so that the built-in type extensions are loaded.

update HardhatUserConfig import path in templates

---

v-next/hardhat-node-test-runner/src/task-action.ts
v-next/hardhat-utils/package.json
v-next/hardhat-utils/src/stream.ts
v-next/hardhat-utils/test/stream.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts

This PR fixes a race condition that we had when piping readable streams into stdout.
It introduces a utility that creates a Writable based on another Writable, which "pipes" everything to the latter, but without closing it.
This allows us to pipe readable into a writable and await for all the writes to complete.

Await output streams

---

.changeset/pre.json
pnpm-lock.yaml
v-next/hardhat/templates/mocha-ethers/.gitignore
v-next/hardhat/templates/mocha-ethers/README.md
v-next/hardhat/templates/mocha-ethers/contracts/Lock.sol
v-next/hardhat/templates/mocha-ethers/hardhat.config.ts
v-next/hardhat/templates/mocha-ethers/package.json
v-next/hardhat/templates/mocha-ethers/test/Lock.ts
v-next/hardhat/templates/mocha-ethers/tsconfig.json

As part of the Alpha prep this adds a mocha/ethers template project (used during `hardhat --init`), that tries to recreate the functionality (we are currently able to support`f of the v2 Ethers typescript project in v3.
It pulls in the `v-next` versions of the mocha test runner, the test helpers and `hardhat-ethers`.
It adds a the `Lock.sol` and `Lock.ts` test file. The test file has been modified to allow for running the tests while we still have rough edges.
Specifically the rough edges are:
- we need to import plugin types to get the full connection type
- we need new patterns for sharing `connection` among tests (I added a `beforeEach`)
- we don't have chai matchers so I added `chai-as-promised` and adapted the tests, sometime crudely.

feat: create a mocha/ethers template project

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts

Just a small PR fixing a zod schema that was too restrictive.

Fix the EDR Network user config validation

---

v-next/example-project/contracts/Counter.t.sol
v-next/example-project/contracts/D.sol
v-next/example-project/contracts/WithForge.t.sol
v-next/hardhat-mocha-test-runner/src/task-action.ts
v-next/hardhat-node-test-runner/src/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
v-next/hardhat/src/internal/core/tasks/resolved-task.ts
v-next/hardhat/templates/mocha-ethers/contracts/Counter.sol
v-next/hardhat/templates/mocha-ethers/contracts/Counter.t.sol
v-next/hardhat/templates/mocha-ethers/contracts/WithForge.t.sol
v-next/hardhat/templates/node-test-runner-viem/contracts/Counter.sol
v-next/hardhat/templates/node-test-runner-viem/contracts/Counter.t.sol
v-next/hardhat/templates/node-test-runner-viem/contracts/WithForge.t.sol

This PR adds a few little messaging improvements, 1 per commit.
While testing it, I also fixed all the compilation warnings in the templates and example project.

A few messaging improvements

---

v-next/hardhat-ethers/src/type-extensions.ts
v-next/hardhat-network-helpers/src/type-extensions.ts
v-next/hardhat-viem/src/type-extensions.ts
v-next/hardhat-viem/src/types.ts
v-next/hardhat/src/types/network.ts

Use the `DefaultChainType` as default type parameter

---

pnpm-lock.yaml
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/templates/mocha-ethers/package.json
v-next/hardhat/templates/node-test-runner-viem/package.json

Our use of `node:test` and `node:assert` in the templates implies we should include the types.

chore: add @types/node to both templates

---

v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts

The resolution was giving different results during testing than in production, due to everything being in `dist/` in production builds. Instead of using a path, I now look for the closest `package.json`, which is safer.

Fix hardhat package resolution

---

pnpm-lock.yaml
v-next/hardhat/templates/mocha-ethers/hardhat.config.ts
v-next/hardhat/templates/mocha-ethers/package.json
v-next/hardhat/templates/node-test-runner-viem/hardhat.config.ts
v-next/hardhat/templates/node-test-runner-viem/package.json

This is to allow users to try the new config variable setup based on values set in the file based (unencrypted) keystore.

add v-next keystore to the templates

---

v-next/hardhat/src/cli.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/src/internal/cli/node-version.ts

This PR moves the function call to print the Node.js version warning to the main CLI entrypoint, so that we do the check before loading main, as loading main can crash already if you have a pretty old version.

Print the Node.js warning before loading main

---

pnpm-lock.yaml
v-next/example-project/contracts/Counter.t.sol
v-next/example-project/hardhat.config.ts
v-next/example-project/scripts/send-op-tx-viem.ts
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/runner.ts

This PR upgrades both versions of EDR.
* `@ignored/edr` now supports `RUST_LOG=debug`
* `@ignored/edr-optimism` can now fork OP Sepolia
* `@ignored/edr-optimism` can use a different chain id than the network it's forking

Upgrade EDR

---

docs/README.md
docs/src/content/hardhat-runner/docs/config/index.md
docs/src/content/ignition/docs/guides/upgradeable-proxies.md

1. File: docs/src/content/ignition/docs/guides/upgradeable-proxies.md
Old text: "This file will look a little different than the others"
New text: "This file will look a little different from the others"
Reason: Using "different from" is grammatically correct when comparing two things, while "different than" is incorrect in formal technical documentation.
2. File: docs/README.md
Old text: "with works fine with SSG sites"
New text: "which works fine with SSG sites"
Reason: The word "which" is the correct relative pronoun to connect the clauses and describe the functionality of Linaria's CSS generation. Using "with" was grammatically incorrect and made the sentence unclear.
Old text: "Landing pages contains"
New text: "Landing pages contain"
Reason: Fixed subject-verb agreement since …

Grammar Fix in Linaria Documentation

---

.github/workflows/autoassign-issues.yml

Include @galargh in the auto-assigner for triaging of incoming GitHub issues.

chore: add piotr to issue auto-assigner

---

docs/src/content/hardhat-runner/docs/advanced/hardhat-and-foundry.md

---
I was just reading the docs and I saw that at getting started there's a pnpm command to install hardhat but there's no pnpm command in the tab group at the integration with foundry page

Add pnpm to tabgroup at hardhat-and-foundry.md

---

docs/src/content/hardhat-runner/docs/guides/command-line-completion.md

---
Add Windows troubleshooting to hardhat-shorthand, resolve #5040

docs: hardhat-completion add windows troubleshooting

---

v-next/hardhat-ethers/src/internal/hardhat-ethers-provider/hardhat-ethers-provider.ts
v-next/hardhat-ethers/src/internal/hardhat-helpers/hardhat-helpers.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/json-rpc-request-modifiers/json-rpc-request-modifier.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-connection.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/src/types/network.ts

---
Resolves #5831
As per https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1732272638933179, this PR ensures that readonly properties referencing NetworkConfig are immutable.

chore: prevent network configuration properties from being modified

---

docs/src/content/hardhat-runner/docs/advanced/using-viem.md
docs/src/content/hardhat-vscode/docs/formatting.md

This pull request addresses minor typo corrections in the Hardhat documentation. The changes improve readability and grammatical accuracy in the following files:
1. **`using-viem.md`**: Corrected the usage of the article from "an" to "a" before "bigint" to align with proper grammatical rules.  
2. **`formatting.md`**: Added a hyphen in "right-clicking" to ensure correct spelling of the term.  
These are minor updates with no impact on functionality, intended to enhance the clarity and professionalism of the documentation.
---
---
- Maintainers are welcome to edit this PR for additional refinements.  
- This is a small fix with no breaking changes.

Fix typos in documentation for using Viem and formatting instructions

---

v-next/hardhat/src/internal/cli/init/init.ts
v-next/hardhat/src/internal/cli/init/template.ts
v-next/hardhat/templates/README.md
v-next/hardhat/templates/mocha-ethers/gitignore
v-next/hardhat/templates/node-test-runner-viem/gitignore
v-next/hardhat/test/internal/cli/init/init.ts

---
This PR introduces the agreed upon workaround for `npm`s inability to publish `.gitignore` files (see https://github.com/npm/npm/issues/3763). 
Going through the comments on the linked issue, it seems that the most common convention for working around this issue is exactly what we came up with, too - which is to copy `gitignore` template files as `.gitignore` workspace files.
I left `.gitignore` files in the templates because it is useful to have, for example, `node_modules` gitignored during development.

fix: copy .gitignore files during project initialization

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/http-provider.ts

This PR addresses several TODOs in the network manager and refactors interfaces for improved clarity and consistency. **Key changes include:**
- **Clarity and consistency between provider types:**
- Pass a configuration object to the `EdrProvider`.
- Extract `HttpProvider.create` parameter types into an interface.
- Set default values for `loggerConfig` and `tracingConfig`.
- Make the `HttpProvider` constructor private and update tests accordingly. An optional `testDispatcher` is now passed to the `HttpProvider.create` function to facilitate this change.
- **Refactored `jsonRpcRequestWrapper`:**
- Eliminated duplication by moving the type definition to `NetworkManager`.
- Defined the function in `NetworkManager` before passing it to the providers.
- **Code cleanup in `NetworkManager`:**
- …

Network manager cleanup Pt1

---

docs/README.md
docs/src/content/hardhat-runner/docs/guides/deploying.md

1. Changed:
```diff
- folders - the list of folders should be included in this layout
+ folders - the list of folders that should be included in this layout
```
- Adds missing relative pronoun "that"
- Improves sentence structure and readability
2. Changed:
```diff
- The documentation section is Themable
+ The documentation section is Themeable
```
- Corrects spelling of technical term
- Maintains consistency with standard spelling conventions
3. Changed:
```diff
- As general rule
+ As a general rule
```
- Adds missing article "a"
- Follows proper English phrase construction

Documentation Grammar and Spelling Improvements

---

pnpm-lock.yaml
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/address.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/rpc/types/tx-request.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts

The branch for this PR was checked out from [this other PR](https://github.com/NomicFoundation/hardhat/pull/5994).
This PR adds logic to handle transactions sent to the null address:
- Updates the version of `micro-eth-signer` to handle transactions directed to the null address. [See release notes](https://github.com/paulmillr/micro-eth-signer/releases/tag/0.12.2).
- If both the "to" field and the "data" field are undefined, an error is thrown.
- If the "to" field is undefined but the "data" field is not, the "to" address is set to "0x", which is the expected address in `micro-eth-signer` for processing transactions to the null address.
NOTES:
If the "to" field and the "data" field are explicitly set to null, a `zod` validation error will be thrown.

micro-eth-signer issue when deploying local accounts

---

v-next/hardhat/src/internal/builtin-global-options.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/helpers/getGlobalHelpString.ts
v-next/hardhat/test/internal/cli/main.ts
v-next/hardhat/test/internal/hre-intialization.ts

Add the `--verbose` flag to enable logging via the `debug` module

Enable debug logging via CLI flag 

---

docs/README.md

This update corrects a minor grammatical issue in the "Content generating technical details" section of the documentation.  
Previously, the phrase:  
> "Layout settings don't affect to page's existence."  
contained an incorrect use of "affect to." The corrected version now reads:  
> "Layout settings don't affect page existence."  
This change ensures the documentation is grammatically accurate and aligns with natural English usage.

docs: Fix grammatical issue Update README.md

---

v-next/hardhat-errors/src/descriptors.ts

When running hardhat and no config file is found, besides throwing the error now it's suggested to run hardhat with the --init flag. The wording is consistent with the "For more info ..." part.

Suggest running hardhat --init when no config file is found

---

v-next/hardhat/src/internal/core/tasks/resolved-task.ts
v-next/hardhat/src/types/tasks.ts
v-next/hardhat/test/internal/core/tasks/task-manager.ts

This PR allows users to call Task.run() without passing any arguments. This will default to an empty object `{}`.
Closes #5982

Make arguments of Task.run() optional, defaulting to empty object

---

docs/src/content/hardhat-runner/docs/advanced/building-plugins.md
packages/hardhat-chai-matchers/src/internal/reverted/reverted.ts
packages/hardhat-chai-matchers/test/reverted/reverted.ts
packages/hardhat-core/src/internal/cli/cli.ts
packages/hardhat-core/src/internal/cli/is-node-version-to-warn-on.ts
packages/hardhat-core/src/internal/core/config/config-validation.ts
packages/hardhat-core/src/internal/core/typescript-support.ts

This PR fixes typographical errors and incorrect usage of articles ("a" vs "an") in documentation and code comments to improve clarity and grammatical accuracy.
- Corrected article usage based on whether the following word starts with a consonant or vowel sound.  
- Fixed minor typographical errors for consistency and readability.  
---
These changes are focused solely on improving documentation and code comments without affecting logic or functionality.

Fix incorrect usage of articles ("a" vs "an") in documentation

---

docs/src/content/ignition/docs/guides/deploy.md

documents this change https://github.com/NomicFoundation/hardhat-ignition/pull/850

Add doc for passing param path to deploy function

---

e2e/run-fixture-projects.sh

A typo in a comment within the Bash script for running e2e tests.  
The incorrect word **`moduled`** has been replaced with the correct term **`modules`** in the following line:  
```bash
npm install >/dev/null 2>&1 # install modules specified in the package.json
```
The updated comment now reads:  
```bash
npm install >/dev/null 2>&1 # install modules specified in the package.json
```
Thanks!

Fix typo in Bash script Update run-fixture-projects.sh

---

packages/eslint-plugin-hardhat-internal-rules/lib/rules/only-hardhat-error.js
packages/eslint-plugin-slow-imports/lib/helpers/module-visitor.js
packages/hardhat-chai-matchers/test/addressable.ts
packages/hardhat-chai-matchers/test/events.ts
packages/hardhat-chai-matchers/test/properAddress.ts
packages/hardhat-chai-matchers/test/properPrivateKey.ts
scripts/check-dependencies.js

-Renamed function arguments (e.g., tc to typeChecker) for better context clarity.
-Corrected test descriptions to align with the actual behavior being tested.
-Fixed typos in comments and variable names to improve code readability and quality.
-Removed redundant checks and optimized certain conditions in modules.
-Updated comments to accurately reflect recent code changes.

Code Enhancements and Fixes for Hardhat

---

docs/src/content/tutorial/deploying-to-a-live-network.md
packages/hardhat-core/test/helpers/errors.ts
packages/hardhat-verify/test/unit/etherscan.ts

This PR addresses the following issues:
1. **Updated broken links**:  
- Fixed a broken link in the Sepolia faucet section of the `deploying-to-a-live-network.md` documentation file.  
- Updated the Chainstack Sepolia Faucet URL for accuracy.
2. **Corrected typos**:  
- Resolved grammatical errors in `errors.ts`:
- Fixed "an non-replaced" to "a non-replaced."
- Resolved a typo in `etherscan.ts`:
- Corrected "it's not a added" to "it's not an added."

fix: update broken links and correct typos in documentation

---

docs/README.md

docs/README.md:
- https://nextjs.org/docs/api-reference/next.config.js/redirects
+ https://nextjs.org/docs/app/api-reference/config/next-config-js/redirects
**Reason**: Updated the NextJS documentation link to reflect the new URL structure in NextJS documentation. The old link was outdated and redirected to the new documentation. This change provides direct access to the current documentation, improving developer experience and maintaining documentation accuracy.
No functional changes, only documentation update.

Update NextJS documentation link

---

docs/src/components/CookiePopUp.tsx

fix: typos in documentation files

---

v-next/hardhat/src/internal/cli/init/init.ts

---
This implements a user experience improvement suggestion from https://nomicfoundation.slack.com/archives/C069TLP61BQ/p1734796294370569 
Namely, after the change, we'll ensure that the project where hardhat is being initialized is of module type earlier on in the flow of init.

chore: ensure module type early in the init flow

---

packages/hardhat-chai-matchers/src/utils.ts

This Pr improves code readability in the build assert file,
[X] tests passing
[X] lint:fix

Refactor build assert

---

docs/src/content/hardhat-runner/plugins/plugins.ts

While browsing new hardhat plugins, I noticed that the npm URL for the **hardhat-gasless-deployer** plugin was returning a 404 error. The issue was that the direct link was provided instead of the package name. I fixed the URL to make it easier for others to find.

Update npm package link for hardhat-gasless-deployer plugin

---

v-next/hardhat/src/cli.ts
v-next/hardhat/src/internal/cli/main.ts

This fixes the issue mentioned [here](https://github.com/NomicFoundation/hardhat/issues/2888#issuecomment-2524080632)
This PR definitely doesn't make Deno easy to use because of the `forge` issue mentioned [here](https://github.com/NomicFoundation/hardhat/issues/2888#issuecomment-2496323103), but it at least makes it usable

Fix tsx.register() crash on Deno

---

v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts

---
Resolves #6051
The issue was that we used POSIX path separators in the `dependenciesToCompile`, but then we weren't translating them to system-aware paths anywhere along the way. Eventually, it made it all the way through to https://github.com/NomicFoundation/hardhat/blob/v-next/v-next/hardhat-utils/src/fs.ts#L120, which expects system-specific path separators, and that's where we errored out.
The resolver for npm paths is https://github.com/NomicFoundation/hardhat/blob/v-next/v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts#L250. I added the path separator translator to https://github.com/NomicFoundation/hardhat/blob/v-next/v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/resolver/dependency-resolver.ts#L254 because it …

Translate path separators when parsing npm direct imports

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts

Solidity stack traces should be stringified properly now.
Extracted the logic from source-map-support package.
Closes #6067

Implement SolidityCallSite.toString()

---

docs/src/content/ignition/docs/advanced/migrating.md
docs/src/content/ignition/docs/guides/create2.md
docs/src/content/ignition/docs/guides/ledger.md
docs/src/content/ignition/docs/reference/cli-commands.md

There are many markdown snippets that have `sh` as the info string but whose content is not shell code. This makes them be incorrectly highlighted. But the main issue is that some angle brackets are escaped:
To be honest, the fact that removing the info string fixes this doesn't make a lot of sense to me. I don't know why they are escaped only when a language is specified. I looked down the remark/rehype rabbit hole, but it was too deep so I went with the fix that works but that I don't understand.

Remove shell lang from some md snippets

---

packages/hardhat-web3-legacy/test/web3-provider-adapter.ts
packages/hardhat-web3/test/web3-provider-adapter.ts

This PR fixes a typo in the test description where "sigle" was incorrectly used instead of "single"

Fix typo in test 

---

.changeset/sixty-fireants-greet.md
docs/redirects.config.js
docs/src/config.ts
packages/hardhat-core/src/internal/cli/project-creation.ts

---
As discussed during the sync, I'm reenabling the Solidity Survey message.

chore: restore the solidity survey message (2024)

---

docs/src/content/hardhat-chai-matchers/docs/overview.md
docs/src/content/hardhat-chai-matchers/docs/reference.md

Resolves #6148
---
---
This PR clarifies how we use the `contract` argument in the `revertedWithCustomError` matcher since it can be confusing why the matcher doesn't check the error origin.
The context for the discussion can be found in https://nomicfoundation.slack.com/archives/C03F2119K4H/p1737098731987269

docs: describe how revertedWithCustomError uses the contract argument

---

docs/src/content/ignition/docs/guides/upgradeable-proxies.md

Same as https://github.com/NomicFoundation/hardhat/pull/6150 but done by a real human, assuming you think that of me.
I also ran `rg 'describe.*async` and didn't find any other instance of this.

Remove async from describe callbacks

---

.changeset/fluffy-sloths-walk.md
packages/hardhat-core/src/internal/core/config/config-loading.ts
packages/hardhat-solhint/test/fixture-projects/no-errors-project/contracts/Greeter.sol

This fixes the "latest dependency versions" CI job. I don't know why this started happening now, but I confirmed manually that these extra checks are needed.

Fix ESM_PROJECT_WITHOUT_CJS_CONFIG heuristic

---

packages/hardhat-toolbox-viem/package.json
packages/hardhat-toolbox/package.json
pnpm-lock.yaml

Enable workspace references in the toolboxes dependencies on the Ignition packages.
Resolves #6166

Refer to Ignition packages through pnpm workspace refs for the toolboxes

---

v-next/hardhat-chai-matchers/src/index.ts

Add the `dependencies` and `npmPackage` properties if they are missing in the new v3 plugins

Add missing properties in v3 plugins

---

v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts

Resolved #6176
---
This introduces an option to run only a subset of solidity tests. The CLI interface I implemented is exactly the same as with the `test node` task.

feat: add testFiles option to test solidity

---

v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat-utils/src/hex.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/errors.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/panic-errors.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/type-validation.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/types/output.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/artifacts.ts
v-next/hardhat/src/internal/constants.ts
v-next/hardhat/src/types/providers.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/http-provider.ts

This is the final cleanup PR for the network stack in preparation for the alpha (and ideally the beta). It includes:
- Normalized the EDR and HTTP providers to make them as similar as possible.
- Removed the emission of the `hardhatNetworkReset` event in the `request` method, as it no longer makes sense in v3.
- Free resources for garbage collection on `close` (unset the `provider` for the EDR provider and the `dispatcher` for the HTTP provider) and throw an error if the `request` method is called after closing.
- EDR Provider – `request` method:
- Removed `InvalidInputError` logic, as it is already handled by `getJsonRpcRequest`.
- Replaced assertions on `jsonRpcResponse.result` with `assertHardhatInvariant`.
- Cleaned up the `#handleEdrResponse` function.
- Improved functions in …

feat: cleanup provider and stack traces logic

---

.changeset/kind-teachers-applaud.md
packages/hardhat-core/package.json
packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts
packages/hardhat-core/src/internal/hardhat-network/stack-traces/constants.ts
pnpm-lock.yaml

Bump EDR to [0.8.0](https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.8.0).
This fixes the following issues:
* https://github.com/NomicFoundation/edr/commit/af26624ae0b705d70bee15d4f4b76e017f5b4dfd: Improved provider initialization performance by passing build info as buffer which avoids FFI copy overhead
* https://github.com/NomicFoundation/edr/commit/4ffb4f60ea1c49977c685dddb702445579d1f41c: fix: ignore unknown opcodes in source maps
* https://github.com/NomicFoundation/edr/commit/5c8c3ddcbd932d47d3fc8705f3e8943a45a4dfdb: Fixed crash when loading EDR on Windows without a C Runtime library installed
* https://github.com/NomicFoundation/edr/commit/2b9b805a48cd340c05ac44af189ecda752270807: Improved stack trace generation performance by eliminating one-way …

chore: bump EDR to 0.8.0

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/accounts/derive-private-keys.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/network.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers-array.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/hd-wallet-handler.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/hd-wallet.ts

The `connect()` method in the network manager was experiencing noticeable slowdowns. This was caused by multiple factors:
1. Bug in `normalizeEdrNetworkAccountsConfig`:
- A resolved HD account was being compared to the default HD account. The resolved account allows configuration variables for `mnemonic` and `passphrase`, while the default account uses `string` values for these fields.
- The issue was temporarily fixed by `get()`ting the string values from the configuration variables before comparison.
- **Next Steps:** evaluate whether it makes sense to use configuration variables in the EDR network accounts config, as the data is not expected to be real. Issue: https://github.com/NomicFoundation/hardhat/issues/6210
2. Slow Imports in `derivePrivateKeys` module:
- The module that exports …

perf: load slow modules dynamically

---

.github/workflows/v-next-ci.yml

---
In this PR, I address the issue described here - https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1738270381236179
`list-packages` started producing too big outputs.
To address this, I:
- added the `base` parameter to the call to `dorny/paths-filter` (this way, this workflow will be detecting changed files in relation to `v-next` rather than `main; we should have had it set in the first place)
- moved the check whether `bundle` should be run or not to  inside the `list-packages` job (this way, we don't have to put all the changed files in the `list-packages` job outputs)

ci: make list-packages outputs smaller

---

docs/src/content/ignition/docs/guides/deploy.md

In file `docs/src/content/ignition/docs/guides/deploy.md`:
Changed:
- `/d+n/` → `/\d+n/`
Reason for change:
The original regex pattern `/d+n/` would incorrectly match one or more literal 'd' characters followed by 'n'. The corrected pattern `/\d+n/` properly matches one or more digits followed by 'n', which is the correct format for bigint literals in JavaScript (e.g. "1000n").
This fix ensures the documentation accurately describes how to specify bigint values in parameter files.

Fix regex pattern for bigint parameter validation

---

v-next/hardhat-typechain/src/internal/generate-types.ts
v-next/hardhat-typechain/test/index.ts

Fixed a bug in the typechain plugin:
In the `typechain` configuration, the artifact paths must also be specified in the `filesToProcess` field. Previously, this property was not set.
Additionally, I added a test to verify that the type file is generated correctly.

Fix generation of type files in the typechain plugin

---

v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat-ethers/src/internal/hardhat-helpers/hardhat-helpers.ts
v-next/hardhat-ethers/src/internal/initialization.ts
v-next/hardhat-ethers/test/helpers/artifact-manager-mock.ts
v-next/hardhat-ethers/test/helpers/helpers.ts
v-next/hardhat-ethers/test/no-accounts.ts
v-next/hardhat-ethers/test/plugin-functionalities.ts
v-next/hardhat-viem/src/internal/contracts.ts
v-next/hardhat-viem/src/internal/initialization.ts
v-next/hardhat/src/index.ts
v-next/hardhat/src/internal/builtin-plugins/artifacts/artifact-manager.ts
v-next/hardhat/src/internal/builtin-plugins/artifacts/artifacts-manager.ts
v-next/hardhat/src/internal/builtin-plugins/artifacts/hook-handlers/hre.ts
v-next/hardhat/src/internal/builtin-plugins/artifacts/type-extensions.ts
v-next/hardhat/src/internal/core/hre.ts
v-next/hardhat/src/types/artifacts.ts
v-next/hardhat/test/test-helpers/create-mock-hardhat-runtime-environment.ts
v-next/hardhat/test/test-helpers/mock-artifact-manager.ts
v-next/hardhat/test/test-helpers/mock-artifacts-manager.ts

While looking at a part of the codebase I noticed that we never addressed tons of TODOs in the `ArtifactManager` interface.
This PR does that, cleaning up the interface, and updating the different implementations.

Clean up and implement the ArtifactManager interface

---

v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/provider-errors.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts

---
Closes #6218
In this PR, I propose to:
- enclose each interactions with the [internal EDR provider](https://github.com/NomicFoundation/hardhat/blob/72b6e43b0bfbbf4021de56a33b2f989824817464/v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts#L137) in a try-catch block
- wrap the unknown errors caught during such interactions in a newly introduced `UnknownError` which extends `ProviderError`
- wrap the unknown errors caught during fetch requests to the [HTTP provider](https://github.com/NomicFoundation/hardhat/blob/72b6e43b0bfbbf4021de56a33b2f989824817464/v-next/hardhat/src/internal/builtin-plugins/network-manager/http-provider.ts#L182) in the same `UnknownError`
- allow for the `UnknownError`s to be reported to sentry
Example report: …

feat: send EDR panics to sentry

---

.changeset/loud-hornets-approve.md
pnpm-lock.yaml
v-next/hardhat/package.json

Bumps `@ignored/edr` to 0.8.0-alpha.2. This brings the following features:
- Stack traces for setup, deployment, fuzz and invariant tests. (Stack traces for unit tests were released in 0.8.0-alpha.1.)
- The stack traces are generated via re-execution of failing tests. This means that there is no performance penalty on the happy path.
**Current limitations to be addressed in upcoming releases**
1. No stack trace support for invariant tests if the `call_override` config option is enabled.
2. Need to verify that re-execution is safe in fork mode based on whether the block spec is cacheable (pretty sure it is).
3. Need to detect if an impure cheatcode was used in the re-executed test and fail stack trace generation with a warning.
**To be aware of**
1. Deviation from Foundry. 
1.1. When …

feat: bump `@ignored/edr` to 0.8.0-alpha.2

---

v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/result.svg
v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/result.txt
v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/asynchronous-activity-test/test.ts
v-next/hardhat-node-test-reporter/integration-tests/index.ts
v-next/hardhat-node-test-reporter/src/formatting.ts

---
This is a quick fix for an issue where we wouldn't display error details that were passed to us via `test:diagnostics` events. This was due to the fact that we accidentally swallowed such messages when formatting the unused diagnostics events.
As a follow-up to this, when the diagnostic message has a file property and that test file has failed to execute, we should display the message next to the file failure instead.

fix: display all unused diagnostics at the end of the test report

---

pnpm-lock.yaml
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts

Upgrades the `@ignored/edr-optimism` package to  v0.6.5-alpha.3
This includes:
- Fix for missing C Runtime on Windows (https://github.com/NomicFoundation/edr/pull/772)
- Optimism predeploys in local mode (https://github.com/NomicFoundation/edr/pull/798)
**To Do**

build: upgrade to edr-optimism v0.6.5-alpha.3

---

v-next/example-project/package.json
v-next/hardhat/package.json
v-next/hardhat/templates/01-node-test-runner-viem/README.md
v-next/hardhat/templates/02-mocha-ethers/README.md

This is a general rename. To ensure it's complete, you can run
```sh
$ rg -i hardhat3 v-next
v-next/hardhat-viem/test/chains.ts
254:      const isHardhat3 = await isHardhatNetwork(provider2);
257:        isHardhat3,
```

Rename the `hardhat3` cli to `hardhat`

---

docs/src/content/hardhat-runner/plugins/plugins.ts

This PR adds a new community plugin: https://github.com/ADISAKBOONMARK/hardhat-task-gen
`hardhat-task-gen` is a Hardhat plugin that automatically generates tasks from ABI files.

Add hardhat-task-gen plugin

---

pnpm-lock.yaml
v-next/hardhat/templates/01-node-test-runner-viem/contracts/Rocket.sol
v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
v-next/hardhat/templates/01-node-test-runner-viem/ignition/modules/Apollo.ts
v-next/hardhat/templates/01-node-test-runner-viem/package.json
v-next/hardhat/templates/01-node-test-runner-viem/scripts/deploy-rocket-from-script.ts

This adds the Rocket example and its module based on the Ignition Getting Started Guide.
It will updated/removed as we iterate on the Public Alpha examples.

add ignition to the viem template

---

v-next/hardhat-ignition/test/deploy/rerun/rerun-after-kill.ts

In the CI the `rerun after kill` would fail non-deterministically. The test manipulates the mempool and involves waits.
The comment and initial feature suggest that the contracts should be deployed batch at a time with `after`, but the test does not include it. Specifically here are the reproduction steps from the original issue:
```markdown
Update the examples/sample module to deploy 5 contracts one after the other using after (each in its own batch).
Set the node so that automining is false and the interval to 1s.
Start the first run and ctrl c after the first batch has started
Rerun the deployment
You should see the 405 error after the 3rd batch
```
I have added in the `after` and will monitor the CI to see if it deals with the non-deterministic failures.
I manually forced reruns of …

test: fix the update after kill test

---

v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/dependency-graph.ts
v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/dependency-graph.ts

---
I discovered that when `paths.sources` and `paths.tests.solidity` share common directories, we might end up with duplicate root paths. This PR ensures they are unique. Also, it adds the source file path information to the hardhat invariant violation error message which was helpful in debugging.
Context: https://nomicfoundation.slack.com/archives/C069TLP61BQ/p1739656187561829

fix: make the root paths in solidity test unique

---

.github/workflows/v-next-ci.yml

---
`for old_link in $(find v-next/hardhat/bundle -type l)` loops over nothing now. We can get rid of this codepath in the bundle creation entirely.

ci: remove unused codepath in v-next ci

---

v-next/hardhat/templates/02-mocha-ethers/scripts/deploy-rocket-from-script.ts

The `./scripts/deploy-rocket-from-script.ts` had an import that reached across the monorepo. This has been updated to directly point at the Ignition module within the package.

fix: correct the Ignition module import in the ethers template script

---

v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/types/artifacts.ts

---
This resolves https://www.notion.so/nomicfoundation/Public-Alpha-Solidity-Test-Comparison-19d578cdeaf58070a453c4059f3df4dd?pvs=4#19d578cdeaf5803da9f0ddc5b4a3ca20
This was tested in https://github.com/galargh/solidity-testing-testing/actions/runs/13395288956/job/37412700270 
The output no longer contains `EvmError: Revert in setUp()` errors in constructors.

fix: correctly identify test suites

---

v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts

---
This change greatly improves solidity testing performance. Before, we would read the same build infos over and over again (for every compilation resul - test root path).

chore: deduplicate build ids before getting build infos

---

v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts

---
When we resolve the network config override, we only keep the values that are present in the override. In particular, even though resolved forking config would have `enabled: true` set, we remove it when resolving the override because the user didn't explicitly want to override that setting. So if the forking is disabled in the original network config, it will remain disabled after applying the override.
https://github.com/NomicFoundation/hardhat/blob/6f1f11084b8a6fd922c31a25e1ba06ff649a92bf/v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts#L142-L149
This is not what we want when providing forking arguments to the `node` task. So I decided to explicitly enable forking in the override when the forking options are passed to that task.

fix: explicitly enable forking when configuring it via override

---

v-next/hardhat-ignition/src/internal/tasks/deploy.ts
v-next/hardhat-ignition/src/internal/tasks/verify.ts

Specifically the message when running `deploy` with the `--verify` flag and the standalone `hardhat ignition verify` task.
This brings the text and styling inline with the other not implemented messages.

feat: update not implemented message on ignition verify tasks

---

v-next/hardhat/src/internal/cli/init/package-manager.ts
v-next/hardhat/test/internal/cli/init/package-manager.ts

Uses the `npm_config_user_agent` env variable to tell if it's been invoked by `pnpm dlx` or `pnpx`
I also tried other 2 approaches but discarded them:
- Using `process.argv`: the binary is set as "node" even though initially invoked by pnpx
- Using `process._`: this doesnt work on windows cmd/powershell
From what I've researched and manually tested, `npm_config_user_agent` is set on both type of operating systems
Closes #6321

Init projects with pnpm when invoking hardhat from pnpx

---

v-next/hardhat-keystore/test/hook-handlers/configuration-variables.ts

Depends on [this PR](https://github.com/NomicFoundation/hardhat/pull/6355)
Be sure that the password is asked only once when there are multiple parallel calls to the configuration variables

[Keystore] Improve test: ask for multiple  config variables in parallel

---

docs/src/content/ignition/docs/guides/upgradeable-proxies.md

---
It's not much but it can cause confusion in the documentation. Above the documentation makes us export the "DemoModule" and here we use "useModule" with the proxy module which is not supposed to be exported, I therefore deduce that we must use the import which was introduced above.
Thank you for taking the time to read me and have a good day.

fix: use unexistent exportation from upgrade module

---

.github/workflows/v-next-changesets-release.yml

This job will not work with the constraints of a build queue (i.e. you cannot commit and push within the job).
This build is effectively disabled - to avoid any danger (and a failing build) lets completely comment out the job.
We will look to revive an improved version of changeset releases in the coming weeks.

chore: disable the v-next changeset release

---

.github/workflows/check-changeset-added.yml

---
This should unblock the merge queue.

ci: run the changeset check in the merge queue

---

.changeset/short-beans-rest.md
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/fixture-projects/cli/parsing/tasks-and-subtasks/hardhat.config.ts
v-next/hardhat/test/internal/cli/main.ts

Now if you run 
- `npx hardhat task nonExistingTask`
- `npx hardhat task nonExistingTask --help`
An error will thrown:
`Invalid subtask "nonExistingTask" for the task "task"`

[Cli parsing] When you run `npx hardhat task unexpected-argument` it doesn't fail if task is an empty task

---

.changeset/early-wolves-move.md
v-next/hardhat-network-helpers/src/internal/network-helpers/helpers/load-fixture.ts
v-next/hardhat-network-helpers/src/internal/network-helpers/network-helpers.ts
v-next/hardhat-network-helpers/test/network-helpers/load-fixture.ts

Fixes https://github.com/NomicFoundation/hardhat/issues/6377
Fix explanation: Hardhat now supports multiple connections. The `snapshots` array used in the `loadFixture` function was declared globally, which meant it was shared across multiple connections, leading to the failure described in the issue.
To fix this problem, I moved the `snapshots` array to the `network-helpers` class declaration. Since a new class is created for every connection, the `snapshots` array will now be unique for each connection.

Invariant error when running chai matchers and load fixture

---

.changeset/hot-birds-cover.md
packages/hardhat-core/src/internal/cli/project-creation.ts

(It seems there are no existing tests for the CLI installation yet, so I have kept the same level of testing for now and added my manual test below).
**Description:**
* (issue #6111) Franco noticed that the install script defaults to using `npm` in some cases, noting that its probably to do with checking the directories package manager related files.
* Confirmed that the checks in `project-creation.ts` are checking for related .lock files, and therefore if the project isn't set up correctly then the CLI could use the wrong package manager.
* Added a new function `getProjectTypeFromUserAgent` which extracts the first part of `process.env.npm_config_user_agent`, this is then added as the first check in the `isYarnProject` and `isPnpmProject` functions. 
* **Note:** This also removes the …

fix: correct package manager selection in CLI install

---

.changeset/selfish-horses-peel.md
packages/hardhat-core/package.json
pnpm-lock.yaml

Bump EDR to [0.10.0](https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.10.0). 
*    1d377bb: Add Prague hardfork to the list of supported `SpecId`s

chore: bump EDR to 0.10.0

---

.changeset/eleven-bees-serve.md
v-next/hardhat-utils/src/request.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts

Closes #6439 
Scanned the v3 codebase for all potential outgoing http requests. Since they all go through utils/request, it all cleanly resolves to a single default value for timeouts (which we use for connection, headers and body timeout). Increased it to match unidici's defaults.

Increase default http request timeout from 30s to 300s

---

v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts

resolves https://github.com/NomicFoundation/hardhat/issues/6198

Restructure validation tests and add tests for missing fields

---

.changeset/tasty-deers-doubt.md
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts

Closes #6012 
I put this logic inside the `resolveUserConfig` hook since by that point it was already zod-checked. I also considered the `validateUserConfig` hook but if the config had wrong type, it would show both the warning and the zod error (also it could attempt to compare two non-number values).
Let me know if there's a better place to move the warning logic.

Error when using a low interval mining value and mismatching timestamp

---

v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/cache.ts

---
This resolves https://github.com/NomicFoundation/hardhat/issues/6503
I ran the test after changes a 100 times on each runner:
- https://github.com/NomicFoundation/hardhat/actions/runs/14118656535
- https://github.com/NomicFoundation/hardhat/actions/runs/14118548054

test: remove timeouts from the object cache test

---

.changeset/pretty-lizards-roll.md
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/stack-traces/stack-trace-solidity-errors.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/stack-trace-solidity-errors.ts

---
This is a follow-up to https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1742980461593939
It resolved https://github.com/NomicFoundation/hardhat/issues/6505 and https://github.com/NomicFoundation/hardhat/issues/6475
Here's an example run which showcases both error messages inferred from stack trace and new stack trace warnings - https://github.com/galargh/hardhat/actions/runs/14082082256/job/39437613164
Please note that the notes are not part of the actual output.
```
...
✘ Run Failed: 443 tests, 440 passed, 3 failed, 0 skipped (duration: 12062 ms)
Failure (1): setUp()
Reason: Transaction reverted without a reason string
at TokenLocker.constructor (test/vault/VaultReentrancy.t.sol:22)
at TokenLocker.<unknown> (test/vault/VaultReentrancy.t.sol:18)
Failure (2): …
```

feat: support stack trace warnings and infer error messages from stack trace

---

.changeset/shiny-trees-laugh.md
.github/config/regression-tests.yml
.github/workflows/regression-tests.yml
packages/hardhat-core/src/internal/core/config/default-config.ts

**Description:**
This PR extends the Hardhat config to setup hardfork history for Avalanche networks used when forking.
**Related issue(s):**
N/A
**Notes for reviewer:**
This PR follows the same approach as https://github.com/NomicFoundation/hardhat/issues/5511 but for `avax`.

Add hardforkHistory for avalanche network

---

.changeset/many-falcons-relate.md
packages/hardhat-ignition-core/src/internal/batcher.ts
packages/hardhat-ignition-core/src/internal/utils/adjacency-list-converter.ts
packages/hardhat-ignition-core/src/internal/utils/adjacency-list.ts
packages/hardhat-ignition/test/deploy/module-patterns/index-pattern.ts
packages/hardhat-ignition/test/fixture-projects/index-pattern-success/contracts/Test.sol
packages/hardhat-ignition/test/fixture-projects/index-pattern-success/hardhat.config.js
packages/hardhat-ignition/test/fixture-projects/index-pattern-success/ignition/modules/MyModule.js

This issue has two commits:
1. The first commit resolves the original issue (https://github.com/NomicFoundation/hardhat-ignition/issues/857) by recursively collecting all futures from all submodules of a module given as a dependency in an `after` option of a future.
2. The second commit extends the above logic to apply to futures passed as dependencies in an `after` option as well. The reason for this change is to cover what I'm calling a combined "malaga-index" case:
```typescript
const IndexMod = buildModule("IndexMod", (m) => {
const { F1 } = m.useModule(Mod1);
const { F2 } = m.useModule(Mod2);
const { F3 } = m.useModule(Mod3);
const lastCall = m.call(F3, "mustBeCalledByTwoSeparateContracts");
const NewF1 = m.contractAt("F1", F1, { after: [lastCall], id: "NewF1" });
return { NewF1, F2, …
```

Resolve all dependencies when using submodules in `after`

---

.changeset/stale-insects-design.md
pnpm-lock.yaml
v-next/hardhat/package.json

Bump `@ignored/edr` to `0.10.0-alpha.2` which brings two improvements:
1. Better error messages when invoking unsupported cheatcodes. Previously we'd just return "unknown selector 0xafc98040", now we return "cheatcode 'broadcast()' is not supported" instead.
2. Automatically linking libraries for Solidity tests. Note that https://github.com/NomicFoundation/hardhat/pull/6529 needs to be merged to make this work.

feat: bump @ignored/edr to 0.10.0-alpha.2

---

.changeset/wet-students-act.md
v-next/hardhat-mocha/src/index.ts
v-next/hardhat-node-test-runner/src/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-results.ts

---
Resolves #6522
In this PR, I ensure the `compile` task is executed before the test sources compilation in the `test solidity` task. I also ensure that all the artifacts present in the artifacts folder after these two compilations are passed over to EDR for the solidity tests execution.
Context: https://nomicfoundation.slack.com/archives/C03P6B72ZHU/p1743408250467489

fix: pass all artifacts to edr when executing solidity tests

---

packages/hardhat-core/src/internal/core/config/default-config.ts

This PR removes deprecated testnets, adds newly introduced ones, and includes the Prague hardfork configuration for all supported testnets.
Note 1: The mainnet activation block for Prague is still TBD.
Note 2: No changeset is needed, as there's already one indicating Prague support.

feat: update chains map with prague activation blocks

---

v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat-errors/src/errors.ts
v-next/hardhat-errors/test/errors.ts
v-next/hardhat/test/internal/cli/error-handler.ts

This is a small improvement on top of #6552.
I moved the `pluginId` definition from each error descriptor (where it's easy to forget it), to the error categories object.
I didn't add any changeset because it can be seen as covered by #6552's changeset.

Move pluginId to the error category from the error descriptors

---

packages/hardhat-ignition-examples/ens/README.md

Replaced a broken ENS docs link with a working one that points to the ENS smart contracts page:
Old: https://docs.ens.domains/deploying-ens-on-a-private-chain#migration-file-example
New: https://docs.ens.domains/contracts
The previous link returned a 404. The new one still gives useful context for the ENS contracts used in this Hardhat example.
I recommend this replacement, but if there's a more specific or updated link, feel free to suggest it — happy to update the PR!

Fix broken link

---

.changeset/five-birds-invite.md
packages/hardhat-core/package.json
pnpm-lock.yaml

Upgrades EDR to [v0.11.0](https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.11.0).
- 66c7052: Replace const enums with non-const enums in \*.d.ts files

build: upgrade EDR to v0.11.0

---

packages/hardhat-truffle4/README.md
packages/hardhat-truffle5/README.md

Replaced `https://truffleframework.com/docs/truffle/testing/writing-tests-in-javascript`
with `https://archive.trufflesuite.com/docs/truffle/how-to/debug-test/write-tests-in-javascript/`
because the original domain is no longer active.

docs: replace dead Truffle testing link

---

.changeset/eleven-lies-sin.md
v-next/hardhat-utils/src/error.ts
v-next/hardhat-utils/src/fs.ts
v-next/hardhat-utils/src/synchronization.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/base-provider.ts

---
resolve #5605 
Add ensureNodeJSError function to replace unsafe  ensureError<T>

add ensureNodeErrnoExceptionError function to assert the error

---

pnpm-lock.yaml
v-next/hardhat/package.json

This upgrade includes:
- Fixed a bug causing async functions to throw errors at the callsite
- Added hardfork activations for Base Mainnet and Base Sepolia.
- Improved error message for failure to parse `BuildInfo`
- Removed support for pre-Byzantium root field from RPC receipts

build: upgrade to @ignored/edr v0.13.0-alpha.0

---

.changeset/gold-months-try.md
packages/hardhat-core/src/internal/core/providers/accounts.ts

Disable strict mode in `Transaction.prepare`, as it's intended for direct user usage and isn't useful in the context of Hardhat.
Closes https://github.com/NomicFoundation/hardhat/issues/6614

feat: disable strict mode in Transaction.prepare

---

.changeset/wet-walls-jog.md
v-next/hardhat/src/internal/builtin-plugins/network-manager/request-handlers/handlers/accounts/local-accounts.ts

Disable strict mode in `Transaction.prepare`, as it's intended for direct user usage and isn't useful in the context of Hardhat.
This PR is the v3 equivalent of [nomicfoundation/hardhat#6643](https://github.com/NomicFoundation/hardhat/pull/6643).

[v-next] feat: disable strict mode in Transaction.prepare

---

.changeset/chatty-rocks-reply.md
v-next/hardhat/src/internal/builtin-plugins/solidity-test/stack-trace-solidity-errors.ts

---
This fixes the issue reported in #6647.
As a follow-up, we should review the logic of extracting a more detailed error message from stack trace (https://github.com/NomicFoundation/hardhat/blob/999a8153bdedde5435432a28cd7cafd30fac8a90/v-next/hardhat/src/internal/builtin-plugins/solidity-test/stack-trace-solidity-errors.ts#L6) than the failure reason we get here (https://github.com/NomicFoundation/hardhat/blob/999a8153bdedde5435432a28cd7cafd30fac8a90/v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts#L132). cc @kanej @agostbiro 
I tested this on the reproduction repo provided here - https://github.com/agostbiro/hh3-repro
Before:
```
Failure (1): test_IncByZero()
Reason: Contract reverted without a reason string
at Counter.incBy (contracts/Counter.sol:15)
at …
```

fix: remove contract reverted without a reason string message from solidity tests

---

.github/workflows/hardhat-ci.yml

This PR updates the pnpm/action-setup GitHub Action from version 3 to version 4 in the CI workflow configuration.
Changes:
- Updated `pnpm/action-setup@v3` to `pnpm/action-setup@v4` in the hardhat-ci.yml workflow file

Update pnpm/action-setup from v3 to v4

---

.changeset/short-hornets-end.md
v-next/hardhat-node-test-reporter/integration-tests/README.md
v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/no-match-test/result.svg
v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/no-match-test/result.txt
v-next/hardhat-node-test-reporter/integration-tests/fixture-tests/no-match-test/test.ts
v-next/hardhat-node-test-reporter/src/error-formatting.ts

---
This resolves one of the issues reported in https://github.com/NomicFoundation/hardhat/issues/6608
Issue nr. 1 - `assert.match` 
The issue was that we were comparing unrelated types when trying to extract a full diff out of the error and it was showing up to the users as an error message related to their code.

fix: the error message produced by the errorenous regex matches

---

.github/workflows/v-next-ci.yml

---
The PAT created in PRs originating from forks do not have permission to comment on said PRs. In this PR I ensure we skip the comment step on PRs originating from forks.

ci: do not attempt to comment on PRs from forks

---

.changeset/young-baboons-sniff.md
v-next/hardhat/src/internal/builtin-plugins/network-manager/chain-descriptors.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/hre.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts

Closes https://github.com/NomicFoundation/hardhat/issues/6612

Chains config refactor

---

v-next/hardhat/src/internal/config-loading.ts

Without this change, the `if` block on line 41 (now line 39) does not run.

Fix instance of dead code

---

.changeset/happy-carrots-kick.md
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/artifacts.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts
v-next/hardhat/src/types/solidity/compilation-job.ts
v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/compilation-job.ts

resolves https://github.com/NomicFoundation/hardhat/issues/6551

Merge user's output selection with our defaults

---

.changeset/large-papayas-enjoy.md
packages/hardhat-core/src/internal/core/config/config-resolution.ts
packages/hardhat-core/src/internal/core/config/default-config.ts
packages/hardhat-core/test/internal/core/config/config-resolution.ts
packages/hardhat-ethers/test/error-messages.ts

Set Prague as the default hardfork and add the activation block to the hardfork history of mainnet.
Slot: https://beaconcha.in/slot/11649024
Block: https://beaconcha.in/block/22431084
Docs: https://github.com/NomicFoundation/hardhat-website/pull/6

feat: set prague as the default hardfork

---

v-next/hardhat/src/internal/builtin-plugins/telemetry/task-action.ts

I ran the `telemetry` task without any options, and, based on the output message, I thought it had toggled the consent status.  The word "now" in this context implies that the state is not the same as the previous state.

clarify telemetry status message

---

.changeset/bright-planes-talk.md
pnpm-lock.yaml
v-next/hardhat/templates/01-node-test-runner-viem/package.json
v-next/hardhat/templates/01-node-test-runner-viem/scripts/check-predeploy.ts
v-next/hardhat/templates/01-node-test-runner-viem/scripts/send-op-tx.ts
v-next/hardhat/templates/01-node-test-runner-viem/test/Counter.ts
v-next/hardhat/templates/02-mocha-ethers/package.json
v-next/hardhat/templates/02-mocha-ethers/scripts/check-predeploy.ts
v-next/hardhat/templates/02-mocha-ethers/scripts/send-op-tx.ts
v-next/hardhat/templates/02-mocha-ethers/test/Counter.ts
v-next/hardhat/test/internal/cli/init/template.ts

This PR introduces a few changes:
- It adds tests that compile the sample projects, and fail if they fail to compile
- It fixes all the compilation failures (which were related to the change in the network.connect API)
- It improves the ethers template a bit, so that it looks nicer
- It fixes the dependencies in the templates. `hardhat-ignition` and `hardhat-ethers` need to be installed explicitly.

Fix sample projects and add tests to avoid them breaking again

---

.changeset/nervous-cherries-switch.md
v-next/hardhat-typechain/src/internal/generate-types.ts
v-next/hardhat-typechain/test/fixture-projects/custom-out-dir/contracts/A.sol
v-next/hardhat-typechain/test/index.ts

This PR fixes the issue that was leading to errors when running `pnpm build` in the `example-project` after compiling the contracts.
The root of the problem is that typechain generates contract factories for abstract contracts, but they don't extend `ContractFactory`. That made the `attach` fix to generate invalid code.
This PR restricts where we implement the attach fix, skipping abstract contracts.

Fix typechain factories for abstract contracts

---

.changeset/dull-frogs-wait.md
.changeset/gorgeous-eyes-allow.md
.changeset/mean-avocados-matter.md
.changeset/nervous-cherries-switch.md
.changeset/olive-suits-deny.md
.changeset/sixty-socks-roll.md
.changeset/yellow-dolls-behave.md

Updating the text of the next release within the changesets (and adding references to issues):
- 458cc89: Delegate from `npx hardhat test` to appropriate test runner when file test path provided ([#6616](https://github.com/NomicFoundation/hardhat/issues/6616))
- d460644: Add the ability to filter Solidity tests with `--grep` ([#6690](https://github.com/NomicFoundation/hardhat/pull/6690))
- 918df12: Fix an issue with abstract contracts' factories ([#6703](https://github.com/NomicFoundation/hardhat/pull/6703))
- ad1d08b: Fix to ignore top-level `.json` files in the `artifacts` folder, as those are never actual artifacts ([#6613](https://github.com/NomicFoundation/hardhat/issues/6613))
- 624ba10: Fixed unintended deduplication of accounts …

Cleanup text of changesets before release

---

.changeset/nasty-readers-explode.md
packages/hardhat-ignition/src/utils/getApiKeyAndUrls.ts
packages/hardhat-ignition/test/verify/getApiKeyAndUrls.ts
packages/hardhat-verify/src/internal/blockscout.ts
packages/hardhat-verify/src/internal/etherscan.ts
packages/hardhat-verify/test/integration/index.ts
packages/hardhat-verify/test/unit/etherscan.ts

Closes #6716
This PR means to support the api v2 of Etherscan.io. The main difference is that with v2 you can use only one api key (from etherscan.io), to access the explorer services on all supported chains,  in contrast with having to register and have multiple api keys and explorers.
There are three main scenarios in which the plugin is used right now, related to this change, and we intend to provide support for all of them.
1- The user specifies a single api key in the config. This is assumed to be an etherscan.io key and it will be used to verify contracts on all the supported chains, using the api v2.
2- The user specifies a map with network -> api key combination. This is now deprecated and we show a warning, but we still attempt to use the v1 api using these keys and endpoints …

Support Etherscan API v2

---

.changeset/kind-bags-yawn.md
v-next/hardhat/package.json

---
We need to include `coverage.sol` in the files included in the hardhat bundle.
If we don't include it in the bundle, then when hardhat is installed properly, then we don't have access to it.

fix: distribute coverage.sol inside hardhat package

---

.changeset/sixty-beans-pretend.md
pnpm-lock.yaml
v-next/example-project/contracts/FailingContract.sol
v-next/example-project/contracts/Rocket.sol
v-next/example-project/hardhat.config.ts
v-next/example-project/package.json
v-next/example-project/test/node/example-test-of-assertions.ts
v-next/example-project/tsconfig.json
v-next/hardhat-toolbox-viem/package.json
v-next/hardhat-toolbox-viem/src/index.ts
v-next/hardhat-toolbox-viem/src/type-extensions.ts
v-next/hardhat-toolbox-viem/tsconfig.json
v-next/hardhat-viem-matchers/README.md

This PR adds a few elements to allow us to include the new `@nomicfoundation/hardhat-viem-matchers` plugin in the template projects:
1. It adds a basic README.md that shows basic usage of each assertion function.
2. It adds the plugin to the viem toolbox
3. It adds a changeset
4. It adds the plugin to the example project to ease manual testing
The `README.md` is roughly based on the chai matcher reference page of the docs: https://hardhat.org/hardhat-chai-matchers/docs/reference.

add readme for viem matchers

---

.changeset/spicy-grapes-crash.md
v-next/hardhat/src/internal/builtin-plugins/test/index.ts
v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts

Fixes https://github.com/NomicFoundation/hardhat/issues/6726
Usage examples:
```
// no test runner specified, no file paths specified
pnpm hardhat test --grep "Other example"
// no test runner specified, file paths specified
pnpm hardhat test --grep "Other example"  test/node/*
// test runner specified, no file paths specified
pnpm hardhat test node --grep "Other example" 
```

Support grep on the npx hardhat test task

---

.changeset/wild-flowers-greet.md
v-next/hardhat/src/internal/cli/main.ts

Closes #6444
When -v, -vv, etc, flags are detected when passed to the `test` or `test solidity` task, we  fail and show a message

Warn on usage of verbose foundry flag for solidity tests

---

v-next/hardhat-verify/src/internal/artifacts.ts
v-next/hardhat-verify/src/internal/verification.ts

The build profile was not being passed to the `getCompilerInput`, making the results invalid.

fix: pass buildProfile to getCompilationJobs

---

v-next/hardhat-verify/src/internal/artifacts.ts
v-next/hardhat-verify/src/internal/verification.ts

Set "production" as the default build profile if `--build-profile` isn't specified.

fix: use production build profile by default

---

.github/workflows/autoassign-issues.yml

As Ignition has been folded into the Hardhat repo most new Ignition issues are coming from Hardhat.

chore: add Zoey and Armando to issue assigner

---

.github/config/regression-tests.yml

Reverts NomicFoundation/hardhat#6800
It turns out that the test is just flaky. See this run for example: https://github.com/NomicFoundation/hardhat/actions/runs/15506491633
It passed on macos but failed on linux and windows.

Revert "chore(regression-tests): unignore testBumpSlot"

---

.changeset/fruity-brooms-stare.md
packages/hardhat-foundry/src/foundry.ts

Closes #6824 
Up to version 1.0.0 of foundry, the `--no-commit` flag is mandatory on our usage of `forge install`. From `1.1.0` onwards, it's mandatory to not use it. The simplest way to detect this for me is to just run `forge install --help` and see if the `--no-commit` flag is there.

fix: check the --no-commit flag is supported on installed forge version

---

.changeset/chubby-flies-shine.md
packages/hardhat-core/CHANGELOG.md
packages/hardhat-core/package.json
pnpm-lock.yaml

Upgraded EDR to [v0.11.1](https://github.com/NomicFoundation/edr/releases/tag/%40nomicfoundation%2Fedr%400.11.1):
- Fixed bug where native token sent to test account does not increase recipient balance.
Fixes https://github.com/NomicFoundation/hardhat/issues/6791

build: upgrade EDR to v0.11.1

---

.changeset/stupid-cars-suffer.md
v-next/hardhat/src/internal/cli/init/init.ts

Fix warning: passing args to `spawn` when shell is set to true

---

.changeset/pre.json
.changeset/twelve-taxes-help.md
pnpm-lock.yaml
v-next/hardhat-toolbox-viem/package.json
v-next/hardhat/templates/01-node-test-runner-viem/package.json

We released a new major version of the viem toolbox. Hence the alpha version has to be incremented by a major version.
I tested the version change manually using verdaccio, then installed both the viem and ethers toolbox template projects and ran through the standard compile/test/run/ignition smoke tests.

chore: bump the version of the viem toolbox

---

.changeset/fluffy-glasses-beam.md
pnpm-lock.yaml
v-next/config/eslint.config.js
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/edr-provider.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/runner.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/test/index.ts
v-next/hardhat/src/internal/builtin-plugins/test/task-action.ts
v-next/hardhat/src/internal/edr/chain-type.ts
v-next/hardhat/test/fixture-projects/solidity-test/contracts/Predeploy.sol
v-next/hardhat/test/fixture-projects/solidity-test/test/contracts/failing/Failing.t.sol
v-next/hardhat/test/fixture-projects/solidity-test/test/contracts/op/Predeploy.t.sol
v-next/hardhat/test/internal/builtin-plugins/solidity-test/task-action.ts

This PR introduces support for multichain testing in the Solidity test runner.
- Configure predeploys for the solidity test runner.
- Allow passing `--chain-type` as an option to the `test solidity` task and validate it.
- Allow passing `--chain-type` as an option to the `test` task and forward it to `test solidity`.
- Add tests to ensure the `chainType` parameter is passed and predeploy contracts are working as expected.
- Refactor utilities: moved logic from `network-manager` to `internal/edr` and renamed.
- Fix ESLint `import/order` rule by adding the `"internal"` group so absolute imports from local packages are correctly ordered between external and relative imports.
Closes https://github.com/NomicFoundation/hardhat/issues/6866

Enable multichain testing support in Solidity test runner

---

.changeset/tough-rice-jam.md
v-next/hardhat-utils/src/internal/bytecode.ts
v-next/hardhat-viem/test/contracts.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/artifacts.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
v-next/hardhat/src/types/artifacts.ts

This PR changes how we store the link references in artifacts, which fixes a bug that prevented solidity tests from using libraries

Use input source names in the link references

---

.changeset/spicy-ravens-type.md
v-next/hardhat/src/internal/core/arguments.ts
v-next/hardhat/test/internal/core/arguments.ts
v-next/hardhat/test/internal/core/global-options.ts

---
This is the most straighforward fix for https://github.com/NomicFoundation/hardhat/issues/7028
In an usual case, we do not expect flag options to be associated with values. However, that's not always the case in our codebase. In particular, we're parsing global options differently to task options. This is because global option values can be also provided via the environmental variables. In particular, `--coverage` global flag option can be provided via `HARDHAT_COVERAGE` environmental variable. When that happens, we should know how to parse its' value (exactly the same as we do for boolean options). This is why we have to remove the invariant of never expecting flags to be associated with values from the `parseArgumentValue` function.

fix: global flag option parsing

---

.changeset/cold-oranges-guess.md
v-next/example-project/hardhat.config.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/build-system.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/config.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/index.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/tasks/build.ts
v-next/hardhat/src/internal/builtin-plugins/solidity/type-extensions.ts
v-next/hardhat/test/internal/builtin-plugins/solidity/build-system/build-system.ts
v-next/hardhat/test/internal/cli/main.ts

This PR renames the `dependenciesToCompile` config property to `npmFilesToBuild`.
Also it introduces a new task, `build`, that is just an alias for `compile`. It uses the same arguments and task action as `compile`
Closes #6877

Rename dependencies to compile and build task

---

.changeset/sour-pandas-attend.md
v-next/hardhat-ignition-ethers/src/internal/ethers-ignition-helper.ts
v-next/hardhat-ignition-viem/src/internal/viem-ignition-helper.ts
v-next/hardhat-ignition/src/internal/tasks/deploy.ts
v-next/hardhat-ignition/test/deploy/reset.ts
v-next/hardhat-ignition/test/deploy/writeLocalhost.ts
v-next/hardhat-ignition/test/plan/index.ts

In Hardhat 2, the deployment folder is not generated if running against an in-memory network or `writeLocalhostDeployment` is enabled. The rule for in-memory network is detected was based on the name (i.e. "hardhat").
The rule is now changing to be based on whether the network running against is of type `edr`, which indicates that the network is running in-memory in Hardhat 3.
The rule is updated in the `deploy` task, as well of the helper objects in the viem and ethers Ignition plugins.
Resolves #6999.

fix: change deployment folder rule for ignition

---

v-next/hardhat-utils/README.md

The `hardhat-utils` package is internal to Hardhat. It can be used from external plugins, but we do not commit to keeping major versions of utils inline with Hardhat.
Put another way, if we need to make breaking changes to the util APIs for a patch update of Hardhat, we will.

docs: add a warning to Hardhat utils indicating it is internal

---

.changeset/calm-taxis-film.md
v-next/hardhat/src/internal/builtin-plugins/solidity/build-system/compilation-job.ts

Closes #7049 
This PR only changes the build info ids to include the compiler (only solc for now) and the version in the build id. This directly affects the file names for both the build infos and the build info outputs.

Update build info ids to include compiler and version

---

.changeset/lovely-dodos-tell.md
v-next/hardhat-viem-assertions/package.json
v-next/hardhat-viem-assertions/src/internal/assertions/emit/emit-with-args.ts
v-next/hardhat-viem-assertions/src/internal/assertions/revert/revert-with-custom-error-with-args.ts
v-next/hardhat-viem-assertions/src/internal/helpers.ts
v-next/hardhat-viem-assertions/src/internal/predicates.ts
v-next/hardhat-viem-assertions/src/predicates.ts
v-next/hardhat-viem-assertions/test/fixture-projects/hardhat-project/contracts/Events.sol
v-next/hardhat-viem-assertions/test/fixture-projects/hardhat-project/contracts/Revert.sol
v-next/hardhat-viem-assertions/test/internal/assertions/emit/emit-with-args.ts
v-next/hardhat-viem-assertions/test/internal/assertions/revert/revert-with-custom-error-with-args.ts

Closes #7038 
Predicates support has been added to `emitWithArgs` and `revertWithCustomErrorWithArgs`.
The assertion failures when using predicates to match are not displayed the same way as when passing primitive values. This is because for the latter we leverage assert.deepEqual, which shows the diff in the following way:
```
AssertionError: The event arguments do not match the expected ones.
- Expected
+ Received
Array [
-   2n,
+   1n,
]
```
When using predicates and the assertion fails, we have to build a custom message and it looks like this:
```
AssertionError: The event arguments do not match the expected ones:
Expected: ["<predicate>"]
Emitted: ["1"]
```

Support predicates on viem-assertions

---

.changeset/chilled-mails-call.md
v-next/hardhat-viem/src/internal/chains.ts
v-next/hardhat-viem/src/internal/clients.ts
v-next/hardhat-viem/test/chains.ts
v-next/hardhat-viem/test/clients.ts

Fixed viem L2 actions, which @schaable broke by making the mistake of trusting my judgement.
Notice that I'm only adding the contracts. Even this is conceptually wrong because EDR doesn't add all the contracts in viem's `optimism` chain, but I think this is a good middle ground.
I also removed a skipped test that didn't make sense anyway.

Fix hh-viem l2 actions when using the optimism chain type

---

.changeset/friendly-cameras-notice.md
v-next/example-project/hardhat.config.ts
v-next/hardhat-node-test-runner/src/hookHandlers/config.ts
v-next/hardhat-node-test-runner/src/hookHandlers/test.ts
v-next/hardhat-node-test-runner/src/task-action.ts
v-next/hardhat-node-test-runner/src/type-extensions.ts
v-next/hardhat-node-test-runner/test/registerFileForTestRunner.ts

In Hardhat config rename `path.tests.nodeTest` to `path.tests.nodejs`. We renamed the Node Test Runner task from `node` to `nodejs`, this small change to the config name brings the path inline with the task name:
```js
// ...
paths: {
tests: {
mocha: "test/mocha",
nodejs: "test/node",
solidity: "test/contracts",
},
},
```

rename path.tests.nodeTest to path.tests.nodejs

---

.changeset/proud-colts-itch.md
.changeset/spotty-pianos-confess.md
pnpm-lock.yaml
v-next/hardhat/package.json

---
This PR builds on top of https://github.com/NomicFoundation/hardhat/pull/7102 and should be merged in order.
I upgrade the dependency for EDR to `@nomicfoundation/edr v0.12.0-next.3`, with the following changes:
- 6ea800c: Removed deprecated JSON-RPC methods: `eth_mining`, `net_listening`, `net_peerCount`, `hardhat_addCompilationResult`, `hardhat_intervalMine`, and `hardhat_reset`.
- a5cc346: Added cheatcode error stack trace entry. This fixes stack traces for errors from expect revert cheatcodes and improves stack traces for other cheatcode errors.

build: upgrade to @nomicfoundation/edr v0.12.0-next.3

---

.changeset/gorgeous-knives-yawn.md
v-next/example-project/hardhat.config.ts
v-next/example-project/scripts/send-op-tx-viem.ts
v-next/example-project/scripts/send-op-tx.ts
v-next/example-project/scripts/viem-plugin-example.ts
v-next/hardhat-viem/src/internal/chains.ts
v-next/hardhat-viem/src/internal/clients.ts
v-next/hardhat-viem/src/types.ts
v-next/hardhat-viem/test/clients.ts
v-next/hardhat-viem/test/contracts.ts
v-next/hardhat/src/internal/constants.ts
v-next/hardhat/src/types/network.ts
v-next/hardhat/templates/01-node-test-runner-viem/hardhat.config.ts
v-next/hardhat/templates/01-node-test-runner-viem/scripts/check-predeploy.ts
v-next/hardhat/templates/01-node-test-runner-viem/scripts/send-op-tx.ts
v-next/hardhat/templates/01-node-test-runner-viem/test/Counter.ts
v-next/hardhat/templates/02-mocha-ethers/hardhat.config.ts
v-next/hardhat/templates/02-mocha-ethers/scripts/check-predeploy.ts
v-next/hardhat/templates/02-mocha-ethers/scripts/send-op-tx.ts
v-next/hardhat/templates/02-mocha-ethers/test/Counter.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/test/internal/builtin-plugins/solidity-test/task-action.ts

Renames `optimism` to `op` for the network chaintype in Hardhat config e.g.
```ts
const config: HardhatUserConfig = {
networks: {
op: {
type: "http",
chainType: "op", // <-- previously "optimism"
url: "https://mainnet.optimism.io/",
accounts: [configVariable("OP_SENDER")],
},
},
}
```
This brings our naming inline with the Optimism docs.
The mainnet is called `op`, as evidenced by:
* https://explorer.optimism.io/
* https://docs.optimism.io/stack/getting-started
* https://chainlist.org/chain/10
It should be noted that `optimism` is the label for the chain in `viem` e.g.:
```ts
import { optimism } from "viem/chains";
console.log(optimism.name); // "OP Mainnet"
```
However, we are choosing to move closer to the official documentation.
Resolves #7085

Rename `optimism` chaintype to `op`

---

.changeset/pink-schools-exercise.md
packages/hardhat-core/src/internal/util/download.ts
packages/hardhat-verify/src/internal/undici.ts
packages/hardhat-verify/test/integration/mocks/etherscan.ts
packages/hardhat-verify/test/integration/mocks/sourcify.ts

This PR switches user user of `undici`'s `getGlobalDispatcher` to initializing our own `Agent`.
The reason to do it is that `getGlobalDispatcher` can return `Node.js`'s internal dispatcher, which can have different APIs depending on the version that the user is running 🤯. This PR makes things more stable.
@schaable I think we also want to implement this in v3.
fixes #7118

Don't use `undici`'s global dispatcher

---

.changeset/khaki-seahorses-develop.md
v-next/example-project/hardhat.config.ts
v-next/hardhat-mocha/src/hookHandlers/config.ts
v-next/hardhat-mocha/src/task-action.ts
v-next/hardhat-mocha/src/type-extensions.ts
v-next/hardhat-mocha/test/fixture-projects/invalid-mocha-config/hardhat.config.ts
v-next/hardhat-mocha/test/index.ts
v-next/hardhat/package.json
v-next/hardhat/src/internal/builtin-plugins/solidity-test/config.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/helpers.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/task-action.ts
v-next/hardhat/src/internal/builtin-plugins/solidity-test/type-extensions.ts
v-next/hardhat/src/internal/builtin-plugins/test/config.ts
v-next/hardhat/src/internal/builtin-plugins/test/hook-handlers/config.ts
v-next/hardhat/src/internal/builtin-plugins/test/index.ts
v-next/hardhat/src/internal/builtin-plugins/test/type-extensions.ts
v-next/hardhat/src/types/test.ts
v-next/hardhat/test/internal/builtin-plugins/test/config.ts

Move the Mocha and Solidity test configurations under a `test` property of the Hardhat config.
Also rename `solidityTest` to just `solidity`.
So from top level properties:
```js
mocha: {
color: true,
},
solidityTest: {
timeout: 1000,
},
```
They are now grouped under a `test` property:
```js
test: {
mocha: {
color: true,
},
solidity: {
timeout: 1000,
},
}
```
1. In `test` built-in plugin extend `HardhatConfig` and `HardhatUserConfig` with `HardhatTestConfig` and `HardhatTestUserConfig`
2. Export `HardhatTestConfig` and `HardhatTestUserConfig` as types under `types/test`
- should this be under `types/config`?
4. Add config hook to `test` built-in plugin that adds an empty object for `test` in the returned `HardhatConfig` instance
- Note: no validation was added for this empty config object …

regroup test configs under a test object

---

.changeset/long-rules-glow.md
v-next/example-project/hardhat.config.ts
v-next/example-project/scripts/send-op-tx-viem.ts
v-next/hardhat-errors/src/descriptors.ts
v-next/hardhat-ethers-chai-matchers/test/multi-network-connections.ts
v-next/hardhat-ethers/src/internal/signers/signers.ts
v-next/hardhat-ethers/test/hardhat-ethers-signer.ts
v-next/hardhat-ignition-core/test-integrations/fixture-projects/dont-throw-on-reverts/hardhat.config.js
v-next/hardhat-ignition-ethers/src/internal/ethers-ignition-helper.ts
v-next/hardhat-ignition-viem/src/internal/viem-ignition-helper.ts
v-next/hardhat-ignition/src/internal/tasks/deploy.ts
v-next/hardhat-ignition/test/config.ts
v-next/hardhat-ignition/test/fixture-projects/default-with-new-chain-id/hardhat.config.js
v-next/hardhat-ignition/test/fixture-projects/reset-flag/hardhat.config.js
v-next/hardhat-verify/test/fixture-projects/integration/hardhat.config.ts
v-next/hardhat-viem/test/clients.ts
v-next/hardhat-viem/test/contracts.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/config-override.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/network-manager.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-extensions/config.ts
v-next/hardhat/src/internal/builtin-plugins/network-manager/type-validation.ts
v-next/hardhat/src/internal/builtin-plugins/node/task-action.ts
v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/hardhat.config.ts
v-next/hardhat/templates/hardhat-3/02-mocha-ethers/hardhat.config.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/config-resolution.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/hook-handlers/config.ts
v-next/hardhat/test/internal/builtin-plugins/network-manager/network-manager.ts

This rename gives a clearer indication that the network config is for a local in-memory simulation via EDR.
Resolves #7051

rename `edr` label in network config `edr-simulated`

---

.changeset/neat-apes-beam.md
v-next/hardhat/src/internal/cli/help/get-global-help-string.ts
v-next/hardhat/src/internal/cli/help/get-help-string.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/help/get-global-help-string.ts
v-next/hardhat/test/internal/cli/help/get-help-string.ts
v-next/hardhat/test/internal/cli/main.ts

`GLOBAL OPTIONS:` section is displayed in the help message in all cases where the help message specifies that global options can be used (message contains `GLOBAL OPTIONS`)
For example: `Usage: hardhat [GLOBAL OPTIONS] <TASK> [SUBTASK] [TASK OPTIONS] [--] [TASK ARGUMENTS]`
This applies to all tasks, subtasks and global help
[Design doc](https://www.notion.so/nomicfoundation/Hardhat-CLI-help-247578cdeaf580b59adedc18f1d21af4?source=copy_link)

7114 global options arent displayed in the help message of a task

---

.changeset/breezy-feet-impress.md
v-next/hardhat/src/internal/cli/error-handler.ts
v-next/hardhat/src/internal/cli/main.ts
v-next/hardhat/test/internal/cli/error-handler.ts

This fixes how we print errors. The previous version was skipping the error causes.
I also tried calling `inspect` on the error, but that doesn't work the same as just `console.error()` them. `console` methods are smarter with respect to coloring and the like.

Print error cause when showing stack traces

---

.changeset/curly-shrimps-speak.md
v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/README.md
v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/hardhat.config.ts
v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/test/Counter.ts
v-next/hardhat/templates/hardhat-3/02-mocha-ethers/README.md
v-next/hardhat/templates/hardhat-3/02-mocha-ethers/hardhat.config.ts
v-next/hardhat/templates/hardhat-3/02-mocha-ethers/test/Counter.ts

This PR removes comments from template project files that now are meant to be included in the docs.
These are the points I think are currently missing from the docs, that were removed from the files:
- Config docs in general (plugins, network and build profiles). Looks like they are WiP in the docs site
- Examples for mocha-ethers stack (the ts testing section only has node+viem example)
Additionally I removed references to hardhat being alpha in the template projects' readmes. I think this wasn't in scope but thought it might be useful.
Closes #7149

Remove comments from template projects

---

.changeset/gentle-planets-travel.md
.changeset/wild-rivers-float.md
v-next/hardhat-network-helpers/src/internal/network-helpers/network-helpers.ts
v-next/hardhat-network-helpers/src/internal/network-helpers/time/time.ts
v-next/hardhat-network-helpers/test/index.ts
v-next/hardhat-utils/src/lang.ts
v-next/hardhat-utils/test/lang.ts

Previously this would fail
```ts
const {networkHelpers: {mine}} = await network.connect();
```

Bind all network helpers

---

README.md

For the image to appear properly on `npm` we need a full link.

chore: update header image link to absolute

---

.changeset/shy-lies-camp.md
v-next/hardhat/src/internal/builtin-plugins/solidity-test/reporter.ts

fixes https://github.com/NomicFoundation/hardhat/issues/7168 temporarily
This error message actually comes from [EDR](https://github.com/NomicFoundation/edr/blob/ce3c978db8fa678e9231860e5311dfd313a8a7b4/crates/foundry/cheatcodes/src/fs.rs#L1195), and it should ideally be changed on their end. For the time being, however, this PR is a temp fix until then.

Add temporary fix for incorrect error message

---

packages/hardhat-core/README.md

Add a note explaining development for Hardhat 2 is on the `v2` branch.

docs: update reamde to include note on branches

---

v-next/hardhat-keystore/README.md
v-next/hardhat-verify/README.md
v-next/hardhat-viem/README.md

Hi! While reading through the docs for hardhat-verify, hardhat-viem and hardhat-keystore I noticed that some links still point to the old hardhat3-alpha pages. Those URLs are no longer valid and give 404s.

fix: broken links in plugin READMEs

---

.github/config/regression-tests.yml

---
Excludes unsupported `testFail` test cases from the regression tests suite.

chore: restore testFail cases exclusion

---

.changeset/metal-owls-itch.md
pnpm-lock.yaml
v-next/hardhat/templates/hardhat-3/01-node-test-runner-viem/package.json
v-next/hardhat/templates/hardhat-3/02-mocha-ethers/package.json

resolves https://github.com/NomicFoundation/hardhat/issues/7192
The logic for adding peer dependencies to the install command for appropriate package managers is already there, the peer dependencies just needed to be added to the template projects.

Fix v3 yarn support

---

.changeset/three-rats-share.md
v-next/hardhat/src/internal/cli/telemetry/sentry/anonymizer.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/reporter.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/subprocess.ts
v-next/hardhat/src/internal/cli/telemetry/sentry/transport.ts
v-next/hardhat/test/internal/cli/telemetry/sentry/anonymizer.ts

Our Sentry exception reporting is including exceptions coming from within user scripts and tests. We need to improve our filtering to reduce the number of exceptions being reported that are really user land issues rather than Hardhat issues.
We intend to do this over a serious of tightening iterations. At the first pass we re-enable a filter and explicitly exclude:
* require in ESM exceptions
* cannot find package exceptions
* cannot find modules exceptions
We also broadly exclude exceptions originating in a `hardhat.config.{js,ts}` or that originate in a `node_modules` package that is not a hardhat package.
We attempt to exclude errors originating in user project files e.g. `./scripts/run.js` or `./ignition/modules/my-module.ts`.
Once we have established this baseline we will tighten up …

improve exception filtering before sending to Sentry

---

.github/workflows/release.yml

The release PR created by changeset should update the Hardhat lockfile.

chore: update pnpm lock file in release PR

---

.changeset/honest-queens-perform.md
v-next/hardhat-viem-assertions/src/predicates.ts
v-next/hardhat-viem-assertions/src/type-extensions.ts
v-next/hardhat-viem-assertions/src/types.ts

Add detailed JSDoc to the HardhatViemAssertions interface and all public methods:
- balancesHaveChanged
- emit
- emitWithArgs
- revert
- revertWith
- revertWithCustomError
- revertWithCustomErrorWithArgs
Document anyValue predicate export for use in argument/predicate-based assertions.
Document viem.assertions property in Hardhat viem helpers module augmentation.
Fix #6758

docs: add JSDoc for assertions API to improve IntelliSense discoverability

---

.changeset/orange-experts-try.md
v-next/hardhat-ignition-core/src/type-guards.ts

ENCODE_FUNCTION_CALL doesn’t submit transactions (initialized and marked SUCCESS without networkInteractions) and is excluded by pending-onchain selectors. The guard wrongly included it, causing inconsistency. Updated guard to exclude it at type and runtime.

fix(type-guards): exclude ENCODE_FUNCTION_CALL from isFutureThatSubmitsOnchainTransaction

---

.github/workflows/LATEST_DEPENDENCY_VERSIONS.yml

This is a v2 CI check that has still to be ported to Hardhat 3. For the moment we point it back at the Hardhat 2 branch.
The same test fails currently on `main` due to issues with mocha tests in Ignition core. We should swap out the Ignition tests to use Node test runner.

chore: update the dependency check CI job to point at v2

---

.changeset/dirty-pens-tell.md
v-next/hardhat/src/internal/builtin-plugins/solidity-test/config.ts
v-next/hardhat/test/internal/builtin-plugins/solidity-test/config-validation.ts

This property was renamed from `solidityTest` to `test`, but this change was missed.
See https://github.com/NomicFoundation/hardhat/pull/7101 for context.

fix: update the validation to reflect the new property

---

.changeset/popular-bats-doubt.md
v-next/hardhat-verify/src/internal/contract.ts

Add missing optional chaining operator when accessing compiler output contracts
to prevent potential runtime TypeError in ContractInformationResolver.
The fix ensures that accessing buildInfoOutput.output.contracts[inputSourceName][contractName]
is safe by using optional chaining for both array accesses, preventing crashes
when either the contracts object or the specific source contracts array is undefined.
This change maintains the existing error handling through assertHardhatInvariant
while making the code more robust against unexpected data structure states.

fix: add safe optional chaining for contract access in verify module

---

.changeset/wild-wombats-compare.md
packages/hardhat-toolbox-viem/src/index.ts
packages/hardhat-toolbox/src/index.ts

When we [upgraded](https://github.com/NomicFoundation/hardhat/pull/6886) `hardhat-gas-reporter` to v2, the `REPORT_GAS` variable stopped working.
The toolboxes READMEs have this snippet:
```
REPORT_GAS=true npx hardhat test
```
But now gas is reported whether you set the variable or not. The reason is that v2 of `hardhat-gas-reporter` now uses `extendConfig` and sets its options to some default values. `gasReport.enabled` defaults to true, so our code never changes it.
I changed the code so that `enabled` is set using the `REPORT_GAS` envvar only if the **user** config of gas reporter doesn't have an `enabled` field. This also means that gas is **not** reported by default, unlike what happens if you install the plugin manually. This was a conscious decision, both to have the same behavior …

Fix REPORT_GAS envvar in toolboxes

---

.changeset/clever-days-remain.md
v-next/hardhat/src/internal/builtin-plugins/coverage/coverage-manager.ts
v-next/hardhat/test/internal/builtin-plugins/coverage/coverage-manager.ts

Replace the splatting conversion of arrays into arguments with for loops.
This allows us to load larger coverage data files.
Resolves https://github.com/NomicFoundation/hardhat/issues/7385.

fix: code coverage max callstack on load

---

.changeset/wet-turkeys-care.md
v-next/hardhat-verify/src/internal/etherscan.ts
v-next/hardhat-verify/test/etherscan.ts
v-next/hardhat-verify/test/verification.ts

- [ +] Because this PR includes a **bug fix**, relevant tests have been included.
---
Changes:
- Use `apiUrl` from `etherscanConfig` for verification
Closes https://github.com/NomicFoundation/hardhat/issues/7509

fix: use apiUrl from etherscanConfig for verification
